### PR TITLE
B-18115 updating prime sim sit extension

### PR DESCRIPTION
**Pull request by taeJungCaci**
## Summary

Updating the Prime Simulator to have the functionality to send SIT extension requests.
Currently, there is an API already implemented in the Prime API, but the Prime Simulator is missing UI to send requests.

### How to test

1. Create a HHG shipment move, complete counseling, and approve as a TOO.
2. Change role to prime and go to the move you created in the Prime Simulator.
3. Create a new SIT service item for the shipment.
4. Approve SIT request as a TOO.
5. Go back to the Prime Simulator and a "Request SIT Extension" button should be visible in shipment details (only visible if there exists a SIT service item & is a HHG shipment.
6.  Click on the button and fill out the form in the Request SIT Extension page, then submit.

## Screenshots

image
image
image

### CODE REVIEW

**Comment by KonstanceH** [comment]
I can see intended functionality working and added tests are passing for me but, there's a coverage failure happening in the CircleCI, it just says that coverage decreased from 75.1 to 75.0
Screenshot 2023-12-11 at 10 21 57 AM

**Review by WeatherfordAaron — APPROVED** [review]
Looks good. As a general practice, I would recommend using Promise.all at the same level as the other awaits in the playwright test as opposed to a loop just because it is possible that an error could be returned if something hangs up any of the other async operations above that loop.

However, since it isn't currently breaking any tests, I'm good with approving.

**Comment by taeJungCaci** [comment]
> I can see intended functionality working and added tests are passing for me but, there's a coverage failure happening in the CircleCI, it just says that coverage decreased from 75.1 to 75.0 Screenshot 2023-12-11 at 10 21 57 AM

More tests added to fill the coverage. It should be good now!

**Review by KonstanceH — APPROVED** [review]
Intended functionality and added tests are passing for me.

**Pull request merged**
