### PR TITLE
MB-15408: Text updates for backup address fields

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Summary

This pull request updates the header and helper text for the Backup Address form fields, in both the customer onboarding flow, and the edit customer profile page; specifically, it removes the word "mailing" from both headers and standardizes the helper text.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Log in locally to the client application as a new customer user.
2. Proceed through the onboarding flow normally until you get to the onboarding step that formerly contained the header text "Backup mailing address."
3. Verify that the header text has changed (removing the word "mailing"), and that help text exists between the header and the form fields.
4. Finish the onboarding flow and progress to the customer's home page.
5. Click the "Edit" button on the right side of the first progression step.
6. Click "Edit" on the customer details section.
7. Scroll down and verify that the header text for the Backup address section also no longer includes the word "mailing," and that the help text between it and the form fields matches the help text in step 3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
* [Onboarding flow, desktop width](https://user-images.githubusercontent.com/83614364/231880698-4d5b48dd-27e7-42c4-81b0-cfe58b07d143.png)
* [Onboarding flow, mobile width](https://user-images.githubusercontent.com/83614364/231880816-7db2284c-ccab-4fe5-b290-f0d99d75fb68.png)
* [Edit profile, desktop width](https://user-images.githubusercontent.com/83614364/231880940-973c5103-b5c2-4517-93f9-f8b7960696bf.png)
* [Edit profile, mobile width](https://user-images.githubusercontent.com/83614364/231881030-5b9fa1a4-6b37-450a-b025-2e78d51d83a4.png)

### CODE REVIEW

**Review by pearl-truss — APPROVED** [review]
LGTM 🚀

**Review by felipe-lee — COMMENTED** [review]
I found a few places that still reference "backup mailing address" that I think likely should be updated, though tbh, I'm not really familiar with some of these files (like the move template ones), so without digging in more, I'm not sure how some used:

* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx#L8
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx#L10
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.test.jsx#L63
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/components/form/AddressFields/AddressFields.stories.jsx#L122
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/constants/MoveHistory/Database/FieldMappings.js#L79
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/pages/MyMove/Profile/BackupContact.test.jsx#L197
    * This one is more to help with the name of the test matching
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/pages/MyMove/Profile/BackupContact.test.jsx#L242
    * This one is more to help with the name of the test matching
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/scenes/Office/BackupInfoPanel.jsx#L21
* https://github.com/transcom/mymove/blob/2d4983fb66e85ade39b3e704b416820ccc5c95e3/src/scenes/Office/BackupInfoPanel.jsx#L69

**Comment by kylehilltruss** [comment]
> I found a few places that still reference "backup mailing address" that I think likely should be updated

I don't think these were explicitly in the A/C, but I should fix them. (Will rename the component while I'm at it.)

**Review by rileyorr — APPROVED** [review]
@kylehilltruss this LGTM - great job!

**Pull request merged**
