### PR TITLE
Add user info to upload lookup

### PR DESCRIPTION
**Pull request by mkrump**
## Description

This PR adds the uploading user's information to the "Search by Upload ID" page in the admin interface. If an office user was responsible for an upload, then that office user's id and email will be populated and if a service member was responsible for an upload then the service member's user id will be populated.

## Reviewer Notes

1) Start the server, office client and admin client and seed the db with the e2e data
```
make server_run
make office_client_run
make admin_client_run
make db_dev_e2e_populate
```
2) Chose an upload id from the uploads table
3) In the Admin interface, go to "Search by upload ID" and search for the upload. The uploading service member's id should be displayed along with the other upload summary information.
4) Now as an office user upload a document. Repeat steps 2 and 3 with the new upload, but now the service member id should be blank while the office user's id and email should be populated.

## Setup

```sh
make server_test
```

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/n/projects/2181745) for this change

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
Can you add an animated gif to your ticket here? What we had to give in the incident report for the upload was Name, email (if available), phone (if available). I'm gathering from this that phone isn't available yet.

And while it wasn't part of the story it would also be nice to view the tags on the upload in the same view. Primarily `av-signature` which tells us what the problem was. But we can also do that part later.

**Comment by mkrump** [comment]
> Can you add an animated gif to your ticket here? What we had to give in the incident report for the upload was Name, email (if available), phone (if available). I'm gathering from this that phone isn't available yet.
> 
> And while it wasn't part of the story it would also be nice to view the tags on the upload in the same view. Primarily `av-signature` which tells us what the problem was. But we can also do that part later.

I can add the other fields (name, phone), but I wanna link Linda to this comment, since the ticket specifically excluded info if uploader was a service member, just want to make sure there wasn't a reason that info wasn't included already https://www.pivotaltracker.com/n/projects/2181745/stories/168913993.

**Comment by chrisgilmerproj** [comment]
Let's talk with @setch-l about this. We really need to get this info in one place and this story and another story are starting to make me feel that the ban on PII in the admin interface is obstructing our ability to do operations more than it ought to. So we have got to find some resolution here.

**Comment by mkrump** [comment]
upload-info

@chrisgilmerproj gif

**Comment by chrisgilmerproj** [comment]
@mkrump - excellent! I'm not going to block this story. We can revisit the name, email, phone in another place.

**Comment by mkrump** [comment]
> > Can you add an animated gif to your ticket here? What we had to give in the incident report for the upload was Name, email (if available), phone (if available). I'm gathering from this that phone isn't available yet.
> > And while it wasn't part of the story it would also be nice to view the tags on the upload in the same view. Primarily `av-signature` which tells us what the problem was. But we can also do that part later.
> 
> I can add the other fields (name, phone), but I wanna link Linda to this comment, since the ticket specifically excluded info if uploader was a service member, just want to make sure there wasn't a reason that info wasn't included already https://www.pivotaltracker.com/n/projects/2181745/stories/168913993.

Going to add in additional fields in follow on PR, but will keep in the same story.

**Pull request merged**
