### PR TITLE
MB-6399 Setup benchmarking tool with puppeteer 

### PR DESCRIPTION
**Pull request by donaldthai**
## Description

This PR does the initial setup for benchmarking the document viewer page. Puppeteer v7 is imported since v1 is quite old. The time is calculated using the browser `performance api` and parsing all the log entries for `navigation` and `resource` events. The script works locally and as well as with the S3 bucket though some setup is needed.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

**Locally**
```sh
make db_bandwidth_up // to create documents
make server_run
make office_client_run
node puppeteer/benchmarking.js // to run the benchmarking script
```

**S3**
Uncomment from `.envrc` file:
```
export STORAGE_BACKEND=s3
```
Terminal
```sh
// reload configs
direnv allow

// upload documents to s3
aws-vault exec transcom-gov-dev -- make db_bandwidth_up

// key in your aws OTP
aws-vault exec transcom-gov-dev -- make server_run

// run client
make office_client_run

// run script
node puppeteer/benchmarking.js
```

**Example of result**
image

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6399) for this change
* [this api](https://pptr.dev/#?product=Puppeteer&version=v7.0.1) is used.

### CODE REVIEW

**Review by suzubara — COMMENTED** [review]
Have we considered using Cypress to take these benchmarks instead of Puppeteer? I just ask because we already have Cypress in the project and I believe it can be used to achieve everything here. Their docs have an example of using Cypress to take performance metrics: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__performance-metrics/cypress/integration/spec.js

We also have the cypress-audit plugin set up which we are only using for a11y testing right now, but it can also be used to generate Lighthouse performance reports: https://github.com/mfrachet/cypress-audit/blob/master/docs/lighthouse.md

I don't know if these satisfy your use case but I wanted to make sure we were considering the tools we already have before adding a new one.

**Comment by donaldthai** [comment]
> Have we considered using Cypress to take these benchmarks instead of Puppeteer? I just ask because we already have Cypress in the project and I believe it can be used to achieve everything here. Their docs have an example of using Cypress to take performance metrics: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__performance-metrics/cypress/integration/spec.js

I believe so but we came across this article by Cypress saying [it isn't meant to be used for performance testing.](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Can-Cypress-be-used-for-performance-testing) One of the key reasons why we decided on Puppeteer is that we are able to throttle the network connection. We also noticed that Puppeteer **v1** was already included in the project but decided to pull in **v7** since it got a bit frustrating to look at the api.

> We also have the cypress-audit plugin set up which we are only using for a11y testing right now, but it can also be used to generate Lighthouse performance reports: https://github.com/mfrachet/cypress-audit/blob/master/docs/lighthouse.md

Yea, I believe will end up using lighthouse later on for a more detailed report page performance.

> I don't know if these satisfy your use case but I wanted to make sure we were considering the tools we already have before adding a new one.

Yes, feel free to checkout our [doc on gathered tools](https://docs.google.com/document/d/1qF8fLZOKUAbDXGiMwWF4J2OjRzaQG9wm54CivZjpqv8/edit#heading=h.iqfo3yj7xhna). @duncan-truss can probably add some more comments.

**Comment by monfresh** [comment]
I'm getting an error. Looks like it can't find the user ID?

```
node puppeteer/benchmarking.js
(node:43994) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `button[value="9bda91d2-7a0c-4de1-ae02-b8cf8b4b858b"]` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/Users/moncef/projects/mymove/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1280:33)
    at /Users/moncef/projects/mymove/puppeteer/benchmarking.js:41:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:43994) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43994) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by monfresh** [comment]
Does this work only with certain browsers? Can we specify which browser to use? I launched the office app in Safari.

**Comment by monfresh** [comment]
Oh, it's because the user was not created due to a known bug with `make db_bandwidth_up` that I just fixed. Could you please rebase with master?

**Comment by donaldthai** [comment]
> Oh, it's because the user was not created due to a known bug with `make db_bandwidth_up` that I just fixed. Could you please rebase with master?

@monfresh just pushed up merge from master

**Comment by donaldthai** [comment]
> Does this work only with certain browsers? Can we specify which browser to use? I launched the office app in Safari.

By default, puppeteer uses chromium. I think the other supported browser is Firefox.

**Comment by monfresh** [comment]
Was the goal for this PR to only have a quick initial script in place? If so, do we have follow up stories to test the individual files, for both the TOO and TIO? Currently, from what I can tell, this only loads the first image in the doc viewer. We also want to test the performance of the other 2 files.

**Comment by donaldthai** [comment]
> Was the goal for this PR to only have a quick initial script in place? If so, do we have follow up stories to test the individual files, for both the TOO and TIO? Currently, from what I can tell, this only loads the first image in the doc viewer. We also want to test the performance of the other 2 files.

Yup, we have other stories to test all the files. We're just making sure the initial setup is good. @duncan-truss already got a huge head start on that in [his PR](https://github.com/transcom/mymove/pull/5902).

**Review by monfresh — APPROVED** [review]
Initial script works for me. Thanks for setting this up.

**Review by duncan-truss — APPROVED** [review]

**Pull request merged**
