### PR TITLE
Prime demo helper script

### PR DESCRIPTION
**Pull request by gidjin**
## Description

This script is to facilitate demoing the role of the prime in our monthly slice demos. It is a bash script that runs and uses the `prime-api-client` and `jq` to go through the steps of creating a payment request and generating an edi.

## Reviewer Notes

This can be run against local or staging. For staging you will need a move setup, you can probably reuse the backup from one of the recent demos.

### Tips
* This script now runs fetch-mto-updates to verify that the server is up. The result is cached though for subsequent use.
* Estimated weight can only be set once per shipment, the script will check for it and ask if it is not present or output it if it is present

## Setup

You will need some documents for proofs of service, any png, pdf, or jpg that doesn't contain sensitive information can be used. I can share some examples if needed.

Local MTO Id: 9c7b255c-2981-4bf8-839f-61c7458e2b4d

```sh
make db_dev_e2e_populate
make server_run
./scripts/prime-api-demo 9c7b255c-2981-4bf8-839f-61c7458e2b4d local path/to/proof/of/service.png
```

Staging MTO that should work: 25e0ba4f-0a69-448b-9338-8ddd34a9bdb4
NOTE: Staging will require a CAC

```
./scripts/prime-api-demo 9c7b255c-2981-4bf8-839f-61c7458e2b4d api.stg.move.mil path/to/proof/of/service.png
```

## Code Review Verification Steps

* [ ] Request review from a member of a different team.

### CODE REVIEW

**Review by garrettqmartin8 — APPROVED** [review]
I hit the EDI generation error from the [bug](https://dp3.atlassian.net/browse/MB-4427) that I'm working on, but this script itself works nicely. Awesome work @gidjin and @reggieriser!

**Review by reggieriser — COMMENTED** [review]
Love the script.  Could we add a "usage" response for when `prime-api-demo` is executed with no parameters?  Right now, a pretty cryptic error is returned.

**Comment by reggieriser** [comment]
I tried to run it locally and now if I just do a `prime-api-demo <uuid>` it returns immediately (pretty sure this worked in the version I used in the slice demo).  If I do a `prime-api-demo <uuid> local` it starts the process fine.

**Review by reggieriser — APPROVED** [review]
LGTM!  Thanks for the changes!  :shipit:

**Pull request merged**
