### PR TITLE
MB-9265 add yellow alerts for missing weights

### PR DESCRIPTION
**Pull request by YanZ777**
## Description

Added in an alert to the review max billable weight sidebar area. 
Refactored the tests so they're a bit more isolated out. 
Broke up things into describes so it's easier to categorize the tests.
Added logic to the missing weight icon that shows up on the payment requests page in the billable weight component so that shipments that don't have a prime estimated weight also get the yellow icon.
Put in some safeties so that the tests don't stop emitting console messages.

## Reviewer Notes

_**We might want to merge [Pearl's PR](https://github.com/transcom/mymove/pull/7415) first since this branch is based off her hers.**_
(It's been merged)

Are all the tests added that should be added? Does the test breakdown make sense?

I didn't put in all the icons and alerts, a good amount existed already, but just putting in pictures because it's more clear what this work is related to.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make office_client_run
make server_run
```
Login as a TIO. 
Select the moves with either the locators of `MISHRW` or `NOESTW`
There should be flags (yellow icons) on the billable weight component next to the shipment on the payment requests page 
Go to the review billable weight page
On the edit max billable weight sidebar, there should an alert saying `Missing shipment weights may impact max billable weight.`.
When clicking through the shipments, depending on which move you picked, it will either have a missing prime estimated weight or a missing reweigh weight. 

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9265) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

image

The above image is included to make sure spacing between alerts is good, it may not necessarily reflect a normal scenario.

image

image

image

image

image

### CODE REVIEW

**Comment by YanZ777** [comment]
@lynzt @felipe-lee @kylehilltruss You've been tagged since the stuff I did cleans up the console messages.

**Review by cosburn — APPROVED** [review]
Looks good to me!

**Review by donaldthai — APPROVED** [review]
:shipit:

**Review by felipe-lee — APPROVED** [review]
Awesome, thank you for fixing the test console messages! 

(I only really reviewed for that and ran the tests locally, but you already have other approvals for the rest of it)

**Pull request merged**
