### PR TITLE
B-18633 Actual Move Date not in the future backend 

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

Integration PR: https://github.com/transcom/mymove/pull/12262

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Create a PPM move
2. Login as a SC, edit and submit the move
3. As customer click Upload PPM documents
4. Enter Departure Date(it is required, this is the same as actual move date)
5. Verify seeing "UpdateError" when attempting to set date in the future

## Screenshots
Screenshot 2024-03-18 at 10 40 44 AM

### CODE REVIEW

**Review by WeatherfordAaron — APPROVED** [review]
lgtm

**Comment by JamesHawks224** [comment]
verify rpt.
there are diffs.
[B18633-12327.verify_rpt.txt](https://github.com/transcom/mymove/files/14873390/B18633-12327.verify_rpt.txt)

**Comment by KonstanceH** [comment]
> verify rpt. there are diffs. [B18633-12327.verify_rpt.txt](https://github.com/transcom/mymove/files/14873390/B18633-12327.verify_rpt.txt)

All of the diffs are correct and complete

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
