### PR TITLE
MAIN B-18631 All shipment weight values displayed sc closeout

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18631](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18631)

INT PR: https://github.com/transcom/mymove/pull/12264
Merge Fix from Brooklyn: https://github.com/transcom/mymove/commit/58209654abbfc213f5c44db41ad3fd3fe1a4abb7

## Summary

This adds the ability to see all HHG shipment weights while Closeout SC is closing out a member's PPM. 
This is to be displayed to the closeout counselor during their review of the PPM weights.

### How to test
Test using `ApprovedMoveWithPPMWeightTicketOfficeWithHHG` or create your own move.

With `ApprovedMoveWithPPMWeightTicketOfficeWithHHG`:
1. Use `ApprovedMoveWithPPMWeightTicketOfficeWithHHG` testharness.
2. Find the move as Closeout SC -> review the documents -> You should see `Estimated Weight` and `Approved Weight` above `PPM 1` on the right side bar.

With your own move:
1. Create a move with at least one HHG and a PPM shipment.
2. As a SC -> Submit the move.
3. As a TOO -> Approve HHG.
4. As a Prime -> `Update Shipment` in Prime Sim for the HHG move.
5. Fill in the appropriate fields and make note of your `Actual Weight` and `Estimated Weight`.
6. As a customer -> Upload your PPM documents.
7. As a closeout SC -> use the search function to find the move.
8. Review the PPM document and you should see `Estimated Weight` and `Approved Weight` above `PPM 1` on the right side bar.

## Screenshots
image

### CODE REVIEW

**Comment by taeJungCaci** [comment]
closing this since Main is still locked.

**Comment by JamesHawks224** [comment]
Verify rpt.
there was diffs.
[B18631-12343.verify_rpt.txt](https://github.com/transcom/mymove/files/14874104/B18631-12343.verify_rpt.txt)

**Review by JamesHawks224 — APPROVED** [review]
LGTM.

**Review by brooklyn-welsh — APPROVED** [review]
LGTM ✅

**Pull request merged**
