### PR TITLE
B 19785 add spouse pro gear payment packet integration

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

This PR updates the payment packet to show the customer's spouse gear entitlement.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Create or use any existing move
2. Login as a SC
3. Edit and submit move
4. Refresh page **
5. Click "Download Payment Packet"
6. Verify in packet the spouse entitlement is populated
** or login as TOO and find move

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### _Before_
Spouse Gear Before

### _After_
Screenshot 2024-05-13 at 8 21 25 AM

### CODE REVIEW

**Comment by taeJungCaci** [comment]
Not sure if I am doing something wrong, but mine is still showing 0 when I had put a spouse pro gear weight

**Comment by taeJungCaci** [comment]
This payment packet is supposed to get downloaded after the Closeout SC approves the PPM Documents I believe. and this is where I am seeing 0

**Comment by taeJungCaci** [comment]
So I think the problem I was having was that when I as a customer submits PPM Documents and have spouse pro gear filled in there -> then Closeout SC approves -> then download the Payment packet -> The Spouse pro gear entitlement shows 0. Should this show 0?

**Review by taeJungCaci — APPROVED** [review]
LGTM!

**Review by WeatherfordAaron — APPROVED** [review]
sorry it took so long. I was getting weird errors just trying to make a move. This morning I was able to test and LGTM! 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽 👽

**Pull request merged**
