### PR TITLE
Adding shauna keating's cac migration

### PR DESCRIPTION
**Pull request by shimonacarvalho**
## Description

Adding shauna keating's cac. Shauna is design on milmove.

## Related
[[MB-567] Prime API: Internal Testing for Product/Design - Jira](https://dp3.atlassian.net/browse/MB-567)

[MB-567]: https://dp3.atlassian.net/browse/MB-567

### CODE REVIEW

**Comment by shimonacarvalho** [comment]
@chrisgilmerproj I am doing that step now - the instructions said "make a PR" prior to the step about uploading to experimental and staging. You were quick on the draw.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj I am doing that step now - the instructions said "make a PR" prior to the step about uploading to experimental and staging. You were quick on the draw.

I try not to slow people down :) If you want to send another PR that updates the docs to say "Upload before sending a PR" that would be fine. It's up to you.

**Comment by shimonacarvalho** [comment]
Actually I'm getting an error on the upload... seen this before?

```Testing migrations ... (This could be several minutes!)
Destroying the milmove-db-deployed-migrations docker database container...
docker rm -f milmove-db-deployed-migrations || echo "No database container"
Error: No such container: milmove-db-deployed-migrations
No database container
rm -fr mnt/db_deployed_migrations # delete mount directory if exists
brew services stop postgresql 2> /dev/null || true
Starting the milmove-db-deployed-migrations docker database container...
# If running do nothing, if not running try to start, if can't start then run
docker start milmove-db-deployed-migrations || \
		docker run -d --name milmove-db-deployed-migrations \
			-e POSTGRES_PASSWORD=mysecretpassword \
			-p 5434:5432\
			postgres:10.12
Error response from daemon: No such container: milmove-db-deployed-migrations
Error: failed to start containers: milmove-db-deployed-migrations
Unable to find image 'postgres:10.12' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/postgres/manifests/10.12: Service Unavailable.
See 'docker run --help'.
make: *** [db_deployed_migrations_start] Error 125
```
I tried docker pull postgres:10.12 but that failed too.

**Comment by chrisgilmerproj** [comment]
> Actually I'm getting an error on the upload... seen this before?
> 
> ```
> Destroying the milmove-db-deployed-migrations docker database container...
> docker rm -f milmove-db-deployed-migrations || echo "No database container"
> Error: No such container: milmove-db-deployed-migrations
> No database container
> rm -fr mnt/db_deployed_migrations # delete mount directory if exists
> brew services stop postgresql 2> /dev/null || true
> Starting the milmove-db-deployed-migrations docker database container...
> # If running do nothing, if not running try to start, if can't start then run
> docker start milmove-db-deployed-migrations || \
> 		docker run -d --name milmove-db-deployed-migrations \
> 			-e POSTGRES_PASSWORD=mysecretpassword \
> 			-p 5434:5432\
> 			postgres:10.12
> Error response from daemon: No such container: milmove-db-deployed-migrations
> Error: failed to start containers: milmove-db-deployed-migrations
> Unable to find image 'postgres:10.12' locally
> docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/postgres/manifests/10.12: Service Unavailable.
> See 'docker run --help'.
> make: *** [db_deployed_migrations_start] Error 125
> ```
> 
> I tried docker pull postgres:10.12 but that failed too.

Run `docker pull postgres:10.12`

**Comment by shimonacarvalho** [comment]
I did try `docker pull postgress:10.12` it failed.

```
>  docker pull postgres:10.12
Error response from daemon: Get https://registry-1.docker.io/v2/library/postgres/manifests/10.12: Service Unavailable
```

**Comment by chrisgilmerproj** [comment]
I don't know what is the issue. The output should be this:

```
$ docker pull postgres:10.12
10.12: Pulling from library/postgres
Digest: sha256:73d3ac7b17b8cd2122d27026ec3552080e8aaea95fef0b6e671fa795ac547f94
Status: Image is up to date for postgres:10.12
docker.io/library/postgres:10.12
```

And it doesn't look like docker is having any issues: https://status.docker.com/

So maybe restart your docker instance?

**Pull request merged**
