### PR TITLE
B 18560

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary
Update Transportation Offices - needed for go-live

## Verification Steps for the Author

These are to be checked by the author.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1.  Log in as Army or Airforce User
2.  Complete Profile Pages:
3. Where are you moving
4. Create your Profile: Army or Air Force
5. Name
6. Your contact info
7. Current Address
8. Backup address
9. Backup contact        
10. Click Add Orders
11. Under Current duty location, validate the following offices can be selected:
12. ·         PPPO NAVSUP FLC San Diego - USN
13. ·         PPPO West Point/ USMA - USA
14. ·         PPPO USAG Miami - USA
15.  
16. Under New duty Location, validate the following offices can be selected:
17. ·         PPPO NAVSUP FLC San Diego - USN
18. ·         PPPO West Point/ USMA - USA
19. ·         PPPO USAG Miami - USA
20.  
21. Click Next
22. Upload your orders and click Next
23. Click Set up your shipments
24. Click Next
25. Select PPM
26. Click Next
27. Add Origin and Destination Addresses
28. Under Closeout Office, validate the following offices can be selected:
29. ·         PPPO NAVSUP FLC San Diego - USN
30. ·         PPPO West Point/ USMA - USA
31. ·         PPPO USAG Miami - USA
32.  
33. Validate the following can not be selected:
34. ·         PPPO Base San Pedro – USCG

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
LGTM!

**Comment by traskowskycaci** [comment]
> 12\. PPPO NAVSUP FLC San Diego - USN

For this one, had a slightly different result from that value on the origin and destination duty location, the other two matched exactly. 
image

Then on the PPM closeout office page, it did match exactly:
image

**Comment by traskowskycaci** [comment]
> this is due to - the duty locations drop down pulls from duty_locations/names table- which can be different than the dropdown of closeout offices that is derived from the transportation_offices table where 'provides services counseling' is true so the text for the name could be differnt and the duty location for this wasnt modified

Gotcha, so no worries then. Approving!

**Review by traskowskycaci — APPROVED** [review]

**Review by cameroncaci — APPROVED** [review]
commits match

**Pull request merged**
