### PR TITLE
Doc on "how to query cloudwatch logs"

### PR DESCRIPTION
**Pull request by rdhariwal**
## Description

This PR documents how to easily query logs in cloudwatch using insights. Insights allow us to parse logs and query against them using sql like syntax and crunch through large amount of data easily.

## Code Review Verification Steps

* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/163436835) for this change

### CODE REVIEW

**Comment by jim** [comment]
@rdhariwal This looks like it would be helpful to folks. Is this still WIP or are you ready for a review?

**Comment by rdhariwal** [comment]
> @rdhariwal This looks like it would be helpful to folks. Is this still WIP or are you ready for a review?

ahh great question, this pr started out as a thought experiment but morphed into a cli tool see this [pr](https://github.com/transcom/ppp-infra/pull/494) 

I meant to delete this draft pr entirely as we went with a cli tool approach but if you believe others might find value in gui driven approach I can do an additional clean up pass.

**Comment by rdhariwal** [comment]
> > @rdhariwal This looks like it would be helpful to folks. Is this still WIP or are you ready for a review?
> 
> ahh great question, this pr started out as a thought experiment but morphed into a cli tool see this [pr](https://github.com/transcom/ppp-infra/pull/494)
> 
> I meant to delete this draft pr entirely as we went with a cli tool approach but if you believe others might find value in gui driven approach I can do an additional clean up pass.

@jim ^^

**Comment by jim** [comment]
@rdhariwal At this point let's just go with the CLI. I'll close this PR.

**Pull request closed without merging**
