### PR TITLE
Adds office instructions for payment request [finishes #159244893]

### PR DESCRIPTION
**Pull request by stangah**
## Description

Implements instructions for office users to complete the payment request process ([wireframe](http://slicedbreadclient.com/dds/dp3/wireframes/BackOffice/round8/PPM_expansion_office_generate_paperwork.pdf))

## Reviewer Notes

- The attachment packet generation button becomes disabled when clicked, and un-disables when the request is returned. Seemed like a nice thing to do when the request might take a bit of time
- When the upload button is clicked, a query string is passed along to the url which sets the `SHIPMENT_SUMMARY` document type in the uploader, then the uploader clears the query string from the route. Also seemed like a nice thing to do

## Code Review Verification Steps

* [ ] End to end tests pass (`make e2e_test`).
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/blob/master/docs/backend.md#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] Any migrations/schema changes also update the diagram in docs/schema/dp3.sqs
* [ ] There are no aXe warnings for UI.
* [ ] This works in IE.
* Any new client dependencies (Google Analytics, hosted libraries, CDNs, etc) have been:
  * [ ] Communicated to @willowbl00
  * [ ] Added to the list of [network dependencies](https://github.com/transcom/mymove#client-network-dependencies)
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/159244893) for this change

## Screenshots

screenshot 2018-08-08 16 37 12
screenshot 2018-08-08 16 37 19

### CODE REVIEW

**Comment by stangah** [comment]
@tinyels I think this should be good to go now

**Comment by tinyels** [comment]
This is happening on the payment request page:
image

@stangah can you resolve the conflict and merge master--I think that will fix it, but I cannot test/review without making a payment request.

**Comment by tinyels** [comment]
You can upload pngs as move documents but if you do this happens:
image

**Comment by stangah** [comment]
@tinyels Can you send me what files you think are breaking it? I was able to get some PNGs to work so I wonder if it's some more malformed files, either PNG or PDF

**Comment by tinyels** [comment]
Still getting this error:
image

Steps to reproduce:

1. change to branch
2. reset to e2e db
3. view details for move FDXTIU
4. use document viewer to add these docs as storage and expense items:
image
weight-ticket
5. Try to download attachments

**Pull request merged**
