### PR TITLE
B 17984 update reminder email

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

Merge into main from integration
https://github.com/transcom/mymove/pull/12014

### How to test

1. Create a move with an estimateDepartureDate that is <= 14 days from today, and has no null estimate values(incentive, weight), and set the personal email to one you can access
2. Approve this move as a service counselor
3. Run `aws-vault exec transcom-gov-dev` to get into the subshell
4. Run `go run ./cmd/milmove-tasks send-payment-reminder --email-backend=ses --aws-ses-domain=devlocal.dp3.us  --aws-ses-region=us-gov-west-1`
5. You should get a payment reminder email in a couple minutes max

## Screenshots
Screenshot 2024-02-21 at 10 36 59 AM

### CODE REVIEW

**Review by WeatherfordAaron — APPROVED** [review]
LGTM

**Comment by JamesHawks224** [comment]
Verification rpt done.
There were diffs.

[B17984.verify_rpt.txt](https://github.com/transcom/mymove/files/14377623/B17984.verify_rpt.txt)

**Comment by KonstanceH** [comment]
> Looks like you are missing this commit that is in your Integration branch: [fa6f8a6](https://github.com/transcom/mymove/commit/fa6f8a6e7bbdd2c5b8ea913f9a6787079f49623a)
> 
> I guess I can still approve if you think those changes are not gonna affect much (the date).

Ah I made that change when I first started troubleshooting, I went ahead and reverted it back to the old date.

**Comment by KonstanceH** [comment]
> Verification rpt done. There were diffs.
> 
> [B17984.verify_rpt.txt](https://github.com/transcom/mymove/files/14377623/B17984.verify_rpt.txt)

I reverted the old date back so that should resolve the first diff. 
The rest of the diffs are correct and complete.

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
