### PR TITLE
Update the PKCS7 file to v5.9

### PR DESCRIPTION
**Pull request by chtakahashi**
The current PKCS7 file, v5.6, contains expired certificate authorities. We need to update to the latest which is v5.9

- Followed the instructions in the README [here](https://github.com/transcom/mymove/blob/main/config/tls/README.md#updating-the-dod-certificate-authority-package)
  - Updated the instructions with new file paths after finished.

Ran the following commands to update the milmove cert package:
```
openssl pkcs7 -inform DER -outform PEM -in config/tls/Certificates_PKCS7_v5.9_DoD.der.p7b -print_certs > tmp/certificate_bundle.cer
```
```
openssl crl2pkcs7 -nocrl -certfile config/tls/ECA_Root_CA_4.cer -certfile config/tls/IdenTrust-ECA-S23.cer -certfile tmp/certificate_bundle.cer -outform DER -out config/tls/milmove-cert-bundle.p7b
```

Update:
- Find all replace'd `Certificates_PKCS7_v5.6_DoD.der.p7b` for `Certificates_PKCS7_v5.9_DoD.der.p7b`

### CODE REVIEW

**Comment by chtakahashi** [comment]
I realize that the latest update still leaves https://github.com/transcom/mymove/blob/29a2c8a1827f5be3e15e098d4426b36e4b67503b/Dockerfile#L18 as v5.9 when it needs to be renamed.

**Comment by rogeruiz** [comment]
I'm working through reviewing this now.

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

**Review by CoryAtTruss — APPROVED** [review]
LGTM too

**Review by ahobson — APPROVED** [review]
Thank you! Looks good

**Pull request merged**
