### PR TITLE
[MB-11630] Remove validation for Prime UI forms for address

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

The front end validation for certain shipments will be disabled. These shipments will be NTS and NTS-R. Before setting the component schema, the shipmentType will be checked to ensure if the address field will need to be validated in the front end or not. 

## Setup to Run Your Code

<details>
<summary>💻 You will need to use <b>two separate terminals</b> to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the server locally.

```sh
make server_run
```
</details>

### Additional steps

1. Create a move available to prime that includes NTS or NTS-R shipments.
2. Edit one of these NTSx shipments
3. Leave the destination address blank since they are not necessary for these shipment types
4. The form should not suggest that things are required or invalid for the destination address fields

## Verification Steps for Author

These are to be checked by the author.

- [ ] ~~Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)~~
- [ ] ~~Request review from a member of a different team.~~
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Documentation

- [x] [Confluence page exists and is readable under the Prime Simulator Outcome page](https://dp3.atlassian.net/wiki/spaces/MT/pages/1653309507/Prime+UI+validations).

## Screenshots

<details>
<summary>📸  Pickup address with validation - Screenshot(s)</summary>

Captura de Pantalla 2022-02-15 a la(s) 6 21 22 p m

</details>

<details>
<summary>📸  Destination address with validation - Screenshot(s)</summary>

Captura de Pantalla 2022-02-15 a la(s) 6 21 26 p m

</details>

### CODE REVIEW

**Comment by rogeruiz** [comment]
Drafting this PR as it's going to be trickier than I original thought. I'm going to update the logic in here and it should be covered by the current criteria for this ticket. But for now this work is not "fully complete" because of what I've read in #8139 about NTS-R requiring a destination address.

I personally think having validation for destination addresses for NTS-R is required, while the NTS shipments should not have a destination address field in the UI.

**Comment by rogeruiz** [comment]
Okay having thought about this a little longer, I don't want to overcomplicate the Prime Simulator with edge-case logic. While the trade-off here is that it will lead to a different UX than the Office App, the Prime Simulator does not need to match UX with the office application and the backend validation and new documentation is enough to catch edge-cases around destination address fields.

**Comment by rogeruiz** [comment]
Okay having thought about this a little longer, I don't want to overcomplicate the Prime Simulator with edge-case logic. While the trade-off here is that it will lead to a different UX than the Office App, the Prime Simulator does not need to match UX with the office application and the backend validation and new documentation is enough to catch edge-cases around destination address fields.

**Comment by rogeruiz** [comment]
@mlm55 thank you. I missed this in my testing. I'll move the card back to Started.

**Comment by rogeruiz** [comment]
@mergifyio refresh

**Comment by rogeruiz** [comment]
whoops. I meant @mergifyio rebase

**Comment by rogeruiz** [comment]
@mergifyio rebase

**Review by donaldthai — APPROVED** [review]
Seems to be working for the update address page

**Pull request merged**
