### PR TITLE
MB-7384 services counselor is able to add shipment

### PR DESCRIPTION
**Pull request by YanZ777**
## Description

Add a new page to handle adding a shipment.

## Reviewer Notes

Refactored the shipment form to accept submit handler as well as the move task order ID.

Questions:
1. What do I do for the destination address? Should that be required on the form?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make office_client_run
make_server_run
```
Sign in as a services counselor on the office app. 
Click on a move. 
Click on the "Add a shipment" button. 
Fill out the form and hit save.

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7384) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

image

### CODE REVIEW

**Review by felipe-lee — APPROVED** [review]
LGTM, though I'd like another set of eyes in case my friday brain missed things. I tested locally and was able to add shipments successfully!

**Comment by felipe-lee** [comment]
Oh and to answer your question, AFAIK, destination address should be ok to just leave the zip still. Unless you mean something else.

**Review by amanda5iu — APPROVED** [review]
Works like a dream!

**Comment by YanZ777** [comment]
> Oh and to answer your question, AFAIK, destination address should be ok to just leave the zip still. Unless you mean something else.

Yep, that was my question!

**Pull request merged**
