### PR TITLE
MB-4739 TOO tag requested shipments move details page

### PR DESCRIPTION
**Pull request by donaldthai**
## Description

> GIVEN I am the TOO, WHEN there are shipments awaiting approval, THEN I want to be able to see a notification alerting me to the number of requested shipments requiring attention.

Tags are now rendered on the left nav for `requested shipments`. The number represents how many shipments still needs approval.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make server_run 
make office_client_run
```

Test
1. Log in as TOO
2. Click on any move that is in `New move` status

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4739) for this change

## Screenshots

image

### CODE REVIEW

**Review by Ryan-Koch — APPROVED** [review]

**Review by jenniferlynparsons — APPROVED** [review]
Looks good.

**Review by brooksr4 — CHANGES_REQUESTED** [review]
When the screen shrinks in width the tag looks weird. Its height is the height of its container. Let's give the tag a fixed height of 18px, and lets make center it vertically when there is a carriage return in the container.

**Comment by donaldthai** [comment]
> When the screen shrinks in width the tag looks weird. Its height is the height of its container. Let's give the tag a fixed height of 18px, and lets make center it vertically when there is a carriage return in the container.

@brooksr4 alright, got the height fixed and vertical centered:
image

**Review by brooksr4 — APPROVED** [review]
Looks great!

**Pull request merged**
