### PR TITLE
Mb 14327 cant delete orders once submitted

### PR DESCRIPTION
**Pull request by LeDeep**
## [Jira ticket](https://dp3.atlassian.net/browse/MB-14327)

Per Prakit’s comment in the ticket users can now no longer delete their orders once submitted. So, if their move is in `DRAFT` status, they can delete a previously uploaded order. Once they submit and the move goes to `SUBMITTED` status, they can no longer delete orders. They can still upload new or updated orders.

### How to test

1. Go through move creation and upload your orders
2. Before submitting the move, you will see the `Delete` button and are able to delete the orders file
3. After submitting the move, you will not see the `Delete` button as you should not be able to delete orders after submitting a move.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by ahobson** [comment]
Huh. Is it sufficient to only put the check in the frontend? A sufficiently advanced user could bypass the check, so I'd be included to also put something on the backend. Thoughts?

**Comment by ahobson** [comment]
Do you think it would be worthwhile to add a playwright integration test? I don't think it would be too onerous and would provide a good sanity check

**Comment by LeDeep** [comment]
> Huh. Is it sufficient to only put the check in the frontend? A sufficiently advanced user could bypass the check, so I'd be inclined to also put something on the backend. Thoughts?

Yeah, it's probably a good idea. I'll make the update.

**Review by ahobson — APPROVED** [review]
Looks good to me. I'd love to get thoughts from other folks that have worked more with our services to make sure this is following our current best practices (I think it does, but I'm not knee deep in them on a daily basis).

**Pull request merged**
