### PR TITLE
[MB-11011] Fix inability of a SC to create an NTS-Release shipment

### PR DESCRIPTION
**Pull request by reggieriser**
## Summary

Prior to this PR, a services counselor (SC) was unable to successfully create an NTS-Release shipment.  There appeared to be two problems:

- `requestedPickupDate` was marked as required by the API but an NTS-Release shipment does not have a pickup date.
- `requestedDeliveryDate` was not passed as part of the API but needed by an NTS-Release shipment.

This PR fixes both of those issues and puts in associated tests.  I also refactored a little along the way.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```
</details>

### Additional steps

See the JIRA ticket for steps that were used to demonstrate the problem.  To try this PR locally, pick a move code from the services counselor queue and add a new NTS-Release shipment.  Verify that it saves without errors (may want to inspect to see the XHR requests), then look in the database that all data is persisted as expected to the `mto_shipments` table.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### CODE REVIEW

**Review by amanda5iu — COMMENTED** [review]
The new shipment gets saved! It doesn't appear to save the shipment weight value though - that row appears blank in the summary, even after I go in to edit it. 

Also not sure if this is related, but after I save my changes and return to move details, I'm scrolled to the bottom of the move details page.

**Comment by reggieriser** [comment]
> The new shipment gets saved! It doesn't appear to save the shipment weight value though - that row appears blank in the summary, even after I go in to edit it.

Good catch!  The shipment weight was being saved correctly in the `nts_recorded_weight` field, but apparently the pre-existing shipment card was still reading `prime_actual_weight`.  I've fixed that, so please try it again if you can and see if it looks OK now.

> Also not sure if this is related, but after I save my changes and return to move details, I'm scrolled to the bottom of the move details page.

I don't think it's related, but it is a bit odd and just happened to me too.  I assume it's a pre-existing issue since I didn't change any front-end code (that is, until my most recent commit which came after you initially tested).  I'll dig into this a little but we may need a separate story so as not to hold up this PR.

**Review by leia-sefkin — APPROVED** [review]
Code looks good - appreciate the refactors and test cleanup. I was able to add the new shipment type successfully with no errors in the console. Thanks for detailed instructions!

**Review by mlm55 — APPROVED** [review]
lgtm! was able to add an ntsr shipment and didn't see any errors. also verified that the displayed shipment weight is ntsRecordedWeight rather than primeActualWeight

**Review by amanda5iu — APPROVED** [review]
Reggie and I discussed this in [Slack](https://ustcdp3.slack.com/archives/C029R9LDTD4/p1642617126071600?thread_ts=1642541157.043200&cid=C029R9LDTD4). The SC can create and save a new NTS-release successfully, but editing doesn't work. This should probably be addressed in a separate ticket so as not to hold up this work.

**Pull request merged**
