### PR TITLE
[MB-9425] Weight Summary Component Hookup

### PR DESCRIPTION
**Pull request by pearl-truss**
## Description

This PR hooked the billable weight to the weight summary component and added test for the flags that appear if a shipment is overweight or if the max billable weight has been exceeded

## Reviewer Notes

Do the test make sense? Are there any other fields displayed on the weight summary component that need to be hooked in or adjusted?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_run client_run
```
- In the office app, log in as a TIO
- On the payment request tab, select Review Weights and in the side bar confirm that the weight summary card displays as expected on the edit billable weights view of the side bar
- Click the 'Review Shipment weights' button and confirm that the weight summary component card also displays as expected on the review billable weights view of the side bar
- Choose a variety of moves to see a range of the different variations of weight summary card (i.e if there are flags or not). NOTE: PKBWFC is a move code to use to see a weight summary card with no flags

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9425) for this change

## Screenshots
Screen Shot 2021-09-21 at 10 16 35 AM
Screen Shot 2021-09-21 at 10 18 25 AM
Screen Shot 2021-09-21 at 10 19 41 AM

### CODE REVIEW

**Review by YanZ777 — COMMENTED** [review]
Code looks good! 
Could we clean up the console errors in the devtools that the weight summary is generating though?

**Comment by pearl-truss** [comment]
> Code looks good!
> Could we clean up the console errors in the devtools that the weight summary is generating though?
> Also, the Review Billable Weight test is emitting a console log, it looks like it's related to the console errors in the devtools (stuff is required but it's not there).

this is addressed

**Review by donaldthai — APPROVED** [review]
:shipit:

**Review by YanZ777 — APPROVED** [review]
Thanks for fixing the console errors!

**Review by cosburn — APPROVED** [review]

**Pull request merged**
