### PR TITLE
MAIN B-18739 and b 18740 ppm aoa and packet download from multi move dashboard

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION PR](https://github.com/transcom/mymove/pull/12424)

## [Agility ticket B-18739](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18739)

**NOTE**
There will be some discrepancies between this `main` PR and the `integrationTesting` PR due to adding in some deleted code that was removed from `integrationTesting`

## Summary

Adding the PPM Packet & AOA Packet download functionality to the multi move dashboard. Since these packets are available at the shipment level, the customer will need to expand the move in order to see the download button, but ain't no thing.

I wasn't super hot on how the whole dropdown button looked inside the shipment container, so I updated the dropdown button to include a `minimal` parameter that removes the outline & box shadow of the button, which really cleaned it up nicely.

This PR does the following:
- updates `ButtonDropdown` component to take in `minimal` parameter
- added flash messaging capabilities to the Multi-Move dashboard
- added conditional logic that renders the PPM packet download button
- added logic that determines which buttons the dropdown shows based on `ppmShipment` values
- updated css to use `@media` that changes flex direction on mobile
- added to multi move test data to handle PPM download button use cases
- updated all relevant tests based on updated code

**NOTE**
I am also throwing in some swagger code that was removed (IT WAS ME OKAY) on accident [in this commit](https://github.com/transcom/mymove/commit/8e20a63d3df787213319af4f2a705d9364e3de1f). This commit is already in `main` so just ensuring it is back in `integrationTesting`.

### How to test

1. Access MM as a customer
2. Go through the process of creating a move with a couple of PPM shipments, sign it
3. Go through the SC process and approve
4. Go through the TOO process and make approvals
5. Sign back in as the customer and you should now see the download button visible on the shipment

## Screenshots
Screenshot 2024-04-05 at 1 36 21 PM

Screenshot 2024-04-05 at 1 36 44 PM

Screenshot 2024-04-05 at 1 37 04 PM

Screenshot 2024-04-05 at 1 36 54 PM

Screenshot 2024-04-05 at 2 20 25 PM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Can I get a Happo check?

**Comment by traskowskycaci** [comment]
> Can I get a Happo check?

Was just trying to get you that but it's making me log in and it never has before. Anyone else?

**Comment by danieljordan-caci** [comment]
> > Can I get a Happo check?
> 
> Was just trying to get you that but it's making me log in and it never has before. Anyone else?

Workin' fine for me

**Review by traskowskycaci — APPROVED** [review]
Mostly matches up, and I see the swagger code in your integration branch is already in main. Nice!

**Review by cameroncaci — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]

**Pull request merged**
