### PR TITLE
MB-14342 Add tags to reviewed shipment cards for SC

### PR DESCRIPTION
**Pull request by scottmries**
## Summary

This adds a "Packet Ready for Download" tag to a PPM shipment card when the SC has either approved or excluded it, and a "Sent to Customer" tag when they have rejected it.

The component is available in Storybook at `Office Components / Shipment Display / PPM Service Counselor [Approved/Rejected/Excluded]`, which can be found [at this link](https://output.circle-artifacts.com/output/job/7ee03b94-a9fe-48f7-ae67-25c9aad8ab3d/artifacts/0/storybook/index.html?path=/story/office-components-shipment-display--ppm-shipment-service-counselor-approved).

## Setup to Run Your Code

<details>
<summary>💻 You will only need Storybook to test this locally.</summary>

##### Terminal 1

Start Storybook locally.

```sh
make storybook
```

</details>

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

### CODE REVIEW

**Review by bellex3 — COMMENTED** [review]
Storybook renders the correct tags on the shipment cards. I'm not in design so @rileyorr can also double check, but it looks to me the font-size for the tags should be 16px. It is currently 13px. Also, the background color of the tags should be "#F0F0F0". It is currently "#ecf1f7".

**Comment by scottmries** [comment]
@bellex3 Good eye, thanks for pointing it out. There are some other tags that can also appear in that location, so I had originally used their style. I went ahead and updated just these tags to match the design here, though. I updated the Storybook link, too.

**Review by bellex3 — APPROVED** [review]
LGTM. Approved

**Comment by rileyorr** [comment]
+1 Great catch @bellex3! 

What's the padding between the `PPM` H3 and the tag? It should be 16px, but it looks like those two elements may be a bit closer together in storybook. I added screenshots from Storybook and Figma below in case that's a helpful reference: 

**Storybook**

Screenshot 2023-01-31 at 10 12 53 AM

**Figma**
Screenshot 2023-01-31 at 10 13 30 AM

**Comment by scottmries** [comment]
@rileyorr That's fixed now, and the Storybook link is updated.

**Review by rileyorr — APPROVED** [review]
@scottmries thank you for making that update! The storybook components LGTM

**Pull request merged**
