### PR TITLE
B 17716 tooltip component update

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Created custom component for a tooltip that displays text on hover. Takes in three props:
`position`: can be either `left`, `right`, `bottom`, or `top` but when not passed in it defaults to `top`
`icon`: this displays the `<FontAwesomeIcon />` with passed in icon parameter. If left blank, it defaults to `circle-question`
`text`: this is the text that will display when hovering over or clicking the icon
`color`: this changes the color of the tooltip icon - can be HTML color code (like `#FF0000` for red) - default color is `blue`

An example of the ToolTip being used with all the bells & whistles and overrides defaults:
`<ToolTip text="this is the text that shows on hover" position="right" icon="circle-exclamation" color="#E43131" />`

Or you can keep it short and simple like this - which will display it on top with a blue `circle-question` icon:
`<ToolTip text="just keep it simple" />

I left the size of the text box fixed to keep positioning consistent. This will allow for constant results when displaying the text boxes on hover.

I also implemented a `useRef` functionality that hides all of the tooltip boxes when clicked outside of the `<div>` containing the tooltip. Multiple tooltips can be displayed and I did not implement an `onMouseLeave` function in case the office user needs to copy something and figured it'd be nice to leave the tooltip text displayed because hovering over a small icon can be a little finicky.

### Setup to Run the Code

- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Find any spot in the code and implement `<HoverTooltip text="Test text or whatever" icon="circle-question" position="left" /> or whatever you wish to pass in for initial props
2. Start the server & client and log in as an office user and navigate to where you implemented the tool tip
3. Hover over the icon and confirm text box displays in correct position
4. Click outside of the tooltip and confirm text box disappears

### CODE REVIEW

**Comment by cameroncaci** [comment]
What is the main difference between this tooltip and src/shared/ToolTip?

**Comment by danieljordan-caci** [comment]
> What is the main difference between this tooltip and src/shared/ToolTip?
No significant difference other than it was easier to create a new component (at least for me) than editing an older component. I tried messing with the ToolTip component and I was having a hard time getting the positioning to do what I wanted.

Also the ToolTip component has dated React code (like `class ToolTip extends Component`) instead of the modern React way of exporting components.

**Comment by cameroncaci** [comment]
Thanks for the clarification, I would recommend replacing the old tooltip entirely then to ensure there aren't any inconsistencies. It looks like it was only used in two other places so it should be a quick fix (Just gotta check to make sure it looks right on the actual page).

`src/scenes/Office/MoveInfo.jsx`
`src/scenes/Office/Ppm/PaymentsPanel.jsx`

Then renaming from `CustomToolTip` to just `ToolTip`

**Comment by danieljordan-caci** [comment]
> Thanks for the clarification, I would recommend replacing the old tooltip entirely then to ensure there aren't any inconsistencies. It looks like it was only used in two other places so it should be a quick fix (Just gotta check to make sure it looks right on the actual page).
> 
> `src/scenes/Office/MoveInfo.jsx` `src/scenes/Office/Ppm/PaymentsPanel.jsx`
> 
> Then renaming from `CustomToolTip` to just `ToolTip`

Well.. There's also an `IconWithTooltip` component that has the same issue with the dated React code and was difficult to get it to do what I wanted. That is being used in two other places as well, `SubmittedPpmMoveDetails` and PpmMoveDetails`.

**Comment by cameroncaci** [comment]
> > Thanks for the clarification, I would recommend replacing the old tooltip entirely then to ensure there aren't any inconsistencies. It looks like it was only used in two other places so it should be a quick fix (Just gotta check to make sure it looks right on the actual page).
> > `src/scenes/Office/MoveInfo.jsx` `src/scenes/Office/Ppm/PaymentsPanel.jsx`
> > Then renaming from `CustomToolTip` to just `ToolTip`
> 
> Well.. There's also an `IconWithTooltip` component that has the same issue with the dated React code and was difficult to get it to do what I wanted. That is being used in two other places as well, `SubmittedPpmMoveDetails` and `PpmMoveDetails`.

That isn't fun or pretty.. Think it'd be a hassle to replace? I see you're using your current tooltip as an "icon tooltip" as well just like they seem to be doing with `IconWithTooltip`

**Comment by danieljordan-caci** [comment]
> > > Thanks for the clarification, I would recommend replacing the old tooltip entirely then to ensure there aren't any inconsistencies. It looks like it was only used in two other places so it should be a quick fix (Just gotta check to make sure it looks right on the actual page).
> > > `src/scenes/Office/MoveInfo.jsx` `src/scenes/Office/Ppm/PaymentsPanel.jsx`
> > > Then renaming from `CustomToolTip` to just `ToolTip`
> > 
> > 
> > Well.. There's also an `IconWithTooltip` component that has the same issue with the dated React code and was difficult to get it to do what I wanted. That is being used in two other places as well, `SubmittedPpmMoveDetails` and `PpmMoveDetails`.
> 
> That isn't fun or pretty.. Think it'd be a hassle to replace? I see you're using your current tooltip as an "icon tooltip" as well just like they seem to be doing with `IconWithTooltip`

I don't think it'll be a hassle to replace, it would be a hassle to try and get to these pages to confirm it looks alright haha. It's wombo combo of customer & office users seeing the tooltip that displays under specific situations. I don't mind putting in that work and I get what you're saying - get rid of the technical debt and replace what's being used with what has been created. I'm not against it - just might take a little poking and prodding.

**Comment by cameroncaci** [comment]
Depending on remaining story points we may need to create an issue ticket

**Comment by danieljordan-caci** [comment]
> Looks like the remaining story points allow making these changes per our standup today

Complete. Deleted the tech debt of the old ToolTip and replaced with new & hot ToolTip (formerly known as HoverTooltip)

**Review by TevinAdams — APPROVED** [review]
Code looks good. Tests are passing. Tooltip seems 508 Compliant.

**Comment by TevinAdams** [comment]
> @TevinAdams when you say seems 508 compliant... is that just the eye test or did you use a tool to verify?

I looked it up, looked at examples, and used a tool. Below is some sources I looked at. Not a 508 compliant expert as it gets deep but based on the sources I looked at it seemed 508 compliant to me.

Sources:
https://userway.org/contrast/?fg=000000&bg=ffffff
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
https://demos.telerik.com/aspnet-ajax/tooltip/examples/accessibility/defaultvb.aspx?show-source=true

**Review by deandreJones — APPROVED** [review]

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
