### PR TITLE
MB-12330: Service counselor can add a PPM shipment

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Summary

This pull request completes(!) the work to allow a Service Counselor user to create (and edit) a PPM shipment. Specifically, it allows users to click "Save and Continue" in order to update the values of an existing shipment on both pages of the form to add/edit a PPM shipment.

Completion of this story will also complete the following Jira stories:

* [MB-12301](https://dp3.atlassian.net/browse/MB-12301),
* [MB-12302](https://dp3.atlassian.net/browse/MB-12302), and
* [MB-12303](https://dp3.atlassian.net/browse/MB-12303).

This story also completes a significant amount of the work for [MB-11866](https://dp3.atlassian.net/browse/MB-11866), although I'll want to go in an add additional tests around that functionality in a future pull request, so I'm not marking that story as complete until that takes place.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make office_client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Login to the office application locally as a Service Counselor user, and select any move from the queue that will allow you to add a new shipment.
2. Use the dropdown to add a PPM shipment.
3. Fill out the first page of the add shipment form, then hit "Save and Continue".
4. Verify that you're taken to the second page, and that the "Incentive and Advance" and "Remarks" sections now display. Verify that the "No" radio button in the incentive and advance section is selected.
5. Select "Yes" in the incentive and advance section, and verify that the "Save" button is disabled.
6. Enter an amount larger than the maximum advance, and verify that the "Save" button is disabled with an error message displaying to the user.
7. Enter an amount smaller than the maximum advance, then click "Save."
8. Verify that the user is taken back to the Move Details page, and that the card displaying the PPM shipment displays "Yes, $[amount entered]" for "Amount Requested".
9. Click "Edit Shipment" for that shipment to go back to the Edit Shipment page. Change some of the values in the first page of the form, then click "Save and Continue" to go to the second page.
10. Select "No" in the incentive and advance section, then enter some text in the "Counselor remarks" field and click "Save."
11. Verify the following on the Move Details page (or by editing the shipment again):
  - That the "Amount requested" row displayed on the shipment card has changed to "No"
  - That the remarks entered display on the shipment card
  - That any values changed on the first page have been updated.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### CODE REVIEW

**Comment by kylehilltruss** [comment]
• https://my-milmove-pr-8951.mymove.sandbox.truss.coffee/
• https://admin-milmove-pr-8951.mymove.sandbox.truss.coffee/
• https://office-milmove-pr-8951.mymove.sandbox.truss.coffee/
• https://prime-milmove-pr-8951.mymove.sandbox.truss.coffee/

**Review by scottmries — APPROVED** [review]
LGTM! Adding and editing works as expected.

**Review by reggieriser — COMMENTED** [review]
LGTM.  Didn't see any issues in the code, although it may be worth a more front-end person reviewing too.

I tested everything out and did notice a few things (some of these are not necessarily blockers for the PR, but things we may want to address):
- if I hit "Yes" for SIT, then put in dates for the start/end, then remove the dates and choose "No" for SIT, the "Save and Continue" button is still disabled.  If you click "Yes" again, you'll see the dates are complaining about a value of "Invalid Date" which may be coming from the date box component.  I was fighting something similar on the prime simulator side but haven't figured out how to get around it (other than removing the validation entirely).
- there's a little funky formatting around the "Optional" marker on the secondary zips.  On Chrome on my machine, it bumps it to another line (presumably it's too much text to fit in the width above the text box).
- The AC for MB-12301 talks about a "Calculate SIT" button.  I know we moved that to the second page and another story, but we should get the AC adjusted before we UAT this.
- The AC for MB-12303 talks about the estimated incentive being stuck at 10k, but I think that's old text that we can take out since the incentive is being calculated now.
- When you edit a PPM and change a zip, it wipes out the previous advance (I believe that's happening on the backend).  I think that's expected, but just making sure.

**Comment by kylehilltruss** [comment]
> if I hit "Yes" for SIT, then put in dates for the start/end, then remove the dates and choose "No" for SIT, the "Save and Continue" button is still disabled. If you click "Yes" again, you'll see the dates are complaining about a value of "Invalid Date" which may be coming from the date box component. I was fighting something similar on the prime simulator side but haven't figured out how to get around it (other than removing the validation entirely).

Yeah, this isn't great -- I'll see if I can change it, but it's one of those "gosh, Yup validation sucks when you're dealing with artificial data types" things.

> there's a little funky formatting around the "Optional" marker on the secondary zips. On Chrome on my machine, it bumps it to another line (presumably it's too much text to fit in the width above the text box).

Dina called that out in the last PR around this last month. Not ideal but was surprisingly challenging to try and fix given how the project's MaskedTextField components calculate width with CSS.

> The AC for MB-12301 talks about a "Calculate SIT" button. I know we moved that to the second page and another story, but we should get the AC adjusted before we UAT this. 
> The AC for MB-12303 talks about the estimated incentive being stuck at 10k, but I think that's old text that we can take out since the incentive is being calculated now.

Yep -- I'll ask about changing the ACs.

> When you edit a PPM and change a zip, it wipes out the previous advance (I believe that's happening on the backend). I think that's expected, but just making sure.

That seems... correct? Certainly it's just displaying whatever comes from the backend, regardless of whether or not that's desired behavior.

**Pull request merged**
