### PR TITLE
Update the make target for downloading the rds cert

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

This updates a change I suggested in https://github.com/transcom/mymove/pull/1485#discussion_r266677674.  My previous suggestion didn't work but this one does.

Try:

```
rm bin/rds-combined-ca-bundle.pem
make bin/rds-combined-ca-bundle.pem
```

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
Should `make clean` remove the cert? I hadn't considered that but it occurred to me just now and maybe we should put it in this PR.

**Comment by chrisgilmerproj** [comment]
> Cert is in `bin` should be automatically removed now by `clean`. Can't we just have the `bin/rds-combined-ca-bundle.pem` target and remove the `download_rds_certs` target? We'd need to update the .circleci file with the new target, too. Also, probably just want to rebase on master.

You're absolutely right. Here's the updated version and I think I updated all the places that reference it.

**Comment by pjdufour-truss** [comment]
Could we actually add a `mkdir -p bin` to the `bin/rds-combined-ca-bundle.pem` target before the curl?  Unlike `go build` it doesn't add the intermediate directories if they were deleted after clean.

**Comment by chrisgilmerproj** [comment]
> Could we actually add a `mkdir -p bin` to the `bin/rds-combined-ca-bundle.pem` target before the curl? Unlike `go build` it doesn't add the intermediate directories if they were deleted after clean.

Done! Good catch.

**Pull request merged**
