### PR TITLE
MB-9622 react select upgrade

### PR DESCRIPTION
**Pull request by leia-sefkin**
## Description

Dependabot prompted update of react-select library, put into a manual merge to fix some display issues with the DutyStationSearchBox component. 

Fix was relatively easy in the end, but could use some extra eyes on the happo diffs. There's quite a few that seem to be flaky tests or false failures, but I want to be sure I addressed all issues present. 

## Code Review Verification Steps

* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9622) for this change

## Screenshots

Original Happo Diffs showing affected components: https://happo.io/a/488/p/603/compare/d5ad96f9a883ac3efd9428919815568422e9bdb9/3f9629b4c6216fbfa4681ee17e1d89bc2866f67d

Current Happo Diffs after change: 

https://happo.io/a/488/p/603/compare/365d93b08c8cf3695268e3c81648188aeae68ae5/cae4ac15cd39ee81a7dc53800305b2dbd7f06cfa

### CODE REVIEW

**Review by eamahanna — COMMENTED** [review]
The change makes sense to me. Did you need to make any changes to the MuliSelectCheckBoxFilter? I saw that it uses react-select as well.

**Review by brooksr4 — APPROVED** [review]

**Comment by leia-sefkin** [comment]
> The change makes sense to me. Did you need to make any changes to the MuliSelectCheckBoxFilter? I saw that it uses react-select as well.

thanks for calling this out @eamahanna just checked and i'm seeing some issues so i'll see what i can do

**Comment by leia-sefkin** [comment]
@eamahanna just pushed a fix, can you take a look?

**Review by eamahanna — APPROVED** [review]
This looks good to me. I just took a look at the happo diffs and nothing looks too crazy. Do you know if the diff for `ReviewServiceItems - Basic` could be related to something you changed? It looks like a margin is different.

**Comment by leia-sefkin** [comment]
> This looks good to me. I just took a look at the happo diffs and nothing looks too crazy. Do you know if the diff for `ReviewServiceItems - Basic` could be related to something you changed? It looks like a margin is different.

@eamahanna - that's not due to this change, it's showing up in other PRs as well, and seems to be mostly an artifact of how the component is rendering in storybook only on safari (with extra margins). i also checked other locations react-select is used and components look good.

**Comment by eamahanna** [comment]
> > This looks good to me. I just took a look at the happo diffs and nothing looks too crazy. Do you know if the diff for `ReviewServiceItems - Basic` could be related to something you changed? It looks like a margin is different.
> 
> @eamahanna - that's not due to this change, it's showing up in other PRs as well, and seems to be mostly an artifact of how the component is rendering in storybook only on safari (with extra margins). i also checked other locations react-select is used and components look good.

Sounds good! Feel free to merge! I just wanted to double check :)

**Pull request merged**
