### PR TITLE
B-20617: SC and TOO Creating Mobile Home Shipment and Shipment Card Display

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Testing Steps
1. You can start with just a user, a move with no shipment, or a move with a shipment. Using information from either the user, move, or shipment, search as a SC.
2. If you have opened a user finish setting up the move and click the "Add a new shipment" dropdown and select "Mobile Home" as the type of shipment to add.
3. Fill out information for the Mobile Home and once done you should see a shipment card with all the relevant details.
4. Now log in as a TOO and search for the Move/Shipment. Once you have opened the Move to see the shipments, you should be able to edit the Mobile Home Shipment.

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
LGTM, tested and working, ready to merge in once tests pass.

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Inserting myself in a few mobile home PRs here!

Threw in a few things I noticed with boat vs mobile home verbiage.

Also looking at the AC, I'm not seeing the following fields on the card when viewing it as the TOO
- Releasing agent
- Requested delivery date
- Receiving Agent

image

I do have all of those fields filled out, here is a screenshot of the _customer_ view of that same FV7KKG-02 shipment
image

Couple playwright tests failing at the moment

**Comment by traskowskycaci** [comment]
I stand corrected on the playwright tests failing, looks like you took care of those!

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
One more comment because I am also looking at Konstance's changes for the customers - can we make the destination address field match? I'm good with either `Destination` or `Destination address`, whatever you both agree on. Just would like it to be the same if it's not too big of a deal :)

`Destination` for customer on the left bottom vs `Destination address` for office user on the right bottom
image

cc @KonstanceH

**Comment by WeatherfordAaron** [comment]
> Inserting myself in a few mobile home PRs here!
> 
> Threw in a few things I noticed with boat vs mobile home verbiage.
> 
> Also looking at the AC, I'm not seeing the following fields on the card when viewing it as the TOO
> 
> * Releasing agent
> * Requested delivery date
> * Receiving Agent
> 
> image
> 
> I do have all of those fields filled out, here is a screenshot of the _customer_ view of that same FV7KKG-02 shipment image
> 
> Couple playwright tests failing at the moment

Regarding not seeing those agent fields:
You have to click the "expand" icon at the top-right of any of these cards to see those particular fields.

**Comment by traskowskycaci** [comment]
> I'm not sure I follow the logic on this one. In the customer card it reads "Pickup location" and the office side reads "Origin address".
> 
> Since the PO hasn't requested that change, I'd be reluctant to change that.

This is regarding the destination address, not pickup

**Comment by WeatherfordAaron** [comment]
> > I'm not sure I follow the logic on this one. In the customer card it reads "Pickup location" and the office side reads "Origin address".
> > Since the PO hasn't requested that change, I'd be reluctant to change that.
> 
> This is regarding the destination address, not pickup

I got that. I was merely making a point. Want to keep the convo going on here or side chat?

**Comment by traskowskycaci** [comment]
> > > I'm not sure I follow the logic on this one. In the customer card it reads "Pickup location" and the office side reads "Origin address".
> > > Since the PO hasn't requested that change, I'd be reluctant to change that.
> > 
> > 
> > This is regarding the destination address, not pickup
> 
> I got that. I was merely making a point. Want to keep the convo going on here or side chat?

Ok, I guess I didn't follow the pickup comment. However, you guys are both meeting your ACs with destination vs destination address so I will take back that feedback

**Comment by WeatherfordAaron** [comment]
> > > > I'm not sure I follow the logic on this one. In the customer card it reads "Pickup location" and the office side reads "Origin address".
> > > > Since the PO hasn't requested that change, I'd be reluctant to change that.
> > > 
> > > 
> > > This is regarding the destination address, not pickup
> > 
> > 
> > I got that. I was merely making a point. Want to keep the convo going on here or side chat?
> 
> Ok, I guess I didn't follow the pickup comment. However, you guys are both meeting your ACs with destination vs destination address so I will take back that feedback

As always, I appreciate the time and consideration.

**Comment by traskowskycaci** [comment]
> Regarding not seeing those agent fields: You have to click the "expand" icon at the top-right of any of these cards to see those particular fields.

Noted. Just curious though - why are those particular fields only displayed conditionally on the expand?

Seeing mobile home here now, looks good
image

**Comment by WeatherfordAaron** [comment]
> > Regarding not seeing those agent fields: You have to click the "expand" icon at the top-right of any of these cards to see those particular fields.
> 
> Noted. Just curious though - why are those particular fields only displayed conditionally on the expand?
> 
> Seeing mobile home here now, looks good image

I wish I knew. it looks like that was done about 2 years ago initially. This is us just copying how the app works in other places.

**Comment by traskowskycaci** [comment]
> I wish I knew. it looks like that was done about 2 years ago initially. This is us just copying how the app works in other places.

Ok. I could see your PO potentially having the same question - seems kinda random to exclude those three fields lol

**Comment by WeatherfordAaron** [comment]
> > I wish I knew. it looks like that was done about 2 years ago initially. This is us just copying how the app works in other places.
> 
> Ok. I could see your PO potentially having the same question - seems kinda random to exclude those three fields lol

If we treated this card differently than how it's treated elsewhere in the app, our PO would ask questions about that for sure.

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Hopefully getting to the bottom of my list here, thanks for being quick on the replies😄 Would you mind making this match between TOO and counselor views?

TOO: Mobile Home with a space
image

Counselor: MobileHome without the space
image

**Comment by WeatherfordAaron** [comment]
> Hopefully getting to the bottom of my list here, thanks for being quick on the replies😄 Would you mind making this match between TOO and counselor views?
> 
> TOO: Mobile Home with a space image
> 
> Counselor: MobileHome without the space image

You got it. Just pushed that change up.

**Comment by traskowskycaci** [comment]
> > > I wish I knew. it looks like that was done about 2 years ago initially. This is us just copying how the app works in other places.
> > 
> > 
> > Ok. I could see your PO potentially having the same question - seems kinda random to exclude those three fields lol
> 
> If we treated this card differently than how it's treated elsewhere in the app, our PO would ask questions about that for sure.

I totally see where you're coming from. It might be worth it to just bring to their attention that we have historically hidden those and check if they still want that behavior.

**Review by traskowskycaci — APPROVED** [review]
Looks good, thanks for making those changes!

**Pull request merged**
