### PR TITLE
[ MB-13923 ] Reworking SQL templating

### PR DESCRIPTION
**Pull request by kctruss**
## Summary

[ MB-13923 ] Since the first attempt at SQL templating using a third party library was unsuccessful, it has been reverted. Now, testing a new approach: 

- Use go-embed to initialize a package-level variable for storing all .SQL files at compile. 
- Call a new method to read the specified query string when fetching move history. 
- Move query string to separate file.
- Add empty .sql file for testing, and should add server tests for the query fetcher go code.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app
2. Login as an office user
3. Navigate to move history

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

### CODE REVIEW

**Comment by kctruss** [comment]
I failed to follow-up correctly but this reworking should have been branched under [MB-13923](https://dp3.atlassian.net/browse/MB-13923)

**Comment by michaelvaldes-truss** [comment]
**suggestion:** Is test_empty.sql being used for anything, or can we remove it?

**Comment by kctruss** [comment]
@michaelvaldes-truss I used it to test my error catches. It can be removed for now, but I anticipate it would be useful for writing unit tests.

**Review by michaelvaldes-truss — APPROVED** [review]
Lgtm! Move history works on my machine

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

**Pull request merged**
