### PR TITLE
[MB-13807] exp SSL certificate update

### PR DESCRIPTION
**Pull request by chtakahashi**
- Updated the certificate in all the places in AWS and CircleCI
- Updated the certificates in here
- Ran the following commands:
```
bin/milmove gen certs-migration --update -f **** -s **** -n **** --certid ****
ENVIRONMENTS="exp" upload-secure-migration 20220908163100_app_exp_cert_migration.up.sql
```

then after emptying the file,
```
ENVIRONMENTS="demo stg prd loadtest" upload-secure-migration migrations/app/secure/20220902182104_app_demo_cert_migration.up.sql
```

UPDATE:
ran:
```
ENVIRONMENTS="exp" upload-secure-migration tmp/20220908163100_app_exp_cert_migration.up.sql

ENVIRONMENTS="demo stg prd loadtest" upload-secure-migration migrations/app/secure/20220908163100_app_exp_cert_migration.up.sql

```

### CODE REVIEW

**Comment by duncan-truss** [comment]
@chtakahashi Can you try downloading the migration in experimental?  I'm seeing it as showing a blank file when it should contain the update statement.

**Comment by duncan-truss** [comment]
In you second upload statement I think you used the demo migration name when you probably meant `migrations/app/secure/20220908163100_app_exp_cert_migration.up.sql` so I got a download error when trying to retrieve it from the other environments.  Be careful if you overwrote the prior demo migration that you uploaded.  It should have already been applied but if it was ever re-run it wouldn't have the updated hash signature you added in your last PR.

**Comment by chtakahashi** [comment]
I _think_ I've now uploaded what I need to upload? @duncan-truss

**Review by duncan-truss — APPROVED** [review]
Verified the new migration with the update statement was in exp S3 and that the other environments have placeholders.  Also ran `make run_exp_migrations` with no issue.

Did you actually want to test deploy it from this branch by editing the .circleci/config.yaml https://github.com/transcom/mymove/blob/4d0bc938d9faca707bb755ada666dfd816657d75/.circleci/config.yml#L33-L36

**Pull request merged**
