### PR TITLE
B 21455 int

### PR DESCRIPTION
**Pull request by CoryKleinjanCACI**
## Summary

This change update the service counselor and TOO roles to be able update ppm shipments that have a estimated incentive of zero. An estimated incentive of zero can, currently, only be achieved when a customer pushes a PPM when DTOD is down. 

The Service Counselor role updates the ppms when they select the 'Submit move details' button.

The TOO updates the ppms when the attempt to approve either the move or an individual shipment.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Service Counselor:
1. Set DTOD_SIMULATE_OUTAGE to true and run the app
2. Access the Customer application
3. Login as a Customer
4. Create a Move
5. Add a PPM
6. Submit the move for review
7. Validate the the estimated incentive is zero in the ppm_shipments table for the shipment you created
8. Set DTOD_SIMULATE_OUTAGE to false and re-rerun the server (you can also run the test without this step, but you will be unable to approve the move and will instead see a message about DTOD being down)
9. Login as a Service Counselor
10. Select the move you created
11. Fill in missing details 
12. Submit the move
13. Validate the the estimated incentive in the ppm_shipments table is no longer zero for the shipment you created

##THE ABILITY FOR TOO TO APPROVE PPMS IS CURRENTLY BROKEN IN INTEGRATION DUE TO ANOTHER TASK
TOO:
1. Set DTOD_SIMULATE_OUTAGE to true and run the app
2. Access the Customer application
3. Login as a Customer
4. Create a Move with the Current Duty Station set to 'NS Mayport' (this allows the TOO to approve ppm shipments without the SC approval)
5. Add a PPM
6. Submit the move for review
7. Validate the the estimated incentive is zero in the ppm_shipments table for the shipment you created
10. Set DTOD_SIMULATE_OUTAGE to false and re-rerun the server (you can also run the test without this step, but you will be unable to approve the move and will instead see a message about DTOD being down)
11. Login as a TOO
12. Select the move you created
13. Fill in missing details 
14. Select the PPM shipment for approval
15. Select the Counseling check box
16. Attempt to approve the Move and ppm shipment you created
17. Validate the the estimated incentive in the ppm_shipments table is no longer zero for the shipment you created

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by antgmann — COMMENTED** [review]
So far everything looks good. Following the testing instructions, here's the shipments with no calculated values, correct errors and successes when submitting as SC and TOO:
Pasted Graphic
Pasted Graphic 1
Pasted Graphic 2
Pasted Graphic 3

Only thing that's holding me up from approving is this error when approving a PPM as a TOO once DTOD is back online. It appears to be creating base HHG service items and panicking when there is no requested pickup date on the MTOShipment model: 
image

Not sure if that's as a result of these changes, Cory hasn't seen it before but we've briefly discussed that it's happening.

**Review by antgmann — APPROVED** [review]
As it turns out, the error I'm seeing is a result of very recent changes on the integrationTesting branch, not from B-21455 (hence why Cory wasn't seeing it on his local - his local didn't have the most recent int, upon updating he was able to recreate the same error and find the underlying cause). 

The new changes make requestedDeliveryDate a requirement for a CS Service item, which prime counseled PPMs create (but since they don't have an rDD, it fails). 

This means this PR is good to go, Cory is reaching out to communicate the issue to those who worked in that area to find the best way to resolve it.

**Comment by r-mettler** [comment]
image
Get DTOD down message as customer as expected. 
Estimated incentive for customer displays a 0 in the ppm_shipments table. Updated after SC submitted when DTOD up.

TOO worked as well.

**Comment by r-mettler** [comment]
> So far everything looks good. Following the testing instructions, here's the shipments with no calculated values, correct errors and successes when submitting as SC and TOO: Pasted Graphic Pasted Graphic 1 Pasted Graphic 2 Pasted Graphic 3
> 
> Only thing that's holding me up from approving is this error when approving a PPM as a TOO once DTOD is back online. It appears to be creating base HHG service items and panicking when there is no requested pickup date on the MTOShipment model: image
> 
> Not sure if that's as a result of these changes, Cory hasn't seen it before but we've briefly discussed that it's happening.
> 
> Edit: I only got this error when including the counseling service. Looking now to see if it's being caused by my local database

**Review by r-mettler — APPROVED** [review]
Looks good

**Review by MInthavongsay — APPROVED** [review]
Looks good. Had an issue with TOO test case. Determined it's related to a bug outside the scope of this ticket.

**Pull request merged**
