### PR TITLE
B 18909 rejected dsh or dlh main

### PR DESCRIPTION
**Pull request by traskowskycaci**
## [Integration PR](https://github.com/transcom/mymove/pull/12247)

When an address change results in a move from short haul to line haul or vice versa, we reject the old DSH or DLH service and create a new one. For the rejected service item, we want to show it on the MTO page in the rejected section, but without the "Approve" button.

Other rejected service items will have the Approve button, but if it's a DSH or DLH that was auto rejected as a result of a shipment address change, we take away the approve button.

DLH example with other rejected service items: 
image

DSH example:
image

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
Hashes match up. LGTM!

**Review by cameroncaci — APPROVED** [review]
Commits look good

**Comment by cameroncaci** [comment]
I believe main is still locked - just synced

**Comment by traskowskycaci** [comment]
Can I get this one merged @deandreJones?

**Pull request merged**
