### PR TITLE
B-18312-multi-move-dashboard

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

This PR introduces the Multi Move dashboard. When the service member logs in they are routed to the multi move dashboard.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Ensure that the multiMove feature flag is switched on for your respective environment
2. Log into MilMove as a service member
3. You should have been routed to the Multi Move Dashboard

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Your code doesn't seem to match up to your integration branch merge:
https://github.com/transcom/mymove/pull/11837

Looks like you have a ton of commits that aren't yours.

**Review by traskowskycaci — COMMENTED** [review]
This branch has quite a few more commits than the one going into `integrationTesting`. Is that expected?

**Comment by traskowskycaci** [comment]
> This branch has quite a few more commits than the one going into `integrationTesting`. Is that expected?

Disregard, didn't see Daniel's comment above.

**Review by traskowskycaci — COMMENTED** [review]
You may want to check in with Cameron or Dre on whether the undos are ok - I know Cameron and I ran into a case where undoing commits was causing some issues. @cameroncaci do you see anything wrong with undoing commits here?

**Comment by TevinAdams** [comment]
> This branch has quite a few more commits than the one going into `integrationTesting`. Is that expected?

No. i have been fighting with the commits on this branch for days. I created a new branch with the work that is in integration because the commits and work I didnt do is making this branch messy.

**Comment by TevinAdams** [comment]
> Your code doesn't seem to match up to your integration branch merge: #11837
> 
> Looks like you have a ton of commits that aren't yours.


I have been fighting with the commits on this branch for days. I created a new branch with the work that is in integration because the commits and work I didnt do is making this branch messy.

**Pull request closed without merging**
