### PR TITLE
INT  - TEMP LOGGING  - B 21478 rate area name id prime api

### PR DESCRIPTION
**Pull request by MInthavongsay**
## [B-21478](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1016131&RoomContext=TeamRoom%3A855664&concept=TeamRoom)

[Original INT PR](https://github.com/transcom/mymove/pull/14112)

This PR adds logging to trace through code in attempt to resolve issue in loadTesting. RateArea is not present in loadTesting and we don't know why.  The logging will be removed before it is merged into MAIN.

### CODE REVIEW

**Review by ajlusk — APPROVED** [review]

**Review by danieljordan-caci — COMMENTED** [review]
Are you not able to log into loadtest db and investigate?

**Comment by r-mettler** [comment]
> Are you not able to log into loadtest db and investigate?

He did but didn't see anything in the db that was out of the ordinary and causing the issue.

**Review by r-mettler — APPROVED** [review]

**Comment by MInthavongsay** [comment]
> Are you not able to log into loadtest db and investigate?
I've queried the data in loadTesting and everything checks out. I'm kind of stumped at the moment.

**Review by deandreJones — COMMENTED** [review]
g2g long as we plan to remove the query from the logs after trouble shooting

also - couldn't this be determined with some db queries instead of app logging?

**Comment by danieljordan-caci** [comment]
Also there is a `get_rate_area_id` function I created in loadtest you can try out. It takes in consideration CONUS & OCONUS moves.
```
CREATE OR REPLACE FUNCTION get_rate_area_id(
    address_id UUID,
    service_item_id UUID,
    OUT o_rate_area_id UUID
)
RETURNS UUID AS $$
DECLARE
    is_oconus BOOLEAN;
    zip3_value TEXT;
BEGIN
    is_oconus := get_is_oconus(address_id);

    IF is_oconus THEN
        -- re_oconus_rate_areas if is_oconus is TRUE
        SELECT ro.rate_area_id
        INTO o_rate_area_id
        FROM addresses a
        JOIN re_oconus_rate_areas ro
        ON a.us_post_region_cities_id = ro.us_post_region_cities_id
        WHERE a.id = address_id;
    ELSE
        -- re_zip3s if is_oconus is FALSE
        SELECT rupr.zip3
        INTO zip3_value
        FROM addresses a
        JOIN us_post_region_cities uprc
        ON a.us_post_region_cities_id = uprc.id
        JOIN re_us_post_regions rupr
        ON uprc.us_post_regions_id = rupr.id
        WHERE a.id = address_id;

        -- use the zip3 value to find the rate_area_id in re_zip3s
        SELECT rz.rate_area_id
        INTO o_rate_area_id
        FROM re_zip3s rz
        WHERE rz.zip3 = zip3_value;
    END IF;

    -- Raise an exception if no rate area is found
    IF o_rate_area_id IS NULL THEN
        RAISE EXCEPTION 'Rate area not found for address % for service item ID %', address_id, service_item_id;
    END IF;
END;
$$ LANGUAGE plpgsql;
```

**Comment by MInthavongsay** [comment]
> g2g long as we plan to remove the query from the logs after trouble shooting
> 
> also - couldn't this be determined with some db queries instead of app logging?

This will be removed when issue is resolved.  Everything works locally. Yes -- I've already queried the loadTesting db. I've executed the queries using loadTesting data and everything checks out. At this time, I don't know what it can be. This logging will confirm if it is going into  the expected Prime V3 API.  It merely wil log the actual sql the service layer is running.

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
I'm going to block this for now because I think there are additional actions and resources that can be used to troubleshoot instead of adding in logging.

I see you're depending on `v_locations`, but if you check out the function I made, there's different queries for CONUS & OCONUS.

**Comment by deandreJones** [comment]
Let tag up in the morning and get in the DB to poke around

**Comment by MInthavongsay** [comment]
> I'm going to block this for now because I think there are additional actions and resources that can be used to troubleshoot instead of adding in logging.
> 
> I see you're depending on `v_locations`, but if you check out the function I made, there's different queries for CONUS & OCONUS.

How do you resolve the fact the issue is not present when running INT locally, regardless of present implementation?

**Comment by MInthavongsay** [comment]
> I'm going to block this for now because I think there are additional actions and resources that can be used to troubleshoot instead of adding in logging.
> 
> I see you're depending on `v_locations`, but if you check out the function I made, there's different queries for CONUS & OCONUS.

BTW, this was written PRIOR to the new function.

**Comment by MInthavongsay** [comment]
Beth Grohmann db fix resolved loadTesting issue we were seeing. Temp debugging logging is no longer needed.

**Pull request closed without merging**
