### PR TITLE
MAIN B-18313 Multi-Moves Profile Validation & Create a Move Btn Functionality

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION PR](https://github.com/transcom/mymove/pull/11859)
[INTEGRATION PR - updates](https://github.com/transcom/mymove/pull/11911)

## Summary

As we transition to allowing for multiple moves, we need to allow for the customer to validate their profile prior to starting a new move. If the service member does not have a previous move, then there's no need for them to validate their profile - technically it should already be current.

I went ahead and leveraged the `useLocation` hook to pass around a state value (`needsToVerifyProfile`) when a user is validating their profile. At first I was using `searchParams` but it felt a little clunky and was a lot harder to test, so I transitioned to using local `state` and passing that `state` to the relevant components.

This PR does the following:
- updates profile links to pass around the `state` object holding the current value of `needsToVerifyProfile`
- based on that state, specifically in the `Profile` component, conditional rendering will occur of links and an alert banner
- updated tests

### How to test Scenario 1 (previous moves)

1. Access MM as a customer
2. Once logged in you should be directed to the multi move home page
3. You'll see the multi move dashboard (currently using dummy/static data)
4. With default data, click on the `Create a Move` button
5. This will navigate the user to the profile page with an alert, a `Create a Move` button, and `Return to Dashboard` (instead of `Return to Move`)
6. Validate any data/cancel any data and the alert/button/dashboard link should remain
7. Once you're finished, click the `Create a Move` button and you'll be navigated to the current home page

### How to test Scenario 2 (no previous moves)

1. Access MM as a customer
2. Once logged in, put in `http://milmovelocal:3000/?moveData=noMoves` into the url
3. You'll see the multi move dashboard with no current or previous moves
4. Click on the `Create a Move` button
5. This will navigate the user to the current home page since there is no previous data to validate

## Screenshots

Screenshot 2024-01-25 at 2 19 15 PM

### CODE REVIEW

**Comment by cameroncaci** [comment]
Missing commit hashes from integration branches

**Comment by danieljordan-caci** [comment]
> Missing commit hashes from integration branches

You're correct. I was getting some crazy errors and weird white space issues so it was easier just to fix the files themselves via copy/paste.

**Comment by danieljordan-caci** [comment]
> Missing commit hashes from integration branches

For these MM PRs into `main` specifically, it might be a little atypical. 
1. They were started prior to the `integrationTesting` process began so there were some... learning curves
2. Most of these were actually started off of `integrationTesting` first because the dependency code did not exist in `main`

Tryin' my best here.

**Review by traskowskycaci — APPROVED** [review]
Anything I saw different between the main and int PR was addressed in the int updates PR - all looks like it's matching.

**Review by cameroncaci — APPROVED** [review]
commits g2g

**Pull request merged**
