### PR TITLE
B21575-INT2-add order types

### PR DESCRIPTION
**Pull request by JamesHawks224**
## Agility ticket
[B21575](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21575)

## Notes
This PR is a remake of prior PR.  Prior PR was: [14091](https://github.com/transcom/mymove/pull/14091)
Please see this PR for any prior comments or corrections.

## Summary
For the customer, 2 new order types were added:  Student Travel, Early Return of Dependents.  If either of these were selected, then "Has Dependents" would default to "yes" and be disabled so it can't be changed.  If another order type besides these 2 were selected, "Has Dependents" would be re-enabled and would be reset to nothing selected.

### How to test
In the .envrc.local file, add the following to turn on the feature flag:
export FEATURE_FLAG_ENABLE_ALASKA=true
restart server and client

Scenario 1: Creating a move
* login as a customer
* create a move
* at the move orders page ("tell us about your move orders")
  - set initial values all fields:
    - order type: Permanent Change of Station
    - remaining fields: any value is fine
* verification
  - verify: order type,  changing existing type to another existing type
    - change order type to local move
    - verify no fields are changed
  - verify: order type, changing existing type to new type (student travel)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (student travel) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing existing type to new type (early return of dependents)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (early return of dependents) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing new type (early return of dependents) to to new type (student travel)
    - change order type to early return of dependents
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
* finish creating the move w/a ppm shipment.

Scenario 2: edit existing orders
* login as a customer
* use the move just created in scenario 1
* click on "review your request"
* edit orders
* on the "edit orders" page, set the initial values the same as in scenario 1
* perform verification the same verification as in scenario 1.
* save the page

Scenario 3: turn off feature flag
In the .envrc.local file, add the following to turn on the feature flag:
export FEATURE_FLAG_ENABLE_ALASKA=false
restart server and client
* Create a move: On the orders page, verify neither Student Travel or Early Return of Dependents shows up in the drop down list
* Edit a move: On the orders page, verify neither Student Travel or Early Return of Dependents shows up in the drop down list

## ANDI Screenshots
Creating a move:
image

Editing existing orders:
image

## Testing Screenshots
N/A

### CODE REVIEW

**Comment by JamesHawks224** [comment]
From the prior PR:
Tae Jung - "I think we might need to add FF or use existing Alaska FF for this story so these new types don't get shown in Production until they are ready. Please check if this is true and confirm."

**Comment by JamesHawks224** [comment]
> From the prior PR: Tae Jung - "I think we might need to add FF or use existing Alaska FF for this story so these new types don't get shown in Production until they are ready. Please check if this is true and confirm."

It was determined that a FF was needed.  it will use the Alaska FF.  This comment will be updated when change is added.

**Review by WeatherfordAaron — APPROVED** [review]
Code: lgtm
Tests: lgtm
Notes: Everything works as far as I was able to test it and in harmony with what the request states in the AC.
👽

**Comment by taeJungCaci** [comment]
Looks like you have some pre_test fails related to your code change and possible client_test fail that may not be flaky

**Pull request merged**
