### PR TITLE
MB-8046 MM Header Refactor CSS Followup

### PR DESCRIPTION
**Pull request by Shkeating**
## Description

This branch makes some adjustments to sizing and placement of elements in the `userInfo` section of the MilMove navigation to be in better alignment to our designs. The comps I referred to to make these adjustments can be located here:

- [Customer Profile](https://zpl.io/aRZ8xlg) in Zeplin
- [MilMove Header](https://zpl.io/257yrk0) in MMDS

### Adjustments of note:
- for all MilMove headers, the text is now 15px on desktop and 13px on mobile
- for the Customer logged in state with profile link, the desktop version gives 32px of space to each side of the `userInfo` items, with 48px in between them
- On mobile, there is 16px of space around both items

## Reviewer Notes

I was not able to replicate the gap that was mentioned in the ticket. If anyone is able to run the office app locally and sees a gap that looks like the screenshot below, please let me know!
image

## Setup

```sh
yarn storybook
```
[http://localhost:6006/?path=/story/components-headers-milmove-header--logged-in-customer-header-with-profile-link](http://localhost:6006/?path=/story/components-headers-milmove-header--logged-in-customer-header-with-profile-link)

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8046?atlOrigin=eyJpIjoiMGQzOGQxNTM2ZmVhNDllZmIzNTliYTBhMzAxNTY5MTkiLCJwIjoiaiJ9) for this change
- [Customer Profile](https://zpl.io/aRZ8xlg) in Zeplin
- [MilMove Header](https://zpl.io/257yrk0) in MMDS

## Screenshots

image
image
image
image

### CODE REVIEW

**Comment by YanZ777** [comment]
The gap that you weren't able to reproduce was fixed [here](https://github.com/transcom/mymove/pull/6422#issuecomment-829661761).

**Review by YanZ777 — APPROVED** [review]
These changes look good to me!

**Review by jenniferlynparsons — APPROVED** [review]
Looks good!

**Review by amanda5iu — APPROVED** [review]
Looking good 👍🏼

**Pull request merged**
