### PR TITLE
B-18322 Update Requested pickup date

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
[Integration Testing PR for reference](https://github.com/transcom/mymove/pull/11889)

[Agility Ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a873997)

### CODE REVIEW

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by KonstanceH — APPROVED** [review]
LGTM

**Comment by JamesHawks224** [comment]
Testing status:

branch checkout failed. 
below is 2 items:  checkout text and git status

checkout text:
Switched to branch 'amw-kickback-B18326-B18327-Update-the-Estimated-Weight-PPM-Remove-select-fields-from-MTO'
Your branch and 'origin/amw-kickback-B18326-B18327-Update-the-Estimated-Weight-PPM-Remove-select-fields-from-MTO' have diverged,
and have 483 and 108 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)
Auto-merging .circleci/config.yml
Auto-merging migrations/app/migrations_manifest.txt
Auto-merging migrations/app/secure/20240124155759_20240124-homesafeconnect-cert.up.sql
CONFLICT (content): Merge conflict in migrations/app/secure/20240124155759_20240124-homesafeconnect-cert.up.sql
warning: Cannot merge binary files: pkg/gen/ghcapi/embedded_spec.go (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging pkg/gen/ghcapi/embedded_spec.go
CONFLICT (content): Merge conflict in pkg/gen/ghcapi/embedded_spec.go
warning: Cannot merge binary files: pkg/gen/internalapi/configure_mymove.go (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging pkg/gen/internalapi/configure_mymove.go
CONFLICT (content): Merge conflict in pkg/gen/internalapi/configure_mymove.go
warning: Cannot merge binary files: pkg/gen/internalapi/embedded_spec.go (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging pkg/gen/internalapi/embedded_spec.go
CONFLICT (content): Merge conflict in pkg/gen/internalapi/embedded_spec.go
warning: Cannot merge binary files: pkg/gen/internalapi/internaloperations/mymove_api.go (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging pkg/gen/internalapi/internaloperations/mymove_api.go
CONFLICT (content): Merge conflict in pkg/gen/internalapi/internaloperations/mymove_api.go
warning: Cannot merge binary files: pkg/gen/primeapi/embedded_spec.go (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging pkg/gen/primeapi/embedded_spec.go
CONFLICT (content): Merge conflict in pkg/gen/primeapi/embedded_spec.go
Auto-merging pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
Auto-merging pkg/handlers/internalapi/api.go
CONFLICT (content): Merge conflict in pkg/handlers/internalapi/api.go
Auto-merging pkg/services/shipment_address_update/shipment_address_update_requester_test.go
CONFLICT (content): Merge conflict in pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Auto-merging playwright/tests/my/mymove/onboarding.spec.js
CONFLICT (content): Merge conflict in playwright/tests/my/mymove/onboarding.spec.js
Auto-merging playwright/tests/my/mymove/orders.spec.js
CONFLICT (content): Merge conflict in playwright/tests/my/mymove/orders.spec.js
Auto-merging src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
CONFLICT (content): Merge conflict in src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
Auto-merging src/components/Office/ShipmentContainer/ShipmentContainer.jsx
CONFLICT (content): Merge conflict in src/components/Office/ShipmentContainer/ShipmentContainer.jsx
Auto-merging src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
CONFLICT (content): Merge conflict in src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
Auto-merging src/constants/routes.js
Auto-merging src/pages/MyMove/EditOrders.jsx
CONFLICT (content): Merge conflict in src/pages/MyMove/EditOrders.jsx
Auto-merging src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
CONFLICT (add/add): Merge conflict in src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
Auto-merging src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
CONFLICT (add/add): Merge conflict in src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
Auto-merging src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
CONFLICT (add/add): Merge conflict in src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
Auto-merging src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
CONFLICT (add/add): Merge conflict in src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
Auto-merging src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
CONFLICT (add/add): Merge conflict in src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
Auto-merging src/scenes/MyMove/index.jsx
Auto-merging src/shared/constants.js
CONFLICT (content): Merge conflict in src/shared/constants.js
Auto-merging swagger-def/internal.yaml
CONFLICT (content): Merge conflict in swagger-def/internal.yaml
Auto-merging swagger-def/prime.yaml
warning: Cannot merge binary files: swagger/ghc.yaml (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging swagger/ghc.yaml
CONFLICT (content): Merge conflict in swagger/ghc.yaml
warning: Cannot merge binary files: swagger/internal.yaml (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging swagger/internal.yaml
CONFLICT (content): Merge conflict in swagger/internal.yaml
warning: Cannot merge binary files: swagger/prime.yaml (HEAD vs. e65381555344a16e83a50f6fe0872ed0511dfda8)
Auto-merging swagger/prime.yaml
CONFLICT (content): Merge conflict in swagger/prime.yaml
Automatic merge failed; fix conflicts and then commit the result.
ERROR... git pull failed. branch=[amw-kickback-B18326-B18327-Update-the-Estimated-Weight-PPM-Remove-select-fields-from-MTO]   rc=[1]




git status:
$ git status
On branch amw-kickback-B18326-B18327-Update-the-Estimated-Weight-PPM-Remove-select-fields-from-MTO
Your branch and 'origin/amw-kickback-B18326-B18327-Update-the-Estimated-Weight-PPM-Remove-select-fields-from-MTO' have diverged,
and have 483 and 108 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	modified:   .circleci/config.yml
	modified:   .github/CODEOWNERS
	modified:   .github/workflows/auto-approve.yml
	modified:   .github/workflows/go-auto-approve.yml
	modified:   Dockerfile.e2e
	modified:   Dockerfile.migrations
	modified:   Dockerfile.migrations_local
	modified:   Dockerfile.reviewapp
	modified:   Dockerfile.tools
	modified:   Dockerfile.tools_local
	renamed:    config/tls/Certificates_PKCS7_v5.12_DoD.der.p7b -> config/tls/Certificates_PKCS7_v5.13_DoD.der.p7b
	deleted:    config/tls/ECA_Root_CA_4.cer
	deleted:    config/tls/IdenTrust-ECA-S23.cer
	modified:   config/tls/milmove-cert-bundle.p7b
	deleted:    config/tls/mmb.gov.uat.homesafeconnect.com.cer
	modified:   go.mod
	modified:   go.sum
	modified:   migrations/app/migrations_manifest.txt
	new file:   migrations/app/schema/20240206173201_update_shipment_address_update_table_sit_and_distance_columns.up.sql
	new file:   migrations/app/secure/20240129153006_20240129-homesafeconnect-cert.up.sql
	new file:   migrations/app/secure/20240201174442_20240201_homesafe_prd_cert.up.sql
	modified:   pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request.go
	modified:   pkg/gen/primeclient/sit_address_update/sit_address_update_client.go
	modified:   src/constants/routes.js
	modified:   src/scenes/MyMove/index.jsx
	modified:   swagger-def/prime.yaml

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   migrations/app/secure/20240124155759_20240124-homesafeconnect-cert.up.sql
	both modified:   pkg/gen/ghcapi/embedded_spec.go
	both modified:   pkg/gen/internalapi/configure_mymove.go
	both modified:   pkg/gen/internalapi/embedded_spec.go
	both modified:   pkg/gen/internalapi/internaloperations/mymove_api.go
	both modified:   pkg/gen/primeapi/embedded_spec.go
	both modified:   pkg/handlers/internalapi/api.go
	both modified:   pkg/services/shipment_address_update/shipment_address_update_requester_test.go
	both modified:   playwright/tests/my/mymove/onboarding.spec.js
	both modified:   playwright/tests/my/mymove/orders.spec.js
	both modified:   src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
	both modified:   src/components/Office/ShipmentContainer/ShipmentContainer.jsx
	both modified:   src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
	both modified:   src/pages/MyMove/EditOrders.jsx
	both added:      src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
	both added:      src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
	both added:      src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
	both added:      src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
	both added:      src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
	both modified:   src/shared/constants.js
	both modified:   swagger-def/internal.yaml
	both modified:   swagger/ghc.yaml
	both modified:   swagger/internal.yaml
	both modified:   swagger/prime.yaml

**Comment by JamesHawks224** [comment]
Verification rpt attached.
There were differences.

[B18322.verify_rpt.txt](https://github.com/transcom/mymove/files/14376869/B18322.verify_rpt.txt)

**Comment by JamesHawks224** [comment]
Per dev, main pr is correct and complete.

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
