### PR TITLE
MAIN B-18680 Departure Date For Origin Sit Is Not Persisting

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18680](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a905470)

INT PR: 
https://github.com/transcom/mymove/pull/12099 & https://github.com/transcom/mymove/pull/12110
INT PR has other changes from Main that are not mine. Please only check these files to compare(should be 10 files from this PR):

```
- pkg/handlers/primeapi/mto_service_item_test.go
- pkg/handlers/primeapi/payloads/payload_to_model.go
- pkg/handlers/primeapi/payloads/payload_to_model_test.go
- playwright/tests/office/txo/sitUpdates.spec.js
- src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
- src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
- src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
- src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
- src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
- migrations/app/schema/20240220145356_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
```

## Summary

When adding an Origin SIT via Prime and entering both entry and departure at the same time SIT is added, the departure date does not display in the SIT details > SIT Departure Date (TOO)

This PR fixes that and other related quick fixes were added as well.

**Updates:**

- Label changed: `SIT Departure Date` to `SIT departure date`.
- Date format changed to: `dd mm yyyy` to match.
- Value for `SIT departure date` now shows up in the SIT module when Prime requests a SIT and is approved by TOO.
- Added `SIT departure date` in Convert to Customer Expense modal to match with other views.

### How to test

1. Create a HHG move -> SC approves/submits -> TOO approves move
2. Find the move in Prime Simulator -> Click `Add Service Item` -> Fill out the form to add Origin SIT and make sure to include the SIT departure date.
3. Go to TOO's Move Task Order page -> Scroll down and approve SIT requested Items.
4. You should see the date for `SIT departure date` populated.
5. Also label should read `SIT departure date` with date format of `dd mm yyyy`.

## Screenshots
image
image

### CODE REVIEW

**Review by WeatherfordAaron — APPROVED** [review]
LGTM

**Review by KonstanceH — APPROVED** [review]
LGTM

**Comment by taeJungCaci** [comment]
@JamesHawks224 Ready for you sir

**Review by JamesHawks224 — APPROVED** [review]
Code changes verified.  Approved.

**Pull request merged**
