### PR TITLE
Constrain the number of DB connections by configuring the DB pool and idle pool sizes via flags

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

While load testing in #1597 we discovered that the app was configured to have unlimited DB connections. This is an issue because our RDS instance has a limit of around 200 maximum connections based on the instance size db.t2.small.  Since we have 4 app containers running at any one time they all have to share the connection space, meaning that each container can only have a max of 50 connections reserved. 

This PR provides two new flags `--db-pool` and `--db-idle-pool` with sane defaults and a max upper limit. 

## Reviewer Notes

If we add more containers via autoscaling or just by bumping them up then the connection pool reservation size would need to be decreased accordingly. Is there a good way to do that or should we hold off until that becomes a reality?

## Setup

I tested this code as part of #1597 and all the `pq: sorry too many clients already` errors disappeared completely.

## Code Review Verification Steps

* [x] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/166890544) for this change

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
> We should close the database connection as part of our graceful shutdown logic.

Take a look at my `defer` in b76c2e03a.

**Comment by pjdufour-truss** [comment]
`os.Exit` is not the same as panic.  I'd use a sync.Once, to directly close the connection once the server listeners are closed, but also with the defer, so it catches panics.  That should the various scenarios better.

https://godoc.org/sync#Once

**Comment by chrisgilmerproj** [comment]
@pjdufour-truss - are you thinking of something like this?

```diff
@@ -879,6 +897,11 @@ func serveFunction(cmd *cobra.Command, args []string) error {
        logger.Info("All listeners are shutdown")
        logger.Sync()

+       var dbClose sync.Once
+       defer dbClose.Do(func() {
+               dbConnection.Close()
+       })
+
        shutdownError := false
        shutdownErrors.Range(func(key, value interface{}) bool {
                if srv, ok := key.(*server.NamedServer); ok {
```

**Comment by chrisgilmerproj** [comment]
I'm going to want to test this on experimental one more time I think.

**Comment by chrisgilmerproj** [comment]
In deploy https://circleci.com/workflow-run/c164cb7e-b953-40f6-9d88-9c7dabce065c I saw the DB connection close correctly in these log streams:

- https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=ecs-tasks-app-experimental;stream=app/app-experimental/cf20b5e4-bbf5-4b72-a2bc-0fb9a0011e4a;start=2019-06-30T16:47:18Z
- https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=ecs-tasks-app-experimental;stream=app/app-experimental/90309344-5f85-4ca3-81f5-c9e231f66b69;start=2019-06-30T16:47:17Z

As an example for one of them I have the contents here:

Screen Shot 2019-07-01 at 9 57 25 AM

**Comment by chrisgilmerproj** [comment]
When running this code locally I also saw the correct behavior:

```
2019-07-01T17:09:48.036Z        INFO    milmove/serve.go:236    Starting listener       {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160", "name": "no-tls", "idle-timeout": "2m0s", "listen-address": "localhost:8080", "max-header-bytes": 1000000, "port": 8080, "tls": false}
2019/07/01 17:09:55 Got signal:  terminated
2019-07-01T17:09:55.360Z        INFO    milmove/serve.go:874    received signal for graceful shutdown of server {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160", "signal": "terminated"}
2019-07-01T17:09:55.360Z        INFO    milmove/serve.go:884    Waiting for listeners to be shutdown    {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160", "timeout": "25s"}
2019-07-01T17:09:55.361Z        INFO    milmove/serve.go:917    All listeners are shutdown      {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160"}
2019-07-01T17:09:55.361Z        INFO    milmove/serve.go:922    closing database connections    {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160"}
2019-07-01T17:09:55.361Z        INFO    milmove/serve.go:933    shutdown server {"git_branch": "cg_166890544_db_pool", "git_commit": "4b4633ed1e847ad4b07daf159536f5029946b160", "name": "no-tls", "addr": "localhost:8080", "port": 8080}
make[1]: *** [server_run_default] Error 1
make: *** [server_run] Error 130
```

**Pull request merged**
