### PR TITLE
MAIN B-21374 ub fields main

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Agility
[B-21374](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1014669)
Includes issue fix for [I-13575](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=I-13575) (Int based)

## Int PRs
https://github.com/transcom/mymove/pull/13977 <- Main one
https://github.com/transcom/mymove/pull/14279 <- Issue fix

### CODE REVIEW

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Missing this commit from the first integration PR: https://github.com/transcom/mymove/pull/13977/commits/fc7c7693db0f42ad5c5a157b15709bac43545248

**Comment by cameroncaci** [comment]
Cherry picked maria's commit to match int to main, not sure why that's missing

**Comment by cameroncaci** [comment]
Git history is polluted, starting a new branch and PR

**Review by traskowskycaci — APPROVED** [review]
All changed files match up from the INT PR and the issue fix PR!

**Comment by cameroncaci** [comment]
Need codeowner and happo

**Comment by danieljordan-caci** [comment]
I can't approve, but LGTM!

**Comment by traskowskycaci** [comment]
> Need codeowner and happo

Happo approved

**Review by WeatherfordAaron — APPROVED** [review]
lgtm I was unable to find diffs

**Comment by traskowskycaci** [comment]
conflicts @cameroncaci

**Comment by cameroncaci** [comment]
main is locked

**Comment by cameroncaci** [comment]
still locked, should unlock this morning

**Pull request merged**
