### PR TITLE
[MB-15310] Only allow prime to make payment requests for approved service items

### PR DESCRIPTION
**Pull request by mboren**
## Summary
Service items must be approved by office users before the prime can request payment for them.
We weren't enforcing this rule in code, so the prime was able to request payment for any service item
that they submitted.

## Setup to Run Your Code
```sh
make server_run
```
```sh
make client_run
```

### Additional steps
1. Log in to the office app as a prime user
2. Select a move
3. Add a new service item (e.g. Domestic Crating)
4. Select "Create Payment Request" and check the service item (note it's current status is "submitted")
5. Click "Create Payment Request"
6. Verify that you get an error message and are unable to create the payment request

## Verification Steps for Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### CODE REVIEW

**Comment by mandaem** [comment]
This is the error I'm getting at #6: ```
Prime API: Conflict Error 
ID: 914df2c8-2694-4483-b8cf-5f257c3fb404 is in a conflicting state Service Item is not approved
```

**Comment by mandaem** [comment]
When I check the box the first time, I am able to click 'submit payment request' btn and it shows the error. Then if I uncheck the box and then re-check it (or if I check any other checkbox on that page), that btn doesn't become active again. In order to be able to use that btn again, I must manually reload the page in Chrome.

**Comment by mboren** [comment]
Great, I think that's all expected behavior. The Prime Simulator doesn't have super robust error handling.

**Review by mandaem — APPROVED** [review]
LGTM

**Pull request merged**
