### PR TITLE
B-18312-multi-move-dashboard(MERGE-AFTER-B18310)(Merge-AFTER-B18309)

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

This PR introduces the Multi Move dashboard. When the service member logs in they are routed to the multi move dashboard. Had to comment out playwright tests in  playwright/tests/my/mymove 
 and playwright/tests/my/milmove/ppms because they depend on the Home page.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Ensure that the multiMove feature flag is switched on
2. Log into MilMove as a service member
3. You should have been routed to the Multi Move Dashboard

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Should we still be routed through the customer flow for new service member creation?

I am routed to the new member dashboard if I have an existing profile but still go through new customer profile creation for a brand new service member

**Comment by TevinAdams** [comment]
> Should we still be routed through the customer flow for new service member creation?
> 
> I am routed to the new member dashboard if I have an existing profile but still go through new customer profile creation for a brand new service member

If its a new user then they create their profile then get routed to their move dashboard. I think thats a correct flow.

**Comment by traskowskycaci** [comment]
> > Should we still be routed through the customer flow for new service member creation?
> > I am routed to the new member dashboard if I have an existing profile but still go through new customer profile creation for a brand new service member
> 
> If its a new user then they create their profile then get routed to their move dashboard. I think thats a correct flow.

Ok. After I created the profile and before I entered orders, I was at the MM dashboard. As long as that's intended, I am good with it. At some point we still need to let them enter their orders and shipments but I don't know at what point in the flow we want to route them to the dashboard

**Comment by traskowskycaci** [comment]
> > > Should we still be routed through the customer flow for new service member creation?
> > > I am routed to the new member dashboard if I have an existing profile but still go through new customer profile creation for a brand new service member
> > 
> > 
> > If its a new user then they create their profile then get routed to their move dashboard. I think thats a correct flow.
> 
> Ok. After I created the profile and before I entered orders, I was at the MM dashboard. As long as that's intended, I am good with it. At some point we still need to let them enter their orders and shipments but I don't know at what point in the flow we want to route them to the dashboard

@danieljordan-caci do you know the answer to this? Do they run through customer profile creation, then hit your new component, and then "Go to move" and continue entering their orders and stuff?

**Comment by traskowskycaci** [comment]
> > > > Should we still be routed through the customer flow for new service member creation?
> > > > I am routed to the new member dashboard if I have an existing profile but still go through new customer profile creation for a brand new service member
> > > 
> > > 
> > > If its a new user then they create their profile then get routed to their move dashboard. I think thats a correct flow.
> > 
> > 
> > Ok. After I created the profile and before I entered orders, I was at the MM dashboard. As long as that's intended, I am good with it. At some point we still need to let them enter their orders and shipments but I don't know at what point in the flow we want to route them to the dashboard
> 
> @danieljordan-caci do you know the answer to this? Do they run through customer profile creation, then hit your new component, and then "Go to move" and continue entering their orders and stuff?

Nevermind, this does make sense to me after talking with Tevin. They get routed to the new dashboard and will enter orders and shipments for each move.

**Review by traskowskycaci — APPROVED** [review]
Looks good!

**Pull request closed without merging**
