### PR TITLE
B-17828-Prime API Doc Updates for SIT

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Updating the API docs to add detail on SIT (Storage in Transit) pertaining to payment requests and the parameters involved to consider partial and full payments for partial and full deliveries. This was all changes to `/swagger-def` which auto generates `/swagger` and is used for API Documentation [here](https://transcom.github.io/mymove-docs/api/prime/v1/).

### How to test

1. Fire up the client and server
2. Head over to the Swagger API for Prime `http://officelocal:3000/swagger-ui/prime.html`
3. Review the `createPaymentRequest` and `createUpload` endpoints, as well as the `paymentRequest` summary

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Looks good! I like the larger text.

**Review by cameroncaci — APPROVED** [review]

**Comment by cameroncaci** [comment]
The acronym breakdowns are much appreciated!

**Review by TevinAdams — APPROVED** [review]

**Comment by deandreJones** [comment]
dont forget to run a deploy on mymove-docs repo

**Comment by danieljordan-caci** [comment]
> dont forget to run a deploy on mymove-docs repo
Shouldn't have to according to the docs, but I'll check the docs in the afternoon and if it's still not updated then I'll push it.

image

**Comment by deandreJones** [comment]
interesting, when i did the revert for this - i had to manually redploy mymove-docs to show the changes

**Pull request merged**
