### PR TITLE
MAIN B-18753 Move History Log for Service Counselor Approves

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18753](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18753)

PR into INT: https://github.com/transcom/mymove/pull/12195

## Summary
There are missing details for events logged in Move History where it only shows `-`.
This PR adds in details to missing fields in Move History when SC approve a PPM. 

Changes:

- Removed additional history log created for `mto_shipments` table when SC completes counseling a PPM shipment.
- Shows status `WAITING ON CUSTOMER` in Move History when SC completes counseling a PPM shipment.
- Shows status `PAYMENT APPROVED` in Move History when Closeout SC approves a PPM.

### How to test

1. As a customer -> create a normal move with a PPM shipment.
2. As a SC -> Find the move and complete counseling by making all the edits necessary and clicking submit button. 
3. Go to `Move history` tab and you should see rows with `Counseling Completed` and `Status: WAITING ON CUSTOMER`. Check the uploaded screenshots below for reference.
4. As a customer -> Upload PPM documents and fill out the form to submit to Closeout SC for a review.
5. As a Closeout SC -> Find the move -> Review documents -> Approve all the documents.
6. Go to `Move history` tab and you should see a row with `Status: PAYMENT APPROVED`. Check the uploaded screenshots below for reference.

### SC completes counseling:
image

### Closeout SC approves a PPM:
image

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
Changes look the same as INT branch, tested and working, looks good 👍

**Comment by JamesHawks224** [comment]
verify rpt:
[B18753-12205.verify_rpt.txt](https://github.com/transcom/mymove/files/14562351/B18753-12205.verify_rpt.txt)
A few diffs.

**Comment by taeJungCaci** [comment]
> verify rpt: [B18753-12205.verify_rpt.txt](https://github.com/transcom/mymove/files/14562351/B18753-12205.verify_rpt.txt) A few diffs.

Thank you. I verified the files and it looks like they are showing as diffs on your report because file itself is not the same while my changes are the same.

**Comment by JamesHawks224** [comment]
> > verify rpt: [B18753-12205.verify_rpt.txt](https://github.com/transcom/mymove/files/14562351/B18753-12205.verify_rpt.txt) A few diffs.
> 
> Thank you. I verified the files and it looks like they are showing as diffs on your report because file itself is not the same while my changes are the same.

Ok.  So, diffs can be disregarded.

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
