### PR TITLE
Cleanup Backup Contacts

### PR DESCRIPTION
**Pull request by macrael**
## Description

This makes adding backup contacts optional and does some visual cleanup requested by Elliott/design.

## Reviewer Notes

All of the acceptance criteria from the pivotal are complete except for returning to the exact right spot if you navigate away from the flow.

The AC requested that if you have gotten to backup contact and you reload the app you go back to BC, but if you have clicked 'Next' (even if BC is blank) and then reload the app you are supposed to go to the transition screen. 

As is, if you click 'Next' on a blank BC and then reload the app it will take you back to BC. 

I'm not sure how to cleanly do this, there's nothing on the server right now to indicate that you picked "no" backup contact. It would be possible to do this with local state but that seems like a lot of effort for a very small win. LMK if you think there's a good way to do this. 

Additionally, if have entered a backup contact, go back to the BC screen, delete everything and hit 'Next' it correctly deletes the BC. However, it will display some annoying "Required." notices for the two required fields. I think changing that would be a big overhaul of this system, which again, seemed like it was not worth the effort for now. 

## Code Review Verification Steps

* [ ] End to end tests pass (`make e2e_test`).
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] There are no aXe warnings for UI.
* [ ] This works in IE.
* [x] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/158638545) for this change

## Screenshots

screen shot 2018-08-20 at 1 52 44 pm

### CODE REVIEW

**Comment by tinyels** [comment]
Sorry it has taken me so long to get to this. I just asked DDS and SBD for some clarification. At the moment if the user doesn't add a backup contact in the wizard there is no other way to add it. The edit option doesn't appear on the review/summary page and the save for it doesn't work in the office. We may just want to get the new warning added. I'll let you know when I know.

**Comment by tinyels** [comment]
Requested changes to make sure this doesn't get merged. Not sure when work needs to be done to address concerns.

**Comment by macrael** [comment]
understood. Would being able to add them at the summary screen be enough? Or do they need to be able to be added after the move has been submitted?

**Comment by tinyels** [comment]
closing pr since we are never going to merge this as is

**Pull request closed without merging**
