### PR TITLE
MAIN B-18552 deprecate prime v1 createMTOShipment endpoint

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INT PR](https://github.com/transcom/mymove/pull/13569)

**NOTE** this will be merged after [B-18553](https://github.com/transcom/mymove/pull/13586) due to some weird merge conflicts that had to occur after that was pushed

## Summary

We are deprecating the `v1` version of the Prime endpoint `createMTOShipment` per our [documentation](https://transcom.github.io/mymove-docs/api/prime/v1#tag/mtoShipment/operation/createMTOShipment).

I decided to leave the description for guidance on which endpoint that should be used, but removed all code and functionality. It was confirmed in the `proj-ghc` channel in Slack that HomeSafe does not use this endpoint any more. This is also documented in the Agility ticket.

### How to test

1. Fire up your environment
2. Hit up the url [for the Prime v1 Swagger UI](http://officelocal:3000/swagger-ui/prime.html#/)
3. Confirm `createMTOShipment` is deprecated
4. Attempt to use the endpoint via Swagger and should get a "not found" error

## Screenshots
Screenshot 2024-08-26 at 3 25 02 PM

### CODE REVIEW

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Seeing a few lines of difference between int and main in pkg/handlers/primeapi/api.go

image

**Comment by danieljordan-caci** [comment]
> Seeing a few lines of difference between int and main in pkg/handlers/primeapi/api.go
> 
> image

Yup - see the note in the description. I'll need to make those changes after merging the other one first.

**Comment by traskowskycaci** [comment]
> > Seeing a few lines of difference between int and main in pkg/handlers/primeapi/api.go
> > image
> 
> Yup - see the note in the description. I'll need to make those changes after merging the other one first.

Sounds good! I will hold off on reviewing until then

**Comment by danieljordan-caci** [comment]
> > > Seeing a few lines of difference between int and main in pkg/handlers/primeapi/api.go
> > > image
> > 
> > 
> > Yup - see the note in the description. I'll need to make those changes after merging the other one first.
> 
> Sounds good! I will hold off on reviewing until then

Check now!

**Review by traskowskycaci — APPROVED** [review]
Matches up!

**Pull request merged**
