### PR TITLE
[ MB-16350 ] Adding payment request DOSFSC DDSFSC to testharness

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

- [x] Adding DOSFSC to the MTO Service Item Factory
- [x] Adding DDSFSC to the MTO Service Item Factory
- [x] Adding the \*FSC service items to an existing test;

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Use the `/testharness/list` UI.
1. Click the button for `MakeHHGMoveWithServiceItemsAndPaymentRequestsAndFilesForTOO`.
1. Note the new service items for `DOSFSC` and `DDSFSC`.

### CODE REVIEW

**Review by StuTruss — COMMENTED** [review]
LGTM we'll just need to update playwright tests since integration tests are failing looks like

**Comment by rogeruiz** [comment]
@StuTruss just as I thought. These  tests are looking for a certain number of items. So we'll need to bump up the items that it's searching for. 

Could you handle that? You can commit directly on my branch please.

**Comment by StuTruss** [comment]
> @StuTruss just as I thought. These tests are looking for a certain number of items. So we'll need to bump up the items that it's searching for.
> 
> Could you handle that? You can commit directly on my branch please.

sure thing!

**Comment by rogeruiz** [comment]
awesome @StuTruss thanks! I'll add more PRs then for the other scenarios while you're working through this. 🚀

**Comment by rogeruiz** [comment]
Oh also, I've merged in #10992 which means that this branch needs to be updated with `main` in order to take into account the first two commits on this branch already existing in `main`. I won't merge things in here. But just wanted to let you know about that @StuTruss.

**Comment by StuTruss** [comment]
@rogeruiz would you like me to go ahead and rebase this branch before pushing my changes?

**Comment by rogeruiz** [comment]
@StuTruss thats aounds likes. Good strategy. All up to you. I'll make sense of the changes locally when I pull things down.

**Review by StuTruss — APPROVED** [review]

**Pull request merged**
