### PR TITLE
[MB-10776] Update ADR Links for 0066

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

- [x] Fix some typos
- [x] Reorder links to reflect where they're linking to

### CODE REVIEW

**Review by felipe-lee — APPROVED** [review]
LGTM, thanks for making those fixes.

**Comment by felipe-lee** [comment]
This does make me wonder, are you thinking we should eventually also use Vale in this repo for the READMEs, ADRs, etc. like we're starting to use in the mymove docs repo?

**Comment by rogeruiz** [comment]
> This does make me wonder, are you thinking we should eventually also use Vale in this repo for the READMEs, ADRs, etc. like we're starting to use in the mymove docs repo?

short answer yes. longer answer, yeeesss

but I also don't have the power to decide that unilaterally. I'll message you in Slack about it.

**Comment by rogeruiz** [comment]
😢 I should have committed this with `[skip-ci]` as it's just Markdown changes and CircleCI is having a bad day.

**Comment by felipe-lee** [comment]
> 😢 I should have committed this with `[skip-ci]` as it's just Markdown changes and CircleCI is having a bad day.

😢 yeah several of our PRs are stuck now

**Comment by rogeruiz** [comment]
@gidjin could you ~~approve~~ merge this in? I skipped CI, but I really don't need it to run the full suite for Markdown ADRs. 😭

**Pull request merged**
