### PR TITLE
MB-9313 hookup billable weight component on payment requests page

### PR DESCRIPTION
**Pull request by YanZ777**
## Description

Wrote up some custom hooks to calculate the total billable weight and the total weight requested.
Replaced some spots where the custom hook would be useful at.
I fixed up the MovePaymentRequests tests since they were spitting out a bunch of console errors

## Reviewer Notes

Did I change the shipment list item to use the correct value?
Is the logic for calculating the total billable weight and the total weight requested correct?
Are things living in the right places?
Did I name things ok?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make office_client_run
make server_run
```
Login as a TIO and use any of the following moves (I can not ensure the integrity of any other moves):
Move with billable weights
Locator BILWEI

Reweigh with multiple shipments 
Locator MULTRW

Shipment missing reweigh
Locator MISHRW

Max billable weight exceeded
Locator MAXCED

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9313) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

image

### CODE REVIEW

**Review by pearl-truss — APPROVED** [review]
Changes look good to me! My only non-blocker comment is the name /hooks/custom seems kind of vague. I'm wondering if there's a more specific thing it could be named but I can't think of anything myself

**Comment by YanZ777** [comment]
> Changes look good to me! My only non-blocker comment is the name /hooks/custom seems kind of vague. I'm wondering if there's a more specific thing it could be named but I can't think of anything myself

Yea, I'm not sure if we should have a file with all our custom hooks or if we should have a folder with custom hooks split out by type. Given that I'm also the first person to write shared custom hooks, I don't know how useful it would be to have a folder with a single file in it.

**Review by donaldthai — APPROVED** [review]
LGTM

**Review by cosburn — APPROVED** [review]
Logic looks good with the caveat that it we'll need to test the logic through the whole workflow once the the forms are hooked up. Nicely done!

**Pull request merged**
