### PR TITLE
B-20121 corrected label for non-FSC items

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Steps I took to test
1. Create test harness move with 'HHGMoveInSITEndsToday'.
- Copy Move Locator
2. Log in as Prime office user
3. Find the move by it's Move Locator and open it
4. Create a Payment Request for either Destination or Origin FSC
5. Switch user role to TIO or TOO office user
6. Find the move by it's Move Locator and open it
7. Review the Payment Requests
- You may have to click the Review Weights button and navigate back to the Payment Request Review page
8. You should no longer see "Fuel Rate Adjustment" at the bottom as the label of the total. It should now read "Total:"

### CODE REVIEW

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by KonstanceH — APPROVED** [review]
LGTM

**Comment by JamesHawks224** [comment]
verify rpt:
[B20121-12628.verify_rpt.txt](https://github.com/transcom/mymove/files/15253454/B20121-12628.verify_rpt.txt)

No diffs. Looks good.

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
