### PR TITLE
MAIN B-19902 locking moves and UI changes

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION PR](https://github.com/transcom/mymove/pull/12639)
[ISSUE FIX PR](https://github.com/transcom/mymove/pull/12684)

## Summary

In order to "lock" moves while office users are working on them, we must initially set that lock and then display the relevant UI elements to inform the users that the move is currently being worked on at a glance (when viewing their queue) as well as who is working on the move (after entering the move).

This PR does the following:
- updating all database queries done when searching and viewing queues to pull in foreign key values from the `office_users` table 
- updating swagger definitions with newly introduced values
- created new service object to lock a move with office user that is locking it and 30 minute expiration timer
- created component for `LockedMoveBanner.jsx`
- added lock icon to all queues that conditionally renders on values in move
- wrapped all relevant UI code in feature flag checks for `move_code` feature flag

### How to test

1. In your `envrc`, turn `FEATURE_FLAG_MOVE_LOCK` to `true`
2. Fire up `client` & `server`
3. Log in as an office user (can use multi role for efficiency)
4. Enter any move as TOO/TIO/SC
5. Log out
6. Log back in as another user
7. When your queue loads, you should be able to see a lock icon to the left of the move that the previous user entered (we are simulating them "working on it")
8. Enter the move
9. You should see a banner displayed at the top of the screen of the first & last name of the user that is "working on it" as well as their transpo office
10. The lock icon & banner will display until the time in `lock_expires_at` passes, but if any office user enters the move after that time, it will be reset to 30 minutes. Future work will be done to clear these values when the user returns to their queue. Right now they will stay in the database, but UI elements will conditionally render.
11. Within each office role, view queues, perform searches, and the lock icons should still be visible in the queue - if the lock icon is on the move, the banner should display if you are NOT the user that has it locked

## Screenshots
TOO view with locked moves
Screenshot 2024-05-09 at 2 51 20 PM

TOO search with locked move
Screenshot 2024-05-09 at 2 51 32 PM

TIO with locked moves
Screenshot 2024-05-09 at 2 51 43 PM

SC with locked moves in counseling queue & PPM closeout queue
Screenshot 2024-05-09 at 2 50 59 PM

Screenshot 2024-05-09 at 2 52 01 PM

Banner that displays when user is viewing a locked move - read only permissions are being handled in later stories
Screenshot 2024-05-09 at 2 52 35 PM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Looks like there are some differences.
- `swagger-def` has a different placement of `orderType` in the definition. Not sure why that is, but it still exists in the `SearchMoves` definition.

**Comment by danieljordan-caci** [comment]
Could I also get a Happo check from someone? Due to the added `LockedMoveBanner` component.
Thanks!

**Comment by cameroncaci** [comment]
Happo accepted

**Review by cameroncaci — COMMENTED** [review]
Swagger "Affiliation" is also missing from the commit history.. But I see it is present in main. Very odd

**Comment by danieljordan-caci** [comment]
> Swagger "Affiliation" is also missing from the commit history.. But I see it is present in main. Very odd

Yeah I noticed that, too. I went through and checked everything to make sure it was all working and didn't find anything fishy, so.. who knows.

**Review by cameroncaci — APPROVED** [review]
Discrepancies present, but nothing harmful

**Comment by cameroncaci** [comment]
Many discrepancies already present between main and diff
See conflicts https://github.com/transcom/mymove/pull/12044

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
