### PR TITLE
[MB-15421] Remove shipment types for HHG_LONGHAUL_DOMESTIC and HHG_SHORTHAUL_DOMESTIC

### PR DESCRIPTION
**Pull request by bellex3**
## Summary
-Removed all mentions of shipment types `HHG_LONGHAUL_DOMESTIC` and `HHG_SHORTHAUL_DOMESTIC`
Also removed corresponding tests for those shipment types. 
-For the tests that called on `HHG_LONGHAUL_DOMESTIC` and `HHG_SHORTHAUL_DOMESTIC`, I updated the shipment type to `HHG`. 
-Updated Storybook components that mentioned `HHG_LONGHAUL_DOMESTIC` and `HHG_SHORTHAUL_DOMESTIC` shipment types to `HHG`.
-Created a migration file to delete `HHG_LONGHAUL_DOMESTIC` and `HHG_SHORTHAUL_DOMESTIC` shipment types from the `mto_shipments` table and update existing `HHG_LONGHAUL_DOMESTIC` and `HHG_SHORTHAUL_DOMESTIC` shipment types to `HHG`.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test
1) Pull down branch and run `make client_test` and `make server_test`

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by rileyorr** [comment]
Hi @bellex3! I noticed the storybook components for [HHG Longhaul Domestic](https://output.circle-artifacts.com/output/job/5ec77e58-7471-4f17-85bf-30f5bd1e50b7/artifacts/0/storybook/index.html?path=/story/office-components-reviewserviceitems-newserviceitemcards--hhg-longhaul-domestic) and [HHG Shorthaul Domestic](https://output.circle-artifacts.com/output/job/5ec77e58-7471-4f17-85bf-30f5bd1e50b7/artifacts/0/storybook/index.html?path=/story/office-components-reviewserviceitems-newserviceitemcards--hhg-shorthaul-domestic) contain the HHG label. However, when I look at [the Happo diffs](https://happo.io/a/488/p/603/compare/be14a0ff5b11e6029dd5a5581c2d6d18a417d8ce/a9400528b4089f3611e854beb48b4a31345ef842) the before shows the HHG label and the after shows the Basic Service Items label. Does this align with what I should be seeing?

**Review by kylehilltruss — APPROVED** [review]
Whew, this was a huge pull request -- thanks for doing it!

The database migration looks sensible to me, but having another set of eyes on it since we're doing so much alteration makes sense. Everything else looks clean and straightforward.

**Comment by bellex3** [comment]
> Hi @bellex3! I noticed the storybook components for [HHG Longhaul Domestic](https://output.circle-artifacts.com/output/job/5ec77e58-7471-4f17-85bf-30f5bd1e50b7/artifacts/0/storybook/index.html?path=/story/office-components-reviewserviceitems-newserviceitemcards--hhg-longhaul-domestic) and [HHG Shorthaul Domestic](https://output.circle-artifacts.com/output/job/5ec77e58-7471-4f17-85bf-30f5bd1e50b7/artifacts/0/storybook/index.html?path=/story/office-components-reviewserviceitems-newserviceitemcards--hhg-shorthaul-domestic) contain the HHG label. However, when I look at [the Happo diffs](https://happo.io/a/488/p/603/compare/be14a0ff5b11e6029dd5a5581c2d6d18a417d8ce/a9400528b4089f3611e854beb48b4a31345ef842) the before shows the HHG label and the after shows the Basic Service Items label. Does this align with what I should be seeing?

@rileyorr Thank you for catching that. I fixed that NewReviewServiceItem Storybook component and the Happo diff for that is no longer there. It should say HHG now.

**Review by rileyorr — APPROVED** [review]
@bellex3 thank you for making those changes! Confirming the storybook components now have the HHG heading and I reviewed the Happo diffs. LGTM

**Review by kctruss — APPROVED** [review]
Migration looks great, builds with no issues, and when I ran the following query I do not see the deprecated types:

```
SELECT
    pg_type.typname, 
     pg_enum.enumlabel
FROM
    pg_type 
JOIN
    pg_enum ON pg_enum.enumtypid = pg_type.oid
WHERE pg_type.typname = 'mto_shipment_type'
```

Nice work!

**Pull request merged**
