### PR TITLE
Change to using order type variable for comparison instead of pointer.

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## Relevant INT PR
#14285

## Summary

This is just a quick fix for an issue caught by @traskowskycaci on the original PR, the original code could potentially generate a nil pointer exception, so this PR now uses the variable further up in the code that uses logic to handle that case.

### How to test

1. Enable the "FEATURE_FLAG_UNACCOMPANIED_BAGGAGE" FF in the .envrc and re-run `make server_run`
2. Create a move with an OCONUS origin/destination duty location (I used Tok, AK) 
3. Create a UB Unaccompanied baggage shipment. (This weight limiting will work with any shipment type since it's on the order level, but the UB shipment gives us an extra UI spot to verify that the limiting is working).
4. Sign for the move, then login as SC and access the move, you should see on the "Allowances" card that the "Unaccompanied Baggage" field shows 350 lbs:Screenshot 2024-11-26 at 3 07 48 PM
5. Also check the shipment by clicking "Edit Shipment" on the UB shipment card, then verify that this also shows 350 lbs:
Screenshot 2024-11-26 at 3 10 08 PM

P.S. you can also create moves without UB and instead have any other shipment type, and you should still see the "Allowances" card show 350 lbs as shown in step 4, you just won't get the UB shipment card as shown in step 5.

### CODE REVIEW

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by KonstanceH — APPROVED** [review]
LGTM

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Requesting changes while talking with Brooklyn on slack about something I just noticed - when the student travel orders type is selected, both the UB allowance and the move allowance get updated to 350 lbs, which could be an issue

**Comment by traskowskycaci** [comment]
> Requesting changes while talking with Brooklyn on slack about something I just noticed - when the student travel orders type is selected, both the UB allowance and the move allowance get updated to 350 lbs, which could be an issue


After talking with Brooklyn, the [BL AC](https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic:1038429) only mentioned limiting the UB allowance, but at the [feature level](https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic:1038429), there is AC for limiting both. Dismissing my requested changes, thanks for clearing that up @brooklyn-welsh!

**Review by traskowskycaci — APPROVED** [review]
Looks good!

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
