### PR TITLE
Fix some "dep check" issues

### PR DESCRIPTION
**Pull request by reggieriser**
## Description

I hooked up the dep integration in GoLand this morning and it started complaining to me about a few `dep` things.  Ran a `dep check` and it noted we were out of sync on `gobuffalo/uuid` and `mitchellh/mapstructure`.  The former actually is deprecated, so I've fixed the references to it.  The latter was added recently, but the `Gopkg.lock` wasn't updated.  Those have been fixed by running `dep ensure` (after `make clean` and `make server_generate`).

There was another issue it noted:

> \# vendor is out of sync:
> github.com/stretchr/testify: hash of vendored tree not equal to digest in Gopkg.lock

That hash was fixed by the `dep ensure`, but I noticed that `/stretchr/testify` shows version `1.3.0` in the Gopkg.lock file but version `1.2.2` in the Gopkg.toml file.  Maybe that was just a timing issue between when the updater changed the version in `Gopkg.lock` and the explicit version was added to `Gopkg.toml`.

In addition, I get this warning when running `dep ensure`:

> Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
> 
>   ✗  github.com/stretchr/objx
> 
> However, these projects are not direct dependencies of the current project:
> they are not imported in any .go files, nor are they in the 'required' list in
> Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
> these rules will have no effect.
> 
> Either import/require packages from these projects so that they become direct
> dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
> on these projects, if they happen to be transitive dependencies.

I don't see any direct usages of `objx` in the codebase.  @chrisrcoles, do you have any insight into this `stretchr` stuff?  It looks like you added the `Gopkg.toml` constraints.

### CODE REVIEW

**Comment by mkrump** [comment]
> That hash was fixed by the dep ensure, but I noticed that /stretchr/testify shows version 1.3.0 in the Gopkg.lock file but version 1.2.2 in the Gopkg.toml file. Maybe that was just a timing issue between when the updater changed the version in Gopkg.lock and the explicit version was added to Gopkg.toml.

The `Gopkg.toml` has somewhat misleading syntax imo. https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#version 
> Note: When you specify a version without an operator, dep automatically uses the ^ operator by default.

**Comment by chrisgilmerproj** [comment]
Can we specify operators then?

**Comment by reggieriser** [comment]
OK, that makes sense as to why version `1.3.0` was OK in the lock file -- `1.2.2` is going to match anything prior to `2.0`.  I'm curious what our intention was, though, with the version number constraints for the two `stretchr` libraries.  The operator we use would depend on that.

Also, to prevent future sync issues, it looks like we could put a `dep check` [pre-commit hook](https://golang.github.io/dep/blog/2018/07/25/announce-v0.5.0.html#dep-check) in place pretty easily if we can get this sorted out.

**Comment by reggieriser** [comment]
Merged with master and fixed a new sync issue with `github.com/honeycombio/beeline-go/trace`.

**Comment by chrisrcoles** [comment]
Hey @reggieriser - there's no explicit need to lock the versions down for `github.com/stretchr/objx` and `github.com/stretchr/testify`. We can remove these references in the `Gopkg.toml` file. These two dependencies were added as a result of adding the mock generation and mock testing assertion work for the service object work for the [`CreateForm`](https://github.com/transcom/mymove/pull/1679) service object work. Although, I'm not exactly sure how these were added to the `Gopkg.toml`, removing those references should clean everything up.

**Comment by reggieriser** [comment]
Thanks, @chrisrcoles!  I removed the `stretchr` libraries from `Gopkg.toml` and all still seems to be well.  Could you and @chrisgilmerproj please remove your blocks and approve now?

**Pull request merged**
