### PR TITLE
B 19669 Integration

### PR DESCRIPTION
**Pull request by ajlusk**
## Summary
This resolves an null pointer error when searching for a move as a QAE/CSR where one of the resulting moves contains orders with a null origin GBLOC.

In the DB orders.gbloc can be null but there are multiple places in the office API's model_to_payload.go that can't handle a null value. I haven't found a reason that column should be nullable, an alternative solution would have been to make the column not nullable and backfill the bad data in staging. Perhaps that's something to look into in the future.

The same null check was added to the model_to_payload function for the SC's Queue for consistency/future-proofing since the problematic code block was mostly copied from there, however, since the queue is filtered by the SC's GBLOC prior to that function it'll never encounter the issue. 

[Another PR](https://github.com/transcom/mymove/pull/12560) for this issue was prematurely created previously. This solves the issue in a simpler way.

It also re-adds a single line change that was part of B-18891 to solve I-12710 that was overwritten in main. The change is at CustomerInfo.jsx:83. It exists in the [INT PR](https://github.com/transcom/mymove/pull/src/pages/Office/CustomerInfo/CustomerInfo.jsx) but is missing from the [Main PR](https://github.com/transcom/mymove/pull/src/pages/Office/CustomerInfo/CustomerInfo.jsx) for B-18891.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

#### Locally (we need to recreate the "bad" data that exists in staging)
1. Access the orders table in DBeaver/pgadmin
2. Clear the gbloc value for any order (I used the one with id "000606b7-422d-4c56-acf6-78d2c0b782cb" from the e2e_populate data)
3. Access the office app
4. Login as a SC or QAE/CSR.
5. Search for the move you removed the orders for (if you used the same one as me, search for "SPTRMK")
6. You shouldn't receive any errors.
7. Select the move that is missing an origin GBLOC.
8. That move should open without any errors.
9. Repeat the search and opening the move as the other user type.

#### On Staging
1. Access the Office App
2. Login as a SC or QAE/CSR, GBLOC shouldn't matter since you'll be searching.
3. Search for a move by customer name using "pro" as your search term. This is the same search term used when the error was discovered, see "Search Error.docx" on the agility ticket.
4. You should not receive an error. See the attachment on the ticket to see what was occurring before.
5. Find a move with a blank origin GBLOC in the results. This is the/one of the moves that was causing the error. Select it.
6. That move should open without any errors.
7. Repeat the search and opening the move as the other user type.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by MInthavongsay — APPROVED** [review]
Manually manipulated database to create test condition and saw it passed. This is worse case scenario handler but we may want to create a TODO backlog task to look into how/why some orders might potentially might have null values for gbloc.

**Comment by ajlusk** [comment]
> Manually manipulated database to create test condition and saw it passed. This is worse case scenario handler but we may want to create a TODO backlog task to look into how/why some orders might potentially might have null values for gbloc.

Agreed. 

I was unable to recreate the scenario without manually modifying the DB. My speculation is that staging has some old data that can no longer be recreated in-app. 

I set the column to not-null then created and processed several moves without issue.

**Review by CoryKleinjanCACI — APPROVED** [review]
Passes tests and code changes look good.

**Review by r-mettler — APPROVED** [review]
Looks good to me.

**Pull request merged**
