### PR TITLE
B-19923: Admin Office User UI

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

In the PR I am fixing the validation messaging for the Admin Create Office User form and added a restriction that doesn't allow the TOO and TIO role to both be selected.

*Note: There isn't any tests for the Admin Pages like there is for MyMove, and Office pages. There are playwright tests to make sure the Admin can still perform functions.

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Admin App
2. Go to create an office user
3. Try to create an office user with TOO and TIO role (Shouldn't be able to do this)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### BEFORE FIX SCREENSHOTS
image
image

### AFTER FIX SCREENSHOTS
image
image

### CODE REVIEW

**Review by traskowskycaci — DISMISSED** [review]
Would you mind making the error message shown match closer to what Cameron had for what the office user sees [in his PR](https://github.com/transcom/mymove/pull/12698)? Might have to modify the verbiage a bit

**Comment by TevinAdams** [comment]
> Would you mind making the error message shown match closer to what Cameron had for what the office user sees [in his PR](https://github.com/transcom/mymove/pull/12698)? Might have to modify the verbiage a bit

Yeah let me check out what he has.

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
You'll need to also address the situations where an office user can:
- edit a requested office user
- edit an existing office user

Screenshot 2024-05-20 at 11 56 54 AM

Right now I can approve a ROO and edit an office user with both TOO and TIO roles

**Comment by TevinAdams** [comment]
> You'll need to also address the situations where an office user can:
> 
> * edit a requested office user
> * edit an existing office user
> 
> Screenshot 2024-05-20 at 11 56 54 AM
> 
> Right now I can approve a ROO and edit an office user with both TOO and TIO roles

The AC only has create. But I can add those in the AC but the points for the story will go up because I have to fix the validation for those.

**Comment by danieljordan-caci** [comment]
> > You'll need to also address the situations where an office user can:
> > 
> > * edit a requested office user
> > * edit an existing office user
> > 
> > Screenshot 2024-05-20 at 11 56 54 AM
> > Right now I can approve a ROO and edit an office user with both TOO and TIO roles
> 
> The AC only has create. But I can add those in the AC but the points for the story will go up because I have to fix the validation for those.

Description of the feature paints a broader brush, so we need to make sure we are also looking at that:
```
As a MilMove Admin, I want MilMove to ensure that a user cannot have both TOO & TIO roles, so that US TRANSCOM policy requiring the separation of these two roles is enforced.

ORIGINAL DESCRIPTION:

MilMove allows one user to have both TOO & TIO roles.  US TRANSCOM policy  does not allow one user to have both roles.
 
MilMove will enforce the policy of only allowing one role to be selected in both the registration process and under the Admin capability.
```

**Comment by TevinAdams** [comment]
> > > You'll need to also address the situations where an office user can:
> > > 
> > > * edit a requested office user
> > > * edit an existing office user
> > > 
> > > Screenshot 2024-05-20 at 11 56 54 AM
> > > Right now I can approve a ROO and edit an office user with both TOO and TIO roles
> > 
> > 
> > The AC only has create. But I can add those in the AC but the points for the story will go up because I have to fix the validation for those.
> 
> Description of the feature paints a broader brush, so we need to make sure we are also looking at that:
> 
> ```
> As a MilMove Admin, I want MilMove to ensure that a user cannot have both TOO & TIO roles, so that US TRANSCOM policy requiring the separation of these two roles is enforced.
> 
> ORIGINAL DESCRIPTION:
> 
> MilMove allows one user to have both TOO & TIO roles.  US TRANSCOM policy  does not allow one user to have both roles.
>  
> MilMove will enforce the policy of only allowing one role to be selected in both the registration process and under the Admin capability.
> ```

I didn't hit expand. I see the update AC there. Im still going to have to fix those validations though.

**Comment by TevinAdams** [comment]
> > > You'll need to also address the situations where an office user can:
> > > 
> > > * edit a requested office user
> > > * edit an existing office user
> > > 
> > > Screenshot 2024-05-20 at 11 56 54 AM
> > > Right now I can approve a ROO and edit an office user with both TOO and TIO roles
> > 
> > 
> > The AC only has create. But I can add those in the AC but the points for the story will go up because I have to fix the validation for those.
> 
> Description of the feature paints a broader brush, so we need to make sure we are also looking at that:
> 
> ```
> As a MilMove Admin, I want MilMove to ensure that a user cannot have both TOO & TIO roles, so that US TRANSCOM policy requiring the separation of these two roles is enforced.
> 
> ORIGINAL DESCRIPTION:
> 
> MilMove allows one user to have both TOO & TIO roles.  US TRANSCOM policy  does not allow one user to have both roles.
>  
> MilMove will enforce the policy of only allowing one role to be selected in both the registration process and under the Admin capability.
> ```

@danieljordan-caci Its fixed when editing. I just had to apply my same fix. It was simple.

**Comment by danieljordan-caci** [comment]
> > > > You'll need to also address the situations where an office user can:
> > > > 
> > > > * edit a requested office user
> > > > * edit an existing office user
> > > > 
> > > > Screenshot 2024-05-20 at 11 56 54 AM
> > > > Right now I can approve a ROO and edit an office user with both TOO and TIO roles
> > > 
> > > 
> > > The AC only has create. But I can add those in the AC but the points for the story will go up because I have to fix the validation for those.
> > 
> > 
> > Description of the feature paints a broader brush, so we need to make sure we are also looking at that:
> > ```
> > As a MilMove Admin, I want MilMove to ensure that a user cannot have both TOO & TIO roles, so that US TRANSCOM policy requiring the separation of these two roles is enforced.
> > 
> > ORIGINAL DESCRIPTION:
> > 
> > MilMove allows one user to have both TOO & TIO roles.  US TRANSCOM policy  does not allow one user to have both roles.
> >  
> > MilMove will enforce the policy of only allowing one role to be selected in both the registration process and under the Admin capability.
> > ```
> 
> @danieljordan-caci Its fixed when editing. I just had to apply my same fix. It was simple.

Make sure you also cover `RequestedOfficeUserEdit` too

**Comment by cameroncaci** [comment]
@TevinAdams @danieljordan-caci Ticket is improper. Please see attached feature breakdown for the full ticket details, not sure why it wasn't put in there fully the first time around

**Comment by danieljordan-caci** [comment]
> @TevinAdams @danieljordan-caci Ticket is improper. Please see attached feature breakdown for the full ticket details, not sure why it wasn't put in there fully the first time around. The attachment includes "updating an office user" as part of the AC

Understand that, but looks like when admins are editing requested office users we aren't covering down on that. So I believe that would be covered on this BL item since it is in the Admin UI.

Other than that looks like it's all good

**Comment by cameroncaci** [comment]
> > @TevinAdams @danieljordan-caci Ticket is improper. Please see attached feature breakdown for the full ticket details, not sure why it wasn't put in there fully the first time around. The attachment includes "updating an office user" as part of the AC
> 
> Understand that, but looks like when admins are editing requested office users we aren't covering down on that. So I believe that would be covered on this BL item since it is in the Admin UI.
> 
> Other than that looks like it's all good

I concur

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
Tested locally and works good. Looks like you have some integration tests failing, I'll approve once those are all good to go!

**Comment by TevinAdams** [comment]
> Tested locally and works good. Looks like you have some integration tests failing, I'll approve once those are all good to go!

Yeah im fighting playwright locally right now.

**Comment by TevinAdams** [comment]
> Tested locally and works good. Looks like you have some integration tests failing, I'll approve once those are all good to go!

@danieljordan-caci  its done.

**Review by danieljordan-caci — APPROVED** [review]

**Review by traskowskycaci — APPROVED** [review]

**Pull request merged**
