### PR TITLE
update-country-code-from-unitedstates-to-us

### PR DESCRIPTION
**Pull request by NamibiaTorres**
## Summary

The getMoveTaskOrder api for the Prime can return United States or US, but it should only be returning US. This is happening because early in the application's history, data had been inputted with country codes that were more than 2 digits, this has since changes and we want to make sure that the application returns the 2 digit country code all the time. 

This PR updates the addresses table to replace instances of 'United States' with 'US', it's 2 digit country code.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. In the `main` branch check the addresses table, country column, for references to 'United States'
2. Then log into this branch [NT-MB-16799-update-country-code-to-US](https://github.com/transcom/mymove/tree/NT-MB-16799-update-country-code-to-US) and check that the same addresses have an updated country code of 'US'

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by ronaktruss** [comment]
🎉 this works as expected!

I just realized that their might be two similar but separate issues around the country value for addresses:
1. There are addresses that have a country value of United States but we want the value to be US
2. There are addresses that don't have a country value (ie. are null)

This ticket only mentions issue 1 and this PR resolves the issues for that.
Since there are some instances were the UI is not storing the country to the address table because the UI is not sending the value (ie. a shipment's pickup address), we'll need to make similar migrations in the future. 

While these are separate issues, maybe it would make sense to try and resolve the other issue before making this migration so that we don't have to make it multiple times?

**Comment by NamibiaTorres** [comment]
> 🎉 this works as expected!
> 
> I just realized that their might be two similar but separate issues around the country value for addresses:
> 
> 1. There are addresses that have a country value of United States but we want the value to be US
> 2. There are addresses that don't have a country value (ie. are null)
> 
> This ticket only mentions issue 1 and this PR resolves the issues for that. Since there are some instances were the UI is not storing the country to the address table because the UI is not sending the value (ie. a shipment's pickup address), we'll need to make similar migrations in the future.
> 
> While these are separate issues, maybe it would make sense to try and resolve the other issue before making this migration so that we don't have to make it multiple times?

@ronaktruss question to make sure I understand correctly: Since the UI isn't sending the country code instead of blank for that address we need to make sure that null is stored instead?

**Comment by ronaktruss** [comment]
> @ronaktruss question to make sure I understand correctly: Since the UI isn't sending the country code instead of blank for that address we need to make sure that null is stored instead?

@NamibiaTorres Right now since the UI isn't always sending the country code the DB is already storing a NULL value. We probably want to update the UI so that we are always passing and storing `US`.

**Comment by NamibiaTorres** [comment]
> > @ronaktruss question to make sure I understand correctly: Since the UI isn't sending the country code instead of blank for that address we need to make sure that null is stored instead?
> 
> @NamibiaTorres Right now since the UI isn't always sending the country code the DB is already storing a NULL value. We probably want to update the UI so that we are always passing and storing `US`.

What about in the cases where the address potentially isn't in the US?

**Comment by ronaktruss** [comment]
> > > @ronaktruss question to make sure I understand correctly: Since the UI isn't sending the country code instead of blank for that address we need to make sure that null is stored instead?
> > 
> > 
> > @NamibiaTorres Right now since the UI isn't always sending the country code the DB is already storing a NULL value. We probably want to update the UI so that we are always passing and storing `US`.
> 
> What about in the cases where the address potentially isn't in the US?

Right now, we are only supporting conus moves so there are no addresses outside of the US. When we do start to have oconus moves we'll either need to explicitly ask the user to entry the country or make that an option for just those oconus moves.

**Comment by NamibiaTorres** [comment]
> > > > @ronaktruss question to make sure I understand correctly: Since the UI isn't sending the country code instead of blank for that address we need to make sure that null is stored instead?
> > > 
> > > 
> > > @NamibiaTorres Right now since the UI isn't always sending the country code the DB is already storing a NULL value. We probably want to update the UI so that we are always passing and storing `US`.
> > 
> > 
> > What about in the cases where the address potentially isn't in the US?
> 
> Right now, we are only supporting conus moves so there are no addresses outside of the US. When we do start to have oconus moves we'll either need to explicitly ask the user to entry the country or make that an option for just those oconus moves.

I'll make a new PR for this change, but I'm thinking this is feature is something I'll need to record in the new PR and also create a ticket for (if the new contractor is using our remaining JIRA tickets to wrap up our work).

**Review by ronaktruss — APPROVED** [review]
This looks good to me. We discussed some additional related work that is being captured in [this ticket](https://dp3.atlassian.net/browse/MB-17051)

**Pull request merged**
