### PR TITLE
[MB-10351] Update ShipmentDisplay stories to use error and warning props that more accurately reflect usage in the app

### PR DESCRIPTION
**Pull request by hannaliebl**
## Summary

This ended up being pretty small, because the behavior in the app is already correct: any value that is required on the shipment form fields should always show as missing in the collapsed view on the shipment cards if it is missing.

In any case, this is just updating the prop values in the two "missing info" stories for NTS and NTS-release shipments so that those values match what is in the app now. I also added counselor remarks as a "warning" field for demonstration purposes, as that is shown as a warning field on service counselor views.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use one terminal to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

</details>

### Additional steps

1. View the NTS Shipment missing info story (http://localhost:6006/?path=/story/office-components-shipment-display--nts-shipment-missing-info) and the NTS Release shipment missing info story (http://localhost:6006/?path=/story/office-components-shipment-display--nts-release-shipment-missing-info) and confirm that the missing/warning fields show up in both the collapsed and expanded state.

## Verification Steps for Author

These are to be checked by the author.

- [X] Request review from a member of a different team.
- [X] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### CODE REVIEW

**Review by mlm55 — APPROVED** [review]
lgtm!

**Review by YanZ777 — COMMENTED** [review]
I'm ok with these changes. 
I do want to point out that the ShipmentDisplay is being used by both the TOO and Services Counselor, so what things show up as error or warning will change between the two. 
I think that we should have additional stories added to differentiate between all the roles and shipment types for the ShipmentDisplay story, but I'd be interested in hearing what other people think about this too.

**Comment by hannaliebl** [comment]
@YanZ777 that's a good idea, I can do that here.

**Comment by hannaliebl** [comment]
@YanZ777 I added two more stories for SC with missing shipment info.

**Review by YanZ777 — APPROVED** [review]
Thanks for adding extra stories. I think this should help clarify future confusion as to what the shipment displays should be showing for each shipment and role type.

**Review by brooksr4 — APPROVED** [review]

**Pull request merged**
