### PR TITLE
MB-6483 Update host names to match GovCloud

### PR DESCRIPTION
**Pull request by monfresh**
## Description

We still had some files where we were referring to the old host names
before the migration to GovCloud. This PR updates them to the correct
host names.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6483) for this change

### CODE REVIEW

**Review by kilbergr — CHANGES_REQUESTED** [review]
Did you test out running these scripts? 
These look to alter the host names, but I think you may still have issues, at least in the `health-tls-check` script here: https://github.com/transcom/mymove/pull/5770/files#diff-782c855f982ba91748459faa93f197665bdcd78fd6992063d4932b5762ad3723R37, which is referring to the transcom-ppp account ID I suspect. You're also still using the app-experimental chamber commands: https://github.com/transcom/mymove/pull/5770/files#diff-782c855f982ba91748459faa93f197665bdcd78fd6992063d4932b5762ad3723R48. Finally, dps.ENV.move.mil (https://github.com/transcom/mymove/pull/5770/files#diff-782c855f982ba91748459faa93f197665bdcd78fd6992063d4932b5762ad3723R21) no longer exists--it's now my.ENV.move.mil.

I recently updated a similar script: https://github.com/transcom/mymove/blob/master/scripts/deploy-app-client-tls, which I think you could use as a guide.

**Comment by monfresh** [comment]
Thanks for the tips, @kilbergr! I tried the script but I couldn't get authenticated, which is why I asked for Infra's review because I knew I would likely miss some things. For some reason, those links in your comment aren't working. On what line is transcom-ppp being used, and what should it change to?

**Comment by kilbergr** [comment]
It looks like you made the changes ! It was line 37 (which you removed) and making sure the right ids were passed in for each env. The reason you couldn't run it with auth before I believe would be due to the fact that it was in com. Now that it's in gov, you may have the perms to run. Give it a try! I suspect the incantation would be something like `DISABLE_AWS_VAULT_WRAPPER=1 aws-vault exec transcom-gov-milmove-exp -- scripts/health-tls-check`. If you still have auth problems, lmk and I'll run to confirm.

**Comment by monfresh** [comment]
Aha! I was missing the incantation. It worked! Thanks!

**Review by kilbergr — COMMENTED** [review]
Fantastic! 
Now the only thing I would like before you merge is for you to document that incantation in the scripts readme. You can use the one for the `deploy-app` scripts as an example (https://github.com/transcom/mymove/blob/master/scripts/README.md#deployment-scripts).

**Review by duncan-truss — APPROVED** [review]

**Comment by monfresh** [comment]
Thanks @kilbergr! I updated the Readme.

**Review by kilbergr — APPROVED** [review]
Thank you for all those changes. This looks great!

**Pull request merged**
