### PR TITLE
B 18086 identify create values 13 17

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## Summary

[From PR: https://github.com/https://github.com/transcom/mymove/pull/11740] A "GET" end point was added to PPM Shipments to retrieve PPM closeout calculations. The calculations will be added to the response by other stories...

In this PR the calculations for values 1-6 from the Feature Agility Ticket E-04525 are implemented.
- Domestic Origin
- Destination Price
- Packing Price 
- Unpacking price
- SIT Reimbursement Charges
- Individual breakdown

### Obtain a ppm shipment id

Find a move that has a PPM Shipment.
Use the following query to get the PPM shipment id
Change "m.locator" in the where clause to the move code.

```
  select m.locator as move_code
         , m.id as move_id
         , ms.id as mto_shipment_id
         , ps.id as ppm_shipment_id
         , ms.shipment_type
    from moves m 
         inner join mto_shipments ms
         on m.id = ms.move_id
         inner join ppm_shipments ps
         on ms.id = ps.shipment_id
   where 1 = 1
     and m.locator = 'CHANGE_ME'
     and ms.shipment_type = 'PPM'
  order by m."locator"
           , ms.id 
           , ms.shipment_type 
```

### Get MilMove login cookie values

Login to MilMove as a counselor
Open developer tools
Go to: Applications tab > Storage > Cookies > http://officelocal:3000/
Record the values for the following cookies:
_gorilla_csrf
masked_gorilla_csrf
office_session_token
Open Postman.

In the MilMove GHC API collection, drill down to the closeout endpoint.
ppm-shipments > {ppmShipmentId}/closeout/Get the closeout calculations

**NOTE**: This PR adds a check so that only PPM moves that are ready for closeout (i.e. the customer has submitted the final PPM documentation) are valid for this endpoint, if a PPM move isn't ready for final closeout, you'll get an HTTP 404 error with a message telling you this.

Under the "Send" button, click the "cookies" link to add cookies

Add the 3 cookies recorded previously

Add an additional cookie, "X-CSRF-Token". Its value will be the same as the "_gorilla" cookie. Then close the cookies window.

In the "Path Variables" section, set the PPM shipment id and click "Send".

Verify the values for the field in the JSON response matches the associated fields for values 1-6 from that particular PPM shipment.
## Screenshots
Screenshot 2024-01-19 at 5 45 51 PM
ts

### CODE REVIEW

**Review by taeJungCaci — APPROVED** [review]
Code works for me.

**Comment by brooklyn-welsh** [comment]
> It seems like the other fields that were previously populated are null now even if they have values in the db

Okay, I'll double check and make sure everything's working on my end.

**Comment by KonstanceH** [comment]
> > It seems like the other fields that were previously populated are null now even if they have values in the db
> 
> Okay, I'll double check and make sure everything's working on my end.

Actually looks like my linter took a minute to catch up to me? I was missing a line from the top and it was crashing without telling me. Everything looks good!

**Review by KonstanceH — APPROVED** [review]

**Comment by brooklyn-welsh** [comment]
Closing in response to new dev process in effect starting today.

**Pull request closed without merging**
