### PR TITLE
B 21455 main

### PR DESCRIPTION
**Pull request by CoryKleinjanCACI**
## Summary

This change update the service counselor and TOO roles to be able update ppm shipments that have a estimated incentive of zero. An estimated incentive of zero can, currently, only be achieved when a customer pushes a PPM when DTOD is down. 

The Service Counselor role updates the ppms when they select the 'Submit move details' button.

The TOO updates the ppms when the attempt to approve either the move or an individual shipment.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Service Counselor:
1. Set DTOD_SIMULATE_OUTAGE to true and run the app
2. Access the Customer application
3. Login as a Customer
4. Create a Move
5. Add a PPM
6. Submit the move for review
7. Validate the the estimated incentive is zero in the ppm_shipments table for the shipment you created
8. Set DTOD_SIMULATE_OUTAGE to false and re-rerun the server (you can also run the test without this step, but you will be unable to approve the move and will instead see a message about DTOD being down)
9. Login as a Service Counselor
10. Select the move you created
11. Fill in missing details 
12. Submit the move
13. Validate the the estimated incentive in the ppm_shipments table is no longer zero for the shipment you created

##THE ABILITY FOR TOO TO APPROVE PPMS IS CURRENTLY BROKEN IN INTEGRATION DUE TO ANOTHER TASK
TOO:
1. Set DTOD_SIMULATE_OUTAGE to true and run the app
2. Access the Customer application
3. Login as a Customer
4. Create a Move with the Current Duty Station set to 'NS Mayport' (this allows the TOO to approve ppm shipments without the SC approval)
5. Add a PPM
6. Submit the move for review
7. Validate the the estimated incentive is zero in the ppm_shipments table for the shipment you created
10. Set DTOD_SIMULATE_OUTAGE to false and re-rerun the server (you can also run the test without this step, but you will be unable to approve the move and will instead see a message about DTOD being down)
11. Login as a TOO
12. Select the move you created
13. Fill in missing details 
14. Select the PPM shipment for approval
15. Select the Counseling check box
16. Attempt to approve the Move and ppm shipment you created
17. Validate the the estimated incentive in the ppm_shipments table is no longer zero for the shipment you created

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by MInthavongsay — APPROVED** [review]
There are some subtle differences that I attribute to the merges between INT vs MAIN. But overall, this PR should be good merge.

**Review by r-mettler — APPROVED** [review]
same as INT

**Review by antgmann — CHANGES_REQUESTED** [review]
image

Wanted to document the current failing client test, I'm encountering it even on my local so it's definitely not flaky. It's required to pass to merge anyways.

**Comment by loganwc** [comment]
> image
> 
> Wanted to document the current failing client test, I'm encountering it even on my local so it's definitely not flaky. It's required to pass to merge anyways.

Are there changes in integration that this is dependent on? The test doesn't look like it was failing in integration

**Comment by antgmann** [comment]
> Are there changes in integration that this is dependent on? The test doesn't look like it was failing in integration

We've been investigating, we're not sure of the cause yet. It does pass in int. The submit move details button is greyed out when the client test is trying to click it, so not sure what the root cause is yet

**Review by antgmann — APPROVED** [review]
Client test is now passing with latest changes, which are being pulled into int in https://github.com/transcom/mymove/pull/14322#pullrequestreview-2476254916

Looks good for a merge once the above is in INT and main is unlocked.

**Pull request merged**
