### PR TITLE
ADR defining browser support

### PR DESCRIPTION
**Pull request by ntwyman**
## Description

Pulled from github/jeffsclark/mymove patch-1 and patch-2, so can be landed via CircleCI

## Reviewer Notes

Note this came from upstream source.

## Verification Steps

* [x] All tests pass.
* [n/a] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely) have been satisfied.
* [n/a] There are no [aXe](https://www.deque.com/products/aXe/) warnings for UI.
* [n/a] This works in IE.

### CODE REVIEW

**Comment by akostibas** [comment]
What a wonderful use of an ADR

**Comment by kilbergr** [comment]
Missing ADR 0014

**Comment by jim** [comment]
In an effort to push this towards completion, I came up with the following requirements by looking at browser release dates. For rapid release browsers, I selected base versions based on what the most recent version was 1 year ago. For those with less frequent releases, I chose the previous major version.

_Windows 10_
IE 11, Edge 12+

_Windows 10, macOS_
Chrome 56+
Firefox 52+

_macOS_
Safari 10+

_iOS 10+_
Mobile Safari (Locked to OS version)

_Android_
Chrome for Android 56+

@brainsik WDYT?

**Comment by brainsik** [comment]
@jim Looks great!

**Comment by jeffsclark** [comment]
I am good on everything.  I think we can get a little tighter on the rapid release browsers.  Google has stated they only support their products on the current and previous version of browsers.  I think we can tighten our support to Firefox 58+, and Chrome to 64+.  Even if they use an older version of Firefox or Chrome, the risk of error is very small.

All other browser are spot on.

**Comment by brainsik** [comment]
Following on Jeff's comment, I think the real reality is we'll always be testing on the latest Firefox and Chrome. Chrome is particularly aggressive with giving you updates. The version numbers here seem more like minimum requirements than testing requirements. Let's clarify that.

**Comment by jim** [comment]
@jeffsclark and @brainsik Thanks for the input and working through this. I think we're close!

I have updated the minimum supported versions in the comment above and also added that list and an explanation about the difference between those versions and what we'll be regularly testing in as we develop. (You can see see the latest version of the document [here](https://github.com/transcom/mymove/blob/318861f4170ce0428b02b3f51f2810b8fe64e603/docs/adr/0016-Browser-Support.md) or using the Files Changed tab above).

Please let me know if there are other tweaks to be made before we get this one merged in.

**Pull request merged**
