### PR TITLE
B-18312-MultiMove-Dashboard Routing-And-Playwright-Tests

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

This PR introduces the Multi Move dashboard. When the service member logs in they are routed to the multi move dashboard.

*note - Yarn install needed to be ran on my integration branch but not on this main branch which is why yarn.lock is not auto modified on ths PR. This is why 24 files are changed in this PR rather than 25.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Ensure that the multiMove feature flag is switched on for your respective environment
2. Log into MilMove as a service member
3. You should have been routed to the Multi Move Dashboard

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image

### CODE REVIEW

**Comment by TevinAdams** [comment]
I have been fighting with undoing work I didnt do the old branch so I created a new one off main with the work I submitted into integration. The old branch was getting very messy and I was not sure why. I suspect it because I created that main branch a long time ago before the new branching strategy and it has had old feature flag work from other feature branches merged in, integration accidentally merged into it then reverted from when we first started the new branch strategy, then a bunch of commits and reverts from me trying to undo work on the branch I did not do. This branch is off main and has only the work I submitted to integration.

**Comment by cameroncaci** [comment]
@TevinAdams Conflict due to new Flipt implementation. Very small

**Comment by TevinAdams** [comment]
> @TevinAdams Conflict due to new Flipt implementation. Very small

Yeah I just updated it with your changes in main so it should be good to go now.

**Comment by cameroncaci** [comment]
The failing tests may be due to FF. CircleCI runs tests with the FF turned off, we want to make sure that if our FF is turned off then tests are functional

**Review by traskowskycaci — COMMENTED** [review]
Would you mind marking this one as draft if it's still in work?

**Review by traskowskycaci — COMMENTED** [review]
Quite a big difference in changed lines between the integration PR and main PR - anything specifically that would cause that?

**Comment by TevinAdams** [comment]
> Quite a big difference in changed lines between the integration PR and main PR - anything specifically that would cause that?

Yeah so on integration I had to do a yarn install. But I didnt need to do that for main so yarn.lock is not being modified like the PR into integration.

**Comment by traskowskycaci** [comment]
> > Quite a big difference in changed lines between the integration PR and main PR - anything specifically that would cause that?
> 
> Yeah so on integration I had to do a yarn install as it was required by the pipelines. I did the same to my main branch just to keep the consistency even though the pipeline was not requiring it. But It turns out I didn't need to do that for main so yarn.lock is not being modified like the PR into integration. By doing that on Main within the install dependencies job of the linter I was getting permission denied when trying to read from trussworks repo. So I removed that changed and then that issue went away. Not quite sure in totality what yarn install and that yarn.lock file changed but it doesn't work on the Main branch like it did on the integration branch. Mainly it was preventing linter from installing needed dependencies which was causing the job to fail. I removed that change in this branch and now the job can successfully install those dependencies.

Ok. I went through your commits in this branch and saw they match the hashes for the commits in the int branch with the exception of the later commits concerning the yarn lock stuff you mentioned. Looks like extra stuff from other branches in your int may account for some of the diffs too. I am approving but would also be good if someone double checks the yarn stuff going into main too.

**Review by traskowskycaci — APPROVED** [review]

**Review by danieljordan-caci — APPROVED** [review]

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
