### PR TITLE
B 18480 int

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

PPM move is created by Customer from a location that is not services counseled
login in as TOO of origin location to approve move and approve services counseling service item
login as prime  to submit  payment request for counseling
login as TIO to review payment request
click review weights > click review shipment weights
verify estimated weight is now displaying

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Not sure where I am going wrong on the process but I can't get past this point in the services counselor role for the move:
image

My steps: 
- Created PPM move
- Service counseled
- Uploaded PPM docs as customer
- On the services counselor -> PPM closeout page, accepted
- Stuck here, don't see move in prime sim or other roles

**Comment by deandreJones** [comment]
> Not sure where I am going wrong on the process but I can't get past this point in the services counselor role for the move: image
> 
> My steps:
> 
> * Created PPM move
> * Service counseled
> * Uploaded PPM docs as customer
> * On the services counselor -> PPM closeout page, accepted
> * Stuck here, don't see move in prime sim or other roles

for duty_locations that are not services counseled, those will not show up in the counselors queue, it goes straight to the TOO
to approve the move and approve the services counseling for prime to handle
image

image

**Comment by deandreJones** [comment]
updated the steps to be more accurate

  *   thats what i get for copying the steps from the tester, lol

Thanks,

De Andre Jones
Software Engineer, Lead
CACI, Inc
618.420.9433
________________________________

**Review by danieljordan-caci — APPROVED** [review]

**Review by traskowskycaci — APPROVED** [review]
Looks good!
image

**Pull request merged**
