### PR TITLE
B-20462 Enforce N9 1W Character Limit INT

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

We are needing to enforce some characters limits in the EDI 858 invoice generation for fields that have caused issues or could cause issues in the future. One of those fields is the Service Member Name, the N9 1W segment of the EDI 858. We want to truncate the middle name down to the middle initial only, and truncate the entire name down to 30 characters if it happens to be longer. The truncation will also end the name with three trailing dots `...` to indicate that it's been truncated.

To test:

1. Click on View Testharness Data Scenarios as an office user
image
2. Click on MakeMoveReadyForEDI
3. Search for the first_name that is generated, and find that in the database. You'll also use the payment_request_number from this output so don't close out of it.
4. Modify the first name, middle name, and last name to be whatever you want that is under 30 characters total for lastName, M. firstName
5. Generate the EDI 858 locally - `go run ./cmd/generate-payment-request-edi/ --payment-request-number <payment_request_number>` where the payment_request_number comes from the MakeMoveReadyForEDI output.
6. Search for 1W in the output, and check that the middle name is shortened to just the middle initial.
7. Modify the first name, middle name, and last name to be something longer than 30 characters total.
8. Regenerate the EDI 858 and search for 1W in the output, and check that it is truncated down to 30 characters and ends in `...`

## Screenshots
Truncating middle name down to middle initial:
image

- EDI 858 generated:

image

Truncating the entire name down to 30 characters:
image

- EDI 858 generated:

image

### CODE REVIEW

**Comment by TevinAdams** [comment]
@traskowskycaci  Are the trailing "..." included in the 30 characters?

**Comment by traskowskycaci** [comment]
> @traskowskycaci Are the trailing "..." included in the 30 characters?

Yes they are

**Review by TevinAdams — APPROVED** [review]
Test case worked and tested locally.

**Review by danieljordan-caci — APPROVED** [review]
Tested locally. Stupendous.

Screenshot 2024-07-24 at 10 36 35 AM
Screenshot 2024-07-24 at 10 37 37 AM

**Pull request merged**
