### PR TITLE
[MB-6430] Manual date entry in DatePickerInput on TIO filter triggers 500 error

### PR DESCRIPTION
**Pull request by duncan-truss**
## Description

Editing the Submitted at date filter in the TIO payment requests queue manually with the keyboard instead of using the Date Picker UI would cause an 'Invalid date' value being sent to the api causing a 500 error.  The field handled invalid or incomplete dates properly, it was only when you provided a valid date in the format 'DD MMM YYYY' that it sent the bad request.

I've updated the swagger param for the submittedAt filter to be of format date so that it will catch bad requests and return a 422 error instead of a 500 error.

For the DatePickerInput component I saw we were reusing the onChange handler for both when the SingleDateInput picker UI is updated as well as part of the inputProps being passed the input field itself.  I removed attaching the onChange listener to the underlying `<input>` form field.

This DatePickerInput is being used on the Customer side as well in the Orders form and I saw the validation message there was not a user friendly error message so I updated the copy based on recommendations from James https://ustcdp3.slack.com/archives/CTNTFJSBA/p1611766050125800?thread_ts=1611684009.111700&cid=CTNTFJSBA

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make office_client_run
```

Test TIO Queue Filter
1. Login as the TIO user
2. Type a date into the Submitted queue filter text input in the format of '26 Jan 2020'
3. The queue should properly filter the payment requests sending the proper value to the api '2020-01-26' instead of 'Invalid date' causing a 500 error

Test New Validation Message
1. Login as the TOO/TIO user and then navigate to the Edit Orders page either from the Move Details or Move Payment Request page
2. For orders issue date or report by date, type in a malformatted date such as '2021-31-01' or incomplete date '27 Jan 20' and move focus from the input to trigger the form validation

1. Login as a Service Member needing orders information such as the needs@orde.rs test user
2. Choose add orders from the home screen
3. For orders issue date or report by date, type in a malformatted date such as '2021-31-01' or incomplete date '27 Jan 20' and move focus from the input to trigger the form validation

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6430) for this change

## Screenshots

https://user-images.githubusercontent.com/52669884/105884793-5645ff00-5fd6-11eb-8efa-a85da92d5794.mov

https://user-images.githubusercontent.com/52669884/106014502-8c918600-608b-11eb-8bb7-7b3f5a6f8659.mov

Previous Service Member orders validation message
Screen Shot 2021-01-26 at 12 24 02 PM

Updated Service Member orders validation message
Screen Shot 2021-01-27 at 2 25 32 PM

Updated TXO edit orders form validation message
Screen Shot 2021-01-27 at 2 24 08 PM

### CODE REVIEW

**Review by donaldthai — APPROVED** [review]
Works and LGTM :shipit:

**Review by jenniferlynparsons — APPROVED** [review]
Yup! Works and looks good!

**Review by noelledusahel — APPROVED** [review]
LGTM, worked even with a non existent date 29 Feb 2021

**Review by amanda5iu — APPROVED** [review]
NICE.

**Pull request merged**
