### PR TITLE
[MB-4584] - Remove SSN from DODinfo component, update tests

### PR DESCRIPTION
**Pull request by amitch23**
## Description

Removes the SSN from the profile signup flow, as well as all references in the client and API.

Migration to remove SSN table, and SSN column/FK on the service member table here: https://github.com/transcom/mymove/pull/5204 

Migration PR should be merged after this PR.

## Reviewer Notes

There are some SSN references scattered throughout the IWS (identity web services) cmd, pkg, etc. (e.g. https://github.com/transcom/mymove/blob/master/pkg/iws/rbs_person_lookup.go#L30, https://github.com/transcom/mymove/blob/master/pkg/iws/person.go#L36, etc.) 

They look they haven't been touched in quite a while (9 months ago, then 2 years ago) and I'm not sure if we need to support SSN in this area. Feedback welcome :)

## Setup

Run the server and app locally and create a new user. Walk through the flow and ensure the SSN field does not appear. Ensure no errors happen.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4585) for this change

## Screenshots

Mobile:
Screen Shot 2020-11-10 at 5 33 09 PM

Desktop:
Screen Shot 2020-11-10 at 5 33 16 PM

### CODE REVIEW

**Review by lynzt — CHANGES_REQUESTED** [review]
We'll want to split out the migration to drop the SSN field into another pr to run after the code to remove the SSN is merged

**Review by mariaclaratgolfo — APPROVED** [review]
Assuming the page no longer requires the SSN [doesn't block the Next CTA or throw validation errors] to move forward — this looks good!

**Review by Ronolibert — APPROVED** [review]
Field is gone and everything works as expected!

**Review by lynzt — APPROVED** [review]
Took a look at the code but didn't run it locally - But based on Ron's review - 🚢

**Pull request merged**
