### PR TITLE
[MB-4883] Frontend static analysis

### PR DESCRIPTION
**Pull request by duncan-truss**
## Description

This PR removes inline code suppression of the ad-hoc eslint rules in javascript files.  Of note there are multiple .eslintrc configuration files because of legacy code that has made it difficult to migrate all at once.

Main configuration - [.eslintrc](https://github.com/transcom/mymove/pull/5086/files#diff-e7e195d3d8fa5b82fa51ed952f3a179d429cbc46c0432ce1f7b357c54c162822)
Browser E2E test configuration - [cypress/.eslintrc](https://github.com/transcom/mymove/pull/5086/files#diff-b02b07412ac260a9eaca91b22406953db23f0e64cc76b614d4a20469c586e22a)
Scenes configuration - [src/scenes/.eslintrc](https://github.com/transcom/mymove/pull/5086/files#diff-aee380a3b12ea626a19092ed237dab2c70bb7addef0ae21bf915e2cf37961e32)
Shared configuration - [src/shared/.eslintrc](https://github.com/transcom/mymove/pull/5086/files#diff-67aff82badc92a268b79c416b1400367f3a6ef04997d533df85fdc0bbb6ad5dd)

The list of warnings and errors is saved as an artifact of the pre_test circleci job https://app.circleci.com/pipelines/github/transcom/mymove/22722/workflows/4368329b-2787-49a4-9a23-0f3cd6ccd68d/jobs/351310/artifacts

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
yarn lint
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

### CODE REVIEW

**Comment by duncan-truss** [comment]
Suz and Design please ignore this PR it's related to the ATO static analysis attempting to determine potential security issues to address.

**Review by chrisrcoles — APPROVED** [review]
LGTM!

**Comment by duncan-truss** [comment]
> The yarn additions LGTM -- what's the plan for this work? Will we eventually merge this?

@chrisrcoles I didn't think this was going to be a long running branch, just one to inventory the work needed the we'll close it.  I assume it will be fixed piecemeal.

**Review by suzubara — COMMENTED** [review]
commenting to clear this review request for me

**Pull request closed without merging**
