### PR TITLE
[ MB-13693 ] Update SIT Display to show properly

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

Prior to this, the SIT Display component would only update on a hard
page refresh instead of when the data became stale after the user
interacted with the service items on the shipment.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

It's difficult to explain how to test this PR since there are lot of different SIT scenarios that the SITDisplay and other components need to handle. First of all, there is the scenario that is called out in the Jira ticket, which can be tested with the following steps:

1. Create a move using the `HHGMoveIn200DaysSITNotApproved` test harness scenario.
2. Validate that the sit display is not shown when there are no approved sit service items
3. Approve the SIT service items and see the SIT Display updating on the page in
   real-time.

To cover everything else, it may be helpful to navigate through the [UI user flow](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?type=design&node-id=10285-112280&mode=design&t=JaQ0qzSmWRGalEww-4) and ensure that the different scenarios expressed in the user flow behave as expected. There are many testharness scenarios that are helpful here, including:

- HHGMoveIn200DaysSITDeparted
- HHGMoveIn200DaysSITEndsToday
- HHGMoveIn200DaysSITEndsTomorrow
- HHGMoveIn200DaysSITEndsYesterday
- HHGMoveIn200DaysSITNotApproved
- HHGMoveIn200DaysSITStartsInFuture
- HHGMoveIn200DaysSITWithPendingExtension

### CODE REVIEW

**Review by AnnaGingle — DISMISSED** [review]
Functionality is working great! I have one nitpicky request. Even when the screen is at regular laptop size or larger the tag & review request button look funky.
Screenshot 2023-06-30 at 12 24 59 PM

**Comment by rogeruiz** [comment]
@AnnaGingle do you mind if we dismiss your review on the design issue here and make this another ticket? This was the call out I made in our check-in meeting earlier today and I believe it has more to do with our `testharness` data having longer than usual **Release agent** data than this PRs changing the SIT Display component.

**Comment by AnnaGingle** [comment]
@rogeruiz No problem. If you want to re-request my review, I will approve it.

**Review by AnnaGingle — APPROVED** [review]
Great work! Works as expected.

**Pull request merged**
