### PR TITLE
B 20154 a int

### PR DESCRIPTION
**Pull request by r-mettler**
## Summary

This backlog gets rid of the display of PPM pickup and destination zip codes with the full addresses on the Service Counselor's Review Documents page for PPM shipments.

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Login as a Customer
2. Create and submit a PPM shipment
3. Login as a Service Counselor and approve the PPM shipment
4. Login as the Customer and upload PPM documents
5. Submit the documents
6. Login as the Service Counselor and go to the Closeout Queue
7. Click Review Documents for the PPM shipment
8. Expand the PPM details section and verify the full Pickup and Destination Addresses are listed

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### CODE REVIEW

**Review by antgmann — APPROVED** [review]
Data is filling correctly with all 3 address fields, code looks good
image

**Comment by r-mettler** [comment]
> Data is filling correctly with all 3 address fields, code looks good image

I made a change to the scss for that page so the text stayed in the white box and thought I had also fixed the issue where the white background fills the card but I have noticed that it only seems to fill if you refresh that page. Its weird.

**Review by ajlusk — APPROVED** [review]
Changes look good, functions as expected. I would like to see a address line three in one of the new test addresses though that shouldn't be an issue since the formatter you're using includes line three and Anthony's screenshot above shows that it formats correctly.

It looks like the styling that makes the form not fill all the space available to it is the same styling that makes some other forms (like customer contact info and request office account) display with mobile width.
Screenshot 2024-05-30 at 10 34 32 AM

**Comment by r-mettler** [comment]
I noticed that if you remove the usa-form from then it displays properly and fills the background now I see why.

**Pull request merged**
