### PR TITLE
Shipment EDI generation / parsing pkg

### PR DESCRIPTION
**Pull request by aileendds**
## Description

This adds an edi package for parsing and generating EDI formatted strings. I originally began this when we thought we would need to parse invoices (859s) coming from TSPs. I've since removed most of the parsing code but there is still some vestiges of it. We will at some point need to parse EDI files but that's not super relevant right now. 

This handles generating an 858c (which we are calling an invoice, but it's actually "Shipment Information" in EDI land (C = costed, or merged with Invoice).
Here's the documentation for the 858c: https://www.ustranscom.mil/cmd/associated/dteb/files/transportationics/dt858c41.pdf

## Reference Notes
This changes move on a Shipment from a pointer to not a pointer.  Many of the test changes are related to fixes due to that change.

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/blob/master/docs/backend.md#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/160078022) for command line utility created within this change

## Screenshots
The beautiful output of EDI content:
screen shot 2018-08-28 at 3 12 04 pm

### CODE REVIEW

**Comment by aileendds** [comment]
This looks long at first glance but there's a lot of boilerplate.

**Comment by chrisgilmerproj** [comment]
Did we mean to add `./bin/gas` and `./bin/gosec` here? I feel like `./bin/gas` was deprecated for `./bin/gosec`? And I thought `./bin/gosec` was provided by github.com/securego/gosec/cmd/gosec.  Is that right? I may have it wrong.

**Comment by kimallen** [comment]
hmm, I may have messed that up- I don't know what gosec is, but it seemed to be one of those autogenerated logging files that showed up and I didn't add, so I removed it.  I'll check git history to see what is there.

**Comment by kimallen** [comment]
Tests are added and fixed.

**Pull request merged**
