### PR TITLE
B:19465 - Add a public GHCApi endpoint to get the transportation offices(READY)

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

This MR introduces a new GET endpoint in the GHCAPI to retrieve Transportation Offices outside of being logged in. This will enable transportation office look ups for the Office Account Request Form that is being worked in a different story.

## Testing
1. Start up your server and front end
2. Head to GHC API through swagger or Postman
3. send a GET request to /open/transportation-offices?search

## Screenshots
image
image

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
> Code between int and main looks the same apart from the changes made here to `pkg/handlers/routing/routing_init.go`. Do you know where those changes came in from?

This is dependent on [B-18823](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18823) so @cameroncaci needs to get that PR up into `main` when its ready

**Comment by TevinAdams** [comment]
> Code between int and main looks the same apart from the changes made here to `pkg/handlers/routing/routing_init.go`. Do you know where those changes came in from?

@traskowskycaci  Yes so me and Cameron both needed that change. Only thing is his wasn't in Main but I needed it. Instead of merging his branch into mine I made the change on my main. Going into in the change was already there from cameron but it wasn't in main. So now it is showing up here.

**Comment by danieljordan-caci** [comment]
> > Code between int and main looks the same apart from the changes made here to `pkg/handlers/routing/routing_init.go`. Do you know where those changes came in from?
> 
> @traskowskycaci Yes so me and Cameron both needed that change. Only thing is his wasn't in Main but I needed it. Instead of merging his branch into mine I made the change on my main. Going into int the change was already there from cameron but it wasn't in main. So now it is showing up here.

Can this wait until @cameroncaci pushes his PR? Or you can merge his `main` branch and just wait for his to go through and then merge this.

**Comment by TevinAdams** [comment]
> > > Code between int and main looks the same apart from the changes made here to `pkg/handlers/routing/routing_init.go`. Do you know where those changes came in from?
> > 
> > 
> > @traskowskycaci Yes so me and Cameron both needed that change. Only thing is his wasn't in Main but I needed it. Instead of merging his branch into mine I made the change on my main. Going into int the change was already there from cameron but it wasn't in main. So now it is showing up here.
> 
> Can this wait until @cameroncaci pushes his PR? Or you can merge his `main` branch and just wait for his to go through and then merge this.
Yeah this can wait. Camron story was marked to test after my 18830 passes int but my 18830 depends on this. I was trying to get 19465 into main so I do not have to merge it into my 18830 making the commits messy.

**Comment by traskowskycaci** [comment]
PO acceptance for both this story and Cameron's is happening today, so let's hold off until then if that works for you @TevinAdams. I think typically we wait for it to get through PO acceptance until making the main PR unless I am confused on that flow

**Comment by traskowskycaci** [comment]
> > > Code between int and main looks the same apart from the changes made here to `pkg/handlers/routing/routing_init.go`. Do you know where those changes came in from?
> > 
> > 
> > @traskowskycaci Yes so me and Cameron both needed that change. Only thing is his wasn't in Main but I needed it. Instead of merging his branch into mine I made the change on my main. Going into int the change was already there from cameron but it wasn't in main. So now it is showing up here.
> 
> Can this wait until @cameroncaci pushes his PR? Or you can merge his `main` branch and just wait for his to go through and then merge this.

@cameroncaci  can we move this PR of Tevin's through with the change to pkg/handlers/routing/routing_init.go before your 18823 PR gets into main or should we wait for yours?

**Review by traskowskycaci — APPROVED** [review]
Going to go ahead and approve this one, just noting the one diff I called out above but I'm fine with that.

**Review by danieljordan-caci — APPROVED** [review]
In the same head space as @traskowskycaci , I'll approve but let's wait to hear from @cameroncaci before sending this up

**Comment by cameroncaci** [comment]
Spoke with Ricky, yeah that's just the logic to allow for the open endpoints as a whole. My story creates a separate open endpoint, but this code logic here that Tevin put in just allows for his endpoint to open. No need to wait on mine

**Pull request merged**
