### PR TITLE
B 21668  m

### PR DESCRIPTION
**Pull request by deandreJones**
[INT PR2](https://github.com/transcom/mymove/pull/14230)
[INT pr 1 ](https://github.com/transcom/mymove/pull/14325)

[INT 3](https://github.com/transcom/mymove/pull/14369)

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
LGTM

**Review by traskowskycaci — COMMENTED** [review]
Do we want this commit from int here as well?

- add excption: https://github.com/transcom/mymove/pull/14230/commits/ad4727c99cc8b488084a335284c157d93702c657

**Comment by deandreJones** [comment]
awaiting upstream https://github.com/transcom/mymove/pull/13990

**Comment by deandreJones** [comment]
> Do we want this commit from int here as well?
> 
> * add excption: [ad4727c](https://github.com/transcom/mymove/commit/ad4727c99cc8b488084a335284c157d93702c657)

good catch eagle eyes

**Review by traskowskycaci — APPROVED** [review]
Matches INT!

**Comment by deandreJones** [comment]
> Matches INT!

@traskowskycaci does this build for you? failing server tests that passed INT.. might need another set of eyes - thanks

**Comment by traskowskycaci** [comment]
> > Matches INT!
> 
> @traskowskycaci does this build for you? failing server tests that passed INT.. might need another set of eyes - thanks

Builds fine locally, mid-run on server tests now. All your code is an exact match to the int PR

**Comment by traskowskycaci** [comment]
> > > Matches INT!
> > 
> > 
> > @traskowskycaci does this build for you? failing server tests that passed INT.. might need another set of eyes - thanks
> 
> Builds fine locally, mid-run on server tests now. All your code is an exact match to the int PR

does fail for me locally on the same test package as circle

```
2024/12/11 15:31:08 package models_test is attempting to connect to database postgres
2024/12/11 15:31:08 TXNDB: package models_test will use database test_db_1 in pid 21072
--- FAIL: TestModelSuite (0.58s)
    --- FAIL: TestModelSuite/TestCreateApprovedServiceItemsForShipment (0.32s)
        --- FAIL: TestModelSuite/TestCreateApprovedServiceItemsForShipment/test_creating_approved_service_items_for_shipment (0.32s)
            mto_shipments_test.go:317: 
                        Error Trace:    /Users/m.traskowsky_cn/Documents/github/mymove/pkg/models/mto_shipments_test.go:317
                                                                /Users/m.traskowsky_cn/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:115
                        Error:          Received unexpected error:
                                        error creating approved service items: pq: Error creating POEFSC service item for shipment 965f123b-2717-495b-8ba5-476d0826a52f: syntax error at or near "IF"
                        Test:           TestModelSuite/TestCreateApprovedServiceItemsForShipment/test_creating_approved_service_items_for_shipment
FAIL
FAIL    github.com/transcom/mymove/pkg/models   1.611s
```

**Pull request merged**
