### PR TITLE
INT B-21376 I-13558

### PR DESCRIPTION
**Pull request by danieljordan-caci**
Downstream of https://github.com/transcom/mymove/pull/14253 - don't merge until that is merged into INT

## Summary

They wanted to see the UB allowance up top where the weight allowance is shown, so Imma show it.

### How to test

1. Set up your env so you can create UB shipments
2. After adding your orders information, go back to your home page and check out your headers
3. Should see a `UB allowance` up there lookin' all pretty

## Screenshots
Screenshot 2024-11-21 at 9 40 51 AM

Screenshot 2024-11-21 at 12 32 37 PM

Screenshot 2024-11-21 at 12 33 26 PM

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Lookie there! Very nice, I like being able to see that.
image

**Comment by traskowskycaci** [comment]
> > Recommend marking #14253 as an upstream, this PR doesn't work for civilians
> > Screen.Recording.2024-11-22.at.9.33.19.AM.mov
> 
> Updated description of PR - I'll hold off on merging until that's in.

Just merged in the upstream

**Comment by cameroncaci** [comment]
@traskowskycaci could you push the merge? Will retest it

**Comment by cameroncaci** [comment]
@danieljordan-caci Will retest once resynced

**Review by cameroncaci — COMMENTED** [review]
Well.. it works for civilian now, but fails for

- Aviation Cadet
- Service Academy Cadet
- Midshipman

What are we thinking for how to proceed?

https://github.com/user-attachments/assets/6e2369ed-fd63-4eec-b830-a6a50b283464

**Comment by danieljordan-caci** [comment]
> Well.. it works for civilian now, but fails for
> 
> * Aviation Cadet
> * Service Academy Cadet
> * Midshipman
> 
> What are we thinking for how to proceed?
> 
>  Screen.Recording.2024-11-22.at.10.07.40.AM.mov

Well... The only reason why it'd be failing would be the payload is not sending the `ub_allowance`

**Comment by traskowskycaci** [comment]
> Well.. it works for civilian now, but fails for
> 
> * Aviation Cadet
> * Service Academy Cadet
> * Midshipman
> 
> What are we thinking for how to proceed?
> 
>  Screen.Recording.2024-11-22.at.10.07.40.AM.mov

Not a fail - just 0 for the UB allowance for those grades which is expected - https://ustcdp3.slack.com/archives/C06D8HB31HP/p1730480371710309

**Comment by traskowskycaci** [comment]
> > Well.. it works for civilian now, but fails for
> > 
> > * Aviation Cadet
> > * Service Academy Cadet
> > * Midshipman
> > 
> > What are we thinking for how to proceed?
> > Screen.Recording.2024-11-22.at.10.07.40.AM.mov
> 
> Not a fail - just 0 for the UB allowance for those grades which is expected - https://ustcdp3.slack.com/archives/C06D8HB31HP/p1730480371710309

Sorry wrong link - read the comments here
https://ustcdp3.slack.com/archives/C06D8HB31HP/p1730754253194339

**Review by TevinAdams — APPROVED** [review]
Looks good
image

**Review by cameroncaci — APPROVED** [review]
Behavior is G 2 G! All previous comments resolved
🚀 ⛰️ ⛰️ ⛰️ 🌠

**Pull request merged**
