### PR TITLE
B 19892 add columns to tac and loa tables int

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

Need to store and send 2 flags to Advana. Advana gets an export of our tables so adding new columns to store these flags should be sufficient.

One column called valid_loa_for_tac to store the value for the lookup of a LOA for a given TAC:
     - this column will be added to the transporation_accounting_codes table

One column called valid_hhg_code_for_loa to store the value for the lookup of an HHG program code based on the constructed LOA:
    - this column will be added to the lines_of_accouting table

Main branch that is merged into this int branch: https://github.com/transcom/mymove/compare/main...B-19892-add-columns-to-tac-and-loa-tables

### CODE REVIEW

**Comment by traskowskycaci** [comment]
All of the extra commits in here are a result of merging the latest main into integration.

**Comment by danieljordan-caci** [comment]
Could you add `IF NOT EXISTS` to those column additions?

**Comment by traskowskycaci** [comment]
> Could you add `IF NOT EXISTS` to those column additions?

Done, good call!

**Review by danieljordan-caci — APPROVED** [review]
Poppin' up locally. LGTM!

**Comment by danieljordan-caci** [comment]
Conflicts, btw

**Review by TevinAdams — APPROVED** [review]

**Comment by deandreJones** [comment]
conflicts

**Pull request merged**
