### PR TITLE
B-21436: Allow AK to be entered as a state and Enable Alaska FF

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

In this PR I am allowing AK to be entered as a state. I am also creating the feature flag to enable or disable the ability to select AK as a state.

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

*In all cases the message described in the testing steps should read "Moves to this state are not supported at this time".

1. Turn on enable Alaska feature flag
2. Access the MilMove application as a customer.
3. Login as a new user and when prompted for an address, try to select AK.
4. You should not see a message above the State field and the next button should not be disabled.
5. After selecting AK continue with customer info.
6. Next go to set up shipments. Here wherever address fields, including the optional address fields, select AK as a state. There should not be a message above the state field and the next button should not be disabled.
7. Next access office as a SC role.
8. Go to add a shipment.
9. Go through all shipment types selecting AK as the state. Should be able to move on without any messages denying AK as a state.
10. Turn off enable Alaska FF
11. Test again but you should not be able to select AK as a state.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

AK is allowed to be entered as a state on Milmove:
image

AK is allowed to be entered as an address in Office:
image

##508 Compliance Check
image

### CODE REVIEW

**Review by cameroncaci — APPROVED** [review]
Functions and meets AC - this state restriction was frontend only so not seeing any backend code is expected

**Review by danieljordan-caci — APPROVED** [review]

**Comment by danieljordan-caci** [comment]
With the added FF work, make sure that you have also created the appropriate PR over in the [feature flag repo](https://github.com/transcom/milmove-feature-flags/pulls) to add the flag there

**Comment by TevinAdams** [comment]
> With the added FF work, make sure that you have also created the appropriate PR over in the [feature flag repo](https://github.com/transcom/milmove-feature-flags/pulls) to add the flag there

Done.

**Comment by TevinAdams** [comment]
> May need a FF on this work - discussion in the mountain-movers-devs chat around it
> 
> Feel free to dismiss my review if deemed irrelevant

@traskowskycaci  Added FF work. Link added above in the description.

**Review by traskowskycaci — APPROVED** [review]
Thanks for adding the FF!

**Pull request merged**
