### PR TITLE
MAIN B-19507 limit customer access via validation code (MERGE AFTER MAIN B-19506)

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION PR](https://github.com/transcom/mymove/pull/12490)

## Summary

This PR will need to be merged after the `B-19506` branch https://github.com/transcom/mymove/pull/12488#pullrequestreview-1997774962 

---

In the near future, we will be getting some validation code(s) from DPS that a customer will need to input when beginning their move. This is to keep users from creating fake moves and only really allow authenticated and appropriate users to use MilMove. 

In order to make this happen, we need the user to input that validation code before doing anything else. So the logic implemented in this BL item will require the user to put that code in if they haven't set their profile up (AKA have an empty profile) and the feature flag is turned on.

This PR does the following:
- creates a migration file that creates a table called `application_parameters` where the `validation_code` will be stored
- creates `internal` endpoint, `POST /validation-code`
- updates the `getWorkflowRoutes` to 
- refactors the `ConusOrNot.jsx` component to be an updated functional component
- created `ValidationCode.jsx` component to handle the form and API call
- added & updated all relevant tests, cleaned up some code
- my main man @TevinAdams added some playwright test adjustments when the flag is `true`

### How to test

Couple of setup things you need to do first:
- `make db_dev_migrate` (this will create the `application_parameters` table
- You'll need to fill in a row with a value in `validation_code` and `id`, `updated_at` and `created_at` will auto populate
- In your `.envrc`, set `export FEATURE_FLAG_VALIDATION_CODE_REQUIRED=true`
- Now fire up your `client` and `server`

**For the happiest path**
1. Access MM as a customer
2. Login as a brand new customer
3. You should now see the validation code screen
4. Input the code you slapped in the `application_parameters` table
5. It should now let you progress through the profile set up

**For the saddest path**
1. Access MM as a customer
2. Login as a brand new customer
3. You should now see the validation code screen
4. Input anything other than the code you put in the database
5. You should see an error screen and not be able to progress
6. You can have as many attempts as you want when inputting the code (this was a requirement from Kipp)

## Screenshots
Screenshot 2024-04-12 at 11 07 01 AM

Mobile
Screenshot 2024-04-12 at 11 21 56 AM

Screenshot 2024-04-12 at 11 12 31 AM

Mobile
Screenshot 2024-04-12 at 11 21 38 AM

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Matches up, and changes to config/env files are already in int. Nice!

**Comment by danieljordan-caci** [comment]
For some reason I didn't have to update the spectral count in the `integrationTesting` branch, but I apparently have to update it here.

**Comment by cameroncaci** [comment]
@danieljordan-caci conflicts from merging 19506 in

**Comment by cameroncaci** [comment]
Should be real quick and easy

**Comment by danieljordan-caci** [comment]
> Should be real quick and easy

Yup should be good now

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
