### PR TITLE
MAIN B-21679 I-13498 overriding uswds styling

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INT PR](https://github.com/transcom/mymove/pull/14177)
[INT PR 2](https://github.com/transcom/mymove/pull/14164)

## Summary

We have this tricky little issue where for some reason we were having `.usa-form` and `.usa-button` mobile stylings being applied to the application. It seems to be an issue with the third party library that we use `uswds` so the fix is to override the stylings being applied within `_overrides.scss`.

## Screenshots
Screenshot 2024-11-13 at 12 47 28 PM

Screenshot 2024-11-13 at 12 47 42 PM

Screenshot 2024-11-13 at 12 47 54 PM

Screenshot 2024-11-13 at 12 48 07 PM

Screenshot 2024-11-13 at 12 48 18 PM

Screenshot 2024-11-13 at 12 48 29 PM

Screenshot 2024-11-13 at 12 48 46 PM

### CODE REVIEW

**Review by cameroncaci — COMMENTED** [review]
This commit isn't present in int https://github.com/transcom/mymove/pull/14178/commits/45b6f924f5dc2f96f0571c0677502e5ed776662d

**Review by traskowskycaci — APPROVED** [review]
All the changed files match what's currently in INT

**Comment by danieljordan-caci** [comment]
Can I get a Happo check? There's going to be a lot of teeny tiny spacing differences because I had to override the `.usa-button` margins and it's a butterfly fart off so that's why there are 171 diffs.

**Review by TevinAdams — APPROVED** [review]

**Comment by traskowskycaci** [comment]
> Can I get a Happo check? There's going to be a lot of teeny tiny spacing differences because I had to override the `.usa-button` margins and it's a butterfly fart off so that's why there are 171 diffs.

Reviewed

**Review by cameroncaci — APPROVED** [review]
@danieljordan-caci bad link for the second int pr, here's the correct one:
https://github.com/transcom/mymove/pull/14184

Thanks for the clarification, commits are good

**Pull request merged**
