### PR TITLE
B-17812 fix label shifting on error

### PR DESCRIPTION
**Pull request by loganwc**
## Summary

When we get an error on fields on this page the field label is shifted downwards. This also makes the spacing in the calendar inconsistent when there is an error state on the field vs when there isn’t.

The expected behavior should be that the field label doesn’t move relative to the page and instead the warning shows below the existing location of the field label.

Similar behavior was seen in this [PR](https://github.com/transcom/mymove/pull/8216#pullrequestreview-899669954), and was resolved.

Ensure that this works on the Dates and Locations page, as well as all other PPM pages where this is still a bit inconsistent

### How to test

1. Login to milmovelocal
2. Input incorrect information to an input field to display an error
3. Error label should not shift
4. input incorrect date
5. month label in day picker modal should not be squished against input field above

### Frontend

- [ ] There are no aXe warnings for UI.
- [x] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [x] There are no new console errors in the browser devtools.
- [x] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### CODE REVIEW

**Comment by loganwc** [comment]
Need lead override on Happo scan @deandreJones @cameroncaci

**Review by joeydoyecaci — DISMISSED** [review]

**Review by traskowskycaci — COMMENTED** [review]
Seeing a slight shifting up of the "Estimated weight of your pro-gear" and "Estimated weight of your spouse's pro-gear" field labels when an error message appears. Hopped on a quick call with Logan to demo.

**Comment by landan-parker-0** [comment]
I would address the property value assignment.
It would probably be a better practice to consolidate all measurement values such as 1.6rem as css variables in the future so we avoid having to identify values semantically as they are used and associate variables for them.

For example, `margin-top: 1.6rem;` for the error message with `.usa-form-group.warning`
may not be the same applied effect for `.use-form-another-margin-requirement-but-not-that-one` which also happens to have `margin-top: 1.6rem;`

Otherwise, when there is a scenario where you want to change all `1.6rem` values to `1.2rem`, while not realizing some of the values you consider replacing do not apply to the component or behavior you want to achieve.

**Review by landan-parker-0 — APPROVED** [review]

**Comment by joeydoyecaci** [comment]
Have two playwright tests failing. One ProGear related. Other mto service item related. image
image
image

**Pull request merged**
