### PR TITLE
MB-11874 Show Automatic Reweigh Request by the Prime Updating Weights in Move History

### PR DESCRIPTION
**Pull request by YanZ777**
## Summary

Created a new event for documenting when a reweigh request is automatically generated by the prime updates the actual weights and total weight > 90% of weight allowance.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make office_client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app
2. Login as a prime simulator user
3. Select a move that already as payment requested (I used `PENDNG`) - remember the move locator
4. Click the update the shipment button
5. Update the shipment weight such that the actual weights and total weight > 90% of weight allowance (I set the weight requested to be 9,000) and save.
6. Log out and log in as a TIO
7. Select the move of the move locator you updated
8. Go to the move history page
9. There should be an entry for a requested reweigh

## Verification Steps for Author

These are to be checked by the author.
- [ ] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

## Screenshots
image

### CODE REVIEW

**Review by juliemoon — COMMENTED** [review]
I noticed that when I updated the actual weight for one of the shipments - the move history page shows that "Updated shipment / HHG shipment, reweigh requested" twice. I'm not sure if it's because this move had two HHG shipments but I only updated the actual weight for one of them. 
GBLOC: KKFA
MOVE CODE: XVWY93
Screen Shot 2022-06-09 at 11 48 02 AM

**Comment by YanZ777** [comment]
> I noticed that when I updated the actual weight for one of the shipments - the move history page shows that "Updated shipment / HHG shipment, reweigh requested" twice. I'm not sure if it's because this move had two HHG shipments but I only updated the actual weight for one of them. GBLOC: KKFA MOVE CODE: XVWY93 Screen Shot 2022-06-09 at 11 48 02 AM

Ooo interesting, it does look like it is requesting a reweigh for both shipments even though it's just the one over the reweigh weight. I will investigate further!

**Review by donaldthai — APPROVED** [review]
Code LGTM :shipit:

**Comment by YanZ777** [comment]
> I noticed that when I updated the actual weight for one of the shipments - the move history page shows that "Updated shipment / HHG shipment, reweigh requested" twice. I'm not sure if it's because this move had two HHG shipments but I only updated the actual weight for one of them. GBLOC: KKFA MOVE CODE: XVWY93 Screen Shot 2022-06-09 at 11 48 02 AM

@juliemoon Looks like this is expected behavior! 
#7293

**Review by juliemoon — APPROVED** [review]
Thank you @YanZ777

**Pull request merged**
