### PR TITLE
MB-5464 update envrc devlocal bucket

### PR DESCRIPTION
**Pull request by kilbergr**
## Description

We've created a bucket for devlocal in the `transcom-gov-dev` account and are replacing the currently used one in the ppp/legacy account with that.

## Reviewer Notes

I would love to get an app engineer who typically runs commands that result in uploads to the devlocal bucket to run this to make sure it works as they expect.
I suspect there may be failure because we've not yet updated the default AWS region.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5039) for this change

### CODE REVIEW

**Comment by gidjin** [comment]
I'm confused as to what I should be trying. I tried `make run_prod_migrations` and it still tried my com cloud creds and failed. I tried `chamber env transcom-gov-dev` but it asked for com cloud creds and returned nothing. Basically I'm unclear what this is supposed to have fixed from my perspective. Can you provide me with the commands you are expecting have been fixed and I'm happy to try them out.

**Comment by kilbergr** [comment]
Hi @gidjin so sorry about the confusion, I should've explained better. This has nothing to do with secure migrations. This is about the devlocal bucket on S3 that folks interact with when they are running the mymove app locally and upload something (rather than on one of the exp, stg, or prd envs). I want to see what happens when someone tries to make an upload in the mymove site when they're running locally. Does that make sense?

**Comment by gidjin** [comment]
Do you mean where we store secure environment variables for local development? Or are we uploading other things to devlocal? If it's the environment vars I wasn't sure how to access those since `chamber env transcom-gov-dev` didn't return any results. Maybe we can pair on this so I can understand the ask.

**Comment by kilbergr** [comment]
@gidjin that would be great! I'm flying a little in the dark myself. 
This isn't actually about env vars in devlocal, although we have done that (in parameter store). I have double checked and `aws-vault exec transcom-ppp -- chamber list app-devlocal` appears to yield the same result as ` aws-vault exec transcom-gov-dev -- chamber list app-devlocal` (although in different repos. I'm not getting anything from `chamber env transcom-gov-dev` or `chamber env transcom-ppp` and am not sure what you'd expect.

This is about uploading documents to a real environment to make sure that we are actually doing that properly. 

I'll look on your calendar.

**Review by travelar — APPROVED** [review]
Looks good for Infra. Would ask that we get an engineer comments before merging.

**Comment by esacteksab** [comment]
Almost a month old. What do we need to bring this back to life?

**Comment by kilbergr** [comment]
@esacteksab there's a ticket this is tied to https://dp3.atlassian.net/browse/MB-5464. From what I understand, it's dependent on this: https://dp3.atlassian.net/browse/MB-4393 aka the big one.

**Comment by kilbergr** [comment]
Closing in favor of new PR:
https://github.com/transcom/mymove/pull/5433

**Pull request closed without merging**
