### PR TITLE
B 17906 int Prevent Customer Request after Authorized End Date

### PR DESCRIPTION
**Pull request by r-mettler**
## Summary
Follow on from B-17854.
This story prevents Prime from updating the dates for Authorized End Date if the new calculation would be after the current Authorized End Date. Customer dates should not extend the Authorized End Date beyond its current date. This avoids an automatic SIT Extension. 

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Functionality Test

1. Create a new HHG shipment in the Customer app and submit it
2. Login as a Service Counselor and approve the shipment
3. Login as a TOO and accept the shipment
4. Login as a Prime into the Prime Simulator
5. Select the newly created move
6. Update the shipment and make sure you enter values for the estimated and actual weights, this is needed to calculate the required delivery date. Note the weight entered.
7. Click Add Service Item
8. Add a new Origin SIT item, enter today's date for SIT Entry Date
9. Login as a TOO access the move and go to Move Task Order tab.
10. Accept all of the SIT Service Items
11. Login as a Prime to the Prime Simulator
12. Select the Move
13. Click on Edit for DOASIT
14. Enter SIT Departure Date, SIT Customer Contact Date make today and Customer Requested Delivery a few days after today
15. Click Save
16. Go back in and edit the dates
17. For all SIT dates enter dates that are about a month or more in the future to try and extend the SIT Authorized End Date.
18. Click Save
19. You should see an error "dates entered cannot extend authorized end date beyond its current date"

Authorized End Date for Origin SIT: sitAuthorizedEndDate should be GracePeriodDays days after sitCustomerContacted or the sitDepartureDate whichever is earlier.
image

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### CODE REVIEW

**Comment by ajlusk** [comment]
I have not been able to receive the expected error message. The SIT Requested Delivery and SIT Customer Contacted aren't persisting but when I press save I get "Successfully updated SIT service item."

To verify I'm testing correctly I had some questions:

1. Should step #13 read DOFSIT rather than DOASIT? I get the same result with both.
2. For step #15, the 2 months in the future is from the departure date set in #14? Or some other date like the today used for the entry date? I've tried many months out so it shouldn't matter.
3. Is there any reason the move wouldn't show up in my TOO queue during step #9? I figured I messed up somewhere earlier in the process but was able to continue by pasting the move code into the url.

**Comment by antgmann** [comment]
Code looks good, but here is the error message I received when testing, which is not what was expected for #17:
image

**Comment by antgmann** [comment]
I'm afraid that I didn't get an error when attempting to update:
image
image

**Comment by antgmann** [comment]
> I have not been able to receive the expected error message. The SIT Requested Delivery and SIT Customer Contacted aren't persisting but when I press save I get "Successfully updated SIT service item."
> 
> To verify I'm testing correctly I had some questions:
> 
> 1. Should step 13 read DOFSIT rather than DOASIT? I get the same result with both.
> 2. For step 15, the 2 months in the future is from the departure date set in 14? Or some other date like the today used for the entry date? I've tried many months out so it shouldn't matter.
> 3. Is there any reason the move wouldn't show up in my TOO queue during step 9? I figured I messed up somewhere earlier in the process but was able to continue by pasting the move code into the url.

For number 3, I ran into this while testing B-17854. Make sure all of your data has zip codes and states within the GBLOC of your office user's access. I don't know why this would be preventing it from being visible as a TOO, but Ricky walked me through it with test data that was all within AFGM, which allowed me to see it on step 9.

I also may have forgotten about it, tried to test this, reached step 9, and was confused why it wasn't there, before remembering that. Oops!

**Comment by ajlusk** [comment]
@antgmann Thanks. That seems to explain my issue. My first test user's duty stations and destination address were all AGFM but I let my browser autofill my home address for my origin address which, I think, is the tiny GBLOC of BKAS even though it's surrounded by AGFM.

Your screenshots look like what I was getting as well.

**Comment by r-mettler** [comment]
> I have not been able to receive the expected error message. The SIT Requested Delivery and SIT Customer Contacted aren't persisting but when I press save I get "Successfully updated SIT service item."
> 
> To verify I'm testing correctly I had some questions:
> 
> 1. Should step 13 read DOFSIT rather than DOASIT? I get the same result with both.
> 2. For step 15, the 2 months in the future is from the departure date set in 14? Or some other date like the today used for the entry date? I've tried many months out so it shouldn't matter.
> 3. Is there any reason the move wouldn't show up in my TOO queue during step 9? I figured I messed up my first test user somewhere earlier in the process but was able to continue by pasting the move code into the url.

I copy and pasted the steps from 17854 into this one and forgot to make a few updates. Sorry about that. I updated them. You have to go in and edit the dates twice. The first time sets the Authorized End Date and then when you attempt to put in dates that would push the Authorized End Date later than the current date then you should see the error message. This will only work for DOASIT and DDASIT service items as those are the only service items that the Customer dates are supposed to be associated with. 
Anthony is correct on the move not showing up in the TOO queue. You have to login using a TOO who can see the moves in the GBLOC your move is assigned to. If you are not sure which GBLOC you can look up the states in the database jppso_region tables. One has the GBLOC and the other has a list of the city and states and their jppso region ID that matches back to the jppso_region table.

**Review by ajlusk — APPROVED** [review]
Needed an explanation to understand how this should be tested but after that everything seems to be working as expected and local tests are passing.

I believe, as part of testing step 17 you should also change the SIT Departure Date to a date after the SIT Authorized End Date (visible from the move task order tab when logged in as a TOO) that got created behind the scenes earlier in the process.

**Review by MInthavongsay — APPROVED** [review]
All tests passed.

**Pull request merged**
