### PR TITLE
Hotfix for error regarding query client provider

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
Added Query Provider in the tests that are failing since it is not required

### CODE REVIEW

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
Seeing a lot of this in the build: https://app.circleci.com/pipelines/github/transcom/mymove/73617/workflows/be24a008-e265-4644-a04c-aa16d2db2225/jobs/1296523

```
FAIL src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  ● Test suite failed to run

    Automatic publicPath is not supported in this browser
```

Looks to be directly associated with the `DocumentViewer` component:
```
at Object.<anonymous> (src/components/DocumentViewer/DocumentViewer.jsx:10:1)
```

**Comment by deandreJones** [comment]
happo isn't too happy
image

**Comment by WeatherfordAaron** [comment]
> happo isn't too happy image

It is showing some changes because of the QueryClient and some changes that are from a teammate's branch. I dunno why it would be messing up from their branch on my branch in stead of on their branch.

**Comment by WeatherfordAaron** [comment]
> Seeing a lot of this in the build: https://app.circleci.com/pipelines/github/transcom/mymove/73617/workflows/be24a008-e265-4644-a04c-aa16d2db2225/jobs/1296523
> 
> ```
> FAIL src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
>   ● Test suite failed to run
> 
>     Automatic publicPath is not supported in this browser
> ```
> 
> Looks to be directly associated with the `DocumentViewer` component:
> 
> ```
> at Object.<anonymous> (src/components/DocumentViewer/DocumentViewer.jsx:10:1)
> ```

automatic publicPath is a setting in the webpack of the FileViewer component. I changed that setting from '/' to './' which was a change suggested online for these types of situations. We don't have a webpack config file that I can find on this project so I'm assuming changing that option on the FileViewer repo will fix this.

**Review by JamesHawks224 — APPROVED** [review]
lgtm

**Pull request closed without merging**
