### PR TITLE
B-21364 FF: UB shipments selectable for OCONUS duty locations MAIN

### PR DESCRIPTION
**Pull request by traskowskycaci**
## [B-21364 I-12546 INT PR](https://github.com/transcom/mymove/pull/14236)

For the B-21364 PR, you should find matching hashes between this PR and the INT PR, but also duplicate commits in the INT PR, due to the workflow of making a change in the int branch, cherry-picking that same commit into main, then merging main into int. Not a great workflow but there were some dependencies in int that were not yet in main. 

Last three commits in this branch are from the issue fix PR.

### CODE REVIEW

**Comment by traskowskycaci** [comment]
> Please merge this PR first, then after this PR is in main merge the issue fix in: #14261
> 
> ## [INT PR](https://github.com/transcom/mymove/pull/13917)
> You should find matching hashes between this PR and the INT PR, but also duplicate commits in the INT PR, due to the workflow of making a change in the int branch, cherry-picking that same commit into main, then merging main into int. Not a great workflow but there were some dependencies in int that were not yet in main.

Will need a happo check on this one

**Comment by traskowskycaci** [comment]
> @traskowskycaci since the issue fix is part of the same ticket let's merge them both together

@cameroncaci good call, brought in the issue fix commits to this main PR

**Review by cameroncaci — APPROVED** [review]
POA'd, [I-13546](https://www13.v1host.com/USTRANSCOM38/Issue.mvc/Summary?oidToken=Issue%3A1033795) resolved, commits are good

**Comment by cameroncaci** [comment]
failing client test is flaky

**Pull request merged**
