### PR TITLE
INT B-20791 refactor evaluation report to a route

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

We have future work coming in upcoming Sprints that will handle GSR functionality and one of their capabilities will be adding appeals to violations and serious incidents on evaluation reports.

The way that users are reviewing evaluation reports after they are created is via modal, which we have to refactor to use a route instead since we will likely handle adding appeals to evaluation reports via modals. 

This PR does the following:
- creates the `EvaluationReportView` component which handles rendering evaluation report data, violations, serious incidents, and QAE remarks following the creation of the report
- added route to display `EvaluationReportView` component when the user clicks the `View report` button
- updated some CSS

### How to test

1. Access MM as a QAE office user
2. Using existing test moves, you can check out move code `EVLRPT`
3. Click on the `Quality Assurance` tab
4. You should now see a page with some evaluation report overviews
5. View existing reports and make sure you get no errors
6. Go and ahead and click `Create report` and make a beefy report that has SO much wrong, ensure there's a serious incident
7. Submit the report
8. Now view that report and you'll be navigated to `evaluation-report/{reportId}`
9. Check it out, review, make sure all is well and there are no errors

## Screenshots
**Old way** using a modal
Screenshot 2024-08-12 at 11 45 28 AM

Click **View report** to see the refactored modal -> route
Screenshot 2024-08-12 at 11 30 18 AM

Out with the old modal, in with the new route
Screenshot 2024-08-12 at 11 30 30 AM

Also adding in future button functionality, but not rendering it until future work is implemented. The **Add appeal** button will be rendered for a future GSR user.
Screenshot 2024-08-12 at 10 03 24 AM

508 checks are good
Screenshot 2024-08-12 at 10 02 52 AM

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Looks good overall, test case passed and code looks good.

I do see some AC of
"When I am viewing the evaluation report page
Then I will have the ability to navigate back to the previous page I was on" but I don't see a back button when I view the report itself. I just click on the Quality assurance tab - is that what the AC means?

**Comment by danieljordan-caci** [comment]
> Looks good overall, test case passed and code looks good.
> 
> I do see some AC of "When I am viewing the evaluation report page Then I will have the ability to navigate back to the previous page I was on" but I don't see a back button when I view the report itself. I just click on the Quality assurance tab - is that what the AC means?

Yeah I think that meets the AC, but now I kinda want a back button

**Comment by danieljordan-caci** [comment]
> Looks good overall, test case passed and code looks good.
> 
> I do see some AC of "When I am viewing the evaluation report page Then I will have the ability to navigate back to the previous page I was on" but I don't see a back button when I view the report itself. I just click on the Quality assurance tab - is that what the AC means?

Added a back button
Screenshot 2024-08-13 at 3 17 34 PM

Fixed some spacing
Screenshot 2024-08-13 at 3 17 52 PM

**Review by traskowskycaci — APPROVED** [review]
I do like the button. Looks gooood!

**Review by TevinAdams — APPROVED** [review]
Reviewed and test case worked.

**Pull request merged**
