### PR TITLE
Int b 20766 filename correct on downloads

### PR DESCRIPTION
**Pull request by ryan-mchugh**
## Summary
Files downloaded from S3 had filenames matching the UUID of the file in the storage bucket instead of the original filename. This was due to how the browser handles cross-origin downloads (`<a href="..." download="filenameppdf">` no longer works, a header attribute is expected in the content-disposition)

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

Enable s3 local testing per link here https://dp3.atlassian.net/wiki/spaces/MT/pages/1470955567/How+to+test+storing+data+in+S3+locally

Run server:
aws-vault exec transcom-gov-dev -- make server_run

1. Access the app as a services_counselor
2. Select a move and click "Supporting Documents" tab
3. Upload a new document
4. Refresh page after ~10 seconds (avoid another bug - outside of scope)
5. Click "Download file" once file appears within the viewer (refresh again every ~10 seconds until it does appear)
6. Verify that the filename matches that displayed in the Uploads table (not a uuid value)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

**UUID filename (before)**
image

### CODE REVIEW

**Comment by ryan-mchugh** [comment]
> Hey Ryan. So I got a real interesting result when I uploaded a screenshot file and attempted to download it. For whatever reason there is a character being used as a space that is not able to be represented using ISO-8859-1. I wonder if that's something we should check for and handle?
> 
> image
> 
> image
> 
> image

What a catch! Looks like I'll need to encode the filename before passing in the header. I'll update.

https://stackoverflow.com/questions/18389560/how-to-use-unicode-characters-in-s3s-response-content-disposition-header

**Comment by ryan-mchugh** [comment]
@brianmanley-caci Ran with a solution that preserves all characters that are supported, but ignores any character that cannot be encoded within the filename header.

**Review by msaki-caci — APPROVED** [review]
LGTM

**Review by deandreJones — APPROVED** [review]
good work on this

**Review by samaysofo — APPROVED** [review]

**Review by brianmanley-caci — APPROVED** [review]
Works with my files that were previously failing.

**Pull request merged**
