### PR TITLE
MB-16448 update language in customer onboarding screens

### PR DESCRIPTION
**Pull request by dymonmoore**
## Summary

This pull request updates the customer on-boarding screens to have clear, appropriate language. 

The main changes include:
- Removed these contractions: It's, you'll, can't, you're, don't, that's
- Renamed "things" to "personal property"
- Renamed "movers" to "Customer Care Representative"
- Made "Signature" bold on legal agreement
- Added additional context 

## Verification Steps for the Author and Reviewers

- Start the Milmove application 
- Create a new user
- During the customer onboarding screens, verify the language matches the designs and changes highlighted in this [file](https://docs.google.com/spreadsheets/d/1OJef6pq41YhNBMy7pDrQqqspcv_EXH-RfXJmMqNzfZw/edit#gid=0)

### CODE REVIEW

**Review by AnnaGingle — CHANGES_REQUESTED** [review]
Great work! I only found a couple of areas where content needs to be updated. Please reference this [spreadsheet](https://docs.google.com/spreadsheets/d/1cME2qYvImB5LuteHYJ4uTRlEfWl_M85bWOacOULHa98/edit#gid=0), specifically the **PR approved by design** column.

1. Set up shipments
Needs a line break before Note: 


2. Set up shipment / NTS
For the content under Releasing agent change you're to you are.


3. Estimated Weight / Need help estimating your PPM's weight?
Add the word tool after weight estimation calculator.


4. Legal page
The signature label should be in all capitals.


5. Move submitted
Under PPM change things to personal property. under HHG change movers to Customer Care Representative.

**Comment by AnnaGingle** [comment]
Everything is looking great! There are just 2 areas left to fix.
1. **Estimated Weight / Need help estimating your PPM's weight?** / Add the word tool after weight estimation calculator link 
& icon.

This [design](https://www.figma.com/file/tRkjtoWjT8727XH5m9k7mK/Milmove-Customer-App?type=design&node-id=668-12050&mode=design&t=W7S3wnAxqzbsolXL-4) shows what it should look like.
Screenshot 2023-07-26 at 2 15 48 PM

2.Legal page
The signature label should be in all capitals. This is what the PR looks like.
Screenshot 2023-07-26 at 2 16 48 PM

This is a [design](https://www.figma.com/file/tRkjtoWjT8727XH5m9k7mK/Milmove-Customer-App?type=design&node-id=599-8299&mode=design&t=Qakrs2XREm5w8SwB-4) that shows what it should look like. (don't worry about anything besides the label content.)
Screenshot 2023-07-26 at 2 20 59 PM

**Review by AnnaGingle — APPROVED** [review]
Everything looks great! ✨

**Comment by dymonmoore** [comment]
@duncan-truss Is it ok to merge even though these checks are failing?

**Comment by duncan-truss** [comment]
@dymonmoore I think you're ok to merge in this case, it's likely just the increase in lines slightly in the client files caused the percentage to go down.  Testing for copy isn't a great use of our time if it isn't something like a conditional error or alert being displayed.  You didn't modify any backend code so I would expect that to go away by merging in main/letting mergify do it.  There have been new commits to main since your merge yesterday at 4PM.

**Pull request merged**
