### PR TITLE
Approving Shipment Form moves PPM to "PROCESSED"

### PR DESCRIPTION
**Pull request by macrael**
## Description

once a SM has requested payment on a move, the next step is for an office worker to submit those expenses to finance and upload the final shipment form. Once that form has been OK'd, the PPM is moved to PROCESSED and the work is pretty much done

## Reviewer Notes

* Should we just use COMPLETE here instead of PROCESSED? 
* I added saving the PPM into the SaveMoveDocument code, but maybe the transaction should be pulled out to the handler itself and the handler can call save PPM if necessary. 

## Code Review Verification Steps

* [ ] End to end tests pass (`make e2e_test`)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/159220486) for this change

### CODE REVIEW

**Comment by macrael** [comment]
I've changed PPM approval to allow DRAFT -> APPROVED because it used to be possible to Submit a move without that also Submitting the PPM. In the future that shouldn't be possible but this will reduce breakage. I've also filed a bug for error handling on the office page.

**Comment by tinyels** [comment]
The invalid transition I was getting before isn't happening now when I follow these steps:

1. Run make  db_populate_e2e
2. Login to office and approve ppm for FDXTIU
3. Confirm move, ppm status is APPROVED
4. Login to my move and perform payment request
5. Confirm move is approved, ppm is PAYMENT_REQUESTED
6. return to office and Add shipment summary
7. Recheck status
8. Approve shipment summary

However the final state is Move is approved and PPM is complete. Should Move be complete too? A-Team is revisiting how these state transitions work so we may want to talk to them.

**Comment by macrael** [comment]
Re: move being complete. Perhaps? I suppose if the move has no HHG component and the PPM complete then we should complete the move. I don't know if the shipment summary is related to HHG at all.

**Comment by macrael** [comment]
@stangah Where does the PPMID on the move document get set? Is it possible for there to be move documents that have to do with an HHG instead of a PPM? What will we do then?

**Pull request merged**
