### PR TITLE
[MB-4267] Update copy in Helper text component on Home page after move is submitted

### PR DESCRIPTION
**Pull request by SirenaBorracha**
## Description

This PR updates the Helper text that appears at the top of the Service Member's `Home` page, where they are sent after they sign and submit their move request. 

Previously, HHG/PPM/combo specific helper text was displayed. Now we show one Helper component for all moves, and if the SM has selected any combination of moves with a PPM, they are shown a second Helper component below the first, with PPM specific text.

## Setup

```sh
make server_run
make client_run
```

Login as a SM previous to sign and submit (I used needs@orde.rs), navigate through adding a PPM move, then sign and submit, which returns you to the Home screen. Observe the two Helper components, the first sharing general info and the second sharing PPM info. 

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4267) for this change
* [Zeplin Home State 4](https://app.zeplin.io/project/5f7cbab735d969035eb65339/screen/5f7ddea96439376848a1a8fc)
* [GHC Content Spreadsheet](https://docs.google.com/spreadsheets/d/14_qlyhSN6-VjXmBLRtBHj2OUwy76NONOEUbYiRYQ2-w/edit?ts=5ee3fe45#gid=1041135497) (starting around line 100)

## Screenshots

Screen Shot 2020-11-11 at 11 19 26 AM

### CODE REVIEW

**Comment by mariaclaratgolfo** [comment]
This is looking great. I wonder if we could include screenshots of visual changes like these in the description? I took a look at Happo though! I'm also not certain based on your Reviewer Notes what aspects are 'done' vs WIP.

Based on what I can see in Happo:

- Can we remove the extra space in the 'For moving tips:" link sentences?

- Can we make the sentences that appear bold [in spec](https://zpl.io/bojBvzW) bold?

- Unless James requested otherwise, can we remove the " : " following 'For more moving tips'

- Since those links ['Create a custom checklist' and 'Learn more' ] lead to external pages, can we add the [external link icon](https://share.goabstract.com/c41ed45e-8220-49ca-bf3d-55b6aea3087e?collectionLayerId=b5b6c367-fb99-407a-8389-ba24d459a95f&mode=design)

- For the 'Track your move here' primary message, I think you might have unfortunately been referencing an old design. These are the latest cards we should be creating: https://zpl.io/2ZeZAlG

**Review by mariaclaratgolfo — CHANGES_REQUESTED** [review]
I left a comment :)

**Review by suzubara — COMMENTED** [review]
It looks like the new Storybook component is failing because of the `Link` component. There are a couple ways to deal with it, you might be able to use the same `MockedProviders` solution that we added to the tests, and there's also a Storybook router add-on: https://github.com/gvaldambrini/storybook-router/tree/master/packages/react

let me know if you'd like any help resolving!

**Comment by SirenaBorracha** [comment]
> * Can we make the sentences that appear bold in spec bold?

Done!




> * Unless James requested otherwise, can we remove the " : " following 'For more moving tips'

The copy in the content spreadsheet includes the colons, but I can check with him if you feel strongly?




> * Since those links ['Create a custom checklist' and 'Learn more' ] lead to external pages, can we add the external link icon

For whatever reason, Happo can't seem to record those icons existing, but you can see them in the screenshot I added.




> * Can we remove the extra space in the 'For moving tips:" link sentences?

That's where the invisible-to-Happo external link icons are, hopefully 😄 




> * For the 'Track your move here' primary message ... 

I'm not sure what you mean, in Happo I see the 'Track your move' cards in the Before column and the new copy in the After column

**Review by mariaclaratgolfo — APPROVED** [review]

**Review by suzubara — APPROVED** [review]
Yay!

**Pull request merged**
