### PR TITLE
MMHDT 614 adjust accomack county gbloc

### PR DESCRIPTION
**Pull request by cameroncaci**
[MMHDT-614](https://jira.csde.caci.com/browse/MMHDT-614)

[Integration PR](https://github.com/transcom/mymove/pull/14041)

## Summary
All ACCOMACK county GBLOCs must be set to be "BGNC". Currently they are split between two GBLOCS of "BGNC" and "BGAC"

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Matches int PR

**Review by danieljordan-caci — APPROVED** [review]

**Review by taeJungCaci — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]

**Comment by deandreJones** [comment]
was this already applied in prod?

**Comment by deandreJones** [comment]
conflicts

**Comment by cameroncaci** [comment]
> was this already applied in prod?

yes, this is just the migration script because it was meant for all environments. Helps with the git history

**Pull request merged**
