### PR TITLE
MB-16569 - Update golang to 1.20.6

### PR DESCRIPTION
**Pull request by michaelvaldes-truss**
## Summary

[Release notes](https://go.dev/doc/devel/release#go1.20.minor)
[Corresponding circleci-docker pr](https://github.com/transcom/circleci-docker/pull/432)

Following instructions from https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version

## Verification Steps for the Author

- [x] Update go versions in tools files
- [x] Update docker hashes with a hash that has go 1.20.6: https://hub.docker.com/r/milmove/circleci-docker/tags
- [x] Test golangci-lint
- [x] Update nix hash once it is available: https://nixpk.gs/pr-tracker.html?pr=242949
- [ ] Update docker hashes once https://github.com/transcom/circleci-docker/pull/432 merges

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### CODE REVIEW

**Review by StuTruss — APPROVED** [review]

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

Tests passed when running `make server_test` with the new Golang version `1.20.6`.

Captura de pantalla 2023-07-26 a la(s) 10 18 28 p m

**Review by ahobson — APPROVED** [review]
🚀

**Review by reggieriser — CHANGES_REQUESTED** [review]
Looks like there's one more [Go 1.20.5 reference to change](https://github.com/transcom/mymove/blob/6a0d9f901764e76dfe3aacdc7b411bba3857d12e/.github/workflows/go-auto-approve.yml#L30C11-L30C11) in a GitHub action.

**Comment by michaelvaldes-truss** [comment]
> Looks like there's one more [Go 1.20.5 reference to change](https://github.com/transcom/mymove/blob/6a0d9f901764e76dfe3aacdc7b411bba3857d12e/.github/workflows/go-auto-approve.yml#L30C11-L30C11) in a GitHub action.

Nice catch -- fixed!

**Review by reggieriser — APPROVED** [review]
LGTM!

**Pull request merged**
