### PR TITLE
MAIN - B 18161 update email customer submitted moves

### PR DESCRIPTION
**Pull request by taeJungCaci**
This is to merge work done on https://github.com/transcom/mymove/pull/11855 to Main branch.

## Summary

Updating email template that is sent when the customer creates a move with any shipment type.

- Fixed a typo from "an" to a"
- Added a sentence "If you have requested a PPM, DO NOT start your PPM until your counselor has approved it in MilMove. You will receive an email when that is complete."
- Changed email signature to "USTRANSCOM MilMove Team"

### How to test

For Gov't Counseling email:
1. Create a new customer with your email and add any shipment to the move.
2. Once you have finished submitting, you should receive an email with a title: "Thank you for submitting your move details.

For GHC Counseling email:
1. Create a new customer with your email, Marine Corps, and NS Mayport, FL 32228 as the duty location (Might have to pick 32233 as zip for your address if it doesn't work).
2. Choose any shipment for the move and finish submitting.
3. Once you have finished submitting, you should receive an email with a title: "Thank you for submitting your move details.

## Screenshots after the update

Gov't Counseling:
image

GHC Counseling:
image

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
Tested and working 👍

**Comment by JamesHawks224** [comment]
govt counseling, email body:
text from email:
To change any information about your move, or to add or cancel shipments, you should contact your nearest transportation office. You can find the contact information using the [directory of PCS-related contacts](https://installations.militaryonesource.mil/search?program-service=2/view-by=ALL).

This does not match attached screenshot.

**Comment by JamesHawks224** [comment]
govt counseling, email body:
text from email:
This is a confirmation that you have submitted the details for your move to Edwards AFB, CA 93524.

Per screenshot, there should be a "from" in this sentence.  It is not there.

**Comment by taeJungCaci** [comment]
> govt counseling, email body: text from email: To change any information about your move, or to add or cancel shipments, you should contact your nearest transportation office. You can find the contact information using the [directory of PCS-related contacts](https://installations.militaryonesource.mil/search?program-service=2/view-by=ALL).
> 
> This does not match attached screenshot.

That is correct. There are certain duty locations that seem to not have a specific name or a phone number for office. For those duty locations, the "from" is removed and the content for contact information gets changed to the one you received.

This has been discussed with Brittney as well when she was testing and has been noted for PO acceptance.

It was discovered after PR had been merged and forgot to add that into this PR. I can grab a screenshot of what it should look like and add it if you like. But the content you provided is correct.

**Comment by JamesHawks224** [comment]
> > govt counseling, email body: text from email: To change any information about your move, or to add or cancel shipments, you should contact your nearest transportation office. You can find the contact information using the [directory of PCS-related contacts](https://installations.militaryonesource.mil/search?program-service=2/view-by=ALL).
> > This does not match attached screenshot.
> 
> That is correct. There are certain duty locations that seem to not have a specific name or a phone number for office. For those duty locations, the "from" is removed and the content for contact information gets changed to the one you received.
> 
> This has been discussed with Brittney as well when she was testing and has been noted for PO acceptance.
> 
> It was discovered after PR had been merged and forgot to add that into this PR. I can grab a screenshot of what it should look like and add it if you like. But the content you provided is correct.

Sounds good.  Marking as resolved.

**Comment by JamesHawks224** [comment]
> > govt counseling, email body: text from email: To change any information about your move, or to add or cancel shipments, you should contact your nearest transportation office. You can find the contact information using the [directory of PCS-related contacts](https://installations.militaryonesource.mil/search?program-service=2/view-by=ALL).
> > This does not match attached screenshot.
> 
> That is correct. There are certain duty locations that seem to not have a specific name or a phone number for office. For those duty locations, the "from" is removed and the content for contact information gets changed to the one you received.
> 
> This has been discussed with Brittney as well when she was testing and has been noted for PO acceptance.
> 
> It was discovered after PR had been merged and forgot to add that into this PR. I can grab a screenshot of what it should look like and add it if you like. But the content you provided is correct.

No need to.  Sounds good.  Marking this is resolved (and NOT closing the PR).  :)

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Comment by JamesHawks224** [comment]
A very nicely composed PR.  Good work.

**Pull request merged**
