### PR TITLE
B 21036 enforce dodid and emplid int

### PR DESCRIPTION
**Pull request by cameroncaci**
## Summary

Enforced DODID for all affiliations and when Coast Guard also enforces EMPLID. This is a form validation change and endpoint-specific validation change

### How to test

1. Login as a SC
2. Navigate to add a customer (See screenshots below)
3. Create a new customer and test DODID and EMPLID requirements

## Screenshots
image
Screenshot 2024-09-06 at 10 59 33 AM
Screenshot 2024-09-06 at 11 02 11 AM
Screenshot 2024-09-06 at 11 02 59 AM

## 508 Screenshot
Screenshot 2024-09-06 at 11 02 32 AM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
So sorry for the conflicts

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Looks great and functions as expected!

Would you be open to changing the DOD ID to DoD ID (or vice versa, not sure what the gov prefers) just so they match?
image

**Comment by cameroncaci** [comment]
> Looks great and functions as expected!
> 
> Would you be open to changing the DOD ID to DoD ID (or vice versa, not sure what the gov prefers) just so they match? image

Resolved in https://github.com/transcom/mymove/pull/13649/commits/98b7f778cbfa6ac16f12f030e4c2c0752478cca2

**Review by traskowskycaci — APPROVED** [review]
Very nice!

**Review by danieljordan-caci — APPROVED** [review]
Solid work - works with the most recent changes for safety moves as well. LGTM!

Screenshot 2024-09-06 at 1 51 49 PM

**Review by WeatherfordAaron — APPROVED** [review]
lgtm 👽 
In the future though, I'd suggest added a special error case for when a query comes back with no data. Sometimes it can make tracking down issues slightly easier.

**Pull request merged**
