### PR TITLE
[MB-3615] MTO Basic Service Items Fix Parsing of approvedAt Date

### PR DESCRIPTION
**Pull request by duncan-truss**
## Description

Approving a Move Task Order displayed basic service items with an invalid date on the Move Details page.  It was trying to parse the approvedAt timestamp on the MTO Service Item but we were never saving this when creating the basic service items.  This PR changes the date formatting to expect the ISO timestamp format coming back from the api and sets the approvedAt column on basic service item creation in the database.

## Reviewer Notes

I removed the rejected at logic in the component because according to [Donald's PR](https://github.com/transcom/mymove/pull/4859) we are only displaying the approved service items and omitting saving any as rejected.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make server_run
make office_client_run
```

1. Login as the TOO user
2. Find a move from the queue with shipments needing approval
3. Approve at least one shipment along with 1 or more basic service items
4. The service item should be displayed and the date should be properly formatted 

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3615) for this change

## Screenshots

Screen Shot 2020-10-02 at 3 53 21 PM

### CODE REVIEW

**Review by noelledusahel — APPROVED** [review]
LGTM

**Comment by monfresh** [comment]
Something I noticed is that we only show one set of Service Items, even if there are multiple shipments, and the service items that are displayed only correspond to the first shipment. For example, locally, I had a move with 2 shipments, but I had only approved one of them. After I pulled down your branch, I approved the other one, but the approved at date still did not appear. This is not related to your PR, but maybe something to look into.

**Review by monfresh — APPROVED** [review]
LGTM. I verified locally that for newly approved shipments, the date appears in the service items section.

**Comment by duncan-truss** [comment]
> Something I noticed is that we only show one set of Service Items, even if there are multiple shipments, and the service items that are displayed only correspond to the first shipment. For example, locally, I had a move with 2 shipments, but I had only approved one of them. After I pulled down your branch, I approved the other one, but the approved at date still did not appear. This is not related to your PR, but maybe something to look into.

That's right basic service items aren't tied to a shipment just the overall Move Task Order, they are just grouped with the approved shipment.  If you're talking about basic service items that don't have an approvedAt date, did they maybe come from the E2E data instead of the API?

**Review by donaldthai — APPROVED** [review]
:shipit:

**Pull request merged**
