### PR TITLE
[MB-11072] Add external vendor weight summary to payment requests page

### PR DESCRIPTION
**Pull request by hannaliebl**
## Summary

- Add `ExternalVendorWeightSummary` component to display the weight summaries for external vendor shipments.

### ❓Outstanding question:
Is `ntsRecordedWeight` the value on the vendor shipment I should use to calculate the total weight?

I had trouble getting good data to test this. I described what I did in the steps below to make the component show up, but I'm not entirely sure the data is in an accurate state using the reproduction steps. Open to any other suggestions of move codes to try, etc.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Feel free to check storybook for the two ways the `ExternalVendorWeightSummary` component should render
2. Login as a TOO and use the NTSSUB move. Add the facility info and address, approve both shipments.
3. Go back and change those approved shipments to "uses external vendor" in the top radio selection.
4. Now use the prime simulator to look at the NTSSUB move and create a payment request.
5. Now login as the TIO and find the NTSSUB move. You should see the component show up now with the (note: it shows 0 lb as the total weight, unclear to me if that is because `ntsRecordedWeight` is not actually the correct value to use, or if it's because the test data is inaccurate.)

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [x] There are no new console errors in the test output
- [x] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### CODE REVIEW

**Review by amanda5iu — APPROVED** [review]
This looks good to me! To your question: yes, the NTS recorded weight is what should be used for NTS-release shipments. The TOO may update that number after the vendor weighs the shipment coming out of storage, so that number should display here. We won't have a weight for NTS shipments. 

Just to reiterate, the external vendor shipment weight is for information purposes only, and won't influence any TIO flows.

**Comment by hannaliebl** [comment]
@amanda5iu great, thanks. So in the case where there's only an NTS external vendor shipment, it's ok for this weight summary to display 0 lb? Or should I hide this component if it's only an NTS external vendor shipment?

**Comment by hannaliebl** [comment]
@amanda5iu this is ready to be looked at again - the Storybook stories should be updated with the possibilities of NTS/NTS-release shipment combos.

**Review by YanZ777 — APPROVED** [review]
Looks good to me.

**Pull request merged**
