### PR TITLE
MB-3343 Responsive Behavior for Typography

### PR DESCRIPTION
**Pull request by Shkeating**
## Description

This branch scales down h1s, h2s, and h3s on screen widths below the USWDS "tablet" breakpoint, which is 640px. It also makes h1s bold.

## Reviewer Notes
I need to take a look at how this looks in the customer app before merging this. I want to see if this scales everything down enough. This branch makes changes in our typography.scss style sheet, which has broad influence on the entire app. I have assessed the impact on the loki images, and things are looking _less_ messed up in the mobile images that were changed overall.

## Setup

```sh
yarn install
yarn storybook
```

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3343) for this change

## Screenshots

Desktop
image

Mobile:
image

In app preview
image

### CODE REVIEW

**Review by amanda5iu — COMMENTED** [review]
Has h6 always been sentence case in Storybook? It's all caps in the design library. I think it's fine, just wanna make sure we're on the same page.

Otherwise LGTM!

**Review by suzubara — APPROVED** [review]
code changes look good to me!

**Comment by Shkeating** [comment]
> Has h6 always been sentence case in Storybook? It's all caps in the design library. I think it's fine, just wanna make sure we're on the same page.
> 
> Otherwise LGTM!

I'm going to switch it to be uppercase! thanks for pointing this out!!

**Comment by sojeri** [comment]
@Shkeating is this PR ready for review / are you waiting on someone from moose to look it over? I wanted to make sure we're not blocking you. :)

**Review by amanda5iu — APPROVED** [review]

**Pull request merged**
