### PR TITLE
First stab at indexes for four tables

### PR DESCRIPTION
**Pull request by breanneboland**
## Description

This adds new fizz files to add indexes to the blackout_dates, shipments, traffic_distribution_lists, and TSP tables. 

## Reviewer Notes

I feel I should have added verbs to the front of the fizz files ("update..."), but I'd like to confirm that and work out how we want to handle future updating fizz files. If we do want specific naming conventions, I want to add it to a doc somewhere or otherwise codify it.
I'd also appreciate opinions on the order of my indexing. I have reasons for everything I did, but I'm very interested in everyone else's thoughts. 

## Verification Steps

* [x] Run `make db_dev_migrate`
* [x] Connect to the database and run, for example, `dev_db=# \d blackout_dates;` to confirm that this migration succeeded. It will show you the table's schema, followed by any indexes or foreign key constraints. 

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/155384989) for this change
* [The Fixx documentation](https://github.com/gobuffalo/pop/tree/master/fizz) examines the different ways to create and alter tables using fizz files.

### CODE REVIEW

**Comment by breanneboland** [comment]
@jim, I did some renaming and added down migrations. What do you think?

**Comment by kilbergr** [comment]
I think this task will make more sense when we have the tsp performance table, since that's the only one we've thought all that much about indexing on (as far as I know...).
It might help to include info on why you've written the indices you have. e.g. We're expecting to query the shipments table most often to determine which shipments in a specific TDL are being picked up in the 10 days (bad example I know), which is why they're indexed on TDL and pickup_date.
Alexi's work on Reasoning about the Data Model in the RTB might be a good resource for that. For example, I imagine we'd be querying shipments most frequently on TDL with a join on shipment_awards to see which shipments are not yet awarded. So to my thinking the index on TDL in the shipment table makes sense, but I don't know if you get that much added value from the pickup_date and dropoff_date index. Does that make sense?

**Comment by breanneboland** [comment]
@kilbergr, I agree. I'm taking this task as a draft of something that will need to be refined as we dig deeper into using these tables; I have notes about why I chose this initial order and was hoping to talk it through with someone, probably more than once as we move forward. (And yes, it feels unnatural to avoid the still-being-implemented tables, most especially the TSP performance table.)

**Comment by breanneboland** [comment]
@jim, do you think there's any documentation outside of this PR that would benefit us in that respect? I think we're all pretty aware, so maybe that's enough. An ADR for "under construction" seems a little much, hahaha, but I'm always nervous about things getting dropped. I suppose a "revisit indexing order and choices" icebox task would do it.

**Pull request merged**
