### PR TITLE
Int b 21457 too approve email for retiree separatee

### PR DESCRIPTION
**Pull request by samaysofo**
## Summary
Currently when a TOO creates a move task order , emails that gets sent to retirees and separatees state that their move is scheduled to deliver to their HOS/HOR/PLEAD instead of the delivery address on their shipment. So these changes are to let the delivery address on the email to display the right address.

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [x] Has the branch been pulled in and checked out?
- [x] Have the BL acceptance criteria been met for this change?
- [x] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)
**Local testing for emails, you will need to start the server with this:**
EMAIL_BACKEND=ses AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-dev -- make server_run

### How to test

1. Access the application
2. Login as a Customer
3. Create a new move (Select Retirement/ Separation) on the "Tell us about your move orders page".
4. Go through the process of Setting up a shipments (e.g HHG/PPM) to create a shipment , sign a complete(Make sure to copy/save your move code for later).
5. Login as a Service Counselor(SC)
6. Search for your move code in step 4 and navigate to it.
7. Make sure you edit/fix any required fields.
8. Login as a TOO
9. Repeat step 6
10. Select the checkbox  for the shipment created in 4
11. Scroll down and click "Approve selected" button.
12. Click "Approve and send" button.
13. You will receive an email (**it took ~ 15 mins during testing**) with subject"Your personal property move has been ordered" in the email you provided during the Move/shipment creation process.
14. Note that the verbiage in the email "This is a confirmation that a move task order has been placed for your move  [YOUR_MOVE_CODE] to [Destination_address_you_provided_for_shipment].

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
[B-21457-TOO-Approved-Move-Details-Emails.docx](https://github.com/user-attachments/files/17560843/B-21457-TOO-Approved-Move-Details-Emails.docx)

### CODE REVIEW

**Comment by samaysofo** [comment]
Failed client_test seems to be "FLAKY"
image

**Review by ryan-mchugh — APPROVED** [review]

**Comment by samaysofo** [comment]
This pr is still open for review if anyone has some time to take a look.

**Review by msaki-caci — COMMENTED** [review]
lgtm just a couple of flaky failures

**Review by msaki-caci — APPROVED** [review]

**Comment by samaysofo** [comment]
@danieljordan-caci may you please take a look at this pr when you get the chance? thanks

**Review by brianmanley-caci — APPROVED** [review]

**Comment by samaysofo** [comment]
@danieljordan-caci @paulstonebraker this pr is open for review when you get the chance, thanks

**Review by danieljordan-caci — APPROVED** [review]

**Pull request merged**
