### PR TITLE
Int b 19925 sorting branch param to uppercase

### PR DESCRIPTION
**Pull request by MichaelEngelbertCACI**
## Summary

When searching for moves based on branch of service, the wrong number of moves was being returned. Upon further inspection it was discovered that if the affiliator entry wasn't capitalized in service_members then the query wouldn't return the correct number of moves given that branch. To fix this we are allowing for case-insensitive querying of moves based on service branch.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. git fetch and git checkout the branch. 
2. change the afilliator column of one of the entries in service_members to not be all uppercase but still the same word (i.e. ARMY -> Army)
3. Sign into the office app as a TOO or TIO and search for moves based on the service branch of the database entry you changed. 
4. Ensure the entry that you changed in the database is properly queried for in the move search and the total number of moves under that service branch matches the amount in the database.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots
Affiliation case change:

Screenshot 2024-06-05 at 4 45 37 AM

### Before:

Screenshot 2024-06-05 at 4 33 02 AM
Screenshot 2024-06-05 at 4 47 31 AM

### After:

Screenshot 2024-06-05 at 4 25 58 AM
Screenshot 2024-06-05 at 4 49 45 AM

### CODE REVIEW

**Review by deandreJones — CHANGES_REQUESTED** [review]
Need to update destination to integrationTestng

**Comment by MichaelEngelbertCACI** [comment]
> Need to update destination to integrationTestng

whoops sorry about that

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Still seeing the issue described in the PDF on the Agility story.

Steps to reproduce.
1. Checked out your branch
2. Ran make db_dev_fresh to ensure no stale data
3. Logged in as TOO
4. Viewed all the moves first without filtering by Branch. I see 121 moves 
image
5. Then I filtered by Army. I now see 83 moves
image
6. I picked one move to modify the service_member's affiliation for, to test if it will still show up in the queue. Picked 4RR9V7
image
7. In the database, searched for that move
image
8. Went to the orders associated with that move
image
9. Went to the service member for those orders. I see the affiliation currently as "ARMY"
image
10. Modified the affiliation to "Army"
image
11. Refreshed the TOO queue. Still see 121 total moves, with 4RR9V7 right there at the top
image
12. Filtered by Army again in the branch filter. Now, I only see 82 moves. 4RR9V7 is not showing up.
image
13. Just to further test this, I set the affiliation back to "ARMY"
image
14. Filtered by army again and it is now back to showing up in the queue.
image


Let me know if you see something different or if I am not testing correctly, but I recommend taking another look at this.

**Comment by deandreJones** [comment]
looks like you have a failing test

**Comment by traskowskycaci** [comment]
@MichaelEngelbertCACI When someone requests changes on your PR and you make a fix for it, you have to manually re-request a review from them. I am going to re-request myself this time but in your other PRs that's something to keep an eye on and do yourself as the dev, just a heads up. That helps notify that reviewing dev that it is ready to be looked at again

image

**Review by traskowskycaci — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]
Found a move and changed the service member affiliation from ARMY to Army. Filtered the Move list based on Army and still saw the move in the move queue. Also confirmed that the amount of moves when filtering by Army matches the same amount as when I changed the affiliation of a service member from ARMY to Army.

**Review by deandreJones — APPROVED** [review]
I like simple fixes

**Pull request merged**
