### PR TITLE
MB-13654 eval report page two save draft

### PR DESCRIPTION
**Pull request by PDickeyTruss**
## Summary

This PR adds the ability to save all fields on the second page of the Evaluation Report form except for violations (those were done in a previous PR). These fields include serious incident, serious incident description, and four date fields that are conditionally displayed in the form depending on selected violations. I added all of these fields to the Eval Report table and updated related BE/API/FE to allow saving of these fields.

## Important Testing Note:
To test this you will need to use the conditionally displayed date field inputs. You can get these to display by selecting the following violations for a report:
- Counseling > Scheduling
- Shipment Schedule > Pickup
- Loss & Damage > Claims Settlement

Screen Shot 2022-09-26 at 2 47 40 PM

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

## Verification Steps
- [ ] Create a evaluation report, fill out the first page of the form, select 'yes' for 'violations observed', then click 'Next: select violations'
- [ ] From the second page of the Evaluation report form: 
  - [ ] Values entered in the Observed Claims Response Date input are retained after clicking 'Save draft'
  - [ ] Values entered in the Observed Date input are retained after clicking 'Save draft'
  - [ ] Values entered in the Observed Pickup Spread Start Date input are retained after clicking 'Save draft'
  - [ ] Values entered in the Observed Pickup Spread End Date input are retained after clicking 'Save draft'
  - [ ] Value selected in the Serious Incident radio is retained after clicking 'Save draft'
  - [ ] Text entered in the Serious Incident description text input is retained after clicking 'Save draft'
 
## Screenshots

https://user-images.githubusercontent.com/62263329/192858471-75ab8089-84c0-4b3c-a5db-db24093bef8c.mov

### CODE REVIEW

**Comment by cosburn** [comment]
Hi! I noticed that when I save a draft with `serious incident` = `yes` it will correctly save the info, but displays as "no" on the QA reports page. When I click in to edit, it shows "yes." Should these be aligned as part of this PR?

Screen Shot 2022-09-30 at 11 13 47 AM
Screen Shot 2022-09-30 at 11 13 41 AM

**Comment by PDickeyTruss** [comment]
> Hi! I noticed that when I save a draft with `serious incident` = `yes` it will correctly save the info, but displays as "no" on the QA reports page. When I click in to edit, it shows "yes." Should these be aligned as part of this PR?

Good catch! This was hardcoded to 'No' and is now fixed.

**Review by mandaem — COMMENTED** [review]
changes are working :)

**Review by cosburn — APPROVED** [review]
Looks good to me!

**Review by Ryan-Koch — APPROVED** [review]
Migration LGTM

**Pull request merged**
