### PR TITLE
MB 3930 Progress Bar Mobile Styling

### PR DESCRIPTION
**Pull request by Shkeating**
## Description

This PR adds styling to improve the readability  of the status bar in mobile screen widths.

## Reviewer Notes

This PR is in progress. We need to decide whether or not we can remove the "approved" step from the bar. If it has to stay, more work will need to be done ahead of being ready to merge

## Setup

```sh
yarn install
yarn storybook
```

or
```sh
make db_dev_e2e_populate
make server_run
make client_run
```
and on milmovelocal:3000:

1. click **Local Sign In**
2. select a user fomr the list who did their inital account setup already. I used **profile@comple.te (milmove)**
3. That will take you to a page where the status bar lives.

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3930?atlOrigin=eyJpIjoiODQ5MDE0NmRhODQyNDIzYzhiNWJlOTkxYTg2ODliYTgiLCJwIjoiaiJ9) for this change

## Screenshots

image
with all items in status bar

image
with approved item removed

### CODE REVIEW

**Review by mariaclaratgolfo — COMMENTED** [review]
• Can you make sure the padding between each step label is equidistant? It looks like Payment requested and Payment reviewed are slightly wider than the others? 
• I'd also make sure that the text styles are using p--small (I believe they are), and I'd remove the Bolding text style when selected to accommodate more horizontal space. 

Other then that, Good to go :)

**Review by kimallen — APPROVED** [review]
Looks good on local envt to me.  I'm glad to slowly be converting old code to use .scss.

 What is the conversation about removing Approve?  I know there was lots of past research done for these timelines. (I'm assuming if removal happens, it would happen in a future story.  if we do, it will likely impact tests and involve more than just removing from the UI component)

**Review by suzubara — APPROVED** [review]
The code changes look fine, I agree with @kimallen that removing a step may not be so straightforward, and should potentially be addressed separately. Also I want to throw it out there that in case you feel like it, this seems like a greaaaat opportunity to move the `StatusTimeline` component into the components dir, add stories for it, etc....

**Comment by Shkeating** [comment]
pushing an update that will make it look like the below screenshots. I left the Approve step in because it was going to be a lot of work to pull it out, and update tests to reflect it not being there.
image
mobile

image
desktop

**Review by mariaclaratgolfo — APPROVED** [review]

**Pull request merged**
