### PR TITLE
[MB-14371] Upgrade to go 1.19.3

### PR DESCRIPTION
**Pull request by reggieriser**
## Summary

This PR updates the project from Go 1.19.2 to Go 1.19.3 (which includes security fixes).

Go 1.19.x version history:
https://golang.org/doc/devel/release.html#go1.19

Here's the [corresponding PR from circleci-docker](https://github.com/transcom/circleci-docker/pull/320) for the docker image hash referenced in this PR.  Please verify that it seems correct and that all relevant references have been updated.

~~**Note:** After this PR has been initially vetted, I will merge in the circleci-docker PR and update this PR with the new hash.~~ Done!

I generally followed [these upgrade instructions](https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version).

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

To move your local dev environment to 1.19.3 (assuming you're using `asdf`):
```
asdf install
asdf global golang 1.19.3
```
You may want to restart your terminal window after this if you run into issues.

If you're using `nix` instead, you should be prompted to run `./nix/update.sh` .

After moving to go 1.19.3, just try out your normal day-to-day workflow and see if anything falls out.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

### CODE REVIEW

**Review by mandaem — APPROVED** [review]
LGTM using asdf, if someone with nix can also test.

**Comment by rogeruiz** [comment]
running `./nix/update.sh` locally to check this out.

**Comment by rogeruiz** [comment]
running `make test`. The update was fine on my end with Nix.

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

```sh

>_ go version

go version go1.19.3 Darwin/amd64
```
Server tests passed.

```sh
>_ make server_test && echo "tests passed"

#... content shortened for brevity

tests passed
```

**Pull request merged**
