### PR TITLE
MB-13864 update ppm doc review to handle different doc types without errors

### PR DESCRIPTION
**Pull request by felipe-lee**
## Summary

This fixes a bug where if a shipment has document types other than weight tickets, it tries to render the data for the other document types using the weight ticket component. This will now skip the other document types if there are any, and it will go straight to the review page after weight tickets are done. 

Some things to note about the review page after this change:

1. It will show the other document types as being rejected because we currently have that as the [default fallback if no other status matches](https://github.com/transcom/mymove/blob/2d7837014106218a8de2a3eb06338003a715e811/src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx#L53-L59), but really, they should not have been accepted or rejected. We can probably update this to hide the un-reviewed document types, but since we'll eventually add those, I left it for now.
2. The number at the top of the review section that says x of y document sets will show the latest doc set number it got to that was a weight ticket, but is aware if there are more. So for example, you may see 1 of 3 even though you only approved/rejected one weight ticket (the screenshot below shows this). We can make that total only reflect the weight tickets if we want, but for simplicity I just let it keep showing the real total.

I made changes to make it easier to tell which document set we are working with at a given time. This made it easier to then only pass the desired uploads for the current document set rather than all of them every time. I hope these changes also help once we get to implementing the progear weight ticket and moving expense review functionality since I included those in the new structure, I just didn't put in their components to keep the scope more focused.

I split out the commits to differentiate between the main changes and the ancillary changes I made. Each commit contains more details in the body of the commit message so you can click into those if you'd like. 

<details>
<summary>Main changes</summary>

* [refactor: update ReviewDocuments to handle doc types a little better](https://github.com/transcom/mymove/commit/26e1937d09e7b219fd86786f5613ae46a302281a)

</details>

<details>
<summary>Other changes</summary>

* [refactor (js factory): update upload factory to allow overriding fields](https://github.com/transcom/mymove/commit/edd8c97e76ec1a90418a1123d1de77aabdfd6a3f)
* [refactor (tests): update review document tests to follow ideal practices](https://github.com/transcom/mymove/commit/f60f932e7de4b6ab626ec908cd7c5e18760bc75f)
* [refactor (devseed data): add a move with multiple ppm doc types](https://github.com/transcom/mymove/commit/6a7e6a834d8993f4a4ce3c7b07b3d9d33f0e0a81)

</details>

## Setup to Run Your Code

<details>
<summary>💻</summary>

### Terminal 1

Start the UI locally

```sh
make office_client_run
```

### Terminal 2

Start the server.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app either 
    1. locally after following the local setup above or
    2. using the [ephemeral deployment](https://office-milmove-pr-10115.mymove.sandbox.truss.coffee/sign-in)
1. Login as a services_counselor_role@office.mil
1. Click "PPM Closeout"
1. Select the move with the name "AllDocs, PPMCloseout" and move code `CLOSE2`
1. Click "Review Documents"
1. If necessary, approve the first weight ticket. Click "Continue"
1. Note the overview component displays the corresponding information.
1. Click "Confirm" to return to the Move Details page.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

## Screenshots

image

### CODE REVIEW

**Comment by felipe-lee** [comment]
> Thanks for taking this on, @felipe-lee! I appreciate that the user and tests you added let this feature live on the app without introducing new errors for any users, even while we await the future features.
> 
> Issue: I noticed that for moves with one weight ticket (CLOSE0 and CLOSE2), the Back button is disabled once we reach the review panel; contrast with CLOSE1, where it is enabled. I think this is just a matter of updating the logic [here](https://github.com/transcom/mymove/blob/6a7e6a834d8993f4a4ce3c7b07b3d9d33f0e0a81/src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx#L192) to enable Back when `showOverview` is `true`, too, and possibly adding tests. I'm not sure if it's in scope to fix this on this PR (it looks like I had introduced it earlier), but it's worth pointing out.

@scottmries Nice catch! I've pushed up a fix with a new test and a few more expectations in existing tests to ensure this keeps working as we make more changes in future PRs.

**Review by scottmries — APPROVED** [review]
LGTM, @felipe-lee!

**Comment by rileyorr** [comment]
@felipe-lee I took a look at the UI and overall I think these fixes work for now! I also answered your UI questions below: 

> 1. It will show the other document types as being rejected because we currently have that as the [default fallback if no other status matches](https://github.com/transcom/mymove/blob/2d7837014106218a8de2a3eb06338003a715e811/src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx#L53-L59), but really, they should not have been accepted or rejected. We can probably update this to hide the un-reviewed document types, but since we’ll eventually add those, I left it for now.

I think it's fine to leave pro-gear and expenses as rejected for now until those items are added. My only question about this is: would it be beneficial to document this in the pro-gear and expenses tickets so we know to come back to this?

> 2. The number at the top of the review section that says x of y document sets will show the latest doc set number it got to that was a weight ticket, but is aware if there are more. So for example, you may see 1 of 3 even though you only approved/rejected one weight ticket (the screenshot below shows this). We can make that total only reflect the weight tickets if we want, but for simplicity I just let it keep showing the real total.

I think I'm tracking this. Basically weight ticket = set 1, pro-gear = set 2, and expenses = set 3 and the reason why it's showing 1 of 3 on the review page is because we aren't populating pro-gear and expenses yet? I think that's fine for now and can be resolved once we add pro-gear and expenses because not everyone will have all the document set types. 

Let me know if you have any questions!

**Comment by felipe-lee** [comment]
> @felipe-lee I took a look at the UI and overall I think these fixes work for now! I also answered your UI questions below:
> 
> > 1. It will show the other document types as being rejected because we currently have that as the [default fallback if no other status matches](https://github.com/transcom/mymove/blob/2d7837014106218a8de2a3eb06338003a715e811/src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx#L53-L59), but really, they should not have been accepted or rejected. We can probably update this to hide the un-reviewed document types, but since we’ll eventually add those, I left it for now.
> 
> I think it's fine to leave pro-gear and expenses as rejected for now until those items are added. My only question about this is: would it be beneficial to document this in the pro-gear and expenses tickets so we know to come back to this?
> 
Yeah, I can add a note indicating the current behavior to those tickets. I do think they would have likely handled it, but better for us to be explicit.

> > 2. The number at the top of the review section that says x of y document sets will show the latest doc set number it got to that was a weight ticket, but is aware if there are more. So for example, you may see 1 of 3 even though you only approved/rejected one weight ticket (the screenshot below shows this). We can make that total only reflect the weight tickets if we want, but for simplicity I just let it keep showing the real total.
> 
> I think I'm tracking this. Basically weight ticket = set 1, pro-gear = set 2, and expenses = set 3 and the reason why it's showing 1 of 3 on the review page is because we aren't populating pro-gear and expenses yet? I think that's fine for now and can be resolved once we add pro-gear and expenses because not everyone will have all the document set types.
> 
> Let me know if you have any questions!

Yeah, that's exactly what's going on. Sounds good, thanks for reviewing!

**Comment by felipe-lee** [comment]
> > @felipe-lee I took a look at the UI and overall I think these fixes work for now! I also answered your UI questions below:
> > > 1. It will show the other document types as being rejected because we currently have that as the [default fallback if no other status matches](https://github.com/transcom/mymove/blob/2d7837014106218a8de2a3eb06338003a715e811/src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx#L53-L59), but really, they should not have been accepted or rejected. We can probably update this to hide the un-reviewed document types, but since we’ll eventually add those, I left it for now.
> > 
> > 
> > I think it's fine to leave pro-gear and expenses as rejected for now until those items are added. My only question about this is: would it be beneficial to document this in the pro-gear and expenses tickets so we know to come back to this?
> 
> Yeah, I can add a note indicating the current behavior to those tickets. I do think they would have likely handled it, but better for us to be explicit.
> 
Added a comment to the [PPM Processor can see an overview of the approval/rejection of a PPM shipment's expenses and pro-gear documentation sets ticket](https://dp3.atlassian.net/browse/MB-15135)🔒.

**Pull request merged**
