### PR TITLE
MB-6683: remove orders.x.move.mil and orders.move.mil

### PR DESCRIPTION
**Pull request by carterjones**
## Description

Remove references to orders.x.move.mil and orders.move.mil.

## Reviewer Notes

The ticket only specifies orders.x.move.mil. I also removed orders.move.mil. If I should not have done that, please let me know.

## Setup

This is run entirely in CircleCI.

## Code Review Verification Steps

* [x] If the change is risky, it has been [tested in experimental](https://app.circleci.com/pipelines/github/transcom/mymove/27166/workflows/ce08befe-4fe2-446e-989f-be73730ff61c) before merging.
* [x] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6683) for this change

### CODE REVIEW

**Comment by esacteksab** [comment]
So `orders.x.move.mil` or `orders.move.mil` is still a thing. What you've deleted elsewhere were a microservice. What `orders.x.move.mil` or `orders.move.mil` is another entry point in the move.mil app. So we still need the record, because it's still a service.

**Comment by kilbergr** [comment]
This is my bad then--I was under the impression that this should be pulled out too from this conversation:

https://ustcdp3.slack.com/archives/CP496B8DB/p1612455747326700?thread_ts=1612451474.323000&cid=CP496B8DB
Following up with Erik.

**Review by travelar — COMMENTED** [review]
I'm conflicted because I don’t know enough about orders and how it's structured. If we go to any of those urls, they are active and seem to have a purpose. See the alarm that Duncan threw the other day, which I can’t find the thread.

I refer to this conversation that these things are being used: https://ustcdp3.slack.com/archives/CP496B8DB/p1613492254102500

**Comment by carterjones** [comment]
Given https://ustcdp3.slack.com/archives/CP496B8DB/p1613494574108300?thread_ts=1613492254.102500&cid=CP496B8DB, I'm going to close this ticket and mark as won't do.

**Comment by kilbergr** [comment]
@carterjones Can you please document this? We all have minimal context on orders and it will continue to be confusing.

**Comment by carterjones** [comment]
I'd be happy to 👍

**Pull request closed without merging**
