### PR TITLE
[MB-10642] Migrate Step component stories to use component decorator and story args

### PR DESCRIPTION
**Pull request by duncan-truss**
## Summary

The Step component was causing weird diff behavior in Happo after upgrading to Storybook 6.4 and maybe before that.  This PR uses the preferred decorator wrapping of components with args for props.

I created a new milmove user and worked through the various steps to make sure it reflected the current state of things.  The Step component is primarily used on the `src/pages/MyMove/Home` page component.

Some of the button styles were not being applied so I tweaked a selector in the scss module file.  There were some child description text for the legal info that I had to add as well.

These are the storybook docs on the decorator format https://storybook.js.org/docs/react/writing-stories/decorators and args https://storybook.js.org/docs/react/writing-stories/args

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

</details>

### Additional steps

1. Find the Step component that is listed under the Customer Components section http://localhost:6006/?path=/story/customer-components-step--profile-complete
2. Verify the different stories render properly and compare to the local app if desired.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

Screen Shot 2021-12-28 at 10 38 14 AM
Screen Shot 2021-12-28 at 10 38 21 AM
Screen Shot 2021-12-28 at 10 38 28 AM
Screen Shot 2021-12-28 at 10 38 37 AM
Screen Shot 2021-12-28 at 10 38 45 AM
Screen Shot 2021-12-28 at 10 38 51 AM
Screen Shot 2021-12-28 at 10 38 59 AM
Screen Shot 2021-12-28 at 10 38 59 AM

### CODE REVIEW

**Review by YanZ777 — COMMENTED** [review]
I'm seeing a few console errors related to step in storybook when I tab through the stories
image
image

**Comment by duncan-truss** [comment]
> I'm seeing a few console errors related to step in storybook when I tab through the stories

Brilliant, thanks @YanZ777 for surfacing those console errors I was definitely not looking there 🙌

**Review by YanZ777 — APPROVED** [review]
Looks good to me! Thanks for fixing those console errors.

**Review by felipe-lee — APPROVED** [review]
The changes lgtm! 

One thing I did notice though was that when I first load storybook, I get this error:
image

I checked the deployed version and don't get that, but I do on master so it's not from your changes.

**Comment by duncan-truss** [comment]
> The changes lgtm!
> 
> One thing I did notice though was that when I first load storybook, I get this error: image
> 
> I checked the deployed version and don't get that, but I do on master so it's not from your changes.

@felipe-lee I've been seeing that too since before this PR, I think it's referring to the USWDS Accordian component https://designsystem.digital.gov/components/accordion/  so maybe it's an issue with the react-uswds storybook we are including.

**Review by brooksr4 — APPROVED** [review]

**Pull request merged**
