### PR TITLE
B 20967 sit panel main

### PR DESCRIPTION
**Pull request by cameroncaci**
> [!NOTE]
> There is an additional commit on this PR that is just a manual introduction of code modified in a merge conflict with integration testing.

## Integration PRs
https://github.com/transcom/mymove/pull/13556
https://github.com/transcom/mymove/pull/13582
https://github.com/transcom/mymove/pull/13613

### CODE REVIEW

**Review by danieljordan-caci — COMMENTED** [review]
Missing [this commit](dacb4eca291e0ff736629108a4a8cde1075933a0), but doesn't seem like the removed comment is in `main`?

Missing [one commit](6c02dd55e0cfd84b8b1753ac258a289493a66160) from [this PR](https://github.com/transcom/mymove/pull/13613/commits) (I see that you reverted one)

**Comment by cameroncaci** [comment]
@danieljordan-caci 
> Missing [this commit](dacb4eca291e0ff736629108a4a8cde1075933a0), but doesn't seem like the removed comment is in `main`?
> 
> Missing [one commit](6c02dd55e0cfd84b8b1753ac258a289493a66160) from [this PR](https://github.com/transcom/mymove/pull/13613/commits) (I see that you reverted one)

Both of the code changes from these commits are present

https://github.com/transcom/mymove/commit/dacb4eca291e0ff736629108a4a8cde1075933a0 code change is present

https://github.com/transcom/mymove/commit/6c02dd55e0cfd84b8b1753ac258a289493a66160 is https://github.com/transcom/mymove/commit/315a718912e30a11aa7c60c9d9589e1a98296737

This is a product of being past the implementation stage but stuck under test/poa/merge main for almost a full month

**Comment by danieljordan-caci** [comment]
> @danieljordan-caci
> 
> > Missing [this commit](dacb4eca291e0ff736629108a4a8cde1075933a0), but doesn't seem like the removed comment is in `main`?
> > Missing [one commit](6c02dd55e0cfd84b8b1753ac258a289493a66160) from [this PR](https://github.com/transcom/mymove/pull/13613/commits) (I see that you reverted one)
> 
> Both of the code changes from these commits are present
> 
> [dacb4ec](https://github.com/transcom/mymove/commit/dacb4eca291e0ff736629108a4a8cde1075933a0) code change is present
> 
> [6c02dd5](https://github.com/transcom/mymove/commit/6c02dd55e0cfd84b8b1753ac258a289493a66160) is [315a718](https://github.com/transcom/mymove/commit/315a718912e30a11aa7c60c9d9589e1a98296737)
> 
> This is a product of being past the implementation stage but stuck under test/poa/merge main for almost a full month

Gotcha. Thanks for the breakdown!

**Review by danieljordan-caci — APPROVED** [review]
LGTM! Commits match up and explanations make sense for differences.

**Pull request merged**
