### PR TITLE
INT B-19044 I-13328 update to SC count

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Here we are again. You may be asking yourself, "Why, Daniel? Why are you doing this again?"

I admit, I do have a problem, but this issue ticket is not one that I created. It was confirmed by the gov via approving a screenshot that they didn't want unapproved shipment counts in the left tab nav, but wanted it in the top nav.

Then I made a huge mistake - I went on vacation thinking they wouldn't change their mind. I was so naive...

Anyway, this PR does the following:
- removes unapproved shipment count entirely for services counselors
- since this is not an action they need to complete, there should not be a flag for them at all
- or at least until some minds are changed again - who knows?

### How to test

1. Access MM as a services counselor or multi role
2. Find a move that has unapproved shipments
3. Confirm that the unapproved shipments do not show up as a count/flag for services counselors, but does for TOO

## Screenshots
Move for SC with unapproved shipments
Screenshot 2024-09-23 at 11 52 43 AM

Same move for TOO that does show flags since shipments are not approved
Screenshot 2024-09-23 at 11 52 55 AM

### CODE REVIEW

**Comment by cameroncaci** [comment]
> This ticket meets the issue AC perfectly and the code looks good; however, I found a new issue that was missed during the initial review by me and Tevin. Please see attached recording for flags incrementing improperly - let me know if out of scope
> 
> Issue does not occur on SC, only on TOO
> 
>  Screen.Recording.2024-09-24.at.11.17.12.AM.mov

I'm good with approving this but creating a new issue ticket - just wanted to grab your thoughts @danieljordan-caci

**Comment by danieljordan-caci** [comment]
> > This ticket meets the issue AC perfectly and the code looks good; however, I found a new issue that was missed during the initial review by me and Tevin. Please see attached recording for flags incrementing improperly - let me know if out of scope
> > Issue does not occur on SC, only on TOO
> > Screen.Recording.2024-09-24.at.11.17.12.AM.mov
> 
> I'm good with approving this but creating a new issue ticket - just wanted to grab your thoughts @danieljordan-caci

Before you create an issue ticket, let me look into this to see if it's a simple fix

**Comment by cameroncaci** [comment]
Flag incrementing issue does not occur on HHG or PPM red flags, seems to just be NTS
image
image

**Comment by danieljordan-caci** [comment]
> Flag incrementing issue does not occur on HHG or PPM red flags, seems to just be NTS image image

Per our Slack convo, this was a funny one.

In `MoveDetails.jsx` the variable `errorIfMissing` was declared outside of the component render, but inside the module. We want this variable to be rendered inside the component so it re-initializes properly on every render and works as expected since we use passed in props with that variable.

Also good to have a used variable inside the component so it is in local scope instead of global scope.

Once I moved it inside, the count was working as expected. I was getting an error telling me to wrap it in `useMemo` (since it is used in a `useEffect`), but was getting incremental changes on page reload instead of navigation so I took the liberty and added:
```
eslint-disable-next-line react-hooks/exhaustive-deps
```
to quiet the error since we had working functionality.

**Review by cameroncaci — APPROVED** [review]
Couldn't break it anymore after the fix - great stuff!

**Review by TevinAdams — APPROVED** [review]

**Pull request closed without merging**
