### PR TITLE
[MB-9903] Change all instances of NTS-R to NTS-release

### PR DESCRIPTION
**Pull request by jenniferlynparsons**
## Description

Changed all text instances and references to `NTS-R` to `NTS-Release`.

## Setup

Make sure data is up to date:

```
make db_dev_e2e_populate
```

Build and run the office app:

```
make server_run
make office_client_run
```

To check storybook changes locally:

```
make storybook
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9903) for this change

### CODE REVIEW

**Review by LeDeep — APPROVED** [review]
lgtm 🚀

**Review by reggieriser — APPROVED** [review]
LGTM.  I did a few searches across the code and didn't find any other user-facing references to `NTS-R` or `NTSR`.  Started the app up and spot-checked a few places in the UI.  We still have variable names, test descriptions, etc. that reference `NTS-R` or `NTSR`, but that should be OK unless there's another meaning for `NTS-R` that could lead to confusion.

**Review by amanda5iu — COMMENTED** [review]
I feel silly nitpicking this but....the `r` should be lowercase. So `NTS-release` instead of `NTS-Release`. :disappearing-homer:

**Comment by amanda5iu** [comment]
> LGTM. I did a few searches across the code and didn't find any other user-facing references to `NTS-R` or `NTSR`. Started the app up and spot-checked a few places in the UI. We still have variable names, test descriptions, etc. that reference `NTS-R` or `NTSR`, but that should be OK unless there's another meaning for `NTS-R` that could lead to confusion.

`NTS-R` could be mistaken for `NTS retrograde`, which won't exist until we do OCONUS, but will eventually be a thing. Just fyi in case it's easier to change now than later!

**Review by amanda5iu — APPROVED** [review]
🎉 thanks for making the copy change!

**Pull request merged**
