### PR TITLE
MB-10390: Enable devauth for load test environment

### PR DESCRIPTION
**Pull request by pearl-truss**
## Description

This PR switches on devauth for the load test environment so that we may run load test against the office environment without running into 403 unauthorized errors

## Reviewer Notes

Is there anything else I need to do to enable devauth for the load test environment? Do I also need to update `loadtest.app-client-tls.env`? 

## Setup
This PR is currently deployed to the loadtest environment. To test that office load test are now working
- navigate to the milmove_load_testing repo
- run `locust -f locustfiles/office.py --host dp3`

You should see the office test being performed and not returning 403/unauthorized errors 
## References

* [Jira story](https://dp3.atlassian.net/browse/MB-10390) for this change

### CODE REVIEW

**Review by felipe-lee — APPROVED** [review]
I'm not sure if this is the only thing needed or not, but what you changed lgtm so I can approve to unblock you. I guess we'll see if it actually is all that's needed.

**Comment by duncan-truss** [comment]
Could you deploy to the loadtest environment using the CircleCI config like we do experimental? https://github.com/transcom/mymove/blob/662738b027987d1f2f3f6406716976220568481f/.circleci/config.yml#L36

**Comment by duncan-truss** [comment]
FWIW I don't see `devlocal_auth` defined in chamber when I run `DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-milmove-loadtest -- chamber list app-loadtest`

**Review by felipe-lee — COMMENTED** [review]
I was looking at #6401 to see what it took to set up dev local auth for the ephemeral deploys and I _think_ one other place that may need to change is this: 
https://github.com/transcom/mymove/blob/ebf3dad2b607cdf6c807441f6bf7806d3abd5723/cmd/milmove/serve.go#L1021-L1030

**Comment by pearl-truss** [comment]
I made a few changes and now see the load test working  against office (this branch is deployed to the load testing environment). I've updated the PR instructions if someone wants to follow those steps and verify

**Comment by ronaktruss** [comment]
When testing this locally, do we need to do any additional setup process? I am seeing the following error:
```
File "/Users/ronak/Projects/mm/testing/milmove_load_testing/utils/hosts.py", line 194, in create_deployed_cert_file
    raise ImplementationError(
utils.base.ImplementationError: Cannot run load testing in a deployed environment without the matching certificate and key.
```

**Review by duncan-truss — APPROVED** [review]
Verified this is working! @ronaktruss I ran into the same problem, I needed to copy `.envrc.chamber.template` to `.envrc.chamber` in the transcom/milmove_load_testing repo to have the dp3 env vars get populated from what is stored in chamber.

**Comment by ronaktruss** [comment]
@duncan-truss Good catch, forgot to update that when I created a new test repo. I also tested this using the deployed version of locust and it looks good as well.

**Pull request merged**
