### PR TITLE
[MB-8182] Migration to remove CACs for Abigail, Suz, Ren, Kim, and Garrett

### PR DESCRIPTION
**Pull request by mboren**
## Description

Removes CAC access. This doesn't have to be a secure migration because we're only identifying the sha256 digest in dev/experimental/staging/prod. And if it doesn't exist in those environments this is a noop.

## Reviewer Notes

This needs to be deployed manually to experimental to apply in that environment. I will do that after getting initial approval on the PR.

## Setup

```sh
make db_dev_run db_dev_migrate
```
Verify that CAC records for the following users no longer appear in client_certs table:
- abbyoung
- garrettqmartin8
- kimallen
- ralren
- suzubara

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](8182) for this change

### CODE REVIEW

**Review by pearl-truss — APPROVED** [review]
Confirmed I no longer see the record in the client_certs table

**Review by lynzt — APPROVED** [review]
LGTM! Ran migrations locally and that row was deleted 🚢

**Review by lynzt — APPROVED** [review]
I have run the new migration and no longer see any of the people listed in the title
🚢

**Review by jacquelineIO — APPROVED** [review]
lgtm

**Comment by mboren** [comment]
This deployed successfully to experimental, except that the `acceptance_tests` job failed for what looks like an unrelated reason. It looks like this job also failed for the milmob deploy to experimental last week.
It doesn't look like I should hold up this PR for this so I'm gonna merge it and follow up with Infra to see what's up.

**Pull request merged**
