### PR TITLE
B:19465 - Add a public GHCApi endpoint to get the transportation offices

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

This MR introduces a new GET endpoint in the GHCAPI to retrieve Transportation Offices outside of being logged in. This will enable transportation office look ups for the Office Account Request Form that is being worked in a different story.

## Testing
1. Start up your server and front end
2. Head to GHC API through swagger or Postman
3. send a GET request to /open/transportation-offices?search

## Screenshots
image
image

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
This might be expected behavior if this is populating a search bar or something with multiple results, but just wanted to check. For the string "PPPO Aviation Training Center Elizabeth City - USCG" I got a response of 4 transportation offices 
1. PPPO Aviation Training Center Elizabeth City - USCG
2. PPPO Aviation Training Center Mobile - USCG
3. PPPO Training Center Cape May - USCG
4. PPPO Training Center Petaluma - USCG

Is that expected?

Response:
```
[
  {
    "address": {
      "city": "Elizabeth City",
      "country": "United States",
      "eTag": "MjAxOC0wNS0yOFQxNDoyNzozNy40NTY3Nzda",
      "id": "3a74321c-1873-415c-9dcc-d7f7a656c898",
      "postalCode": "27909",
      "state": "NC",
      "streetAddress1": "1664 Weeksville Rd ",
      "streetAddress2": "ATTN: Transportation Office "
    },
    "created_at": "2018-05-28T14:27:37.464Z",
    "gbloc": "BGNC",
    "id": "f7d9f4a4-c097-4c72-b0a8-41fc59e9cf44",
    "name": "PPPO Aviation Training Center Elizabeth City - USCG",
    "phone_lines": [],
    "updated_at": "2018-05-28T14:27:37.464Z"
  },
  {
    "address": {
      "city": "Mobile",
      "country": "United States",
      "eTag": "MjAxOC0wNS0yOFQxNDoyNzo0MS4yNTkzMTRa",
      "id": "ab921270-b5f3-4ce3-9b22-6212ab198a0f",
      "postalCode": "36608",
      "state": "AL",
      "streetAddress1": "8501 Tanner Williams Rd",
      "streetAddress2": "nan"
    },
    "created_at": "2018-05-28T14:27:41.267Z",
    "gbloc": "HAFC",
    "id": "27c8d71a-c3c6-4a2d-ac1b-874cbf6a5f85",
    "name": "PPPO Aviation Training Center Mobile - USCG",
    "phone_lines": [],
    "updated_at": "2018-05-28T14:27:41.267Z"
  },
  {
    "address": {
      "city": "Cape May",
      "country": "United States",
      "eTag": "MjAyNC0wNC0wM1QxOTo1ODoxOC40Mjk4Mjha",
      "id": "3b11a8c4-5e23-4afe-b00b-edda2be5d56d",
      "postalCode": "08204",
      "state": "NJ",
      "streetAddress1": "ATTN: Transportation Office  ",
      "streetAddress2": "1 Munro Ave"
    },
    "created_at": "2024-04-03T19:58:18.429Z",
    "gbloc": "AGFM",
    "id": "7ac0f374-b97a-4b98-9878-eabef89adff9",
    "name": "PPPO Training Center Cape May - USCG",
    "phone_lines": [],
    "updated_at": "2024-04-03T19:58:18.429Z"
  },
  {
    "address": {
      "city": "Petaluma",
      "country": "United States",
      "eTag": "MjAxOC0wNS0yOFQxNDoyNzozNC40MTgwNjVa",
      "id": "f4fa7cb4-f18f-46c9-ac56-63148249f328",
      "postalCode": "94952",
      "state": "CA",
      "streetAddress1": "599 Tomales Rd",
      "streetAddress2": "Bldg 150"
    },
    "created_at": "2018-05-28T14:27:34.426Z",
    "gbloc": "LHNQ",
    "id": "f54d8b95-6ee8-4ffa-bf79-67400ae09aa2",
    "name": "PPPO Training Center Petaluma - USCG",
    "phone_lines": [],
    "updated_at": "2018-05-28T14:27:34.426Z"
  },
  {
    "address": {
      "city": "Yorktown",
      "country": "United States",
      "eTag": "MjAyNC0wNC0wM1QxOTo1ODoxOC40Mjk4Mjha",
      "id": "9672422e-6918-48ff-be43-becd025a0e52",
      "postalCode": "23690",
      "state": "VA",
      "streetAddress1": "ATTN: Transportation Office ",
      "streetAddress2": "1 US Coast Guard Training Center"
    },
    "created_at": "2024-04-03T19:58:18.429Z",
    "gbloc": "AGFM",
    "id": "4ed2762d-73bc-4c62-bea9-725c5c64cb62",
    "name": "PPPO Training Center Yorktown - USCG",
    "phone_lines": [],
    "updated_at": "2024-04-03T19:58:18.429Z"
  }
]
```

**Comment by TevinAdams** [comment]
> This might be expected behavior if this is populating a search bar or something with multiple results, but just wanted to check. For the string "PPPO Aviation Training Center Elizabeth City - USCG" I got a response of 4 transportation offices
> 
> 1. PPPO Aviation Training Center Elizabeth City - USCG
> 2. PPPO Aviation Training Center Mobile - USCG
> 3. PPPO Training Center Cape May - USCG
> 4. PPPO Training Center Petaluma - USCG
> 
> Is that expected?
> 
> Response:
> 
> ```
> [
>   {
>     "address": {
>       "city": "Elizabeth City",
>       "country": "United States",
>       "eTag": "MjAxOC0wNS0yOFQxNDoyNzozNy40NTY3Nzda",
>       "id": "3a74321c-1873-415c-9dcc-d7f7a656c898",
>       "postalCode": "27909",
>       "state": "NC",
>       "streetAddress1": "1664 Weeksville Rd ",
>       "streetAddress2": "ATTN: Transportation Office "
>     },
>     "created_at": "2018-05-28T14:27:37.464Z",
>     "gbloc": "BGNC",
>     "id": "f7d9f4a4-c097-4c72-b0a8-41fc59e9cf44",
>     "name": "PPPO Aviation Training Center Elizabeth City - USCG",
>     "phone_lines": [],
>     "updated_at": "2018-05-28T14:27:37.464Z"
>   },
>   {
>     "address": {
>       "city": "Mobile",
>       "country": "United States",
>       "eTag": "MjAxOC0wNS0yOFQxNDoyNzo0MS4yNTkzMTRa",
>       "id": "ab921270-b5f3-4ce3-9b22-6212ab198a0f",
>       "postalCode": "36608",
>       "state": "AL",
>       "streetAddress1": "8501 Tanner Williams Rd",
>       "streetAddress2": "nan"
>     },
>     "created_at": "2018-05-28T14:27:41.267Z",
>     "gbloc": "HAFC",
>     "id": "27c8d71a-c3c6-4a2d-ac1b-874cbf6a5f85",
>     "name": "PPPO Aviation Training Center Mobile - USCG",
>     "phone_lines": [],
>     "updated_at": "2018-05-28T14:27:41.267Z"
>   },
>   {
>     "address": {
>       "city": "Cape May",
>       "country": "United States",
>       "eTag": "MjAyNC0wNC0wM1QxOTo1ODoxOC40Mjk4Mjha",
>       "id": "3b11a8c4-5e23-4afe-b00b-edda2be5d56d",
>       "postalCode": "08204",
>       "state": "NJ",
>       "streetAddress1": "ATTN: Transportation Office  ",
>       "streetAddress2": "1 Munro Ave"
>     },
>     "created_at": "2024-04-03T19:58:18.429Z",
>     "gbloc": "AGFM",
>     "id": "7ac0f374-b97a-4b98-9878-eabef89adff9",
>     "name": "PPPO Training Center Cape May - USCG",
>     "phone_lines": [],
>     "updated_at": "2024-04-03T19:58:18.429Z"
>   },
>   {
>     "address": {
>       "city": "Petaluma",
>       "country": "United States",
>       "eTag": "MjAxOC0wNS0yOFQxNDoyNzozNC40MTgwNjVa",
>       "id": "f4fa7cb4-f18f-46c9-ac56-63148249f328",
>       "postalCode": "94952",
>       "state": "CA",
>       "streetAddress1": "599 Tomales Rd",
>       "streetAddress2": "Bldg 150"
>     },
>     "created_at": "2018-05-28T14:27:34.426Z",
>     "gbloc": "LHNQ",
>     "id": "f54d8b95-6ee8-4ffa-bf79-67400ae09aa2",
>     "name": "PPPO Training Center Petaluma - USCG",
>     "phone_lines": [],
>     "updated_at": "2018-05-28T14:27:34.426Z"
>   },
>   {
>     "address": {
>       "city": "Yorktown",
>       "country": "United States",
>       "eTag": "MjAyNC0wNC0wM1QxOTo1ODoxOC40Mjk4Mjha",
>       "id": "9672422e-6918-48ff-be43-becd025a0e52",
>       "postalCode": "23690",
>       "state": "VA",
>       "streetAddress1": "ATTN: Transportation Office ",
>       "streetAddress2": "1 US Coast Guard Training Center"
>     },
>     "created_at": "2024-04-03T19:58:18.429Z",
>     "gbloc": "AGFM",
>     "id": "4ed2762d-73bc-4c62-bea9-725c5c64cb62",
>     "name": "PPPO Training Center Yorktown - USCG",
>     "phone_lines": [],
>     "updated_at": "2024-04-03T19:58:18.429Z"
>   }
> ]
> ```

@traskowskycaci  Yes. It acts like a smart search. So the user will type in a drop box and it will send the text to this endpoint then the endpoint returns transportation offices matching what they are typing in. Like a smart search.

**Comment by traskowskycaci** [comment]
> > This might be expected behavior if this is populating a search bar or something with multiple results, but just wanted to check. For the string "PPPO Aviation Training Center Elizabeth City - USCG" I got a response of 4 transportation offices

> @traskowskycaci Yes. It acts like a smart search. So the user will type in a drop box and it will send the text to this endpoint then the endpoint returns transportation offices matching what they are typing in. Like a smart search.

Makes sense! Wondered if that was the case. Thanks for clarifying!

**Review by traskowskycaci — APPROVED** [review]

**Review by danieljordan-caci — APPROVED** [review]
LGTM

**Pull request merged**
