### PR TITLE
MB-9016 remove type from prime api crating payloads and responses

### PR DESCRIPTION
**Pull request by eamahanna**
## Description

This PR removes the Type from the MTOServiceItemDimension definition in the prime and support yamls. This was an unnecessary fields for users to complete. 

## Reviewer Notes

Is there any place I missed removing this field?

## Setup

To verify the tests still execute complete the following command, `make server_test`

To test creating a crating service item without using the type field, use postman and enter the following payload:
```
{
    "moveTaskOrderID": "5e7fce45-ada0-4e7d-b362-9c4337af35aa",
    "mtoShipmentID": "cb04ac08-a369-404f-9270-f7784798fba7",
    "modelType": "MTOServiceItemDomesticCrating",
    "reServiceCode": "DCRT",
    "item": {
        "length": 1000,
        "width": 1000,
        "height": 1000
    },
    "crate": {
        "length": 1100,
        "width": 1100,
        "height": 1100
    },
    "description": "Decorated horse head to be crated.",
    "reason": "Storage items need to be picked up"
}
```

You should see a response that looks like this: 

```
[
    {
        "crate": {
            "height": 1100,
            "id": "65afff50-dad9-4eaf-8f33-9e52a2b8ac13",
            "length": 1100,
            "width": 1100
        },
        "description": "Decorated horse head to be crated.",
        "item": {
            "height": 1000,
            "id": "91431402-6c6a-4be0-ae5a-b8449e48cf94",
            "length": 1000,
            "width": 1000
        },
        "reServiceCode": "DCRT",
        "reason": "Storage items need to be picked up",
        "eTag": "MjAyMS0wOC0xOVQxODozODoyNC4zNDE5NTla",
        "id": "bde9af47-7b47-4a41-ac79-eaea29f4286e",
        "modelType": "MTOServiceItemDomesticCrating",
        "moveTaskOrderID": "5e7fce45-ada0-4e7d-b362-9c4337af35aa",
        "mtoShipmentID": "cb04ac08-a369-404f-9270-f7784798fba7",
        "reServiceName": "Domestic crating",
        "status": "SUBMITTED"
    }
]
```

## Code Review Verification Steps

* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9016) for this change

### CODE REVIEW

**Comment by rogeruiz** [comment]
Hey @eamahanna The tests are passing fine, but I'm wondering if we need to remove this type from other places in the app as well? I see it in the `swagger/ghc.yaml` file. Are we saying that `MTOServiceItemDimension` is going to be unique for the Prime only with a change like this?

**Comment by rogeruiz** [comment]
✅ Tests passed after running `make server_test` locally on this branch.

**Comment by eamahanna** [comment]
@rogeruiz this was only for the prime. It's okay for the prime to differ. I'm not sure if the FE relies on the GHC api containing type.

**Comment by sandy-wright** [comment]
> Hey @eamahanna The tests are passing fine, but I'm wondering if we need to remove this type from other places in the app as well? I see it in the `swagger/ghc.yaml` file. Are we saying that `MTOServiceItemDimension` is going to be unique for the Prime only with a change like this?

In general, we let TTV determine how they want to change the GHC API. We do the Prime, they do GHC. It's not a great system... But as Emily mentioned, we don't really have the context to know the effects of making these updates on the office side. I hope this changes with the new team structure soon 🤞

**Review by sandy-wright — APPROVED** [review]
THANK YOU, this looks so much cleaner in the redoc now. This has bugged me for forever. Approved!

**Pull request merged**
