### PR TITLE
[ MB-12015 ] Documenting Prime reweighs in move history table

### PR DESCRIPTION
**Pull request by mmayo-truss**
## Summary
When the prime conducts a reweigh and updates the reweigh weight, we want to correctly see that those weights on the move history table to see that the reweigh was completed.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_office_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app as a TOO and select move DVRS0N 
2. This has two requested shipments, approve and send one or both of them
3. This should take you to the Move task order page
4. If you scroll down you will see the shipment weight as 980 lbs. 
5. click on request reweigh and submit the request.
6. If you look at the move history at this point, you will see the reweigh requested as the latest entry.
7. sign out and sign back in as a prime simulator user.
8. select move DVRS0N
9. scroll down and you will see the reweigh weight entry missing and highlighted with red.
10. click edit and add the reweigh weight lbs and remarks
11. Click on edit again after it saves and enter a different weight to see the move history entry for updating this weight as well.
12. Sign out and sign back in as a TOO and select move DVSR0N again
13. go to the move history table.
14. You should now see separate entries for each reweigh weight that you entered as the prime simulator.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by @juliemoon 
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

## Screenshots
**Before screenshot** 
image

**After Screenshot** 
image

### CODE REVIEW

**Comment by michaelvaldes-truss** [comment]
**nitpick**: I think that "updateReweighWeigh.test.js" should actually be called "updateReweighWeight.test.js"

**Comment by afoon** [comment]
I'm going to review this after our meeting.

**Comment by mmayo-truss** [comment]
> **nitpick**: I think that "updateReweighWeigh.test.js" should actually be called "updateReweighWeight.test.js"

@michaelvaldes-truss good catch!

**Review by afoon — APPROVED** [review]
LGTM! New event in the history is present and the test pass locally.

**Review by juliemoon — APPROVED** [review]
@mmayo-truss Thanks, I was able to follow the instructions and see the UI changes. This looks great!
Screen Shot 2022-09-06 at 3 02 03 PM

**Pull request merged**
