### PR TITLE
Kim mb 3878 new edit route

### PR DESCRIPTION
**Pull request by kimallen**
## Description

Adds shipmentID into routing for the edit shipment page.  This allows the edit shipment page to identify which shipment to edit and existing values to fill. I also added logic to add the shipment number to the HHG title at the top.

## Reviewer Notes

I used the route `moves/:moveId/mto-shipments/:mtoShipmentId/edit-shipment`, although the story said to use `hhg` and did not have `edit-shipment` in the path, which I believe we need for going specifically to the edit page.  I would reserve the path ending in the shipment id for viewing the shipment.

In addition to the story's AC, I removed some local styling that had a note to remove it when ghc styles were merged.  This helped with the 'Add shipment' button to be closer to desired look, though is still a little off. For some reason I can't get the box-shadow styles to apply.  I also noticed an existing alignment issue with the buttons (aligned right of where they should be).

## Setup

Create a 2-3 shipments without submitting the move.
From `/home-2`, check that you can click each of the shipments and they take you to the edit shipment page, and they contain the correct data.
From the review page, click the Edit for each of the shipments and check the same.

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3878) for this change

### CODE REVIEW

**Review by mariaclaratgolfo — COMMENTED** [review]
I'm not able to see what was done here since I don't have staging setup on my computer. Would be open to screenshots, a screen recording or a quick pair session to go through the experience together!

**Comment by mariaclaratgolfo** [comment]
This layout breaks on desktop. It hides the front end styling once it's reaching a break point. 
The intended display of this page it to very closely match that of the initial HHG form/detail page. 
The designs are available in [this collection](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927), in the second section down titled `Edit pages <> Review`

**Review by mariaclaratgolfo — CHANGES_REQUESTED** [review]
This layout breaks on desktop. It hides the front end styling once it's reaching a break point.
The intended display of this page it to very closely match that of the initial HHG form/detail page.
The designs are available in [this collection](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927), in the third section down titled Edit pages <> Review. It includes mobile and desktop layouts.

**Comment by kimallen** [comment]
> This layout breaks on desktop. It hides the front end styling once it's reaching a break point.
> The intended display of this page it to very closely match that of the initial HHG form/detail page.
> The designs are available in [this collection](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927), in the third section down titled Edit pages <> Review. It includes mobile and desktop layouts.

I have a time set up on the calendar to discuss this PR. This PR doesn't change anything about the styling.  It just changes the routing (so the only visual change should be what you see in the url).

**Review by Ronolibert — APPROVED** [review]

**Review by mariaclaratgolfo — APPROVED** [review]

**Pull request merged**
