### PR TITLE
[MB-9264] Add Notifications for Max Billable Weight

### PR DESCRIPTION
**Pull request by pearl-truss**
## Description

This PR adds in the notifications that appear when the max billable weight has been exceed. The notifications added are
- an exclamation icon in the left sidebar for the billable weight tab
- "move exceeds max billable weight" copy added into the billable weight card that's displayed on the payment request page
- "Max billable weight exceeded" alert appears in the edit billable weight sidebar (that appears after clicking 'Review Weights' button on the payment request page)

## Reviewer Notes

- Are the test written okay? Are any cases missing?
- All of the alerts are using the logic of appearing when: the total billable weight (the calculated billable weight of each shipment summed together) is greater than the max billable weight of the move (`order.entitlements.authorizedWeight`)

## Setup

```sh
make db_dev_e2e_populate server_run client_run
```
- Sign into office as a TIO
- On the move details tab, adjust the Max Billable Weight so that it's lower than the total weight
- Go to the payment request tab and verify that there's a indicator on the left side bar and the max weight exceeded weight copy on the billable weight card
- Click the review weights button and verify the max billable weight alert appears in the sidebar
- Go back to the move details page and change the max billable weight to a number greater than the total weight
- Verify that the notifications on the payment request page and edit billable weight sidebar no longer appear

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9264) for this change

## Screenshots

Screen Shot 2021-09-17 at 1 18 52 PM
Screen Shot 2021-09-17 at 1 18 58 PM

### CODE REVIEW

**Review by donaldthai — COMMENTED** [review]
One case I think we're still missing is showing the red alert when reviewing the billable weight for shipments. Everything else looks good!

zeplin that shows the red alert on the shipment weights:
https://app.zeplin.io/project/6112d5999a811689179723b4/screen/6113cc40fb870a9a782e4715

**Comment by pearl-truss** [comment]
> One case I think we're still missing is showing the red alert when reviewing the billable weight for shipments. Everything else looks good!
> 
> zeplin that shows the red alert on the shipment weights:
> https://app.zeplin.io/project/6112d5999a811689179723b4/screen/6113cc40fb870a9a782e4715

Good catch! I made the update
Screen Shot 2021-09-17 at 4 58 25 PM

**Review by YanZ777 — APPROVED** [review]
Looks good to me!
My ask: Could you update the devseed data so that it triggers the flags for the MAXCED move?

**Comment by pearl-truss** [comment]
> MAXCED

thanks, that's been addressed

**Review by donaldthai — APPROVED** [review]
🎉

**Review by cosburn — APPROVED** [review]
Looks great!

**Pull request merged**
