### PR TITLE
B-18326 Update the Estimated Weight - B-18327 Remove Fields

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Summary

Why are 3 different Agility Tickets on one PR?
The reason I thought appropriate to combine these 3 tickets into a singular PR is that it will cut down on technical overhead since the focal point that needs to be changed/edited is the same for all 3 tickets tickets.

When the details are displayed for a PPM shipment on the MTO tab, it should display the estimated weight entered by the customer in stead of the Prime estimated weight (B-18326). It should also not show Requested Delivery Date, Scheduled Delivery Date, Actual Delivery Date, or Required Delivery Date (B-18327). Additionally, in stead of Requested pick up date it should show Planned Move Date and display the customer's Planned Move Date entered during customer onboarding, Scheduled pick up date should be adjusted to Actual Move Date and display the date the customer identifies that they started their PPM, and Actual pick up date should be adjusted to Actual Arrival Date and display the actual arrival date that the customer identifies as their arrival at their destination (B-18322).

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Make a PPM and note what is entered for the estimated weight during shipment creation.
2. Open the PPM shipment on the MTO tab as a TOO user.
3. Observe that the estimated weight entered matches that entered by the customer.
4. Observe that none of the follow fields show up:
    -Requested Delivery Date
    -Scheduled Delivery Date
    -Actual Delivery Date
    -Required Delivery Date
    -Requested Pickup Date
    -Scheduled Pickup Date
    -Actual Pickup Date
5. Observe that the following fields and values show up in stead:
    -Planned Move Date
    -Actual Move Date
    -Actual Arrival Date

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
Screenshot 2024-01-16 at 6 09 17 PM

### CODE REVIEW

**Review by KonstanceH — APPROVED** [review]
Added tests are passing and intended functionality is working for me

**Comment by brooklyn-welsh** [comment]
@WeatherfordAaron Question before you merge, I might be misunderstanding the Agility ticket, but aren't the date field headers in the screenshot above (and during my testing) not adjusted to be the correct title?

**Comment by brooklyn-welsh** [comment]
> @WeatherfordAaron Question before you merge, I might be misunderstanding the Agility ticket, but aren't the date field headers in the screenshot above (and during my testing) not adjusted to be the correct title?

I.e. shouldn't it be:
"Requested pick up date" -> "Planned Move Date"
 "Scheduled pick up date" -> "Actual Move Date"
"Actual pick up date"  -> "Actual Arrival Date"

**Comment by brooklyn-welsh** [comment]
> > @WeatherfordAaron Question before you merge, I might be misunderstanding the Agility ticket, but aren't the date field headers in the screenshot above (and during my testing) not adjusted to be the correct title?
> 
> I.e. shouldn't it be: "Requested pick up date" -> "Planned Move Date"  "Scheduled pick up date" -> "Actual Move Date" "Actual pick up date" -> "Actual Arrival Date"

Ignore, just checked in testing and the titles are actually correct, I was looking at the screenshot in the PR and got mixed up.

**Review by brooklyn-welsh — APPROVED** [review]
Pulled and tested, everything looks good.

**Pull request closed without merging**
