### PR TITLE
INT B-19458 add linehaul service item order to service item list

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Need to ensure that when a linehaul item is auto rejected & a new one created, we keep it in the same position of the list. Followed what is being done for SIT items and placing the linehaul service items (`DLH` & `DSH`) above those in the list. Lemon squeezy.

### How to test

1. Create a **LOCAL** move as a customer, set up your shipments using different ZIPs, and send it
2. Login as the service counselor and approve all of that bidness
3. Login as the TOO and approve the shipment, head over to the MTO page and you'll see a linehaul service item at the top
4. Login as the prime and request the dest address be changed to a ZIP further than 50 miles
5. Login as the TOO and approve the change as TOO
6. Navigate to the MTO page and you should see the linehaul item rejected at the bottom and the new one essentially "replaces" it at the top of the list

## Screenshots
Screenshot 2024-04-03 at 2 45 41 PM

### CODE REVIEW

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Looks great when going back and forth between shorthaul to linehaul and vice versa!

Would you mind changing the comments and the names from just linehaul to linehaul and shorthaul to make it clear it's both of those service item types and not just linehaul?

**Comment by danieljordan-caci** [comment]
> Looks great when going back and forth between shorthaul to linehaul and vice versa!
> 
> Would you mind changing the comments and the names from just linehaul to linehaul and shorthaul to make it clear it's both of those service item types and not just linehaul?

Hey - it's all linehaul to me, man.

Fixed!

**Comment by traskowskycaci** [comment]
Could we also change the variable names to be generic for sh and lh? Maybe like 'haulServiceItems' or 'haulTypeServiceItems'?

**Comment by danieljordan-caci** [comment]
> Could we also change the variable names to be generic for sh and lh? Maybe like 'haulServiceItems' or 'haulTypeServiceItems'?

ANYTHING ELSE, MY LORD?

**Review by traskowskycaci — APPROVED** [review]
Never hit approve so fast. B-E-A-utiful names!

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
