### PR TITLE
B 17666  admin session timeout

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

- Add Timeout For Admin User

## Verification Steps for the Author

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### How to test

1. Access the admin app
2. Login 
3. wait for 10mins

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Is there a reason why you created a separate component instead of reusing `LogoutOnInactivity.jsx` found in `src/layout/LogoutOnInactivity.jsx`?

**Comment by deandreJones** [comment]
@danieljordan-caci  yes, the other idle component uses properties that are not in the admin session store which caused a lot of problems and unnessary vars being added just to try and make it work

**Comment by danieljordan-caci** [comment]
> @danieljordan-caci yes, the other idle component uses properties that are not in the admin session store which caused a lot of problems and unnessary vars being added just to try and make it work

Makes sense. Thanks for clarifying!

**Comment by deandreJones** [comment]
> > @danieljordan-caci yes, the other idle component uses properties that are not in the admin session store which caused a lot of problems and unnessary vars being added just to try and make it work
> 
> Makes sense. Thanks for clarifying!

i definitely tried, it was a lot of wasted time and heartache

**Comment by danieljordan-caci** [comment]
> > > @danieljordan-caci yes, the other idle component uses properties that are not in the admin session store which caused a lot of problems and unnessary vars being added just to try and make it work
> > 
> > 
> > Makes sense. Thanks for clarifying!
> 
> i definitely tried, it was a lot of wasted time and heartache

Definitely get it. I ran into the same thing with the ToolTip component. Was easier to just create a new component than make the old one work.

**Comment by danieljordan-caci** [comment]
All tests passing locally, admin user logs out of MilMove after 10 minutes, also successfully logs out of Okta upon timeout.

LGTM!

**Review by danieljordan-caci — APPROVED** [review]

**Review by traskowskycaci — APPROVED** [review]
Looks good, also confirmed that the warning prompt goes away and user remains signed in if the user clicks while the warning prompt is displayed.

**Pull request merged**
