### PR TITLE
[WIP] Upgrade Cypress to 5

### PR DESCRIPTION
**Pull request by suzubara**
## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

### CODE REVIEW

**Comment by sojeri** [comment]
here is a story if you want one :) https://dp3.atlassian.net/browse/MB-3683

**Comment by suzubara** [comment]
> here is a story if you want one :) https://dp3.atlassian.net/browse/MB-3683

ooh thanks!

**Comment by sojeri** [comment]
lol if we wait long enough cypress may fix enough memory leak issues to fix the flaky tests on their own. ;p

look only 7 failed with 5.1.0:
https://app.circleci.com/pipelines/github/transcom/mymove/20566/workflows/5d5e4d1c-b1a0-4e44-9476-0fa46df637a3/jobs/318204

**Comment by suzubara** [comment]
Closing since Cypress was upgraded in https://github.com/transcom/mymove/pull/4825

**Pull request closed without merging**
