### PR TITLE
B-17615 isWeightTicket Optional Param & Prev PR

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

This PR is copied over from a previous PR with added changes of making the parameter `isWeightTicket` optional instead of required.

[Previous PR](https://github.com/transcom/mymove/pull/11547)

Here is the description from that PR:

## Summary

Added a requirement of the Prime to add a parameter of `isWeightTicket` to a POST request to the `/createUpload` endpoint. 

This required adding a migration file to add a column, `isWeightTicket` to the `proof_of_service_docs` table. Made the default value of `FALSE` to avoid any `NULL` panics.

Updated the Go Struct for `ProofOfServiceDocs` model to include the `isWeightTicket` boolean value.

Updated the payload that is returned for an upload if the upload is:
1. A proof of service doc
2. A proof of service doc that is a weight ticket
This adds an `isWeightTicket` key to the upload array that is used by the UI when reviewing payment requests and their respective documents.

*NOTE* This story did not have criteria to update the Prime simulator, so when using the Prime Sim you will be unable to test this or add a `isWeightTicket` value to the upload.

In order to see this change in the frontend, I also had to update the `model_to_payload.go` file for the GHC API and allow including the parameter in a `GET` request for payment requests.

*DON'T FREAK OUT* by the number of "Files changed" in this request. When changing any property in `swagger-def`, it changes several auto-generated files. You good. We good. It's all good.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Log into MilMove as the Prime
2. Using Postman, send a POST request to `/createUpload` on an existing payment request. Ensure your body is in `formData` as the `Content-Type` and send it.
```
{
   "file": "filePath",
   "isWeightTicket": true
}
```
3. Sign in as an office user and perform a `GET` request to `/payment-requests/{paymentRequestID}`
4. Confirm you can see the `isWeightTicket` parameter for the `proofOfServiceDoc` and `upload` you added to the payment request

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]

**Comment by danieljordan-caci** [comment]
> So we're sticking with a `v1` mod and switching it to optional to avoid introducing breaking changes? What are the current plans of deprecation to force the requirement?

Correct, Danny Matthews told us to just make it optional which will not break any of their systems - whatever those are. No plans as of right now or that I'm aware of.

**Comment by cameroncaci** [comment]
Okay, we could also make it a `v2` change and then enact deprecation after 6 months while homesafe is still using `v1`

**Review by cameroncaci — APPROVED** [review]
Tested successfully

**Comment by danieljordan-caci** [comment]
> Okay, we could also make it a `v2` change and then enact deprecation after 6 months while homesafe is still using `v1`

Def possible, but that's above my pay grade so I'll let those decisions happen as they come. But def wouldn't mind that. I'd love for it to be a required field, but... Lesson learned here.

**Pull request merged**
