### PR TITLE
INT B-18654 MultiMove Create Move Flow Refactor and Enhancements

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

This is (hopefully) the last BL item to accomplish the functionality of allowing a customer to create multiple moves. The way that the current customer application was set up (specifically regarding `state` and `routes.js`), it did not allow for traversal of multiple moves and orders.

The initial purpose of this BL item was to send the user to a new component, `AddOrders.jsx` when clicking the `Create a Move +` button from `MultiMovesLandingPage.jsx` or `Profile.jsx`, but it was discovered that `state` was favoring one and only one set of orders when populating, creating, editing, updating, deleting, and uploading `orders` - which was the most recent set of orders. This did not allow for a user to edit any orders or uploads when navigating a previous set.

The root problem of this was the selector `selectCurrentOrders`, which was returning the same order data no matter what params you had on a page. This was replaced with `selectOrdersForLoggedInUser` and then the component variables found the right `order` using the `:orderId`.

This called for the use of React's hook of `useParams()`, but in order to do that previous class components had to be refactored into functional components. Once that was complete, I was able to update the routes for the customer to use `:orderId` for the Order & Upload components.

In addition to this, it was discovered that when deleting an upload the backend was picking the first result of the query which was not always accurate. I was able to create a new function and update `swagger-def` and `internalApi.js` to take in the `orderId` which allowed for filtering of the correct `move` that the upload belonged to.

Overall, this BL item has some major infrastructure changes of how orders and uploads are added, updated, uploaded, and deleted. Please review with the most highest scrutiny and try to cover all use cases prior to approving. This is not a simple "read the changed code" and stamp a "LGTM" on the PR. I would like to have all members of Mountain Movers review and approve this prior to merging.

In summary, this PR does the following:
- updates `swagger-def` and `internalApi.js` to take in an `orderId` value to use when filtering multiple returns from a db query
- added `AddOrders.jsx` component that handles creating an order, redirects the user to `UploadOrders.jsx` when order is created and uses the `:orderId` to append to the path
- updated all order routes to use `:orderId` as a parameter
- refactored `Orders.jsx` & `UploadOrders.jsx` to be a functional components and allow for use of `useParams()`
- updated routes of `MoveHome.jsx` and `Home.jsx` (really this is called `index.jsx`) to append `:orderId` to navigation routes to order components
- updated relevant navigation links where appropriate to use params
- updates `Review.jsx` and `SelectShipmentType.jsx` to use appropriate params using dynamic rendering instead of most recent move selector
- updates `Summary.jsx` to use the appropriate data from `serviceMemberMoves` instead of the most recent object in the `orders` object in state
- updates `Review.jsx` to handle the appropriate shipment deletion and update state to reflect changes
- added logic in `getAllMoves` handler to exclude deleted shipments
- updated `CreateOrEditMtoShipment.jsx` component to use `serviceMemberMoves` and filtering out shipment `id` from `selectors.js` to ensure data loads and information is correct on the screen
- added payload convertor to include `closeoutOffice` for shipments to be used in shipment cards

### How to test
*** MAKE SURE TO ALSO TEST WITH MM FEATURE FLAG TURNED OFF ***

1. Access MM as a customer
2. When navigated to the multi move dashboard, click `Create a Move`
3. This should navigate you to the add orders form (`/orders/add`)
4. Add info and create your orders
5. This should navigate you to the upload orders form (`/orders/upload/:orderId`)
6. Upload your orders (or not)
7. If you did not upload orders, ensure that the `Add Orders` button on the move home page takes you there when clicked
8. Once orders are uploaded, you should see an `Edit` button - click that sucker
9. This takes you to `EditOrders.jsx` and should see the params (`/orders/edit/:orderId`)
10. Make changes, add/delete uploads and make sure the data changes and persists
11. Set up some shipments in order to get to the amended orders screen
12. Upload some amended documents and ensure they change and data persists on addition/deletion

If you run into any issues (tons of async problems that could happen, but I think I handled most of the early return of the `LoadingPlaceholder` as data loads), throw a comment and I'll look into it.

### CODE REVIEW

**Review by cameroncaci — CHANGES_REQUESTED** [review]
Creating a shipment on a previous move ends up placing it on the "current" move.
Requirements: `multi_move enabled`

Playwright codegen:

```
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://milmovelocal:3000/');
  await page.goto('http://milmovelocal:3000/sign-in');
  await page.getByTestId('devlocal-signin').click();
  await page.getByRole('button', { name: 'Create a New milmove User' }).click();
  await page.getByText('CONUSStarts and ends in the continental US').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByTestId('dropdown').selectOption('ARMY');
  await page.getByTestId('textInput').click();
  await page.getByTestId('textInput').fill('1234567890');
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('First name').click();
  await page.getByLabel('First name').fill('Cameron');
  await page.getByLabel('First name').press('Tab');
  await page.getByLabel('Middle nameOptional').press('Tab');
  await page.getByLabel('Last name').fill('Jewell');
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Best contact phone').click();
  await page.getByLabel('Best contact phone').fill('555-555-5555');
  await page.getByText('Email', { exact: true }).click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Address 1').click();
  await page.getByLabel('Address 1').fill('Macdill');
  await page.getByLabel('Address 1').press('Tab');
  await page.getByLabel('Address 2Optional').press('Tab');
  await page.getByLabel('Address 3Optional').press('Tab');
  await page.getByLabel('City').fill('Tampa');
  await page.getByTestId('dropdown').selectOption('FL');
  await page.getByLabel('ZIP').fill('3');
  await page.getByLabel('ZIP').click();
  await page.getByLabel('ZIP').fill('33608');
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Address 1').click();
  await page.getByLabel('Address 1').fill('Address');
  await page.getByTestId('fieldset').locator('div').filter({ hasText: 'State- Select -ALAKARAZCACOCTDCDEFLGAHIIAIDILINKSKYLAMAMDMEMIMNMOMSMTNCNDNENHNJN' }).nth(1).click();
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('Tampa');
  await page.getByTestId('dropdown').selectOption('FL');
  await page.getByLabel('ZIP').click();
  await page.getByLabel('ZIP').fill('33680');
  await page.getByTestId('wizardNextButton').click();
  await page.getByTestId('formGroup').first().click();
  await page.getByLabel('Name').fill('Backup');
  await page.getByLabel('Name').press('Tab');
  await page.getByLabel('Email').fill('dummy@dummy.com');
  await page.getByLabel('Email').press('Tab');
  await page.getByLabel('Phone').fill('555-555-5555');
  await page.getByTestId('wizardNextButton').click();
  await page.getByTestId('createMoveBtn').click();
  await page.getByLabel('Orders type').selectOption('PERMANENT_CHANGE_OF_STATION');
  await page.getByLabel('Orders date').click();
  await page.getByLabel('Mon Feb 12 2024').click();
  await page.getByLabel('Report by date').click();
  await page.getByLabel('Tue Feb 13 2024').click();
  await page.getByTestId('form').getByText('No').click();
  await page.locator('#react-select-2-placeholder').click();
  await page.getByLabel('Current duty location').fill('macdill');
  await page.getByText('MacDill', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Start typing a duty location\.\.\.$/ }).nth(3).click();
  await page.getByLabel('New duty location').fill('patrick');
  await page.getByText('Patrick SFB, FL 32925').click();
  await page.getByLabel('Pay grade').selectOption('E_4');
  await page.getByText('BackNext').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByText('click to upload orders').click();
  await page.getByLabel('Drag & drop or click to upload orders').setInputFiles('Screenshot 2024-02-27 at 1.31.56 PM.png');
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Home').click();
  await page.getByTestId('createMoveBtn').click();
  await page.getByLabel('Orders type').selectOption('PERMANENT_CHANGE_OF_STATION');
  await page.getByLabel('Orders date').click();
  await page.getByLabel('Wed Feb 28 2024').click();
  await page.getByLabel('Report by date').click();
  await page.getByLabel('Next Month').click();
  await page.getByLabel('Mon Mar 04 2024').click();
  await page.getByTestId('form').getByText('No').click();
  await page.locator('.css-ndqrim-control').first().click();
  await page.getByLabel('Current duty location').fill('macdill');
  await page.getByText('MacDill AFB, FL 33608').click();
  await page.getByText('Start typing a duty location...').click();
  await page.getByLabel('New duty location').fill('patrick');
  await page.locator('#react-select-3-option-1').click();
  await page.getByLabel('Pay grade').selectOption('E_5');
  await page.getByTestId('wizardNextButton').click();
  await page.getByText('click to upload orders').click();
  await page.getByLabel('Drag & drop or click to upload orders').setInputFiles('Screenshot 2024-02-27 at 8.06.05 AM.png');
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Home').click();
  await page.getByTestId('prevMovesContainer').getByTestId('goToMoveBtn').click();
  await page.getByTestId('shipment-selection-btn').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByText('Movers pack and ship it, paid by the government (HHG)All your personal property ').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('Preferred pickup date').click();
  await page.getByLabel('Mon Feb 19 2024').click();
  await page.getByText('Use my current address').click();
  await page.getByLabel('Preferred delivery date').click();
  await page.getByLabel('Wed Feb 21 2024').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByTestId('wizardNextButton').click();
  await page.getByLabel('SIGNATURE').click();
  await page.getByLabel('SIGNATURE').fill('Signature');
  await page.getByTestId('wizardCompleteButton').click();
  await page.getByTestId('currentMoveContainer').getByTestId('goToMoveBtn').click();
  await page.getByLabel('Home').click();
  await page.getByTestId('prevMovesContainer').getByTestId('goToMoveBtn').click();
});
```

image

**Comment by cameroncaci** [comment]
Then, even more interesting, after creating a shipment on the second move places the shipment under the first move - when I create a "new" shipment under the old move, it only lets me create a PPM

image

**Comment by danieljordan-caci** [comment]
> Creating a shipment on a previous move ends up placing it on the "current" move. Requirements: `multi_move enabled`
> 
> Playwright codegen:
> 
> ```
> import { test, expect } from '@playwright/test';
> 
> test('test', async ({ page }) => {
>   await page.goto('http://milmovelocal:3000/');
>   await page.goto('http://milmovelocal:3000/sign-in');
>   await page.getByTestId('devlocal-signin').click();
>   await page.getByRole('button', { name: 'Create a New milmove User' }).click();
>   await page.getByText('CONUSStarts and ends in the continental US').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByTestId('dropdown').selectOption('ARMY');
>   await page.getByTestId('textInput').click();
>   await page.getByTestId('textInput').fill('1234567890');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('First name').click();
>   await page.getByLabel('First name').fill('Cameron');
>   await page.getByLabel('First name').press('Tab');
>   await page.getByLabel('Middle nameOptional').press('Tab');
>   await page.getByLabel('Last name').fill('Jewell');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Best contact phone').click();
>   await page.getByLabel('Best contact phone').fill('555-555-5555');
>   await page.getByText('Email', { exact: true }).click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Address 1').click();
>   await page.getByLabel('Address 1').fill('Macdill');
>   await page.getByLabel('Address 1').press('Tab');
>   await page.getByLabel('Address 2Optional').press('Tab');
>   await page.getByLabel('Address 3Optional').press('Tab');
>   await page.getByLabel('City').fill('Tampa');
>   await page.getByTestId('dropdown').selectOption('FL');
>   await page.getByLabel('ZIP').fill('3');
>   await page.getByLabel('ZIP').click();
>   await page.getByLabel('ZIP').fill('33608');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Address 1').click();
>   await page.getByLabel('Address 1').fill('Address');
>   await page.getByTestId('fieldset').locator('div').filter({ hasText: 'State- Select -ALAKARAZCACOCTDCDEFLGAHIIAIDILINKSKYLAMAMDMEMIMNMOMSMTNCNDNENHNJN' }).nth(1).click();
>   await page.getByLabel('City').click();
>   await page.getByLabel('City').fill('Tampa');
>   await page.getByTestId('dropdown').selectOption('FL');
>   await page.getByLabel('ZIP').click();
>   await page.getByLabel('ZIP').fill('33680');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByTestId('formGroup').first().click();
>   await page.getByLabel('Name').fill('Backup');
>   await page.getByLabel('Name').press('Tab');
>   await page.getByLabel('Email').fill('dummy@dummy.com');
>   await page.getByLabel('Email').press('Tab');
>   await page.getByLabel('Phone').fill('555-555-5555');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByTestId('createMoveBtn').click();
>   await page.getByLabel('Orders type').selectOption('PERMANENT_CHANGE_OF_STATION');
>   await page.getByLabel('Orders date').click();
>   await page.getByLabel('Mon Feb 12 2024').click();
>   await page.getByLabel('Report by date').click();
>   await page.getByLabel('Tue Feb 13 2024').click();
>   await page.getByTestId('form').getByText('No').click();
>   await page.locator('#react-select-2-placeholder').click();
>   await page.getByLabel('Current duty location').fill('macdill');
>   await page.getByText('MacDill', { exact: true }).click();
>   await page.locator('div').filter({ hasText: /^Start typing a duty location\.\.\.$/ }).nth(3).click();
>   await page.getByLabel('New duty location').fill('patrick');
>   await page.getByText('Patrick SFB, FL 32925').click();
>   await page.getByLabel('Pay grade').selectOption('E_4');
>   await page.getByText('BackNext').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByText('click to upload orders').click();
>   await page.getByLabel('Drag & drop or click to upload orders').setInputFiles('Screenshot 2024-02-27 at 1.31.56 PM.png');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Home').click();
>   await page.getByTestId('createMoveBtn').click();
>   await page.getByLabel('Orders type').selectOption('PERMANENT_CHANGE_OF_STATION');
>   await page.getByLabel('Orders date').click();
>   await page.getByLabel('Wed Feb 28 2024').click();
>   await page.getByLabel('Report by date').click();
>   await page.getByLabel('Next Month').click();
>   await page.getByLabel('Mon Mar 04 2024').click();
>   await page.getByTestId('form').getByText('No').click();
>   await page.locator('.css-ndqrim-control').first().click();
>   await page.getByLabel('Current duty location').fill('macdill');
>   await page.getByText('MacDill AFB, FL 33608').click();
>   await page.getByText('Start typing a duty location...').click();
>   await page.getByLabel('New duty location').fill('patrick');
>   await page.locator('#react-select-3-option-1').click();
>   await page.getByLabel('Pay grade').selectOption('E_5');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByText('click to upload orders').click();
>   await page.getByLabel('Drag & drop or click to upload orders').setInputFiles('Screenshot 2024-02-27 at 8.06.05 AM.png');
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Home').click();
>   await page.getByTestId('prevMovesContainer').getByTestId('goToMoveBtn').click();
>   await page.getByTestId('shipment-selection-btn').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByText('Movers pack and ship it, paid by the government (HHG)All your personal property ').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('Preferred pickup date').click();
>   await page.getByLabel('Mon Feb 19 2024').click();
>   await page.getByText('Use my current address').click();
>   await page.getByLabel('Preferred delivery date').click();
>   await page.getByLabel('Wed Feb 21 2024').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByTestId('wizardNextButton').click();
>   await page.getByLabel('SIGNATURE').click();
>   await page.getByLabel('SIGNATURE').fill('Signature');
>   await page.getByTestId('wizardCompleteButton').click();
>   await page.getByTestId('currentMoveContainer').getByTestId('goToMoveBtn').click();
>   await page.getByLabel('Home').click();
>   await page.getByTestId('prevMovesContainer').getByTestId('goToMoveBtn').click();
> });
> ```
> 
> image
> 
> Additionally, the first move's page goes wonky:
> 
> image
> 
> Then, even more interesting, after creating a shipment on the second move places the shipment under the first move - when I create a "new" shipment under the old move, it only lets me create a PPM
> 
> image

Try and recreate this with the most recent push and let me know if it fixes it. Nice find.

**Review by traskowskycaci — COMMENTED** [review]
At the orders upload step, I can't delete the orders - clicking Delete just gives me a blue outlined box and nothing happens. That blue outline persists until I click somewhere else on the page:
image

**Comment by danieljordan-caci** [comment]
> At the orders upload step, I can't delete the orders - clicking Delete just gives me a blue outlined box and nothing happens. That blue outline persists until I click somewhere else on the page: image

are you getting any console log errors?

**Comment by loganwc** [comment]
> At the orders upload step, I can't delete the orders - clicking Delete just gives me a blue outlined box and nothing happens. That blue outline persists until I click somewhere else on the page: image

this is a known issue, we're waiting on a BL item to be created to work it. You can comment pkg/handlers/internalapi/uploads.go:122 to temporarily fix it

**Review by traskowskycaci — COMMENTED** [review]
You mentioned that once orders are uploaded, we should see an edit button. Is that on the upload page? If so, I don't see it. I can view the move/ page and then click Edit next to the Orders uploaded, and that routes me to moveid/review/edit-orders.

**Comment by danieljordan-caci** [comment]
> > At the orders upload step, I can't delete the orders - clicking Delete just gives me a blue outlined box and nothing happens. That blue outline persists until I click somewhere else on the page: image
> 
> this is a known issue, we're waiting on a BL item to be created to work it. You can comment pkg/handlers/internalapi/uploads.go:122 to temporarily fix it

@loganwc check the "Files Changed" section here. I did realize that when deleting an upload, it was getting multiple returns from the sql query so I did add in the `orderId` in order to filter out only one result.

**Comment by danieljordan-caci** [comment]
> > > At the orders upload step, I can't delete the orders - clicking Delete just gives me a blue outlined box and nothing happens. That blue outline persists until I click somewhere else on the page: image
> > 
> > 
> > this is a known issue, we're waiting on a BL item to be created to work it. You can comment pkg/handlers/internalapi/uploads.go:122 to temporarily fix it
> 
> @loganwc check the "Files Changed" section here. I did realize that when deleting an upload, it was getting multiple returns from the sql query so I did add in the `orderId` in order to filter out only one result.

Yeah that's correct. You'll see the `Edit` button on the move home page on the orders step.

**Review by traskowskycaci — COMMENTED** [review]
Added a couple shipments -> Review and Submit button -> "Review your details" page -> Edit button next to Orders table gives me a 404. No console or server errors

**Comment by danieljordan-caci** [comment]
> Added a couple shipments -> Review and Submit button -> "Review your details" page -> Edit button next to Orders table gives me a 404. No console or server errors

Yup. Found another component to update. Sheesh. Thanks.

**Comment by danieljordan-caci** [comment]
> Added a couple shipments -> Review and Submit button -> "Review your details" page -> Edit button next to Orders table gives me a 404. No console or server errors

This should be fixed now, but I did run into an issue when deleting shipments from that review screen so I'll be making some changes to show the right shipments on there. Right now when you delete a shipment it doesn't get deleted but does get removed from state. Weird.

**Comment by traskowskycaci** [comment]
> > Added a couple shipments -> Review and Submit button -> "Review your details" page -> Edit button next to Orders table gives me a 404. No console or server errors
> 
> This should be fixed now, but I did run into an issue when deleting shipments from that review screen so I'll be making some changes to show the right shipments on there. Right now when you delete a shipment it doesn't get deleted but does get removed from state. Weird.

Looks good other than the shipments issue you mentioned!

**Review by cameroncaci — CHANGES_REQUESTED** [review]
Create 2 different moves. Upload orders for each but set the first one to have a pay grade of E-4 and then the second one to have a pay grade of E-9. Afterwards, go to the "Review your details" portion of each move, both will state E-9 instead of one E-4 and the other E-9.

**Comment by danieljordan-caci** [comment]
> Create 2 different moves. Upload orders for each but set the first one to have a pay grade of E-4 and then the second one to have a pay grade of E-9. Afterwards, go to the "Review your details" portion of each move, both will state E-9 instead of one E-4 and the other E-9. The DB will accurately reflect the pay grades, but the frontend will not.

Nice find. I have discovered this component that I missed using the wrong things in state. `Review.jsx` and `Summary.jsx` if you want to curse them for me that'd be great.

**Comment by danieljordan-caci** [comment]
> Create 2 different moves. Upload orders for each but set the first one to have a pay grade of E-4 and then the second one to have a pay grade of E-9. Afterwards, go to the "Review your details" portion of each move, both will state E-9 instead of one E-4 and the other E-9. The DB will accurately reflect the pay grades, but the frontend will not.

This should be fixed. I do need to fix and update some tests, but wanted to get the functionality out for you to test again.

**Comment by danieljordan-caci** [comment]
> > This should be fixed now, but I did run into an issue when deleting shipments from that review screen so I'll be making some changes to show the right shipments on there. Right now when you delete a shipment it doesn't get deleted but does get removed from state. Weird.
> 
> When I delete a shipment from either the review page or the move/moveId page, they are no longer shown in the UI but I still see them in the database.

Yup. It's called a "soft delete". You should see a value in the `deleted_at` column.

**Comment by traskowskycaci** [comment]
> Yup. It's called a "soft delete". You should see a value in the `deleted_at` column.

Indeed I do. Alright if that's expected behavior then disregard!

**Comment by danieljordan-caci** [comment]
> > Yup. It's called a "soft delete". You should see a value in the `deleted_at` column.
> 
> Indeed I do. Alright if that's expected behavior then disregard!

Yup. I had the same thought when trying to delete things because I would delete them but they would still show up on refresh! So I discovered there was a value in the `deleted_at` column, but the endpoint we use to get all of the moves was not considering that. A fix for that is also in this PR.

**Comment by traskowskycaci** [comment]
> Yup. I had the same thought when trying to delete things because I would delete them but they would still show up on refresh! So I discovered there was a value in the `deleted_at` column, but the endpoint we use to get all of the moves was not considering that. A fix for that is also in this PR.

Interesting. Might be to preserve the shipments for audit reasons or move history? Just didn't know we weren't actually deleting fully

**Review by traskowskycaci — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]
Tested, reviewed and ran through a few scenarios.

**Comment by cameroncaci** [comment]
image

Testing looks good. I only found this issue, but I pulled main and this is an already existing issue, not yours

**Review by cameroncaci — APPROVED** [review]

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
