### PR TITLE
B 21975 int

### PR DESCRIPTION
**Pull request by antgmann**
## Summary
This backlog was made to change a certain move history log that triggers when an update to an MTOShipment automatically updates an entitlement database table entry for the Max Billable Weight of that move. Previously, this was being labeled as "Updated allowance" and "Allowed weight", when in reality the allowance amount is not being updated, just the Max Billable Weight. As a result, the labels will be updated to read "Updated shipment" and "Max billable weight", respectively. The use case that uncovered this was when a prime updated the estimated weight for an HHG, increasing the max billable weight. This is the use case we will use for testing.

This backlog accomplishes this by using the same formatter used in updateBillableWeight.jsx to change the allowed weight value to be parsed by the history log correctly as max billable weight instead. It also updates the event name to "Updated shipment" instead of "Updated allowance".

Additionally, this has led me to think that the file could be better named and organized. Instead of putting it under allowances, I've renamed the file to follow the business process order of operations (update mtoShipment -> update allowance) and moved it under the updateMTOShipment directory instead. I think this meshes more nicely with the process it is trying to capture.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access the application as a new service member
2. Create your information, create a new move, include one or two HHG shipments.
3. Log in as an SC, approve the move you made in step 2.
4. Log in as TOO, send the above move to prime.
5. Log in as a prime, navigate to move.
6. Set pickup dates to the same day of testing, and delivery date in the future. Set estimated and actual weight to valid values.
7. Successfully save your changes.
8. Swap back to TOO, navigate to this move, view the move history tab. 
9. Find the entry with labels "Updated shipment" and "Max billable weight" that reflects your changed values.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image

ANDI is passing as this only changes content of existing components
image

### CODE REVIEW

**Review by ajlusk — COMMENTED** [review]
Screenshot 2024-12-10 at 6 04 04 PM
Testing instructions worked as described. When I deviated from them by adding an HHG as prime including both weights, then approving that shipment as a TOO I encountered a move history record that looks quite similar to what you are replacing in this PR. 

Is this expected? Should the language there be updated too?

Digging into the network tab, it looks like both history records are for changes to "authorized_weight" just one has the new language and one doesn't.

**Comment by brianmanley-caci** [comment]
I tested with the steps you outlined, and it did work correctly.

Screenshot 2024-12-10 at 5 05 20 PM

**Comment by antgmann** [comment]
> Screenshot 2024-12-10 at 6 04 04 PM Testing instructions worked as described. When I deviated from them by adding an HHG as prime including both weights, then approving that shipment as a TOO I encountered a move history record that looks quite similar to what you are replacing in this PR.
> Is this expected? Should the language there be updated too?
> 
> Digging into the network tab, it looks like both history records are for changes to "authorized_weight" just one has the new language and one doesn't.

Thanks for finding this. This log is being called from the approveShipmentUpdateAllowances.jsx move history log, as the call is resulting from approving an MTOShipment rather than updating it. It's not specifically asked for to be changed, so we could skip it to avoid changing any use cases that this shouldn't apply to. 

However, based on the conversations I had with the PO, it's likely they do want the changes to cover this scenario. There's a few reasons for that such as its close proximity to the use case of the change requested, the similar nature of the actions taken, and the location of that file being in the approveShipment directory rather than the updateAllowances directory. Making the change here would bring it in line with how I wanted to have things more organized as well. 

So with all of that said, I think I'm siding with making the change here. Will have that pushed up shortly.

**Comment by antgmann** [comment]
Considering consolidating the formatters added that match across these files after discussing with @ajlusk

**Review by ajlusk — APPROVED** [review]
Language is updated in both scenarios (note this was triggered by the TOO, not the prime). Code changes look good.

Screenshot 2024-12-11 at 2 18 36 PM

**Review by danieljordan-caci — APPROVED** [review]
Solid work. Don't got nothin'! LGTM.

**Pull request merged**
