### PR TITLE
B 18031 prime UI update sit service items

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

In order to simulate the prime using the `PATCH` endpoint `updateMTOServiceItem`, we needed to allow for this functionality in the prime simulator to allow for ease of testing. At this time this functionality is only allowed for SIT service items that have the service codes:
- `DOFSIT`
- `DOASIT`
- `DOPSIT`
- `DDDSIT`

The values that can be updated:
- `sitDepartureDate`
- `sitRequestedDelivery`
- `sitCustomerContacted`
- `sitDestinationFinalAddress` (destination SIT items only)

The following was completed in this PR:
- improved UI at first glance when viewing service items to display service code + service item name
- added new path to handle displaying new forms/components
- created components for destination and origin SIT service items, as well as a parent component that holds logic on displaying the respective components depending on the service item's `reServiceCode`
- updated `swagger-def` & `model_to_payload.go` for origin SIT service items to send the values that were requested to be updated so they can populate in the UI
- created test files for newly created components, updated existing tests that were impacted with new changes
- added `updateMTOServiceItem` to `primeApi.js` so it can be used in the components (was not previously implemented)
- updated button that requested update for final address from `Update Service Items` to `Request Destination SIT Address Change` to improve clarify of button function

*NOTE*
When updating the final destination address for a destination SIT service item, if an existing address is populated in the form then it will NOT be updated if new values are put in. If the service item does not have a final destination address yet, then it will update accordingly. 
This is backend work and is out of scope of this PR - will be addressed at a later date.

### How to test

1. Fire up `officelocal:3000`
2. Login as a the prime simulator
3. Click on a move with service items
4. Scroll down and you'll see an "Edit" button next to SIT service items that can be edited
5. Depending on if it's origin or destination SIT, the respective component will render
6. Fill out the form with the values and submit
7. The service item should be updated in the db, pending no errors

## Screenshots
Screenshot 2023-12-11 at 10 24 06 AM

Screenshot 2023-12-12 at 11 20 58 AM

Screenshot 2023-12-11 at 10 49 34 AM

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Tried to update a destination service item (DDDSIT) and am getting an error that I can't update the SITDestinationFinalAddress. Initially I was trying it with one in 'Approved' so I rejected it and tried again - same error. User error on my part? 
image

image

**Comment by danieljordan-caci** [comment]
> Tried to update a destination service item (DDDSIT) and am getting an error that I can't update the SITDestinationFinalAddress. Initially I was trying it with one in 'Approved' so I rejected it and tried again - same error. User error on my part? image
> 
> image

This is backend work that probably needs to be addressed, but I believe it is out of scope of this PR specifically. If you're getting errors returned from the API then it is successfully calling the respective endpoint and I believe that satisfies the AC of this BL item. That make sense? There's def some backend work that needs to be done because you're correct, there are some fields they are wanting us to update in the prime sim, but can't be updated in the backend as of right now.

Do you happen to know what the invalid input was in that specific call?

**Comment by traskowskycaci** [comment]
> > Tried to update a destination service item (DDDSIT) and am getting an error that I can't update the SITDestinationFinalAddress. Initially I was trying it with one in 'Approved' so I rejected it and tried again - same error. User error on my part? image
> > image
> 
> This is backend work that probably needs to be addressed, but I believe it is out of scope of this PR specifically. If you're getting errors returned from the API then it is successfully calling the respective endpoint and I believe that satisfies the AC of this BL item. That make sense? There's def some backend work that needs to be done because you're correct, there are some fields they are wanting us to update in the prime sim, but can't be updated in the backend as of right now.
> 
> Do you happen to know what the invalid input was in that specific call?

This isn't exactly the input but very close. The address info would've been the same
image

**Comment by danieljordan-caci** [comment]
> Tried to update a destination service item (DDDSIT) and am getting an error that I can't update the SITDestinationFinalAddress. Initially I was trying it with one in 'Approved' so I rejected it and tried again - same error. User error on my part? image
> 
> image

Like there's this block of code in `/pkg/services/mto_service_item/mto_service_item_validators.go`:
```
// checkSITDestinationFinalAddress checks that SITDestinationFinalAddress isn't being changed
func (v *updateMTOServiceItemData) checkSITDestinationFinalAddress(_ appcontext.AppContext) error {
	if v.updatedServiceItem.SITDestinationFinalAddress == nil {
		return nil // SITDestinationFinalAddress isn't being updated, so we're fine here
	}

	if v.oldServiceItem.SITDestinationFinalAddressID == nil {
		return nil // the SITDestinationFinalAddress is being created, so we're fine here
	}

	if v.oldServiceItem.ReService.Code != models.ReServiceCodeDDDSIT {
		return apperror.NewConflictError(v.updatedServiceItem.ID,
			fmt.Sprintf("- SIT Destination Final Address may only be manually created for %s service items.", models.ReServiceCodeDDDSIT))
	}

	if *v.oldServiceItem.SITDestinationFinalAddressID != uuid.Nil &&
		v.updatedServiceItem.SITDestinationFinalAddress != nil &&
		v.updatedServiceItem.SITDestinationFinalAddress.ID != *v.oldServiceItem.SITDestinationFinalAddressID {
		v.verrs.Add("SITDestinationFinalAddress", "cannot be updated")
	}

	return nil
}
```

It's probably hitting this validator.

**Comment by traskowskycaci** [comment]
> Like there's this block of code in `/pkg/services/mto_service_item/mto_service_item_validators.go`:
> 
> ```
> // checkSITDestinationFinalAddress checks that SITDestinationFinalAddress isn't being changed
> func (v *updateMTOServiceItemData) checkSITDestinationFinalAddress(_ appcontext.AppContext) error {
> 	if v.updatedServiceItem.SITDestinationFinalAddress == nil {
> 		return nil // SITDestinationFinalAddress isn't being updated, so we're fine here
> 	}
> 
> 	if v.oldServiceItem.SITDestinationFinalAddressID == nil {
> 		return nil // the SITDestinationFinalAddress is being created, so we're fine here
> 	}
> 
> 	if v.oldServiceItem.ReService.Code != models.ReServiceCodeDDDSIT {
> 		return apperror.NewConflictError(v.updatedServiceItem.ID,
> 			fmt.Sprintf("- SIT Destination Final Address may only be manually created for %s service items.", models.ReServiceCodeDDDSIT))
> 	}
> 
> 	if *v.oldServiceItem.SITDestinationFinalAddressID != uuid.Nil &&
> 		v.updatedServiceItem.SITDestinationFinalAddress != nil &&
> 		v.updatedServiceItem.SITDestinationFinalAddress.ID != *v.oldServiceItem.SITDestinationFinalAddressID {
> 		v.verrs.Add("SITDestinationFinalAddress", "cannot be updated")
> 	}
> 
> 	return nil
> }
> ```
> 
> It's probably hitting this validator.

Ok. Also getting a validation error when trying to update a DOFSIT - "reServiceCode in body should be one of [DDDSIT DOPSIT]. Are fixes for either of these errors in scope for this story or nah?

**Comment by danieljordan-caci** [comment]
> > > Tried to update a destination service item (DDDSIT) and am getting an error that I can't update the SITDestinationFinalAddress. Initially I was trying it with one in 'Approved' so I rejected it and tried again - same error. User error on my part? image
> > > image
> > 
> > 
> > This is backend work that probably needs to be addressed, but I believe it is out of scope of this PR specifically. If you're getting errors returned from the API then it is successfully calling the respective endpoint and I believe that satisfies the AC of this BL item. That make sense? There's def some backend work that needs to be done because you're correct, there are some fields they are wanting us to update in the prime sim, but can't be updated in the backend as of right now.
> > Do you happen to know what the invalid input was in that specific call?
> 
> This isn't exactly the input but very close. The address info would've been the same image

Looks like I needed to pass the id of the destination final address into the body - should be fixed now.

**Review by traskowskycaci — COMMENTED** [review]
Origin SIT Update looks good for SIT departure date and SIT requested delivery. SIT Customer Contacted didn't get updated in the database.

Destination SIT Updates looks good for SIT departure date, SIT requested delivery, and SIT customer contacted. However, the address changes I made didn't seem to populate in the database for the DDDSIT service item.

**Comment by danieljordan-caci** [comment]
> Origin SIT Update looks good for SIT departure date and SIT requested delivery. SIT Customer Contacted didn't get updated in the database on an update.
> 
> Destination SIT Updates looks good for SIT departure date, SIT requested delivery, and SIT customer contacted. However, the address changes I made didn't seem to populate in the database for the DDDSIT service item.

most recent push should fix the customer contacted issue. It was not being considered for origin SIT service items and only destination SIT service items.

I'll look into the address not being updated.

**Comment by traskowskycaci** [comment]
> Origin SIT Update looks good for SIT departure date and SIT requested delivery. SIT Customer Contacted didn't get updated in the database.
> 
> Destination SIT Updates looks good for SIT departure date, SIT requested delivery, and SIT customer contacted. However, the address changes I made didn't seem to populate in the database for the DDDSIT service item.

Origin SIT Update looks good for all three values!

**Comment by danieljordan-caci** [comment]
> Origin SIT Update looks good for SIT departure date and SIT requested delivery. SIT Customer Contacted didn't get updated in the database.
> 
> Destination SIT Updates looks good for SIT departure date, SIT requested delivery, and SIT customer contacted. However, the address changes I made didn't seem to populate in the database for the DDDSIT service item.

Looked into this.

Right now the prime can only create a new final destination address and not edit an existing one. 

This is backend work and if the gov wants the prime to be able to **EDIT** an existing address through this endpoint, then we will address it in a later PR.

**Comment by traskowskycaci** [comment]
> > Origin SIT Update looks good for SIT departure date and SIT requested delivery. SIT Customer Contacted didn't get updated in the database.
> > Destination SIT Updates looks good for SIT departure date, SIT requested delivery, and SIT customer contacted. However, the address changes I made didn't seem to populate in the database for the DDDSIT service item.
> 
> Looked into this.
> 
> Right now the prime can only create a new final destination address and not edit an existing one.
> 
> This is backend work and if the gov wants the prime to be able to **EDIT** an existing address through this endpoint, then we will address it in a later PR.

I agree that would be a separate BL item and PR. Approving since all my concerns have been addressed! Will also approve Happo checks, no issues there.

**Review by traskowskycaci — APPROVED** [review]

**Comment by danieljordan-caci** [comment]
Following conversation with Dan Schuster this morning, he does not want the destination address to be updated via the `updateMTOServiceItem` endpoint so that was removed, description was updated, and new code has been changed to reflect that and pushed.

**Review by traskowskycaci — APPROVED** [review]
Looks good!

**Review by TevinAdams — APPROVED** [review]
Tested and was able to update the 3 serviceItems via prime sim. Also reviewed the code.

**Pull request merged**
