### PR TITLE
[MB-3635] Proof of Service Document Viewer Integration

### PR DESCRIPTION
**Pull request by duncan-truss**
## Description

This PR makes it possible to load prime uploaded proof of service documents (pdf, jpg, png) associated with a payment request that can be reviewed by the TIO office user.

Changes include:
- Modifying the GHC api for the payment request response to include the Proof of Service Docs property
- Updating the payment request fetcher and model payloads to query and format the response json and exclude deleted uploads
- Updates the PaymentRequestReview component to unpack the uploaded files in the response and load them in the document viewer
- Display a file not found placeholder for Payment Requests without a proof of service document
- Truncates long filenames in doc viewer menu and titlebar that included path to only display the name itself
- Updates e2e test data to populate multiple prime uploads for one of the payment requests.

## Reviewer Notes

We had some questions for A-team around if there would really be multiple uploads associated with a proof of service doc model.  The prime api seems to always create a new proof of service doc when adding an upload to a payment request.  In the testdatagen though we can handle this case if it ever occurs.  So that's something where the functionality doesn't match the data models at the moment.

Soft deletes also don't seem to be possible to simulate outside of testdata but we are now excluding those uploads from the database query.

## Setup

```sh
make db_dev_e2e_populate
make server_run
make office_client_run
```

1. Login as the TIO user
2. Click on the first payment request in the queue
3. The document viewer should display a test pdf, the first of 3 prime uploads for the payment request.
4. You should be able to open the document menu and switch to the jpg and png test files as well.
5. Navigate back to the TIO homepage and select the second payment request in the list
6. This payment request has no associated uploads so a File Not Found message should be displayed.

Using the Prime API Client:
```
make run_prime_docker
rm -f bin/prime-api-client && make bin/prime-api-client
prime-api-client --insecure create-upload --filename pkg/testdatagen/testdata/test.png --paymentRequestID a2c34dba-015f-4f96-a38b-0c0b9272e208
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3635) for this change

## Screenshots

officelocal_3000_moves_MOVE_CODE_payment-requests_a2c34dba-015f-4f96-a38b-0c0b9272e208(Laptop with HiDPI screen)
officelocal_3000_moves_MOVE_CODE_payment-requests_a2c34dba-015f-4f96-a38b-0c0b9272e208(Laptop with HiDPI screen) (1)
officelocal_3000_moves_MOVE_CODE_payment-requests_a2c34dba-015f-4f96-a38b-0c0b9272e208(Laptop with HiDPI screen) (2)
Screen Shot 2020-09-17 at 17 25 31

### CODE REVIEW

**Review by Ryan-Koch — CHANGES_REQUESTED** [review]
This is looking really good! The one thing I noticed though is that on chrome and IE11 the document file name text is rendering when the menu isn't expanded for it. Like so 
image

This isn't happening in firefox, so it's likely some sort of cross browser compatibility thing going on with how that's coming out. Happy to pair and explore that with y'all if help is needed.

**Comment by duncan-truss** [comment]
> This is looking really good! The one thing I noticed though is that on chrome and IE11 the document file name text is rendering when the menu isn't expanded for it. Like so
> image
> 
> This isn't happening in firefox, so it's likely some sort of cross browser compatibility thing going on with how that's coming out. Happy to pair and explore that with y'all if help is needed.
> 
> Related to that, it looks like the text overflows the bounds in those browsers also (perhaps the two things are related?)
> image

@Ryan-Koch Thanks I had been testing in Firefox exclusively so wasn't seeing this.  I think this is an issue going back to the orders document viewer work.  I'll investigate, I think it's a combination of local files including the full path in the name and then the styling inconsistencies too.

**Review by Ryan-Koch — APPROVED** [review]
Looks like that push took care of the overflow thing. Nice work! Was able to verify on both chrome and IE 11.

**Comment by duncan-truss** [comment]
> @Ryan-Koch @duncan-truss oh I noticed that the other day also and created a bug ticket for it! https://dp3.atlassian.net/browse/MB-4198

Oh nice, sorry just pushed up changes for setting overflow on the unordered list itself not the text-transform per item.  Could we still show the full filename as title or alt text on hover if we clip with ellipsis?

**Review by amanda5iu — APPROVED** [review]
This looks great - ship it!

**Review by suzubara — COMMENTED** [review]
I don’t love the `filenameFromPath` situation.. ideally the filename property returned by the API is already what should be displayed, but if that’s not possible then I think it would be better for the formatting to happen _before_ passing the file array into the `DocumentViewer` component. IMO the DocumentViewer component should not be responsible for formatting filename, it should just render the string it is given.

**Comment by suzubara** [comment]
> > @Ryan-Koch @duncan-truss oh I noticed that the other day also and created a bug ticket for it! https://dp3.atlassian.net/browse/MB-4198
> 
> @suzubara Oh nice, sorry just pushed up changes for setting overflow on the unordered list itself not the text-transform per item. Could we still show the full filename as title or alt text on hover if we clip with ellipsis?

The fix you pushed is fine but won't resolve the bug ticket, so we should still keep that open. There will still be an overflow issue if the filename is one long string without spaces.

**Pull request merged**
