### PR TITLE
B 19017 int

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

Under Current & New Duty Station fields, add the zip code at the end of the name to match the rest of the list:

- PPPO West Point/ USMA - USA (GBLOC BGAC)
- PPPO USAG Miami - USA (GBLOC CLPK)

this script was already ran in staging/loadtest envs- this is just CM'img the code to ensure any rebaseline doenst lose the update

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Are they duty_location_id uuids the same across all envs?

**Comment by deandreJones** [comment]
> Are they duty_location_id uuids the same across all envs?

yes they are- i did a little research on this
UUIDs should be generated prior to inserting in a migration file- to ensure contunuity across envs
https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#writing-migrations

**Comment by traskowskycaci** [comment]
> UUIDs should be generated prior to inserting in a migration file- to ensure contunuity across envs

Sweet, that is good to hear.

**Review by traskowskycaci — APPROVED** [review]

**Review by danieljordan-caci — APPROVED** [review]
Thanks for adding tests! Looks SO good to me.

**Pull request merged**
