### PR TITLE
B 20915

### PR DESCRIPTION
**Pull request by deandreJones**
## [INT PRs](https://github.com/transcom/mymove/pull/13505)
##[INT PR](https://github.com/transcom/mymove/pull/13433)

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Any reason why your file counts are so different?

I see two different INT PRs that changed ~1,500 lines of code, but this one is changing 4k+?

**Comment by deandreJones** [comment]
> Any reason why your file counts are so different?
> 
> I see two different INT PRs that changed ~1,500 lines of code, but this one is changing 4k+?

confused on what you are saying?
since its db migration- each int pr would require a new migration file

**Review by traskowskycaci — COMMENTED** [review]
Is there a int PR/branch that contains your 20240816200315_update_pws_violations_pt2.up.sql migration to confirm that made it? I'm seeing the part 1 and part 2 for the int PRs

**Comment by deandreJones** [comment]
> Is there a int PR/branch that contains your 20240816200315_update_pws_violations_pt2.up.sql migration to confirm that made it? I'm seeing the part 1 and part 2 for the int PRs

https://github.com/transcom/mymove/commit/072980d98775d34336d7fe337297a73831bd9921


not sure what happened to the PR, but its in integration

**Review by traskowskycaci — APPROVED** [review]
Confirmed, all of this matches up in integrationTesting!

**Review by danieljordan-caci — APPROVED** [review]
Maria beat me to it. Commits match up - send it.

**Pull request merged**
