### PR TITLE
Remove backend uploader filesize limit

### PR DESCRIPTION
**Pull request by mkrump**
## Description

The uploader was causing generated pdfs exceeding 25MB to fail. The filesize check is mainly intended to prevent service members and office users from uploading very large files #2486 . It wasn't intended to block generated files. 

## Reviewer Notes

This is somewhat hard to verify, since you'd have to submit an upload without using the uploader on the front end. So I just changed our previous backend test to check for a successful upload of a file larger than 25mb.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_test
```

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/n/projects/2181745/stories/167945995) for this change

### CODE REVIEW

**Comment by mkrump** [comment]
> How do we enforce upload limits in the future? Are we not going to have a limit for uploads anymore?

The front end would still cover almost all cases. The exception would be someone uploading a file via the api and not going through the front end. Agree that it's better to have a check on the back end too, but probably need to discuss what that looks like (maybe exemptions certain file types, or callers, not exactly sure).

**Comment by chrisgilmerproj** [comment]
> > How do we enforce upload limits in the future? Are we not going to have a limit for uploads anymore?
> 
> The front end would still cover almost all cases. The exception would be someone uploading a file via the api and not going through the front end. Agree that it's better to have a check on the back end too, but probably need to discuss what that looks like (maybe exemptions certain file types, or callers, not exactly sure).

Thanks for the quick answer. Just as an aside, in load testing we use the API explicitly to test with. So there's no mitigation by the client for upload size. This change feels really dangerous to me honestly but I see how it unblocks a problem we're currently having. Would love it if you all would prioritize a backend solution soon. Infra is happy to help but we're not going to block this PR.

**Comment by mkrump** [comment]
> > > How do we enforce upload limits in the future? Are we not going to have a limit for uploads anymore?
> > 
> > 
> > The front end would still cover almost all cases. The exception would be someone uploading a file via the api and not going through the front end. Agree that it's better to have a check on the back end too, but probably need to discuss what that looks like (maybe exemptions certain file types, or callers, not exactly sure).
> 
> Thanks for the quick answer. Just as an aside, in load testing we use the API explicitly to test with. So there's no mitigation by the client for upload size. This change feels really dangerous to me honestly but I see how it unblocks a problem we're currently having. Would love it if you all would prioritize a backend solution soon. Infra is happy to help but we're not going to block this PR.

This limit wasn't in place until the last few days, so it's a fairly new thing. Agree with you re: not great only limiting on the frontend, but I'm not sure how we'd avoid this issue if we leave the file limit in place. Maybe we could narrow the scope? Like only allow office users that are uploading pdfs to be exempted from the 25 mb limit? Definitely others weigh in if I'm missing a better route.

**Comment by kahlouie** [comment]
Since this is broken for office users, I suggest removing just the backend check. I think we should be able to limit file upload for types of user or which app the user is in, to decrease the amount of memory load on our containers.

**Comment by mkrump** [comment]
I made a [story](https://www.pivotaltracker.com/n/projects/2181745/stories/167951106) to look at narrowing the exceptions to the limit. But going to merge this in since blocking office users at the moment.

**Pull request merged**
