### PR TITLE
B19765 int 20240507 fe change text auth receipt total

### PR DESCRIPTION
**Pull request by JamesHawks224**
## Agility ticket
[B19765](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19765)

## Summary

In "Review Documents" page in the "Summary", “Authorized Receipt Total” was changed to “Accepted Receipt Totals”.

### How to test

* Customer:  create a PPM move.
* SC: login and approve it.
* Customer: Upload PPM documents.  Upload expense receipts.
* SC: Review Documents.  Get to the summary screen.  Will see “Accepted Receipt Totals”.

## Screenshots
image

### CODE REVIEW

**Comment by WeatherfordAaron** [comment]
I show 315 files changed as well as some generated code issues. I recommend running
```
git fetch
git pull
make swagger_generate
make mocks_generate
make server_generate
```

**Review by KonstanceH — APPROVED** [review]
Once integration is unblocked this looks good to go

**Review by WeatherfordAaron — APPROVED** [review]
LGTM.. confirmed that the yaml changes don't actually change anything.. it just moved where that block of text is located in the file.
👽

**Comment by JamesHawks224** [comment]
Closing PR and recreating branch.
"Files changed" is reflecting more changes than what was actually done.

**Pull request closed without merging**
