### PR TITLE
B-21500- CM prod datafix

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

## Steps to Test
1. create a move with origin zip of 233**
2. login to office app with a TOO/services counselor with GBLOC of GBNC
3. validate that moves displays

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
Screenshot 2024-09-30 at 3 09 05 PM

Seeing all postal codes that start with 233 have `BGNC` in the `gbloc` column. LGTM!

**Review by cameroncaci — CHANGES_REQUESTED** [review]
Highly recommend bumping timeout

```
```

**Comment by deandreJones** [comment]
> Highly recommend bumping timeout
> 
> ```
> -- Set temp timeout due to large modification
> -- Time is 5 minutes in milliseconds
> SET statement_timeout = 300000;
> SET lock_timeout = 300000;
> SET idle_in_transaction_session_timeout = 300000;
> ```

this was already run in prod- and there are only 38 records affected, I think that might be a bit overkill

**Review by traskowskycaci — COMMENTED** [review]
Looks good for BGNC 
image

**Pull request merged**
