### PR TITLE
B-17796 Partial PPM Move Not Showing In SC's Closeout Queue 

### PR DESCRIPTION
**Pull request by taeJungCaci**
## Summary
For Partial PPM moves, it is not showing up in the Service Counselor's closeout queue.
This has to do with shipment status not changing correctly for the PPM shipment when the move has a HHG also.
The status for PPM shipment should change to "Waiting on Customer" once the Counselor finishes counseling.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [x] Has the branch been pulled in and checked out?
- [x] Have the BL acceptance criteria been met for this change?
- [x] Was the CircleCI build successful?
- [x] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Create a new move with HHG and PPM shipments.
2. As a Service Counselor, review and finish counseling (Submit move details). (Make sure to check the right GBLOC)
3. The move should show up in SC's Closeout Tab. (Make sure to check the right GBLOC)

### Backend

- [x] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [x] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
Looks good to me, pulled, merged in Playwright tests, and verified that everything still works 👍

**Comment by taeJungCaci** [comment]
After confirming with Gary, steps has been edited to be able to see the move in closeout tab once the counseling is finished.

**Comment by JamesHawks224** [comment]
I switched to the branch and updated repo.  restarted server and client.  Created a move (using 90210 for everything), added a HHG and PPM.  Submitted the move.  Signed in as a counselor (KKFA) and submitted the move.  Then, switched to PPM close out and got the following.
b17796 partial_ppm failed_test

**Review by KonstanceH — APPROVED** [review]
Added tests and intended functionality is working for me.
I don't have any recommendations for best practice changes.

**Comment by taeJungCaci** [comment]
> I switched to the branch and updated repo. restarted server and client. Created a move (using 90210 for everything), added a HHG and PPM. Submitted the move. Signed in as a counselor (KKFA) and submitted the move. Then, switched to PPM close out and got the following. b17796 partial_ppm failed_test

That is the successful result as the move is now showing in the table.

**Comment by JamesHawks224** [comment]
> > I switched to the branch and updated repo. restarted server and client. Created a move (using 90210 for everything), added a HHG and PPM. Submitted the move. Signed in as a counselor (KKFA) and submitted the move. Then, switched to PPM close out and got the following. b17796 partial_ppm failed_test
> 
> That is the successful result as the move is now showing in the table.

Agreed.  I incorrectly assumed that "partial" would show in the column.

**Review by JamesHawks224 — COMMENTED** [review]
testing was successful.  code looks good.  no changes.

**Comment by taeJungCaci** [comment]
@deandreJones Reviews are g2g

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
