### PR TITLE
INT B-21073 part dos

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

[First INT PR](https://github.com/transcom/mymove/pull/13853)

This is adding a little cleanup + one missed oopsie of validating the country when the Prime attempts to create an address that contains a country code that is not supported.

Since we do not support international moves at this time, I added in a check that IF the Prime provides a country code that is not `US`, then we are going to send back an error message saying the country code they provided is not supported.

### How to test

1. Access MM as Prime Sim
2. Find a move that you can create a shipment for
3. Endpoint would be `/prime/v3/mto-shipments`
4. Try to pass in an address that has a `Country` value of something that is NOT `US` - should get back a validation error
```
{
  "moveTaskOrderID": "0f21be2a-5045-4e90-8212-95a92de90056",
  "requestedPickupDate": "2024-10-12",
  "primeEstimatedWeight": 4000,
  "customerRemarks": "handle with care",
  "pickupAddress": {
    "streetAddress1": "123 OtherWorldly Ave",
    "city": "Not a US Country",
    "state": "AK",
    "postalCode": "90210",
    "country": "GB"
  },
  "destinationAddress": {
    "streetAddress1": "123 Main Ave",
    "streetAddress2": "Apartment 9000",
    "streetAddress3": "Montmârtre",
    "city": "Anytown",
    "state": "AL",
    "postalCode": "90210",
    "country": "US"
  },
  "shipmentType": "HHG"
}
```

Screenshot 2024-10-11 at 3 55 00 PM

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Code looks good, I like the more informative error logging in the the shipment creator service object as well!

image

**Review by cameroncaci — COMMENTED** [review]
Works perfectly, I'm wondering about the last line of the AC though:

> Then that domestic address should be rejected with a response that 'US' is the only valid country code for domestic addresses.

Currently we only respond that `${country}` is not supported at this time, we don't respond back a list of what is supported

**Comment by cameroncaci** [comment]
> > Works perfectly, I'm wondering about the last line of the AC though:
> > > Then that domestic address should be rejected with a response that 'US' is the only valid country code for domestic addresses.
> > 
> > 
> > Currently we only respond that `${country}` is not supported at this time, we don't respond back a list of what is supported
> 
> This is an interesting AC because right now we don't know what a "domestic" address is. So.. Until we have that functionality, my initial approach is just to blanket block any country value unless it's `US`

Should we default to, instead of displaying a list, blanket responding that only 'US' is allowed?

**Comment by danieljordan-caci** [comment]
> > > Works perfectly, I'm wondering about the last line of the AC though:
> > > > Then that domestic address should be rejected with a response that 'US' is the only valid country code for domestic addresses.
> > > 
> > > 
> > > Currently we only respond that `${country}` is not supported at this time, we don't respond back a list of what is supported
> > 
> > 
> > This is an interesting AC because right now we don't know what a "domestic" address is. So.. Until we have that functionality, my initial approach is just to blanket block any country value unless it's `US`
> 
> Should we default to, instead of displaying a list, blanket responding that only 'US' is allowed?

I'm cool with that

**Comment by danieljordan-caci** [comment]
> Works perfectly, I'm wondering about the last line of the AC though:
> 
> > Then that domestic address should be rejected with a response that 'US' is the only valid country code for domestic addresses.
> 
> Currently we only respond that `${country}` is not supported at this time, we don't respond back a list of what is supported

This was added in [this commit](https://github.com/transcom/mymove/pull/13890/commits/3dbd8ef62b1cce74612fc3fb8d9442c9bebe2ca7)

**Review by cameroncaci — APPROVED** [review]
Thanks for also updating the test case - LGTM!

**Pull request merged**
