### PR TITLE
B-21049

### PR DESCRIPTION
**Pull request by stevengleason-caci**
## B-21049
[Agility B-21049](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1007783)
[Integration PR](https://github.com/transcom/mymove/pull/14003)

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the office app
2. Login as a TOO
3. Search for and select a customer
4. Supporting Documents
5. Upload a PDF or image file
6. To simulate the AWS S3 delay, delete the newest file from mymove/tmp/storage/user/*/uploads/
7. Refresh the Supporting Documents page
8. see the File Not Found message

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by brianmanley-caci** [comment]
@stevengleason-caci in the test steps it says "see the File Not Found message and no download button". I am still seeing the Download file button in the top right corner. Is that correct?

**Comment by stevengleason-caci** [comment]
> @stevengleason-caci in the test steps it says "see the File Not Found message and no download button". I am still seeing the Download file button in the top right corner. Is that correct?

Yes, hiding the download link was not a requested behavior, and it caused unrelated test failures, so I left it there. I'll update the test steps.

**Comment by loganwc** [comment]
Can you include a link to your integration pull request?

**Review by brianmanley-caci — APPROVED** [review]

**Review by msaki-caci — APPROVED** [review]

**Comment by stevengleason-caci** [comment]
@loganwc Do you want to review this PR, or do you see any other issues?

**Review by loganwc — APPROVED** [review]
looks good

**Pull request merged**
