### PR TITLE
B-17677:  tooltip for incomplete ppm shipment on summary page

### PR DESCRIPTION
**Pull request by MInthavongsay**
## Summary

Note: The objective of this PR is to display an indicator denoting if a PPM shipment is INCOMPLETE on the summary page.  Only PPM will have the ability to display INCOMPLETE. The logic to display will be exactly like what is used (see func isPPMShipmentComplete) to display INCOMPLETE for the landing page.  It will check if ppmShipment.hasRequestedAdvance is null or not. The INCOMPLETE label has also been implemented for HHG, NTS, NTSR even though the label will never display the label based on current implementation (see conversation notes in B-17677). Client agrees the code should at least have the ability to display it if in the future it is needed.

E-04557:  https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic%3A834795

## Changes

- New control for INCOMPLETE Tooltip. HHG, NTS, NTSR shipment types will now display when status=DRAFT.
- New modal for INCOMPLETE info.
- Updated stories to include INCOMPLETE tooltip

## Verification Steps for Reviewers
1. Create a PPM - Fill out the info on the first page, (DO NOT FILL OUT ADVANCED REQUEST) and click SAVE
2. Click the MilMove Icon
3. Add an HHG and SAVE. User will be redirected to the shipment summary page. Both PPM and HHG will be listed. PPM will have an "INCOMPLETE" label with an info icon as tooltip. Clicking info will display modal popup. Click OK closes modal.
4.  Edit PPM and fill out advanced request. Save. INCOMPLETE shall not be visible because advanced request has been filled out.

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Create a PPM - Fill out the info on the first page, and click SAVE
2. Click the MilMove Icon
3. Add an HHG and SAVE. User will be redirected to the shipment summary page. Both PPM and HHG will be listed. PPM will have an "INCOMPLETE" label with an info icon as tooltip. Clicking info will display modal popup.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
list
modal

### CODE REVIEW

**Comment by cameroncaci** [comment]
Quick heads up to make sure to apply your team's label to the PRs

**Comment by cameroncaci** [comment]
Also make sure to update PR description with info as well as steps to reproduce and test for other devs (Step by step eg. create a TOO, set a weight amount to X, go to this next page and do this thing, finally you should see the new implementation Y. The more detailed the better) - otherwise individuals could be a little lost on what to action.

**Comment by cameroncaci** [comment]
> Also make sure to update PR description with info as well as steps to reproduce and test for other devs (Step by step eg. create a TOO, set a weight amount to X, go to this next page and do this thing, finally you should see the new implementation Y. The more detailed the better) - otherwise individuals could be a little lost on what to action.

Please ping once all updated and g2g for review @MInthavongsay

**Comment by cameroncaci** [comment]
> Note: The objective is to display an indicator denoting a shipment is incomplete on the summary page for PPM shipments. This is the initial implementation. Additional tickets will be created for next sprint to display INCOMPLETE indicator for ALL shipment types with correct logic to determine when a shipment is incomplete to complete the epic/feature(https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic%3A834795).
> 
> Agility -- B-17677: https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A847095&RoomContext=TeamRoom%3A855664&concept=TeamRoom
> 
> Verification Steps:
> 
>     1. Create a PPM - Fill out the info on the first page, and click SAVE
> 
>     2. Click the MilMove Icon
> 
>     3. Add an HHG and SAVE. User will be redirected to the shipment summary page. Both PPM and HHG will be listed. PPM will have an "INCOMPLETE" label with an info icon as tooltip. Clicking info will display modal popup.
> 
> 
> ppmSummaryPageWithFlagAndTooltip ppmSummaryIncompleteModal

Very nice, just make sure to place that inside the PR description though!

**Comment by antgmann** [comment]
There's still that Happo check being failed. It looks like it's just some whitespace at the start of a couple of attached or generated documents, but I don't understand what would be causing that? Maybe it's a non-issue?

**Comment by deandreJones** [comment]
FYI happo is just a screenshot check to see if the baseline tests change the ui
not usually an issue but the check is there to make sure things arent weirdly place if failing, somone just needs to go in and look then approve if all is ok

**Comment by antgmann** [comment]
Yeah based upon the changes being only whitespace, and the guidelines in the docs here: https://transcom.github.io/mymove-docs/docs/tools/cicd/happo/ 
it makes sense that this isn't actually an issue.

**Comment by antgmann** [comment]
updating and then checking out + testing

**Review by loganwc — APPROVED** [review]

**Review by r-mettler — APPROVED** [review]

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
