### PR TITLE
MB-15819 Refactor the EditMaxBillableWeightModal to use Modal and not Migrated Modal

### PR DESCRIPTION
**Pull request by YanZ777**
## Summary

refactor: Use just the modal and not the migrated modal for the EditMaxBillableWeightModal

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office application
2. Login as a TOO
3. Click on the MoveTaskOrderTab

## Verification Steps for Author

These are to be checked by the author.

- [x] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
image

### CODE REVIEW

**Review by michaelvaldes-truss — APPROVED** [review]
lgtm! The weight modal still works as expected

**Review by michaelvaldes-truss — CHANGES_REQUESTED** [review]
**suggestion:** Oh, one thing I missed on the first pass -- it looks like the storybook story needs to be updated too. I'm not sure how to make a suggestion on a file that isn't already included on the PR, but it probably just needs an `isOpen` arg

**Comment by YanZ777** [comment]
> **suggestion:** Oh, one thing I missed on the first pass -- it looks like the storybook story needs to be updated too. I'm not sure how to make a suggestion on a file that isn't already included on the PR, but it probably just needs an `isOpen` arg

Thanks for catching that! I pushed up changes that should hopefully have it show up in Storybook.
I don't think you can make a suggestion on a file that isn't already included in the PR.

**Review by michaelvaldes-truss — APPROVED** [review]

**Review by AnnaGingle — APPROVED** [review]
LGTM

**Pull request merged**
