### PR TITLE
[MB-10173] Hide line about storage facility on all but NTS-release form

### PR DESCRIPTION
**Pull request by hannaliebl**
## Summary

Is there anything you would like reviewers to give additional scrutiny?

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Set up a new shipment and see that the bullet point "The storage facility or address where your items are currently stored" is on the remarks field for NTS-release shipments but no other shipment types.

### CODE REVIEW

**Review by jenniferlynparsons — CHANGES_REQUESTED** [review]
Everything looks good. We just need to add a Storybook story for the NTS-Release version of the shipment form.

**Comment by hannaliebl** [comment]
@jenniferlynparsons I think it exists already, here: https://github.com/transcom/mymove/blob/master/src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx#L98

**Review by jenniferlynparsons — APPROVED** [review]
LGTM!

**Review by reggieriser — APPROVED** [review]
LGTM!  Tried it out locally and saw the line on NTS-R but not on the other shipment types as expected.

**Pull request merged**
