### PR TITLE
B-21364 I-12546 INT 

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

- Added a check for UB shipment types in src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx, to display "Unaccompanied Baggage" rather than the unspecified "Shipment"
- Updated tests

### How to test

1. Access the milmove app as a customer
2. Create a UB shipment
3. After creating, head to the move home page and expand the shipments drop down.
4. Verify that you see Unaccompanied Baggage" on the page.

### Frontend

- [x] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).
image

## Screenshots
Before:
image

After:
image

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
Screenshot 2024-11-19 at 3 56 59 PM
Ayyyy! Thanks for also refactoring all those fun little variables!

**Review by cameroncaci — APPROVED** [review]
I see that variable cleanup too, much appreciated 👏🏻 

Worked as intended, meets AC.

Interesting thing is that if UB is your only shipment, we still see HHG allowance. Likely an oversight, should we reach out to Wendy before the PO for a possible BLI?
image

image

**Comment by traskowskycaci** [comment]
> I see that variable cleanup too, much appreciated 👏🏻
> 
> Worked as intended, meets AC.
> 
> Interesting thing is that if UB is your only shipment, we still see HHG allowance. Likely an oversight, should we reach out to Wendy before the PO for a possible BLI? image
> 
> image

Hmm.. @danieljordan-caci would this fall in scope of B-21376?

**Comment by danieljordan-caci** [comment]
> > I see that variable cleanup too, much appreciated 👏🏻
> > Worked as intended, meets AC.
> > Interesting thing is that if UB is your only shipment, we still see HHG allowance. Likely an oversight, should we reach out to Wendy before the PO for a possible BLI? image
> > image
> 
> Hmm.. @danieljordan-caci would this fall in scope of B-21376?

@cameroncaci and @traskowskycaci are we saying we want to see the UB allowance as well up there?

**Comment by traskowskycaci** [comment]
> > > I see that variable cleanup too, much appreciated 👏🏻
> > > Worked as intended, meets AC.
> > > Interesting thing is that if UB is your only shipment, we still see HHG allowance. Likely an oversight, should we reach out to Wendy before the PO for a possible BLI? image
> > > image
> > 
> > 
> > Hmm.. @danieljordan-caci would this fall in scope of B-21376?
> 
> @cameroncaci and @traskowskycaci are we saying we want to see the UB allowance as well up there?

I think that would be a good idea - otherwise, the customer can't see their UB allowance anywhere else after they've created the shipment, right?

**Comment by cameroncaci** [comment]
@danieljordan-caci @traskowskycaci I was thinking if they only have UB shipments then only see UB allowance, if they have both to then show both HHG and UB

**Comment by danieljordan-caci** [comment]
> @danieljordan-caci @traskowskycaci I was thinking if they only have UB shipments then only see UB allowance, if they have both to then show both HHG and UB - open to any approach

That's tricky because they could still have shipments added after the fact and they technically are allowed a weight allowance.

My hesitation to add it is because UB weight allowance is WITHIN the weight allowance and not IN ADDITION to. So adding it at the top might confuse the customer and we don't have any way to add those details in that header without cluttering the UI. Any thoughts on seeing if we get POA on it and if they want to add it down the road, we can do it.

**Comment by traskowskycaci** [comment]
> @danieljordan-caci @cameroncaci  this is how the overall weight allowance and the UB weight allowance interact - we aren't really handling this interaction anywhere, not doing any subtraction or addition on the weight allowance itself in regards to the UB allowance - we might need to?

This was a question I had asked Terri and Dan:
Example (made up entitlement values):
- For a service member, let's say their normal existing entitlement is 8,000 lbs
- Then for a UB shipment, it might be 300 lbs
- So can they move 8,000 with 300 lbs of that being UB
- Or can they only move 300 lbs
- Or can they move 8,300?
- Answer: They can move 8,000 lbs with 300 of that being UB (Terri and Dan
confirmed)

**Pull request merged**
