### PR TITLE
INT-B-19226 Revert and redo of form changes

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## Relevant INT PRs
#13474
#13548 
#13567

## Summary

This PR changes customer onboarding and move creation forms in MilMove to label required fields with light grey "Required" text, while getting rid of the existing "Optional" text that currently accompanies optional fields. While this was handled with the other INT PRs, the method used changed behavior across the entire app, which was not in the story scope. Now only forms on the Customer side should be affected.

### How to test
Please follow the steps in the relevant INT PRs, but basically, check all customer side onboarding and move forms to check that all form fields that are needed to submit show a "Required" light grey help label, and that no "Optional" labels are left over.

### CODE REVIEW

**Comment by taeJungCaci** [comment]
I'm seeing `required` and `optional` labels for dimensions in boat shipment form and mobile shipment from. Is this correct? 
image

**Comment by brooklyn-welsh** [comment]
> I'm seeing `required` and `optional` labels for dimensions in boat shipment form and mobile shipment from. Is this correct? image

Good catch, definitely not, I'm assuming something weird happened with merge conflicts that didn't show up while I had the server running since it wasn't like this in my MAIN branch, will edit real quick with a fix

**Comment by taeJungCaci** [comment]
also not sure if this is related to your changes, but the fields styling got changed for city and state - One is from Main and other is INT. Might be someone else's changes, but maybe you might know: 
image
image

**Comment by brooklyn-welsh** [comment]
> also not sure if this is related to your changes, but the fields styling got changed for city and state - One is from Main and other is INT. Might be someone else's changes, but maybe you might know: image image

Yeah this is currently only in INT and is a result of change from Ricky I believe, looks like there's a story that changes it to where the user can just put in their address and the rest auto fills or something like that. From what I can tell that is supposed to be like that, had to refactor a bunch of tests to get them to work with the new UI after changing the optional labels.

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Comment by taeJungCaci** [comment]
I hope you are tracking all the changes with all theses PRs because I can already tell this MAIN PR is gonna be a massive pain.

**Review by WeatherfordAaron — APPROVED** [review]
lgtm

**Pull request merged**
