### PR TITLE
MB 11782 - Added acknowledgeExcessWeightRisk

### PR DESCRIPTION
**Pull request by kennethchow-truss**
## Summary

Adds log for acknowledgeExcessWeightRisk. In the milmove system, a notification may pop up for office users to show an excess weight risk on a move. If the TOO dismisses the notification, the field acknowledgeExcessWeightRisk will be true and a log should appear on the history page for a move

## Setup to Run Your Code

1. Go to `officelocal:3000/`
2. Login as a TOO user
4. Go to `officelocal:3000/moves/RISKEX/details`
5. Dismiss the notification at the top 
6. Go to the move history page
7. Observe that a log is there with event "Updated Move" and details "Dismissed excess weight alert"

### CODE REVIEW

**Comment by kennethchow-truss** [comment]
@mergifyio rebase

**Comment by kennethchow-truss** [comment]
@mergifyio rebase

**Comment by kennethchow-truss** [comment]
@mergifyio rebase

**Review by YanZ777 — APPROVED** [review]
Looks good to me!

**Review by donaldthai — APPROVED** [review]
Once @juliemoon reviews, this is good to merge 👍

**Review by juliemoon — APPROVED** [review]

**Pull request merged**
