### PR TITLE
[ spike, MB-14548, MB-13732 ] Fix generate-deploy-notes script

### PR DESCRIPTION
**Pull request by rogeruiz**
I've gone ahead and fixed the `generate-deploy-notes` script. This was commonly used in the #prod-support channel until one day it just stopped working. I think this script is valuable. If there's no agreement on the usefulness of the script feel free to close out this ticket. I'll be posting this in #prod-support on DP3 slack for review. 

- [x] Modifying the types to get script working again
- [x] Update the output so it can be easily copied
    - When running this script, it can be piped to `pbcopy` on macOS to make
it easier to share the deploy notes with others in Slack. 

This was tested locally at the time of this writing and produced this output.

```
*Release notes for transcom/mymove*
• #9731 Bump ra-data-simple-rest from 4.5.2 to 4.6.1 by dependabot[bot]
        • https://github.com/transcom/mymove/pull/9731
• #9740 Bump github.com/XSAM/otelsql from 0.17.0 to 0.17.1 by dependabot[bot]
        • https://github.com/transcom/mymove/pull/9740
• #9752 Bump eslint-plugin-storybook from 0.6.7 to 0.6.8 by dependabot[bot]
        • https://github.com/transcom/mymove/pull/9752
• #9722 Bump @storybook/addon-essentials from 6.5.13 to 6.5.14 by dependabot[bot]
        • https://github.com/transcom/mymove/pull/9722

```

This is similar to the other approach for generating these kinds of notes using the GitHub API.

[=> Link to compare view in GitHub](https://github.com/transcom/mymove/compare/db7ec1e9598a22bc61b889c7d7b5a4029dc108df...8f950184b7e7f3432d18607390cc8dbfb3d71a60)

The link above is manually generated by using the following commands. Note this requires HTTPie (`https`), but could also be done with cURL (`curl`). The command also requires `jq` as well.

```
open https://github.com/transcom/mymove/compare/$(https my.move.mil/health | jq -r '.gitCommit')...$(https my.stg.move.mil/health | jq -r '.gitCommit')
```

### CODE REVIEW

**Comment by rogeruiz** [comment]
My main reason behind fixing this script isn't for developers to run it themselves. They're more than welcome to though! It's more so we can have some kind of automation which would output this deployment notes to #prod-support in DP3 Slack as part of the deployment reminder that is handled by Slackbot today.

**Comment by shimonacarvalho** [comment]
Is there any documentation on this script? Mine is failing due to a bad token but I can't remember how to create the correct token for this script.

**Comment by shimonacarvalho** [comment]
Okay I tested, looks good to me.

**Review by shimonacarvalho — APPROVED** [review]
Ok tested, looks good to me.

**Comment by rogeruiz** [comment]
@shimonacarvalho I think there is documentation for it, but I didn't look before submitting. I did have issues coming up with the "correct permissions" it turned out all this GitHub token needs is `repo:status` I believe which is much less than what my `gh-cli` needs to do things. But I normally use that second one for testing.

**Comment by rogeruiz** [comment]
Re-running the `ci/circleci: integration_tests` but I'm not seeing output where I was expecting it in #prac-engineering Slack. Not sure what's happening but 🤞🏽 that it works this second time around.

**Pull request merged**
