### PR TITLE
B 18111 pay grade and duty location flow changes

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

This story moves the entry of grade and current duty location to the orders page. Please see the documents attached to the story and associated feature as they are really helpful.

With this story, the service member rank is still being maintained and updated to be the order grade value, which will make sure nothing is broken that is still using the service member rank.

As of right now, both the Profile and the Orders page will show the pay grade and current duty location, and can be edited from both spots. Editing from the profile may change in the future, depending on what the gov would like to see.

- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access the milmove app
2. Login as a customer
3. Create a new profile, running through the flow. Do not add orders yet.
4. After creating the profile and before adding orders, go to the Edit Profile page and see that there is no information for pay grade and current duty location. 
5. Verify that you are not asked for pay grade and current duty location until adding your orders.
6. Add orders, entering pay grade and current duty location.
7. After entering, go to the database and verify that the order grade and order origin duty location match the information you provided.
8. Important: Also go to the service member table and verify that the rank and current location of the service member match the orders values you provided.
9. Edit the orders pay grade and orders current duty location.
10. Verify that in the database, both the service member and orders values are updated.
11. (Optional) As of right now, the customer can also edit the orders values from the Profile page.

### CODE REVIEW

**Comment by traskowskycaci** [comment]
Ready for review! Happo check is failing which is to be expected. Questions for my reviewers:
- Do you believe this would be fine being deployed to staging rather than going to experimental?
- Should I delete some of the duty location pages that aren't being used anymore, or save that for the backend cleanup story? 
image

**Review by TevinAdams — APPROVED** [review]
Test case passed, ACs met, Code reviewed and looks good.

**Review by cameroncaci — COMMENTED** [review]
Should we add a ternary or tooltip to point out that grade and current duty location are tied to orders? I can image a service member trying to get that in there since it's important information and getting frustrated if they can't find out how (Edge case, but worth a thought).

image

**Comment by traskowskycaci** [comment]
> Should we add a ternary or tooltip to point out that grade and current duty location are tied to orders? I can image a service member trying to get that in there since it's important information and getting frustrated if they can't find out how (Edge case, but worth a though)
> 
> image

Danny already reviewed a PR with this behavior in here. I think it looks funny and have a question out to Danny to address this issue in my current frontend story, but I think it's out of scope for this story.

**Comment by cameroncaci** [comment]
>(Optional) As of right now, the customer can also edit the orders values from the Profile page.

Should this include grade and current duty location? Cause I'm not able to replicate being able to edit those fields (After it has been inputted that is)

**Review by danieljordan-caci — APPROVED** [review]
LEWKSGEWDTEWMI

**Comment by traskowskycaci** [comment]
Spoke with @TevinAdams and @cameroncaci and got their opinions - they agree this is ok to go directly to staging and avoid experimental. If anyone disagrees, lmk! @danieljordan-caci @deandreJones

**Pull request merged**
