### PR TITLE
Add the ability to search for office users

### PR DESCRIPTION
**Pull request by garrettqmartin8**
## Description

Currently, the only way to find the specific person you're looking for is to click through dozens of pages of people and hope you don't miss them. This PR makes it easy to find the person you're looking for.

## Setup

- `make server_run`
- `make client_run`
- Log into the admin app and use the search field to find office users by email, first name, or last name.

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/169293430) for this change

### CODE REVIEW

**Comment by garrettqmartin8** [comment]
@lynzt thanks for finding those. Totally missed the pagination. Will update that and the indexes. May request to pair with you on a potential trigram index.

**Comment by garrettqmartin8** [comment]
@lynzt I've addressed the `%` and index issues you brought up.

For pagination, #2887 adds a fix that can be more generally applied to correctly counting the TSPP records when using filters. Are you ok with me writing a separate story to apply that fix to the rest of the admin app?

Regarding n+1s, are you ok with saving that work for [this ticket](https://www.pivotaltracker.com/story/show/169295815)? I have a feeling it will require us to adjust the query builder.

**Comment by garrettqmartin8** [comment]
Ah I see, so we can use `%x%` with a trigram index. Do you think it's worth using that strategy for first, last, and email, or just `x%` for first and last with regular indexes? Happy to go either way.

**Comment by lynzt** [comment]
I'd probably do a `*%` search for first_name and last_name... i don't see a time when someone will search for the "middle" of a person's name, but if you do, you can sway me... :)

I do see a use case for `%*%` in the email since we might want to find all `truss.works` emails for instance in addition to `name@%` for instance...

**Comment by garrettqmartin8** [comment]
@lynzt cool!

**Comment by garrettqmartin8** [comment]
@lynzt I adjust the indexes and [created a ticket](https://www.pivotaltracker.com/story/show/169506849) for the n+1 issue

**Comment by garrettqmartin8** [comment]
@lynzt it looks like there's a [default behavior](https://marmelab.com/react-admin/Tutorial.html#adding-search-and-filters-to-the-list) for this:

> Filters are “search-as-you-type”, meaning that when the user enters new values in the filter form, the list refreshes (via an API request) immediately.

**Comment by lynzt** [comment]
@garrettqmartin8 i'm curious what "refreshes (via an API request) immediately" means in the context of filtering a list when typing... I didn't see any numbers, but we might have to dig into the `react-admin` code??

**Comment by garrettqmartin8** [comment]
Ah, looks like it may be [500ms](https://github.com/marmelab/react-admin/blob/4a0fbd24a54947f35e22dabdffee426a45f32c86/packages/ra-core/src/controller/ListController.tsx#L160).

**Comment by garrettqmartin8** [comment]
@lynzt do you this the default is sensible or should we tweak it?

**Comment by lynzt** [comment]
@garrettqmartin8 i am totally ok w/ the default... i just wanted to know what the default was (and that it made sense). thanks so much for checking that! 
feel fee to 🚢!!! :)

**Comment by garrettqmartin8** [comment]
Cool, no worries! Thanks 😎

**Pull request merged**
