### PR TITLE
B-17964 Removed "move reviewed" files.

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## Summary

Removes the "Move Reviewed" email that was sent when a TIO reviewed and approved payment items for a PPM move.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### CODE REVIEW

**Comment by taeJungCaci** [comment]
do `/assets/notifications/templates/move_reviewed_template` files need to get removed as well?

**Comment by brooklyn-welsh** [comment]
> do `/assets/notifications/templates/move_reviewed_template` files need to get removed as well?

Yes they definitely do, will remove and push an update soon.

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by WeatherfordAaron — APPROVED** [review]
I recommend deleting the commented out sections since this all appears to be good to go. I'm going to go ahead and approve since comments are ignored by the compiler anyways.

**Pull request merged**
