### PR TITLE
[MB-9288] Switch to gorilla mux

### PR DESCRIPTION
**Pull request by rogeruiz**
## Description

> Gorilla mux provides the feature of being able to determine which
> route a request is associated with which will be necessary for
> recording metrics associated with the route instead of the file.

> It also provides a way to only enable a route for a given host

> In addition gorilla mux is actively maintained and goji is not.

## Reviewer Notes

This was originally introduced in the PR #7404 and should be its own PR ~~as [it's not related to the Prime Simulator effort as described by @ahobson here](https://github.com/transcom/mymove/pull/7404#discussion_r712472073).~~ because it is related to both the Prime Simulator work and some metrics and observability work in the future.

## Setup

I am not entirely sure what the setup for this is. But I will make space for @ahobson to chime in if he has something to add here. I personally tested this by ensuring that the Applications all come up and that logging is still being done properly. I also ran the tests locally to verify that everything was passing. 

Since this is a low-level change to the Mux Router, I don't know of a better way of testing this without ensuring that tests are passing appropriately and that the Application's routes are working as expected.

There's no expectations for merge conflicts but this is a global change to the whole of `mymove` backend.

## Code Review Verification Steps

* [x] If the change is risky, it has been tested in experimental before merging.

## References

* [Jira](https://dp3.atlassian.net/browse/MB-9288) ticket associated with this work.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Once this is merged into `master`, we can rebase #7404 to get rid of these changes from that PR so that it's less visually noisy since the majority of that effort is to get an MVP of the Prime Simulator up.

**Comment by rogeruiz** [comment]
Here is some [additional context in Slack](https://ustcdp3.slack.com/archives/CP6PTUPQF/p1632324163392800) around why this should be it's own patch series. It has been [specifically discussed here](https://ustcdp3.slack.com/archives/CP6PTUPQF/p1632325382396100?thread_ts=1632324163.392800&cid=CP6PTUPQF) by a member of @transcom/truss-sr-eng. 

I've updated this patch series with some additional commits to ensure that things are passing in CI due to how the work was related to the changes in #7404 but how logically it should be in its own PR.

And I will be adding the necessary code to #7404 which needs this the code in this PR to exist before it can actually be useful. Because of the way Git handles changes, some of these commits may or may not cause merge conflicts, but I can take care of that when this is merged into `master`.

**Review by ahobson — APPROVED** [review]
I like this change! 😁

**Comment by rogeruiz** [comment]
@ahobson has pushed this to EXP in #7405 as that has this SHA in its history. I've logged into the app on the following URLs and tested the API with the EXP certificates from my local machine.

- https://my.exp.move.mil
- https://office.exp.move.mil
- https://admin.exp.move.mil
- https://api.exp.move.mil

This change LGTM 🌈

**Pull request merged**
