### PR TITLE
INT B-20108 refactor SignatureForm to use Formik

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

We are not wanting to use `redux-form` and instead use Formik due to library support. This backlog item addresses the `SignatureForm` component and its use of `redux-form` as well as accessory files.

Luckily, this component isn't being used ANYWHERE in the code base and was tech debt. Removing the file and sending it to the heavens completes this task and should NEVER BE SPOKEN ABOUT AGAIN.

### How to test

1. In VSCode, search for `redux-form`
2. You should no longer see it being used in the `SignatureForm` component
3. Confirm that `SignatureForm` no longer exists in the code base and that it isn't being used anywhere else

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
flaky tests flakily failing

**Comment by loganwc** [comment]
All you did was remove the redux-form, I don't see any changes to point to Formik. Were both implemented and you just removed the old?

**Review by loganwc — APPROVED** [review]
Nvm looks like it's not referenced anywhere in the code, good to go!

**Comment by danieljordan-caci** [comment]
> Nvm looks like it's not referenced anywhere in the code, good to go!

Yup, when we first broke this down we didn't dive too deep and seems like almost all of these components using `redux-form` are just old code

**Review by cameroncaci — APPROVED** [review]
Send it

**Review by deandreJones — APPROVED** [review]

**Review by traskowskycaci — APPROVED** [review]

**Pull request merged**
