### PR TITLE
INT B-18543 deprecate createSITAddressUpdate request and remove tech debt

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

With the deprecation of the [createSITAddressUpdate](https://transcom.github.io/mymove-docs/api/prime/v1#tag/sitAddressUpdate) endpoint, we need to remove all relevant tech debt and update the Swagger documentation.

I have taken the liberty of painting the codebase red and rid the earth of any mention of `SITAddressUpdate` or `sit_address_update`.

This PR does the following:
- removed all handlers and service objects related to creating a SIT address update request
- removed all handlers and service objects related to approving, rejecting, or updating SIT address update requests
- dropping the `sit_address_updates` table as well as the related enum `sit_address_update_status`
- scoured the UI code and removed any unused variables and props used that is related to SIT address updates on the service item level

### How to test

1. Fire up `client` and `server`
2. Navigate the prime sim and GHC applications and make sure you don't get any errors
3. Specific areas would be the MTO page, reviewing service items, and address forms
4. Confirm you can't call the prime `POST` endpoint `/prime/v1/sit-address-updates`

### CODE REVIEW

**Comment by TevinAdams** [comment]
Getting a 500 on MTO page. Seems to be on the history api call. I see you removed a lot from pkg/assets/sql_scripts/move_history_fetcher.sql
image

**Comment by danieljordan-caci** [comment]
> Getting a 500 on MTO page. Seems to be on the history api call. I see you removed a lot from pkg/assets/sql_scripts/move_history_fetcher.sql. Checking to see if this is on main now. image

Have you done a recent pull?

**Comment by danieljordan-caci** [comment]
Flaky server tests failing

**Comment by TevinAdams** [comment]
> 4\. /prime/v1/sit-address-updates

Pulled and saw some new changes for the sql script. No longer getting that activity.

**Review by TevinAdams — APPROVED** [review]
Was not able to hit the endpoint with Postman. Ran through workflow from creating move to submitting payment requests with no issue. All code removed seems to be related to the deprecation of createSITAddressUpdate. ACs seems to have been satisfied.

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
