### PR TITLE
[ MB-11574 ] Refactor GHC API handlers

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

The GHC API needs to be converted to the new pattern for App Context. We're
using the PO9 outcome to get consistency across all the handlers across the
application.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use at least one separate terminal to test this locally.</summary>

##### Terminal 1

Run tests for all the Go code.

```sh
make server_test
```

##### Terminal 2

Run tests specific for the `ghcapi` handlers.

```sh
go test $(go list ./pkg/handlers/ghcapi) -v
```

</details>

### Verification Steps for Reviewer

- [x] Ensure tests pass
- [x] Ensure the refactored handler methods match the new convention
- [ ] Check MilMove public documentation for updated documentation

## Verification Steps for Author

> These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Rebased these commits to reflect the name of the handler I'm refactoring. I'm still on the fence if I should do these all at once in a single PR or split out these commits across different PRs related to the files that are being touched. For instance, the `mto_service_items` handlers would be a single PR. cc: @donaldthai

**Comment by donaldthai** [comment]
> 

Tests are passing so I'm inclined to refactor all the GHC handlers in the PR. Any handler that gives us trouble with the new change, we can always create a new task to address it later.

**Comment by rogeruiz** [comment]
All tests are passing. Also there's no more trace of `appCtx := h.AppContextFromRequest` found in any of the files within `pkg/handlers/ghcapi/`.

Captura de Pantalla 2022-03-09 a la(s) 9 00 21 p m

**Comment by rogeruiz** [comment]
I'm going to make sure that with all the latest changes, I can safely merge this in, so I'm gonna attempt a rebase.

**Comment by rogeruiz** [comment]
@mergifyio rebase

**Pull request merged**
