### PR TITLE
B-20305: FSC Weight Based Distance Multiplier On Reweigh

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

When a shipment has a reweigh the wrong weight based multiplier was being applied to the FSC/FRA service item. This was happening because when there was a reweigh the weight logic was bypassing the reweigh logic which will take the lessor of actual weight and reweighWeight.  By using a shipment with the same weight metrics as the attachment in the ticket. i was able to reproduce the issue of weight multiplier of value 0.000834 being applied because the logic was choosing this based on the weight of 10,640, which is not the lessor of Reweigh and actual weight. After these changes you will see a multiplier value of 0.0006255 being applied because the weight multiplier logic is going off of 9,000 which is the lessor of Reweigh and Actual weight (See Screen Shots).

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access prime simulator and create a shipment close to the one in the screenshots or use a shipment that is already set up as close as possible to the one in the screenshots and edit the weight values or just use a completely different shipment with your own choice of values
2. Make sure the shipment has a FSC service item
3. Make sure the shipment has a reweigh (You can go to the TOO and request a reweigh for that shipment then go back to the prime sim and enter a reweigh weight on the shipment)
4. Once a reweigh weight is applied then create a payment request that includes the FSC service item
5. Go to the TIO to review the payment request and make sure the correct weight multiplier was applied to the FSC service item

weightBilled should be the lessor of Reweigh and ActualWeight

`const weightBasedDistanceMultiplierLevelOne = "0.000417"
const weightBasedDistanceMultiplierLevelTwo = "0.0006255"
const weightBasedDistanceMultiplierLevelThree = "0.000834"
const weightBasedDistanceMultiplierLevelFour = "0.00139"`

`if weightBilled <= 5000 {
		return weightBasedDistanceMultiplierLevelOne, nil
	} else if weightBilled <= 10000 {
		return weightBasedDistanceMultiplierLevelTwo, nil
	} else if weightBilled <= 24000 {
		return weightBasedDistanceMultiplierLevelThree, nil
		//nolint:revive
	} else {
		return weightBasedDistanceMultiplierLevelFour, nil
	}`

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
BEFORE
B-20305_Before

AFTER
B-20305_After

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Looks like I'm seeing the right multiplier locally. Nice!

image

**Comment by traskowskycaci** [comment]
@TevinAdams  I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?

**Comment by TevinAdams** [comment]
> @TevinAdams I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?

No I believe this story is for when there is a reweigh. The screenshots attached to the ticket showing the issue of the shipment having a reweigh with a 9000 pound weight. The method suggested in the analysis is used to do the reweigh calculations wether theres a weight on the reweigh or not. But screenshot had the wrong multiplier and i was able to reproduce what was in the screenshot an noticed the incorrect one being applied. But with these changes the correct one is.

> @TevinAdams I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?

**Comment by traskowskycaci** [comment]
> > @TevinAdams I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?
> 
> No I believe this story is for when there is a reweigh. The screenshots attached to the ticket showing the issue of the shipment having a reweigh with a 9000 pound weight. The method suggested in the analysis is used to do the reweigh calculations wether theres a weight on the reweigh or not. But screenshot had the wrong multiplier and i was able to reproduce what was in the screenshot an noticed the incorrect one being applied. But with these changes the correct one is.

Ok, thanks for the explanation!

**Comment by TevinAdams** [comment]
> > @TevinAdams I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?
> 
> No I believe this story is for when there is a reweigh. The screenshots attached to the ticket showing the issue of the shipment having a reweigh with a 9000 pound weight. The method suggested in the analysis is used to do the reweigh calculations wether theres a weight on the reweigh or not. But screenshot had the wrong multiplier and i was able to reproduce what was in the screenshot an noticed the incorrect one being applied. But with these changes the correct one is.
> 
> > @TevinAdams I reread the description on the story and it mentioned the defect happening for when reweighs do _not_ happen. I think I tested your work for when doing a reweigh - is there more work needed for when a reweigh is not completed by the prime?

No problem. I am still checking with Wendy this morning though because the screenshots doesn't really correlate with the description and title. It is confusing.

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
