### PR TITLE
Add Ruby script to automate prod deploys

### PR DESCRIPTION
**Pull request by monfresh**
**Why**:
The current deploy process followed twice a day by the folks who are
on call is manual and tedious. It requires following these steps:

1. Visit the Circle CI website to view the most recent pipelines for
the master branch
2. Click on the most recent successful pipeline
3. Copy the git commit hash
4. Look up the date for the commit hash via the command line
5. Visit the GitHub website to view pull requests for mymove
6. Filter PRs using this query:
`is:closed base:master merged:>2020-05-04T17:33:46-00:00 sort:updated-asc`
where the date is the one from step 4, but with one second added to
it, and converted to ISO 8601 format that GitHub needs.These first 6
steps are how we can obtain all PRs that have been merged to master
since the last one that was deployed to production.
7. Copy the title of each PR into a new Slack post and share it in
the #prod-support channel
8. Go back to the CircleCI pipelines, and click on the most recent
"ON_HOLD" pipeline.
9. Scroll horizontally until you see the "approve_prod_deploy" job,
and click on it, then type in "approve_prod_deploy" to approve it.

These steps are time-consuming and error-prone. With this script, the
process is reduced from several minutes to a few seconds. If there
aren't any new merged PRs since the last deploy, it will let you know.
If there are PRs to deploy, it will first prompt you to make sure you
really want to deploy. This helps avoid accidental deploys.

For troubleshooting and comparison with the CircleCI website, the
script will output the pipeline number for the most recent successful
and on hold pipelines, and the commit hash for the last deployed PR.
For easy copy and pasting into Slack, it will output the title and URL
for each PR that is about to be deployed.

## Setup

1. Go to https://app.circleci.com/settings/user/tokens
2. Create a new token and save it somewhere safe, like in 1Password. I named mine "mymove-deploy"
3. Go to https://github.com/settings/tokens
4. Click on "Generate new token", and give it only the `repo` permissions, and save it in 1Password
5. Run `docker run -it --rm=true -v $PWD:/app -w /app ruby:2.7-slim bash`
6. Inside Docker, run `export CIRCLE_TOKEN=your_circle_token`
7. Inside Docker, run `export GITHUB_TOKEN=your_github_token`
8. Run `scripts/deploy`

### CODE REVIEW

**Comment by monfresh** [comment]
Yeah, for sure we need a better name than `deploy`. This script doesn't only generate the PR titles and URLs, it also performs the actual deploy by approving the `approve_prod_deploy` job in the CircleCI workflow. 

From what I read in the API docs, it sounded like the token needed to be a personal token, and not a project token. When I tried running the script locally with the token set to the one in our CircleCI project settings (the one with scope `all`), it didn't work. The steps to obtain a personal token are straightforward I think, and I listed them in the "Setup" section of this PR.

We can definitely make this reusable across projects by adding ENV vars for the CircleCI and GitHub project/repo names.

Setting up like `ecs-service-logs` sounds great. I'll take a look.

**Comment by chrisgilmerproj** [comment]
> Yeah, for sure we need a better name than `deploy`. This script doesn't only generate the PR titles and URLs, it also performs the actual deploy by approving the `approve_prod_deploy` job in the CircleCI workflow.

I really like the philosophy of 1 script per tool. So I'd much rather this script only did the PR titles and URLs and posted them to Slack. I'd prefer to keep the actual approval in CircleCI for security concerns. This is mostly because the approval flow is part of an artifact we gave the ISSM for the ATO. If you want a second script for hitting the approval button we can talk about that.

> From what I read in the API docs, it sounded like the token needed to be a personal token, and not a project token. When I tried running the script locally with the token set to the one in our CircleCI project settings (the one with scope `all`), it didn't work. The steps to obtain a personal token are straightforward I think, and I listed them in the "Setup" section of this PR.
>
> We can definitely make this reusable across projects by adding ENV vars for the CircleCI and GitHub project/repo names.

We have a user named `robot-mymove` which already has permissions to do most things. The env vars are already set up in CircleCI so it would be nice to just insert this into the build pipeline and use those credentials. Then nobody actually has to run any code. If you couple that with the fact that we have credentials to post to Slack directly then this script could potentially just do it all after someone clicks "approve deploy" in CircleCI.

> Setting up like `ecs-service-logs` sounds great. I'll take a look.

It's new but its fancy!

**Comment by monfresh** [comment]
That all makes sense. I was gonna ask if we had a special Circle user and it sounds like `robot-mymove` is the one. I like the idea of hitting approve deploy and having the script do the rest. Does `robot-mymove` also have GitHub permissions?

**Comment by chrisgilmerproj** [comment]
> That all makes sense. I was gonna ask if we had a special Circle user and it sounds like `robot-mymove` is the one. I like the idea of hitting approve deploy and having the script do the rest. Does `robot-mymove` also have GitHub permissions?

Yep, sure does. It has all the permissions :)

**Comment by monfresh** [comment]
One scenario the script currently doesn't handle is when there are pipelines in progress, but you don't want to wait for them to finish before deploying. Right now, the script only looks at the last successful pipeline and assumes all PRs merged after that will be part of the next deploy, but that's not always the case. Instead, we should only fetch the commit in between the last successful one and the most recent on hold pipeline.

**Comment by chrisgilmerproj** [comment]
> One scenario the script currently doesn't handle is when there are pipelines in progress, but you don't want to wait for them to finish before deploying. Right now, the script only looks at the last successful pipeline and assumes all PRs merged after that will be part of the next deploy, but that's not always the case. Instead, we should only fetch the commit in between the last successful one and the most recent on hold pipeline.

It would be nice if you could give the CIRCLECI_SHA1 and have it use that. Or if you could have it look at the last pipeline that has gotten to the hold. I think you can figure that out by comparing shasums.

**Comment by chrisgilmerproj** [comment]
> I'm really happy that you built this @monfresh! However, I do have concerns about adding ruby scripting to the project at this time. We've tried to limit our technology stack to golang, javascript, bash, and (reluctantly on my part) python. Adding more languages people need to know makes onboarding new team members more difficult and increases the complexity of the project in ways I would like to discuss with @jacquelineIO @Ryan-Koch @LeDeep @lynzt before this gets merged.

Just to echo this part, ruby isn't in our build chain right now and it's not a dependency we'd really want to support. Our docker images are built on a python base image with golang and node installed. Would prefer to keep ruby out of the project and instead have this script in golang or node. That also makes it more likely other projects will be able to use this code across Truss.

**Comment by monfresh** [comment]
I agree with your concerns about Ruby. It wasn't my intention to introduce a new language to our project. I didn't properly communicate the purpose of this PR. I wrote this to see if I could get something working locally, and this is the kind of thing I can write faster in Ruby. Some folks asked for a PR so they could try it out the next time they're on call.

Now that I know the basic structure of the script and which API calls to make, I'm happy to translate it to Go or node.

**Comment by monfresh** [comment]
Closing in favor of #4231

**Pull request closed without merging**
