### PR TITLE
Add docker logs before anti-virus fails

### PR DESCRIPTION
**Pull request by garrettqmartin8**
## Description

Adds some more logging so we can see what happens right before the `anti-virus` script fails.

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
On line 44 you also want to add 

```sh
if ! docker inspect -f '{{.State.Running}}' "${CONTAINER_NAME}"; then 
  docker logs "${CONTAINER_NAME}"
  echo "Container not running!"
  exit 1
fi
```

Then we can ensure the container is actually running.

**Comment by chrisgilmerproj** [comment]
On line 44 you also want to add 

```sh
if ! docker inspect -f '{{.State.Running}}' "${CONTAINER_NAME}"; then 
  docker logs "${CONTAINER_NAME}"
  echo "Container not running!"
  exit 1
fi
```

Then we can ensure the container is actually running.

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj added the check for the running container

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj this seems to have worked - going to revert the circleci config update.

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj I wasn't able to catch a failure on CircleCI - I'll try again.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj I wasn't able to catch a failure on CircleCI - I'll try again.

With intermittent test failures like this you may have to run several times. I'd also suggest filtering out all the other CircleCI jobs so that this goes faster. Then you don't have to wait for integration tests or something.

**Comment by garrettqmartin8** [comment]
Should we also set that value of # of running containers in the to be super low to test that we get the error output? Can we do that for experimental only?

**Comment by garrettqmartin8** [comment]
After several runs, I still can't get `anti_virus` to fail 😅

**Comment by chrisgilmerproj** [comment]
> After several runs, I still can't get `anti_virus` to fail 😅

Try reducing the `resource_class` for this. We ought to be able to make it fail. Just curious what the trigger is. I worry that just adding this code to master isn't going to help us. We just have to keep at it for a bit.

Trust me, this isn't the worst debug problem I've ever had on CircleCI. There's still more buttons we can push on this.

**Comment by garrettqmartin8** [comment]
Cool, I'll do that. Thanks!

**Pull request merged**
