### PR TITLE
B-18986 Customer: update UI to show the shipment locator

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## PR #12471 [link](https://github.com/transcom/mymove/pull/12471)

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
LGTM

**Comment by JamesHawks224** [comment]
Updated rpt:
[B18986-12519.verify_rpt.txt](https://github.com/transcom/mymove/files/15028376/B18986-12519.verify_rpt.txt)

Still 1 diff.

**Comment by JamesHawks224** [comment]
checked out the branch.  verify server and client could run.  ran the rpt.
[B18986-12519.verify_rpt.txt](https://github.com/transcom/mymove/files/15031730/B18986-12519.verify_rpt.txt)

there are 2 diffs.

**Comment by WeatherfordAaron** [comment]
> checked out the branch. verify server and client could run. ran the rpt. [B18986-12519.verify_rpt.txt](https://github.com/transcom/mymove/files/15031730/B18986-12519.verify_rpt.txt)
> 
> there are 2 diffs.

Those changes are accurate and were technically pulled in when I re-merged to main after they updated the customer creation test.

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
