### PR TITLE
[MB-10353] Create routes and UI elements for TOO users to be able to edit shipments

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Summary

This pull request enables work to be done for TOO users to be able edit existing shipments in the `ShipmentForm`  component (renamed from `ServicesCounselingShipmentForm`). To accomplish this, this pull request:

* Creates an edit shipment route for TOO users (`/moves/:moveCode/shipments/:shipmentId`), which routes users to a TOO-specific `EditShipmentDetails` page component
* Adds an "Edit Shipment" button to the TOO's view of the `ShipmentDisplay` component, as rendered by the `RequestedShipments` component; clicking that button brings the user to the new route
* Updates approximately a billion tests and stories to incorporate these changes.

Note that the backend requires work to allow shipments which are not in the `DRAFT` status to be updatable, and that submitting the `ShipmentForm` component as a TOO user will cause the request to the backend to fail silently; this work will be captured in another ticket, as will the work to properly connect the updated endpoint logic to the front end with an integration test.

Also note that TOO users will see a different set of fields when editing shipments, but that this component is currently only configured to display Service Counselor fields; other tickets (which are presently blocked by this one) will be completed to make the fields that display on that form make logical sense.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make office_client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. In the office front end, sign in locally as a Transporting Ordering Officer user.
2. Click any of the listed moves waiting for approval, and verify that the shipment(s) for that move now display an "Edit Shipment" button at the bottom of the shipment's card.
3. Click one of those buttons to be taken to another page. Verify that the information for that shipment is pre-filled in the form, and that the URL for the page does **not** start with `officelocal:3000/counseling/`.
4. In Storybook, view the `RequestedShipments` and `ShipmentDisplay` components (under "Office Components") and verify that everything looks appropriate.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [x] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [x] There are no new console errors in the browser devtools
- [x] There are no new console errors in the test output
- [x] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots

* [Edit Shipment button displaying to user on full-width card](https://user-images.githubusercontent.com/83614364/146434808-8ef47196-a886-4af0-82c0-1dc822f8254b.png)
* [Edit Shipment button displaying to user on half-width cards](https://user-images.githubusercontent.com/83614364/146434876-a6b7c31a-450e-47e1-a1e4-b8ab0cd66827.png)

### CODE REVIEW

**Comment by kylehilltruss** [comment]
• https://my-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://admin-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://office-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://prime-milmove-pr-7931.mymove.sandbox.truss.coffee

**Review by jenniferlynparsons — COMMENTED** [review]
Code looks good! I didn't get a chance to test it, but I don't see anything that requires changing.

**Review by donaldthai — APPROVED** [review]
LGTM! 

Noticed some things not related to the PR:
- I noticed that we have to update our devseed for shipments to use `HHG` only instead of the other HHG types. 
- Might be good to remove the other HHG types from the yaml file if we don't use it

^ I'll take those things to the slack channel

**Review by YanZ777 — COMMENTED** [review]
The code looks good to me. Some of the shipments on devseed crash, but I'm not sure if that's because of bad devseed data or something else.

**Review by YanZ777 — APPROVED** [review]

**Review by amanda5iu — COMMENTED** [review]
There should be 3 units/24px of space between the bottom of the table and the top of the button. Other than that, it's looking good!

**Comment by kylehilltruss** [comment]
• https://my-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://admin-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://office-milmove-pr-7931.mymove.sandbox.truss.coffee
• https://prime-milmove-pr-7931.mymove.sandbox.truss.coffee

**Review by amanda5iu — COMMENTED** [review]
Noticed this weirdness happening with accounting codes that have no value. Will this maybe be addressed in the other tickets mentioned?

Screen Shot 2021-12-21 at 10 07 54 AM

**Comment by kylehilltruss** [comment]
> Will this maybe be addressed in the other tickets mentioned?

Yep -- I'll handle this problem in current work.

**Review by amanda5iu — APPROVED** [review]

**Pull request merged**
