### PR TITLE
B 19525 I 12786 show original delivery address INT

### PR DESCRIPTION
**Pull request by traskowskycaci**
## [I-12786](https://www13.v1host.com/USTRANSCOM38/issue.mvc/summary?oidToken=Issue%3A938897)

At the time SIT is requested, we still treat it as a non-SIT (direct delivery) shipment. We only store the original delivery/destination address at the service item level when the service item is APPROVED. This story was to show an address on that field while the service item is only requested.

Added a ternary to conditionally show either the shipment destination address (while SIT is only requested) and then after it's approved, show the service item value for the sitDestinationOriginalAddress which will be populated on SIT approval.

Also added a conditional to not show a value for the Final delivery address while the service item is in the requested state.

1. Request destination SIT on a shipment as prime.
2. As TOO, view the dest SIT service items in the requested state.
3. Verify that you see an address rather than `-` for the `Original delivery address` fields.
image
4. Verify you see `-` instead of address for the `Final delivery address` fields.
image
5. Approve all of the destination SIT service items.
6. Verify that for the Domestic destination SIT delivery and Domestic destination SIT fuel surcharge, you now see the `Final delivery address` field populated with an address value.
image

### CODE REVIEW

**Review by cameroncaci — COMMENTED** [review]
~~It isn't explicitly covered by the AC, but the description makes it seem like this should also apply to Domestic Origin, not just Destination. Can we contact Danny and see if we can get the AC enhanced real quick? Let me know if I'm mistaken as well~~
Disregard

**Review by cameroncaci — APPROVED** [review]
Would recommend also screen sharing during standup to make sure Danny only wanted the original delivery address field updated. Sometimes something could be missing from the ticket, besides that though all looks good to me!

**Review by danieljordan-caci — APPROVED** [review]
LGTM! Keep fightin' the good fight.

**Comment by traskowskycaci** [comment]
> Would recommend also screen sharing during standup to make sure Danny only wanted the original delivery address field updated. Sometimes something could be missing from the ticket, besides that though all looks good to me!

Actually met with him last Friday and showed him some screenshots and he is good with this as is!

**Pull request merged**
