### PR TITLE
B 18329 remove na from address

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

When viewing the customer's address as a TOO, the street address is present and would show as "n/a".
This PR removes that "n/a" and only shows city, state, zip for origin and dest location.

### How to test

1. Log in office as TOO
2. select a PPM move
3. Click "Move task order" tab
4. Confirm "customer's addresses" only shows city, state, zip

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

## Before:
Screenshot 2024-01-22 at 3 49 40 AM

## Updated:
Screenshot 2024-01-22 at 3 50 12 AM

### CODE REVIEW

**Comment by brooklyn-welsh** [comment]
@KonstanceH Question, the Happo tests show that the "Customer's Addresses" show the Street name, in addition to the AC fields of city, state, and ZIP. I think it makes sense to display that info, but do we have the okay from PO to do this? Just checking since the "updated" screenshot above doesn't show the street name.

**Comment by taeJungCaci** [comment]
Would this story focusing on PPM moves and not HHG? This code change looks like it may aftect HHG moves as well since there is no condition check for shipmentType right?

**Comment by brooklyn-welsh** [comment]
> Would this story be focusing on PPM moves only? This code change looks like it may affect HHG moves as well since there is no condition check for shipmentType right?

True, we'll probably need an if/switch statemen checking for `SHIPMENT_OPTIONS.PPM` (similar to the switch case at the top of the file) to make sure we don't lose the street names and other address info in HHG shipments, but only display City, State ZIP for PPMs

**Comment by KonstanceH** [comment]
> > Would this story be focusing on PPM moves only? This code change looks like it may affect HHG moves as well since there is no condition check for shipmentType right?
> 
> True, we'll probably need an if/switch statemen checking for `SHIPMENT_OPTIONS.PPM` (similar to the switch case at the top of the file) to make sure we don't lose the street names and other address info in HHG shipments, but only display City, State ZIP for PPMs

Okay I'll add that in there

**Review by WeatherfordAaron — APPROVED** [review]
LGTM

**Pull request closed without merging**
