### PR TITLE
md5sum the secure migrations and compare

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

This is the beginning of a tool that will let us compare the secure migrations in AWS S3.  Each file will be downloaded into memory and we'll take the md5 sum of it.  Those will be compared and differences posted.

## Reviewer Notes

- The output could probably be more readable.  
- Large files (exceeding 10MB) are ignored (this is configurable)
- Errors are printed at the end with an exit code equal to the number of errors (A little non-standard). This allows the entire script to finish with usable output.

## Setup

Run with:

```sh
aws-vault exec $AWS_PROFILE -- go run cmd/compare_secure_migrations/main.go
```

Output:

```sh
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/ size 0 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20180531225720_new_tspp_data.up.sql size 267691151 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20180601042522_revert_tdl_data.up.sql size 133254289 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20180829152436_august2018-tdl-update.sql size 303284524 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20180927194656_tspp-update-oct2018.sql size 303613761 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20181026202620_truss_tsp_in_prod.sql size 0 bytes
SKIP transcom-ppp-app-experimental-us-west-2 secure-migrations/20181228203158_tspp-update-dec2018.sql size 279376630 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20180518011909_2018_tdl_secure_migration.sql size 133254426 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20180531225720_new_tspp_data.up.sql size 267691151 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20180601042522_revert_tdl_data.up.sql size 133254289 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20180829152436_august2018-tdl-update.sql size 303284524 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20180927194656_tspp-update-oct2018.sql size 303613761 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20181026202620_truss_tsp_in_prod.sql size 0 bytes
SKIP transcom-ppp-app-staging-us-west-2 secure-migrations/20181228203158_tspp-update-dec2018.sql size 279376630 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20180518011909_2018_tdl_secure_migration.sql size 133254426 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20180531225720_new_tspp_data.up.sql size 267691151 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20180601042522_revert_tdl_data.up.sql size 133254289 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20180829152436_august2018-tdl-update.sql size 303284524 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20180927194656_tspp-update-oct2018.sql size 303613761 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20181017235059_test_tsp_and_tdl.sql size 0 bytes
SKIP transcom-ppp-app-prod-us-west-2 secure-migrations/20181228203158_tspp-update-dec2018.sql size 279376630 bytes
Migration: secure-migrations/20181026202620_truss_tsp_in_prod.sql
         transcom-ppp-app-experimental-us-west-2
         transcom-ppp-app-staging-us-west-2
         transcom-ppp-app-prod-us-west-2         120580e16fdc812ad6e9af2c12a2b5d2
Migration: secure-migrations/20180924221215_office-users.sql
         Hash: db09bbc502bce200ea26e7311925ec21
Migration: secure-migrations/20181128160411_add-office-users.sql
         Hash: 927340c0957f89c2037d4cc7cbd1a22b
Migration: secure-migrations/20181217161025_add-another-office-user.sql
         Hash: 5c51a8862c59c0496a5916bed951a291
Migration: secure-migrations/20180807171547_add_office_users.sql
         Hash: c062ad60c924d8644ddbe8cbaa266036
Migration: secure-migrations/20181024005814_add_trial_tsp_users.sql
         Hash: b63bdfe74e671999d146256eeb419de0
Migration: secure-migrations/20181206143208_more-hackerone-users.sql
         transcom-ppp-app-experimental-us-west-2         fa8cb338feffb6b62d10467b864d1583
         transcom-ppp-app-staging-us-west-2      e51155ffcf084c837c47c1f3a33749ff
         transcom-ppp-app-prod-us-west-2         fa8cb338feffb6b62d10467b864d1583
Migration: secure-migrations/20180831151530_august2018-new-office-users.sql
         Hash: 59137d4c8b53182f75ba4fb197b33f5e
Migration: secure-migrations/20181023231419_add_new_office_users_prod.sql
         Hash: 4003c5e1b6776693f1868eb49f6d90d0
Migration: secure-migrations/20181203210118_add-office-users.sql
         Hash: c3259013635cc3312863b785f2387474
Migration: secure-migrations/20181024190235_add_dps_users.sql
         Hash: e6987ab00bc351b4d2903ac6cf9321e6
Migration: secure-migrations/20181026174846_apostrophe-apocalypse.sql
         Hash: badac943418ea4d79cd14479b27d22e7
Migration: secure-migrations/20181210210031_even-more-hackerone-users.sql
         transcom-ppp-app-experimental-us-west-2         fa8cb338feffb6b62d10467b864d1583
         transcom-ppp-app-staging-us-west-2      d8fd1ff0e5b2cf0c2579a47d9a20d061
         transcom-ppp-app-prod-us-west-2         fa8cb338feffb6b62d10467b864d1583
Migration: secure-migrations/20180531222748_je_and_other_users.up.sql
         Hash: ca7480b65920cd4cd6363cfb0ce070a1
Migration: secure-migrations/20180806181625_add_conselors.sql
         Hash: 6a8da738cbc362498c9568c3a50751da
Migration: secure-migrations/20181017235059_test_tsp_and_tdl.sql
         transcom-ppp-app-experimental-us-west-2         0264793ebf503554efe6ee1685e8fc93
         transcom-ppp-app-staging-us-west-2      0264793ebf503554efe6ee1685e8fc93
         transcom-ppp-app-prod-us-west-2
Migration: secure-migrations/20181002001931_oct1-office-users.sql
         Hash: 0361aebc62b64abbe17897d71c2418e9
Migration: secure-migrations/20181023003944_import_trial_tsps.sql
         Hash: fad30862fdef4e999806315a02d1b35c
Migration: secure-migrations/20181026190602_add_the_real_trial_tsp_users.sql
         Hash: 4ac9c36e50c467628516872a997da160
Migration: secure-migrations/20180529024018_add_initial_office_users.up.sql
         Hash: 1d78fa35849681f1fcaadee463769d3f
Migration: secure-migrations/20180530234038_fix_initial_office_users.up.sql
         Hash: 1141b7e77a931ae50ddce4f4fc93d90d
Migration: secure-migrations/20180711230749_add_more_office_users.sql
         Hash: b7eef8546e6115f4f2666fc010c72e97
Migration: secure-migrations/20181220182247_add-office-users-#162792520.sql
         Hash: 31de6909af577736a6fea73a1ced383d
Migration: secure-migrations/20181116191945_nov16_dps_users.sql
         Hash: 53ba35b72fcb2aa4443ff500a0bc8535
Migration: secure-migrations/20181130145331_nov30_dps_users.sql
         Hash: fca0f642d9d159fc45ada5e314d68b24
Migration: secure-migrations/20181210151126_hackerone-triage-users.sql
         transcom-ppp-app-experimental-us-west-2         35c038a94582c10529afc674b40203ca
         transcom-ppp-app-staging-us-west-2      57e771b4ebc99673750a9763d2faf76f
         transcom-ppp-app-prod-us-west-2         35c038a94582c10529afc674b40203ca
Migration: secure-migrations/20180711212614_securemigrationtest.up.sql
         Hash: 2bdf1665f56c0ce5b966d9c60a7f7eac
Migration: secure-migrations/20180712151925_something.sql
         Hash: 48bdfc725fde4662aad72b9939344703
Migration: secure-migrations/20181101153739_add_and_fix_office_users.sql
         Hash: a8b94e5c49bb5a64b1d178780c07291b
Migration: secure-migrations/20181213224759_add-new-office-user.sql
         Hash: 3d6a4baa79c3188d4c271149fb43a6b5
Migration: secure-migrations/20180424010930_test.sql
         Hash: 28da233c83a01b4926123eb41c83202a
Migration: secure-migrations/20180518011909_2018_tdl_secure_migration.sql
         transcom-ppp-app-experimental-us-west-2         c5d56e73fcb44f0f75948a7a39bbd04a
         transcom-ppp-app-staging-us-west-2
         transcom-ppp-app-prod-us-west-2
Migration: secure-migrations/20181205002335_add-hackerone-users-to-staging.sql
         transcom-ppp-app-experimental-us-west-2         48bdfc725fde4662aad72b9939344703
         transcom-ppp-app-staging-us-west-2      8a1bf8c6aa2dc1c5adc1cfe380d6d310
         transcom-ppp-app-prod-us-west-2         48bdfc725fde4662aad72b9939344703
```

## Code Review Verification Steps

* [x] Request review from a member of a different team.
* [x] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/162456856) for this change

### CODE REVIEW

**Comment by akostibas** [comment]
The 10MB limit is a little odd to me, given that a large part of the work being done by the secure migrator is importing TDL data. I assume we would certainly want to know if TDL data differed per environment, but maybe I am not understanding the use case for this tool.

**Comment by chrisgilmerproj** [comment]
@akostibas - The 10MB limit is arbitrary.  Essentially you've got to download all of these files to compare them and there are 6 migrations in 3 environments that are on the 250MB+ side, meaning you get 18 concurrent large downloads.  It really takes forever and having an adjustable size meant I could test and develop without issues and check all the non-TDL migration differences.  I could up the limit to 25, 50, 100 or 200 and it would still ignore the large files.  I'm just not prepared to make a script that out-of-the-box will stop your computer from working and kill your internet.

As for real world examples, if you had to do a security audit to tell which files were different you could run this with `--max-object-size 500` and just let it run until everything is finished.  Then use that audit report as a foothold to start digging into which migrations differ from environment to environment.

**Comment by jim** [comment]
@chrisgilmerproj If we tweak how we upload files to S3, we can just get the `Content-MD5` from S3's object metadata and avoid having to download the file contents each time this is run.

**Comment by chrisgilmerproj** [comment]
@jim - I thought we'd have to upload files with the original `Content-MD5` in order to get it back.  As a backup the `Etag` is supposed to be the md5 sum but apparently multi-part uploads and some other factors I wasn't clear about can change the `Etag` to not be the md5.  I settled on downloading because it was the most straight forward way.  But if you can help me figure out how to get around this then I'd love to use the object metadata, its definitely superior all around.

**Comment by jim** [comment]
@chrisgilmerproj I think the AWS CLI (which is what we use in the [script to upload files](https://github.com/transcom/mymove/blob/b80ad3ca76cd3580ed65da706f1f1032822178bc/bin/upload-secure-migration#L79-L81)) will add that header upon submission automatically:

> The AWS CLI will calculate and auto-populate the Content-MD5 header for both standard and multipart uploads.

Or at least, that's what I see in the docs [here](https://docs.aws.amazon.com/cli/latest/topic/s3-faq.html#upload).

I'm not sure how we uploaded all of these files, as some might pre-date that script. Doing an audit of object metadata on the existing files will tell us if the checksums are there.

**Comment by jim** [comment]
@chrisgilmerproj Huh, I can't get it to return a `Content-MD5` header. I was sure I'd done that before, but I think you're right that we'd have to re-upload the files, computing a digest ourselves and adding it as object metadata.

**Comment by chrisgilmerproj** [comment]
I think that if you use the `Content-MD5` header in the upload you can get it back as the `Etag`, but it isn't always perfect (multi-part uploads), which means we can't trust it.

I talked some to @pjdufour-truss about this and our thinking is that we're going to have the highest fidelity if we just download the items each time we need to.  It's really a script for auditing so if we care about checking the huge files we can just spin up the script and wait.  As for the other files its pretty quick to run so I'm not too worried about the download.

**Comment by chrisgilmerproj** [comment]
Oh gosh, you are absolutely right @pjdufour-truss! We had talked about using the `size` attribute as a first pass and I completely forgot.  I'll make an update to this and ping you all again.

**Comment by chrisgilmerproj** [comment]
Here's an update that uses size as the comparison (which is now the default):

```
aws-vault exec $AWS_PROFILE -- go run cmd/compare_secure_migrations/main.go
```

```
Migration: secure-migrations/20181210210031_even-more-hackerone-users.sql
	 transcom-ppp-app-experimental-us-west-2 	 78
	 transcom-ppp-app-staging-us-west-2 	 806
	 transcom-ppp-app-prod-us-west-2 	 78
Migration: secure-migrations/20180529024018_add_initial_office_users.up.sql
	 size: 6462
Migration: secure-migrations/20180530234038_fix_initial_office_users.up.sql
	 size: 8060
Migration: secure-migrations/20180831151530_august2018-new-office-users.sql
	 size: 2332
Migration: secure-migrations/20181024005814_add_trial_tsp_users.sql
	 size: 3181
Migration: secure-migrations/20181024190235_add_dps_users.sql
	 size: 1079
Migration: secure-migrations/20181228203158_tspp-update-dec2018.sql
	 size: 279376630
Migration: secure-migrations/20181002001931_oct1-office-users.sql
	 size: 533
Migration: secure-migrations/20181026174846_apostrophe-apocalypse.sql
	 size: 251
Migration: secure-migrations/20181213224759_add-new-office-user.sql
	 size: 335
Migration: secure-migrations/20180601042522_revert_tdl_data.up.sql
	 size: 133254289
Migration: secure-migrations/20180711212614_securemigrationtest.up.sql
	 size: 10
Migration: secure-migrations/20180712151925_something.sql
	 size: 103
Migration: secure-migrations/20180806181625_add_conselors.sql
	 size: 2021
Migration: secure-migrations/20180927194656_tspp-update-oct2018.sql
	 size: 303613761
Migration: secure-migrations/20181217161025_add-another-office-user.sql
	 size: 345
Migration: secure-migrations/20190102144741_add_dps_cert.sql
	 transcom-ppp-app-experimental-us-west-2 	 774
	 transcom-ppp-app-staging-us-west-2 	 774
	 transcom-ppp-app-prod-us-west-2 	 258
Migration: secure-migrations/20181128160411_add-office-users.sql
	 size: 1185
Migration: secure-migrations/20181210151126_hackerone-triage-users.sql
	 transcom-ppp-app-experimental-us-west-2 	 97
	 transcom-ppp-app-staging-us-west-2 	 8789
	 transcom-ppp-app-prod-us-west-2 	 97
Migration: secure-migrations/20190102225310_remove_hackerone_accounts.sql
	 transcom-ppp-app-experimental-us-west-2 	 79
	 transcom-ppp-app-staging-us-west-2 	 5421
	 transcom-ppp-app-prod-us-west-2 	 79
Migration: secure-migrations/
	 transcom-ppp-app-experimental-us-west-2 	 0
	 transcom-ppp-app-staging-us-west-2 	Not Found
	 transcom-ppp-app-prod-us-west-2 	Not Found
Migration: secure-migrations/20180424010930_test.sql
	 size: 18
Migration: secure-migrations/20180807171547_add_office_users.sql
	 size: 456
Migration: secure-migrations/20181026190602_add_the_real_trial_tsp_users.sql
	 size: 4378
Migration: secure-migrations/20181116191945_nov16_dps_users.sql
	 size: 541
Migration: secure-migrations/20180829152436_august2018-tdl-update.sql
	 size: 303284524
Migration: secure-migrations/20181023003944_import_trial_tsps.sql
	 size: 1431
Migration: secure-migrations/20181206143208_more-hackerone-users.sql
	 transcom-ppp-app-experimental-us-west-2 	 78
	 transcom-ppp-app-staging-us-west-2 	 1194
	 transcom-ppp-app-prod-us-west-2 	 78
Migration: secure-migrations/20190104165135_add-office-users-#162914248.sql
	 size: 676
Migration: secure-migrations/20190112000534_update_office_users.sql
	 size: 438
Migration: secure-migrations/20180531225720_new_tspp_data.up.sql
	 size: 267691151
Migration: secure-migrations/20180711230749_add_more_office_users.sql
	 size: 405
Migration: secure-migrations/20181026202620_truss_tsp_in_prod.sql
	 transcom-ppp-app-experimental-us-west-2 	 0
	 transcom-ppp-app-staging-us-west-2 	 0
	 transcom-ppp-app-prod-us-west-2 	 3948
Migration: secure-migrations/20181203210118_add-office-users.sql
	 size: 4546
Migration: secure-migrations/20181220182247_add-office-users-#162792520.sql
	 size: 802
Migration: secure-migrations/20180518011909_2018_tdl_secure_migration.sql
	 transcom-ppp-app-experimental-us-west-2 	 219290
	 transcom-ppp-app-staging-us-west-2 	 133254426
	 transcom-ppp-app-prod-us-west-2 	 133254426
Migration: secure-migrations/20180531222748_je_and_other_users.up.sql
	 size: 7666
Migration: secure-migrations/20180924221215_office-users.sql
	 size: 945
Migration: secure-migrations/20181023231419_add_new_office_users_prod.sql
	 size: 2112
Migration: secure-migrations/20181219194552_add_marine_corps_orders_cert.sql
	 transcom-ppp-app-experimental-us-west-2 	 508
	 transcom-ppp-app-staging-us-west-2 	 508
	 transcom-ppp-app-prod-us-west-2 	 255
Migration: secure-migrations/20181017235059_test_tsp_and_tdl.sql
	 transcom-ppp-app-experimental-us-west-2 	 3820
	 transcom-ppp-app-staging-us-west-2 	 3820
	 transcom-ppp-app-prod-us-west-2 	 0
Migration: secure-migrations/20181101153739_add_and_fix_office_users.sql
	 size: 1075
Migration: secure-migrations/20181130145331_nov30_dps_users.sql
	 size: 219
Migration: secure-migrations/20181205002335_add-hackerone-users-to-staging.sql
	 transcom-ppp-app-experimental-us-west-2 	 103
	 transcom-ppp-app-staging-us-west-2 	 22258
	 transcom-ppp-app-prod-us-west-2 	 103
```

Here are the new options:

```
aws-vault exec $AWS_PROFILE -- go run cmd/compare_secure_migrations/main.go --help
Usage of /var/folders/by/wb9l8d6x7ld8gz2gdx5cdcth0000gn/T/go-build493842795/b001/exe/main:
      --aws-s3-region string   AWS region used for S3 file storage
      --comparison string      Comparison used against files, either 'size' or 'md5' (default "size")
      --max-object-size int    The maximum size of files to download in MB for use with md5 comparison (default 10)
pflag: help requested
exit status 2
```

You can still compare with md5 using:

```
aws-vault exec $AWS_PROFILE -- go run cmd/compare_secure_migrations/main.go --comparison md5
```

**Pull request merged**
