### PR TITLE
[MB-2477] Add trace middleware to prime and support api

### PR DESCRIPTION
**Pull request by shimonacarvalho**
## Description

Trace middleware will help us connect error messages sent to to client with logger messages in the server. It's not hooked up on prime or support - hooking it up here. 

## Setup

Send a request using prime api client or postman to a prime endpoint and a support endpoint. Both should have a populated milmove_trace_id in the logger.

```
2020-05-04T23:06:03.980Z	INFO	middleware/request_logger.go:85	Request	{
  "git_branch": "sc-mb-2477-add-trace-middleware",
  "git_commit": "5dc329b3388322aef4de2535cfbc9bad95a82ca0",
  "milmove_trace_id": "5be63436-691a-489d-af17-13be3ee2b220",
  "accepted-language": "",
  "content-length": 489,
  "host": "primelocal:9443",
  "method": "POST",
  "protocol-version": "HTTP/1.1",
  "referer": "",
  "source": "127.0.0.1:56748",
  "url": "/support/v1/move-task-orders",
  ...
}
```
### Related
- [[MB-2477] Add trace middleware to prime - Jira](https://dp3.atlassian.net/browse/MB-2477)

[MB-2477]: https://dp3.atlassian.net/browse/MB-2477

### CODE REVIEW

**Comment by shimonacarvalho** [comment]
> Do you also want to add this to the `ordersMux`, `dpsMux` and `sddcDPSMux`? My guess is yes. So could we add this to `site` instead? Would that cause an issue?

Actually we are trying hard to not let tickets change scope at PR stage because this is very hard for us to to plan around. I'd be happy to make another ticket for that though. We needed this for Prime API asap because the prime is going to start reporting errors and we needed this to effectively find them in the logs.

**Comment by chrisgilmerproj** [comment]
> Actually we are trying hard to not let tickets change scope at PR stage because this is very hard for us to to plan around. I'd be happy to make another ticket for that though. We needed this for Prime API asap because the prime is going to start reporting errors and we needed this to effectively find them in the logs and support them.

I hear that but I'm trying to point out that you've put it in the wrong place. It doesn't belong on a per-handler setup. It belongs at the root of the handler for all app-client-tls routes. Which means that your PR should be updated. It would mean less code overall and it's just a copy and paste of your middleware to higher in the file.

You can choose to have someone else approve this but I think its more important to do what is right for the code instead of what's right for the JIRA story.

**Comment by shimonacarvalho** [comment]
> > Actually we are trying hard to not let tickets change scope at PR stage because this is very hard for us to to plan around. I'd be happy to make another ticket for that though. We needed this for Prime API asap because the prime is going to start reporting errors and we needed this to effectively find them in the logs and support them.
> 
> I hear that but I'm trying to point out that you've put it in the wrong place. It doesn't belong on a per-handler setup. It belongs at the root of the handler for all app-client-tls routes. Which means that your PR should be updated. It would mean less code overall and it's just a copy and paste of your middleware to higher in the file.
> 
> You can choose to have someone else approve this but I think its more important to do what is right for the code instead of what's right for the JIRA story.

It's not just a copy paste as I wouldn't want to check it in without testing the 3 paths you mention. Can you explain how to make requests to hit the 3 paths you mentioned so I can check the logger and make sure the trace id is working on those paths?

**Comment by chrisgilmerproj** [comment]
> It's not just a copy paste as I wouldn't want to check it in without testing the 3 paths you mention. Can you explain how to make requests to hit the 3 paths you mentioned so I can check the logger and make sure the trace id is working on those paths?

We talked on Slack and I provided these links:
- [Testing Electronic Orders](https://github.com/transcom/mymove/wiki/upload-electronic-orders)
- [DPS Authentication](https://drive.google.com/drive/folders/1nurBJWLvsQeNN8rq1qQOnAsgEhf9I0R1/1nurBJWLvsQeNN8rq1qQOnAsgEhf9I0R1)

I'm also happy to help with testing this PR if the middleware is updated.

**Comment by shimonacarvalho** [comment]
@chrisgilmerproj I'm seeing an error on following the orders/nom procedure you linked but I also realized on doing that, that `requestLogger` is not hooked up on site. So even if we were to hook up trace-id, I'm not entirely sure if that trace-id will be exposed anywhere. 

Also I recall that I tried to move `requestLogger` up to site before, and when I did so, other information stopped being logged on ghc/prime logs (`client_cert_id`, and ironically `milmove_trace_id`).

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj I'm seeing an error on following the orders/nom procedure you linked but I also realized on doing that, that `requestLogger` is not hooked up on site. So even if we were to hook up trace-id, I'm not entirely sure if that trace-id will be exposed anywhere.

Can you link your test procedure and copy the errors? I'll take a look. 

> Also I recall that I tried to move `requestLogger` up to site before, and when I did so, other information stopped being logged on ghc/prime logs (`client_cert_id`, and ironically `milmove_trace_id`). Might be an ordering thing that would work if we moved up trace, but i wouldn't want to lose client_cert_id.

Sounds like there's an issue with our middleware that is hiding here. We ought to figure this out.

**Comment by shimonacarvalho** [comment]
> Can you link your test procedure and copy the errors? I'll take a look.
So I followed the instructions in here https://github.com/transcom/mymove/wiki/upload-electronic-orders

Copied down this file - `nom_demo_20190404.csv`, set `$TOKEN` and `$MODULE`
And ran this command in the nom repo 
`bin/nom -host orderslocal -port 9443 --insecure --pkcs11module "${MODULE}" nom_demo_20190404.csv`

The error I got was: 
`2020/05/07 17:03:40 Post "https://orderslocal:9443/orders/v1/orders?issuer=navy&memberId=666xxx&ordersNum=N00xxx": remote error: tls: error decrypting message`

(I replaced the memberID and ordersNum when pasting that error here)

One thing I was unsure of - I checked that the `IWS_RBS_HOST` was set as you described in the article, but I noticed there's also an `IWS_RBS_ENABLED` which is set to 0. Do I want that set to 1?

**Comment by chrisgilmerproj** [comment]
> So I followed the instructions in here
> https://github.com/transcom/mymove/wiki/upload-electronic-orders
> 
> Copied down this file - `nom_demo_20190404.csv`, set `$TOKEN` and `$MODULE`
> And ran this command in the nom repo
> `bin/nom -host orderslocal -port 9443 --insecure --pkcs11module "${MODULE}" nom_demo_20190404.csv`
> 
> The error I got was:
> `2020/05/07 17:03:40 Post "https://orderslocal:9443/orders/v1/orders?issuer=navy&memberId=666xxx&ordersNum=N00xxx": remote error: tls: error decrypting message`
>  
> (I replaced the memberID and ordersNum when pasting that error here)

Typically this means there's a certificate mismatch of some kind. I've seen it before and I bet its either something to do with the CAC (which should be supplied with migrations) or with env vars being loaded.   

> One thing I was unsure of - I checked that the `IWS_RBS_HOST` was set as you described in the article, but I noticed there's also an `IWS_RBS_ENABLED` which is set to 0. Do I want that set to 1?

Setting it to 0 is fine because it means the app won't reach out to IWS RBS to ask for SSNs. Instead a fake person function is used to generate data that goes into the dev DB.

I'll use this same procedure a bit later and test it out.

**Comment by shimonacarvalho** [comment]
My cac was plugged in and it did request a pin, just fyi.
I checked my db and the client certs table is populated with my info. 
The only thing I can think of is I used the token off my cac (my fullname with periods etc), but in my local db, what's populated in the `subject` is my github username (where the token used to be).

**Comment by chrisgilmerproj** [comment]
I noticed your command is

```sh
bin/nom -host orderslocal -port 9443 --insecure --pkcs11module "/usr/local/lib/pkcs11/opensc-pkcs11.so" nom_demo_20190404.csv
```

whereas the one I use is 

```sh
bin/nom -host orderslocal -port 7443 -insecure -pkcs11module "${MODULE}" nom_demo_20190404.csv
```

The difference being `-` vs `--` in the command line flags. However, I don't think that's the issue. I think there's a problem with the TLS configuration in `bin/nom`. So instead, let's do an approach that I know works.

---

You can go to https://github.com/transcom/milmove_orders/, clone the repo and build the client. Here are the commands.

```sh
make bin/orders-api-client
orders-api-client --cac --hostname orderslocal --port 9443 --insecure post-revisions --issuer navy --csv-file testdata/nom_demo_20190404.csv
```

You should see output like this on success:

```json
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW61XA","revisions":[{"dateIssued":"2017-10-27T00:00:00.000-07:00","gainingUnit":{"city":"ARLINGTON","country":"US","locality":"VA","name":"ARLING","uic":"N64168"},"hasDependents":false,"losingUnit":{"city":"NORFOLK","country":"US","locality":"VA","name":"NORVA","uic":"N21411"},"member":{"affiliation":"navy","familyName":"BELSON","givenName":"Gabriell","rank":"o-3","title":"Lieutenant"},"ntsAccounting":{},"ordersType":"operational","pcsAccounting":{"tac":"NM48"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2017-12-31","seqNum":2,"status":"authorized","tourType":"accompanied","ubAccounting":{}}],"uuid":"b17826d7-dd36-4791-97d0-24dfb5b904a2"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW61U8","revisions":[{"dateIssued":"2017-10-04T00:00:00.000-07:00","gainingUnit":{"city":"NORTH ISLAND","country":"US","locality":"CA","name":"NORTI","uic":"N55139"},"hasDependents":false,"losingUnit":{"city":"MILTON","country":"US","locality":"FL","name":"MILTON","uic":"N44988"},"member":{"affiliation":"navy","familyName":"Verderame","givenName":"Jamaad","rank":"o-2","title":"Lieutenant Junior Grade"},"ntsAccounting":{},"ordersType":"training","pcsAccounting":{"tac":"NM38"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2017-11-30","seqNum":1,"status":"authorized","tourType":"accompanied","ubAccounting":{}}],"uuid":"4a86aad8-27cf-460b-8876-dd5a7c27f240"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW61ZL","revisions":[{"dateIssued":"2017-11-03T00:00:00.000-07:00","gainingUnit":{"city":"GARDEN CITY","country":"US","locality":"NY","name":"GARDEN","uic":"N62445"},"hasDependents":false,"losingUnit":{"city":"CORONADO","country":"US","locality":"CA","name":"CORNDO","uic":"N46462"},"member":{"affiliation":"navy","familyName":"Tech","givenName":"Saymon","rank":"o-3","title":"Lieutenant"},"ntsAccounting":{},"ordersType":"training","pcsAccounting":{"tac":"NM38"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2017-11-30","seqNum":3,"status":"authorized","tdyEnRoute":true,"tourType":"accompanied","ubAccounting":{}}],"uuid":"b4bf42ea-3830-4099-be9e-b3d00c120cdd"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW620Q","revisions":[{"dateIssued":"2018-06-12T00:00:00.000-07:00","gainingUnit":{"city":"OAK HARBOR","country":"US","locality":"WA","name":"O HARB","uic":"N4353A"},"hasDependents":true,"losingUnit":{"city":"STATE COLLEGE","country":"US","locality":"PA","name":"STATEC","uic":"N63310"},"member":{"affiliation":"navy","familyName":"Weatherford","givenName":"Turley","rank":"o-3","title":"Lieutenant"},"ntsAccounting":{},"ordersType":"operational","pcsAccounting":{"tac":"NM48"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2018-10-31","seqNum":1,"status":"authorized","tdyEnRoute":true,"tourType":"accompanied","ubAccounting":{}}],"uuid":"bcad440b-92c4-4bf4-9ad1-02c3f8f8edba"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW61PN","revisions":[{"dateIssued":"2017-10-11T00:00:00.000-07:00","gainingUnit":{"city":"NORTH ISLAND","country":"US","locality":"CA","name":"NORTI","uic":"N55139"},"hasDependents":false,"losingUnit":{"city":"MILTON","country":"US","locality":"FL","name":"MILTON","uic":"N44988"},"member":{"affiliation":"navy","familyName":"KIRSTENRIVAS","givenName":"Liette","middleName":"Victoria","rank":"o-2","title":"Lieutenant Junior Grade"},"ntsAccounting":{},"ordersType":"training","pcsAccounting":{"tac":"NM38"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2017-11-30","seqNum":2,"status":"authorized","tourType":"accompanied","ubAccounting":{}}],"uuid":"f37d70d0-5a88-4608-bef0-a43481757617"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW620R","revisions":[{"dateIssued":"2017-10-04T00:00:00.000-07:00","gainingUnit":{"city":"SAN DIEGO","country":"US","locality":"CA","name":"SDGO","uic":"N21465"},"hasDependents":false,"losingUnit":{"city":"CHARLESTON","country":"US","locality":"SC","name":"CHARLE","uic":"N47801"},"member":{"affiliation":"navy","familyName":"Harris-Grant","givenName":"Johnie","rank":"o-2","title":"Lieutenant Junior Grade"},"ntsAccounting":{},"ordersType":"training","pcsAccounting":{"tac":"NM38"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2017-11-30","seqNum":1,"status":"authorized","tourType":"accompanied","ubAccounting":{}}],"uuid":"db9f646e-1150-4e81-a0b8-aa3fd13321c4"}
{"edipi":"1234567890","issuer":"navy","ordersNum":"N0002218CTW6249","revisions":[{"dateIssued":"2018-05-21T00:00:00.000-07:00","gainingUnit":{"city":"SAN DIEGO","country":"JA","locality":"CA","name":"SDGO","uic":"N22202"},"hasDependents":false,"losingUnit":{"city":"SAN DIEGO","country":"US","locality":"CA","name":"SDGO","uic":"N55687"},"member":{"affiliation":"navy","familyName":"Seamaster","givenName":"Azantae","rank":"o-2","title":"Lieutenant Junior Grade"},"ntsAccounting":{},"ordersType":"operational","pcsAccounting":{"tac":"NM48"},"povShipmentAccounting":{},"povStorageAccounting":{},"reportNoLaterThan":"2018-10-31","seqNum":4,"status":"authorized","tdyEnRoute":true,"tourType":"accompanied","ubAccounting":{}}],"uuid":"9296f16a-04b8-4cd8-8234-a16ba9fcc23c"}
```

You can check your dev db this way:

```sh
$ psql-dev
localhost:5432 postgres@dev_db=# select * from electronic_orders;
                  id                  |  orders_number  |   edipi    | issuer |         created_at         |         updated_at
--------------------------------------+-----------------+------------+--------+----------------------------+----------------------------
 b17826d7-dd36-4791-97d0-24dfb5b904a2 | N0002218CTW61XA | 1234567890 | navy   | 2020-05-11 21:16:00.523538 | 2020-05-11 21:16:00.523542
 4a86aad8-27cf-460b-8876-dd5a7c27f240 | N0002218CTW61U8 | 1234567890 | navy   | 2020-05-11 21:16:00.546704 | 2020-05-11 21:16:00.546707
 b4bf42ea-3830-4099-be9e-b3d00c120cdd | N0002218CTW61ZL | 1234567890 | navy   | 2020-05-11 21:16:00.561753 | 2020-05-11 21:16:00.561755
 bcad440b-92c4-4bf4-9ad1-02c3f8f8edba | N0002218CTW620Q | 1234567890 | navy   | 2020-05-11 21:16:00.579322 | 2020-05-11 21:16:00.579326
 f37d70d0-5a88-4608-bef0-a43481757617 | N0002218CTW61PN | 1234567890 | navy   | 2020-05-11 21:16:00.599822 | 2020-05-11 21:16:00.599826
 db9f646e-1150-4e81-a0b8-aa3fd13321c4 | N0002218CTW620R | 1234567890 | navy   | 2020-05-11 21:16:00.622904 | 2020-05-11 21:16:00.62291
 9296f16a-04b8-4cd8-8234-a16ba9fcc23c | N0002218CTW6249 | 1234567890 | navy   | 2020-05-11 21:16:00.649594 | 2020-05-11 21:16:00.649598
(7 rows)

Time: 2.354 ms
```

Hopefully that's sufficient to get you off the ground here. Also, I may go and update the wiki shortly to modify the instructions for use with the new repo for e-orders.

**Comment by chrisgilmerproj** [comment]
I found the issue with `bin/nom` and made a PR: https://github.com/transcom/nom/pull/7

**Comment by shimonacarvalho** [comment]
> Do you want to make a similar PR in transcom/milmove_orders or would you like me to take that on?

I'd appreciate if you took that on. API stuff is getting more intense every minute now that we are working with the Prime.

**Comment by chrisgilmerproj** [comment]
Here's the PR for milmove_orders: https://github.com/transcom/milmove_orders/pull/118

**Pull request merged**
