### PR TITLE
switch to make_env_migrations defaulting to govcloud

### PR DESCRIPTION
**Pull request by kilbergr**
## Description

This PR changes the make command destination for migrations to default to gov rather than commercial cloud. The commercial commands still remain.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make run_experimental_migrations
make run_staging_migrations
make run_prod_migrations
```

## Code Review Verification Steps

* [ ] Request review from a member of a different team.

### CODE REVIEW

**Review by esacteksab — APPROVED** [review]

**Review by cblkwell — APPROVED** [review]

**Comment by donaldthai** [comment]
Unrelated to the change I think but when I run `run_gov_prod_migrations`: 

```
2020-09-11T16:53:12.743Z        FATAL   milmove/migrate.go:287  Error listing migrations directory s3://transcom-gov-milmove-prd-app-us-gov-west-1/secure-migrations    {"git_branch": "MB-4186", "git_commit": "4693b56a480469749ea776cc509336fe5b22d5df", "error": "NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: AR5Q3Z1Z3NFV2Y3Y, host id: wBUiNxjb8aVQTB+FdR6fHZnolUo5sTadRJBf8qgxrCrb1VmA2wtr6uAAR+gXkzaAnC85f9Nr+s0="}
main.migrateFunction
```

**Comment by gidjin** [comment]
I ran `make run_experimental_migrations` and it fails. I get the same result for make run_staging_migrations and run_prod_migrations. Is there additional setup I need to do to make this work?

```sh
❯ make run_experimental_migrations
Destroying the milmove-db-deployed-migrations docker database container...
docker rm -f milmove-db-deployed-migrations || echo "No database container"
milmove-db-deployed-migrations
rm -fr mnt/db_deployed_migrations # delete mount directory if exists
brew services stop postgresql 2> /dev/null || true
Starting the milmove-db-deployed-migrations docker database container...
# If running do nothing, if not running try to start, if can't start then run
docker start milmove-db-deployed-migrations || \
                docker run -d --name milmove-db-deployed-migrations \
                        -e POSTGRES_PASSWORD=mysecretpassword \
                        -p 5434:5432\
                        postgres:12.2
Error response from daemon: No such container: milmove-db-deployed-migrations
Error: failed to start containers: milmove-db-deployed-migrations
5cb843af5ec221807418677d71799138f3c9b4f1a27ae13ca8a2a060abadcee2
Create the deployed_migrations database...
DB_NAME=postgres DB_PORT=5434 scripts/wait-for-db && \
                createdb -p 5434 -h localhost -U postgres deployed_migrations || true
> psql postgres://postgres:mysecretpassword@localhost:5434/postgres -c 'select 1;' > /dev/null 2>&1
Checking for database connectivity....success!
Migrating the experimental-migrations database with experimental migrations...
MIGRATION_PATH="s3://transcom-gov-milmove-exp-app/secure-migrations;file://migrations/app/schema" \
        DB_HOST=localhost \
        DB_PORT=5434 \
        DB_NAME=deployed_migrations \
        DB_DEBUG=0 \
        bin/milmove migrate
2020-09-11T18:27:47.012Z        INFO    milmove/migrate.go:179  migrator starting up    {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:27:47.012Z        INFO    milmove/migrate.go:61   checking migration config       {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:27:47.012Z        INFO    milmove/migrate.go:193  using migration paths ["s3://transcom-gov-milmove-exp-app/secure-migrations" "file://migrations/app/schema"]   {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020/09/11 18:27:47 Loading config file /Users/john/.aws/config
2020/09/11 18:27:47 Parsing config file /Users/john/.aws/config
2020/09/11 18:27:47 Looking for sessions for transcom-ppp
2020/09/11 18:27:47 Looking up all keys in keyring
2020/09/11 18:27:47 Session "transcom-ppp session (1588965483)" expires in -3023h9m44.044653s
2020/09/11 18:27:47 Session transcom-ppp session (1588965483) is expired, attempting deleting
2020/09/11 18:27:47 Error deleting session: Keychain Error. (-25244)
2020/09/11 18:27:47 Session "transcom-ppp session (1597181772)" expires in -740h51m35.047305s
2020/09/11 18:27:47 Session transcom-ppp session (1597181772) is expired, attempting deleting
2020/09/11 18:27:47 Error deleting session: Keychain Error. (-25244)
2020/09/11 18:27:47 Session not found in keyring for transcom-ppp
2020/09/11 18:27:47 Looking up keyring for transcom-ppp
Enter token for arn:aws:iam::923914045601:mfa/gidjin: 815706
2020/09/11 18:28:05 Using region "us-west-2" from AWS_DEFAULT_REGION
2020/09/11 18:28:05 Getting new session token for profile transcom-ppp
2020/09/11 18:28:05 Writing session for transcom-ppp to keyring: "transcom-ppp session (1599863285)"
2020/09/11 18:28:05 Using session ****************G2AV, expires in 3h59m59.216976s
2020/09/11 18:28:05 Using region "us-west-2" from AWS_DEFAULT_REGION
2020/09/11 18:28:05 Assuming role arn:aws:iam::923914045601:role/engineer from session token
2020/09/11 18:28:05 Using role ****************YC4V (from session token), expires in 29m59.117085s
2020-09-11T18:28:05.884Z        INFO    cli/dbconn.go:257       Connecting to the database      {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58", "url": "postgres://postgres:*****@localhost:5434/deployed_migrations?sslmode=disable", "db-ssl-root-cert": ""}
2020-09-11T18:28:05.884Z        INFO    cli/dbconn.go:362       Starting database ping....      {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:28:05.902Z        INFO    cli/dbconn.go:369       ...DB ping successful!  {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:28:05.902Z        INFO    milmove/migrate.go:267  tracking migrations using table "schema_migration"    {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:28:05.902Z        INFO    milmove/migrate.go:270  using migration manifest "file:///Users/john/projects/dod/mymove/migrations/app/migrations_manifest.txt"       {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58"}
2020-09-11T18:28:06.330Z        FATAL   milmove/migrate.go:287  Error listing migrations directory s3://transcom-gov-milmove-exp-app/secure-migrations {"git_branch": "master", "git_commit": "14b82a10180ef15468f300147386bb8116e00d58", "error": "NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 6850A5E003D49D4E, host id: Z3ExB+leIHZz/BQ/Tl3+jaWEJUX4Ig7Z5E0do6Zgj9gCNFr6wmIeIi6KNYS45dCY9nDkih7A69w="}
main.migrateFunction
        /Users/john/projects/dod/mymove/cmd/milmove/migrate.go:287
github.com/spf13/cobra.(*Command).execute
        pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838
github.com/spf13/cobra.(*Command).ExecuteC
        pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943
github.com/spf13/cobra.(*Command).Execute
        pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
main.main
        /Users/john/projects/dod/mymove/cmd/milmove/main.go:121
runtime.main
        /usr/local/Cellar/go/1.15/libexec/src/runtime/proc.go:204
make: *** [run_gov_experimental_migrations] Error 1
```

**Review by gidjin — COMMENTED** [review]
things didn't work right when I tried, see comment on PR

**Comment by kilbergr** [comment]
Yes---so--we're having a problem with regions! Update soon.

**Pull request closed without merging**
