### PR TITLE
B 18821 int

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary
added okta-office-group-id for each env

in addition to this code pr, also review chamber values as they match to the ids in the agility artifact

https://dp3.atlassian.net/wiki/spaces/MT/pages/1249542242/0030+How+to+Manage+Secrets+with+Chamber

### CODE REVIEW

**Comment by cameroncaci** [comment]
Group ids aren't sensitive information to my knowledge, thoughts on putting them in the deployment vars so we don't have to worry about chamber?

**Comment by deandreJones** [comment]
> Group ids aren't sensitive information to my knowledge, thoughts on putting them in the deployment vars so we don't have to worry about chamber?

not - completely sensitive, but for the production env, they are treating the office role as a highly privileged role, so we dont want to expose the ID to anyone, so they cant manually add themselves to the group

**Comment by cameroncaci** [comment]
> > Group ids aren't sensitive information to my knowledge, thoughts on putting them in the deployment vars so we don't have to worry about chamber?
> 
> not - completely sensitive, but for the production env, they are treating the office role as a highly privileged role, so we dont want to expose the ID to anyone, so they cant manually add themselves to the group

Okta should offer the group management necessary to where you can't self-add yourself to a group, then even though the ID is exposed nobody can access it unless explicitly added by admins

**Comment by cameroncaci** [comment]
If self adding is a thing we probably want to restrict that from office

**Comment by deandreJones** [comment]
> Group ids aren't sensitive information to my knowledge, thoughts on putting them in the deployment vars so we don't have to worry about chamber?

one thing i will say about moving them, is that seperates where the okta_keys* would be kept.. and i lean toward consistency for things like this

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
