### PR TITLE
B 18310 multi move feature flag

### PR DESCRIPTION
**Pull request by cameroncaci**
[Integration PR](https://github.com/transcom/mymove/pull/11753)

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Do you want these three commits in here going to main?
image

**Review by TevinAdams — APPROVED** [review]

**Comment by cameroncaci** [comment]
> Do you want these three commits in here going to main? image

@deandreJones Thoughts?

**Comment by deandreJones** [comment]
> Also, should the multiMove flag be true for going into main or false for now?

false

**Comment by cameroncaci** [comment]
> Also, should the multiMove flag be true for going into main or false for now?

True because the flipt change is right behind this one - This one is still using the old method

**Comment by cameroncaci** [comment]
If we change it then it will become out of sync with integration - this is only setting multi move to be `true` in dev, exp, and loadtest (Until Flipt goes through and then Flipt will manage it)

**Comment by cameroncaci** [comment]
> > > Do you want these three commits in here going to main? image
> > 
> > 
> > @deandreJones Thoughts?
> 
> good catch- the circle config changes need to be default

Want me to rebase your commits then?

**Comment by cameroncaci** [comment]
@traskowskycaci @TevinAdams @deandreJones 
Closing this PR and putting up a new one - git history rebasing was unfortunately messy due to merges. See clean PR here: https://github.com/transcom/mymove/pull/11984

**Pull request closed without merging**
