### PR TITLE
[ MB-16671 ] Use sit origin hhg original address for origin sit service area payment

### PR DESCRIPTION
**Pull request by mmayo-truss**
## Summary

This PR updates the calculations for the Service Area Origin param so that it is utilizing the SIT origin HHG original address instead of the shipment's pickup address for origin SIT service items. 

I modeled the change off of [this PR](https://github.com/transcom/mymove/pull/10918), which does something similar for destination SIT service items. 

I also updated the ZipPickup param to reflect the SIT origin HHG original address for origin SIT service items as well.  

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test
Okay so this is a little complicated. We are basically testing that we are using the service_area associated with the `SITOriginHHGOriginalAddress` and not the service area associated with the `SITOriginHHGActualAddress`. When you create a SIT service item, the value supplied in the actual address is copied to the shipment pickup address as well. 

So you want to make a move that has an original pickup address that has a different service area from the `SITOriginHHGActualAddress` you provide when creating the origin SIT service item.

I used the following:
pickup zip 90210 is in service area `056`
`SITOriginHHGActualAddress` zip 12345 is in `536`

If you would like you can use the following query to verify other zips on your own:
```SQL
select service_area from re_domestic_service_areas rdsa
join re_zip3s rz3 on rz3.domestic_service_area_id = rdsa.id
	where rz3.zip3 = '<first 3 digits of the zipcode>';
```

1. Create a move as a customer or find a new move as a TOO. Most generated moves will be from pickup zip 90210. 
2. Login as a TOO and make the move available to the prime. You may need to add info to the orders for it to be approvable.
3. Log in to the prime simulator and create the origin SIT service items. Make sure to provide a `SITOriginHHGActualAddress` that has a zip code that is in a different service area than the initial pickup address.
4. Log back in as a TOO and approve the service items.
5. Log back in as the prime and create a payment request for the origin SIT service items
6. Log back in as a TIO and review the service items. 
7. View the Domestic origin add't SIT and the first day SIT service items. Click on 'show calculations' and you should see the SIT Origin service area display the correct service area
image

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by NamibiaTorres — APPROVED** [review]
Thanks for making this fix @mmayo-truss. Work looks good! Appreciate the hard work.

**Comment by NamibiaTorres** [comment]
I went ahead and approved the Happo changes. Looks like it was two files with a few pixels of difference, but they were also not related to the work you did.

**Comment by mmayo-truss** [comment]
@dinabeigelman I marked this review for a design review since there is a slight change to the wording in the calculations area. It used to say "Origin service area" and it now says "SIT Origin service area"

**Review by kctruss — APPROVED** [review]
Migrations look good. I set up some move data to verify no data migration errors, and we're 💯  there. Nice work!

**Comment by khayenis** [comment]
@kctruss @michaelvaldes-truss I would suggest changing the text to "SIT origin service area" (with a lowercase 'o'). This will  be consistent with other areas of the app.

**Comment by kctruss** [comment]
> @kctruss @michaelvaldes-truss I would suggest changing the text to "SIT origin service area" (with a lowercase 'o'). This will be consistent with other areas of the app.

Thanks @khayenis ! To confirm, for destination SIT we're currently using the text "SIT Destination service area" (capital 'D') - should that be changed as well?

**Comment by kctruss** [comment]
> > > @kctruss @michaelvaldes-truss I would suggest changing the text to "SIT origin service area" (with a lowercase 'o'). This will be consistent with other areas of the app.
> > 
> > 
> > Thanks @khayenis ! To confirm, for destination SIT we're currently using the text "SIT Destination service area" (capital 'D') - should that be changed as well?
> 
> Yes, please change 'destination' to lowercase as well. Thanks for catching that! @kctruss

Done @khayenis !

**Review by khayenis — APPROVED** [review]
Approved , thanks!

**Pull request merged**
