### PR TITLE
WIP Add endpoint, models and handlers to fetch transportation office for duty station

### PR DESCRIPTION
**Pull request by amitch23**
## Description

Add endpoint, models and handlers to fetch transportation office for duty station

## Reviewer Notes

Note: Currently only returning the address and phone number on the transportation office if the phone number is a voice (not a fax number). If a transportation office does not exist for a duty station, an object with zero values are returned.

## Code Review Verification Steps

* [x] All tests pass.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/blob/master/docs/backend.md#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/blob/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] Any migrations/schema changes also update the diagram in docs/schema/dp3.sqs
* [ ] There are no aXe warnings for UI.
* [ ] This works in IE.
* Any new client dependencies (Google Analytics, hosted libraries, CDNs, etc) have been:
  * [ ] Communicated to @willowbl00
  * [ ] Added to the list of [network dependencies](https://github.com/transcom/mymove#client-network-dependencies)
* [x] Request review from a member of a different team.
* [ ] (TRIAL) Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/157945475) for this change

## Screenshots

screen shot 2018-05-30 at 3 35 31 pm

### CODE REVIEW

**Comment by tinyels** [comment]
@jim I agree that a 404 would be better when there is no data. While it may seem strange to fetch an object by the id of another thing, we already do that in `/service_members/{serviceMemberId}/current_orders`

**Comment by jim** [comment]
@tinyels Do you know if we are trying to not expose the orders or Transportation Office IDs for a specific reason? Having the actual object ID is better for the client (it knows if the object exist without making a request).

**Comment by tinyels** [comment]
@jim We decided to do it this way to avoid touching already done things at this point in the release. I can add a story to clean it up after today, but a feature that is MVP depends on this endpoint.

**Comment by jim** [comment]
@tinyels @amitch23 and I talked about this and I'm good with just changing the response to a 404 when appropriate. Will approve when that lands.

**Pull request merged**
