### PR TITLE
B-21363 INT

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

This is adding in some explicit feature flag checks for UB shipments, dependent on the unaccompanied_baggage FF being enabled or not.

To test, please verify the following AC:

Use the createMTOShipment to create a UB. Example body for creating a shipment with the createMTOShipment:
```
{
  "moveTaskOrderID": "91154a53-6880-460b-a270-57bcb53d631a",
  "shipmentType": "UNACCOMPANIED_BAGGAGE",
  "requestedPickupDate": "2024-10-04",
  "pickupAddress": {
      "streetAddress1": "123 Main St",
      "city": "Nicholasville",
      "state": "KY",
      "postalCode": "40356",
      "country": "US",
      "county": "JESSAMINE"
   }
}
```

Given I am interacting with the MilMove customer app
When the unaccompanied_baggage FF is disabled and I try to create a shipment
Then I receive a 422 response with a message of "Unaccompanied baggage shipments can't be created unless the unaccompanied_baggage feature flag is enabled"

Given I am interacting with the MilMove customer app
When I have previously created a UB shipment with the unaccompanied_baggage FF on, but then turn the unaccompanied_baggage FF off
Then I can no longer see the UB shipments listed

With the UB FF on after creating UB shipments:
image

With the UB FF off after creating UB shipments:
image

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
*chef kiss*

Screenshot 2024-10-17 at 8 50 42 AM

**Review by TevinAdams — CHANGES_REQUESTED** [review]
When FF is off i am still able to see UB shipment

**Comment by traskowskycaci** [comment]
> When FF is off i am still able to see UB shipment

Great catch, did some cleanup and removed too much code yesterday. Give 'er a pull and retest when you can!

**Review by TevinAdams — APPROVED** [review]
After cleanup i no longer see the UB shipment when F is off.

**Pull request merged**
