### PR TITLE
Add pre-commit hook for running model-vet

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

I've seen a few recent PRs pass through where the DB schema didn't match the code. Jim wrote an excellent tool for this but it didn't make it into our pre-commit checks. This is probably because several of the models need to be fixed with new migrations. This PR adds the pre-commit check but it won't pass until we fix the DB.

## Setup

```sh
pre-commit-model-vet
```

Also try `pre-commit run -a model-vet`.

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
> LGTM... I assume we'll keep this branch unmerged but up to date with master till we fix some of the discrepancies? Or can we split this into a separate pre-commit that won't block if/when it fails as we're fixing changes...?
> only blocking till I know more...

Yeah, I figure we should keep this unmerged until we have a migration to fix all the discrepancies. I don't think this is one where we can add it and let it pass while we fix stuff because folks will just ignore the output. 

I'd also love for someone to take this over since it touches application code. I mostly wanted to get the ball rolling here so we wouldn't forget. Essentially each error here represents a bug that is in production but hasn't caused us a 500 error yet (or at least that we know of).

**Comment by chrisgilmerproj** [comment]
@tinyels - can we find someone to take this? All the findings from this tool represent errors we're probably experiencing in production that aren't rising to the level of an investigation.

**Comment by reggieriser** [comment]
@tinyels @chrisgilmerproj -- I'd be willing to try to fix the issues reported by the tool if we can find space in the A-Team sprint that starts later today.

**Comment by chrisgilmerproj** [comment]
> @tinyels @chrisgilmerproj -- I'd be willing to try to fix the issues reported by the tool if we can find space in the A-Team sprint that starts later today.

That would be cool! Let me know if you do.

**Comment by chrisgilmerproj** [comment]
@reggieriser - I updated this branch with master. Here is the remaining output:

```
2020-04-13T21:40:01.425Z        INFO    model-vet/main.go:166   Move
2020-04-13T21:40:01.425Z        INFO    model-vet/main.go:181           *Show : show is NOT NULL
2020-04-13T21:40:04.855Z        INFO    model-vet/main.go:166   Tariff400ngServiceArea
2020-04-13T21:40:04.855Z        INFO    model-vet/main.go:181           SIT185ARateCents : sit_185a_rate_cents is NULL
2020-04-13T21:40:04.859Z        INFO    model-vet/main.go:181           SIT185BRateCents : sit_185b_rate_cents is NULL
2020-04-13T21:40:04.864Z        INFO    model-vet/main.go:181           SITPDSchedule : sit_pd_schedule is NULL
2020-04-13T21:40:04.877Z        INFO    model-vet/main.go:166   Tariff400ngShorthaulRate
2020-04-13T21:40:04.877Z        INFO    model-vet/main.go:181           CreatedAt : created_at is NULL
2020-04-13T21:40:04.883Z        INFO    model-vet/main.go:181           UpdatedAt : updated_at is NULL
2020-04-13T21:40:04.889Z        INFO    model-vet/main.go:181           CwtMilesLower : cwt_miles_lower is NULL
2020-04-13T21:40:04.896Z        INFO    model-vet/main.go:181           CwtMilesUpper : cwt_miles_upper is NULL
2020-04-13T21:40:04.903Z        INFO    model-vet/main.go:181           RateCents : rate_cents is NULL
2020-04-13T21:40:04.908Z        INFO    model-vet/main.go:181           EffectiveDateLower : effective_date_lower is NULL
2020-04-13T21:40:04.914Z        INFO    model-vet/main.go:181           EffectiveDateUpper : effective_date_upper is NULL
2020-04-13T21:40:04.979Z        INFO    model-vet/main.go:166   Tariff400ngZip5RateArea
2020-04-13T21:40:04.979Z        INFO    model-vet/main.go:181           CreatedAt : created_at is NULL
2020-04-13T21:40:04.985Z        INFO    model-vet/main.go:181           UpdatedAt : updated_at is NULL
2020-04-13T21:40:04.990Z        INFO    model-vet/main.go:181           RateArea : rate_area is NULL
2020-04-13T21:40:04.997Z        INFO    model-vet/main.go:181           Zip5 : zip5 is NULL
```

Getting really close!

**Comment by chrisgilmerproj** [comment]
@reggieriser - this looks really close. Here's the remaining output now that I've updated:

```
Move
  *Show : show is NOT NULL

Tariff400ngServiceArea
  SIT185ARateCents : sit_185a_rate_cents is NULL
  SIT185BRateCents : sit_185b_rate_cents is NULL
  SITPDSchedule : sit_pd_schedule is NULL
```

I'm assuming if we get these fixed then we're ready to go!

**Comment by reggieriser** [comment]
> I'm assuming if we get these fixed then we're ready to go!

I think we're down to a couple that we already looked at but our harder to solve for various reasons.  I think we need to make a few adjustments to the tool itself.  More info in this Slack thread: https://ustcdp3.slack.com/archives/CP6F568DC/p1591647197120500

**Comment by chrisgilmerproj** [comment]
> > I'm assuming if we get these fixed then we're ready to go!
> 
> I think we're down to a couple that we already looked at but our harder to solve for various reasons. I think we need to make a few adjustments to the tool itself. More info in this Slack thread: https://ustcdp3.slack.com/archives/CP6F568DC/p1591647197120500

My sense is we should probably just add a config struct that indicates which models to ignore when running the tool. Then at least we could get this merged and use it against new work being done on the app.

**Comment by chrisgilmerproj** [comment]
@reggieriser - Do you mind if I hand this off to you so I don't have to keep following it? Alternatively I can close this PR if you want to open up a different one.

**Comment by reggieriser** [comment]
> @reggieriser - Do you mind if I hand this off to you so I don't have to keep following it?

Sure, that's fine.

**Pull request closed without merging**
