### PR TITLE
B 21230 resolve canvas dependency v2 int

### PR DESCRIPTION
**Pull request by cameroncaci**
> [!IMPORTANT]
> See parent PR https://github.com/transcom/react-file-viewer/pull/12.

## Ticket
[B-21230](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1013111)

## Summary

- Upgrades [react-file-viewer](https://github.com/transcom/react-file-viewer)
- Upgrades from pdfjs-dist v1.8.357 to ^4.6.82
- Adds canvas support for web API and rendering
- Adds PDF rotation capability
- Adds new step for setting up client dependency serving from the server
  - This is required because the ESM chunk to be served will not work with the current runtime compiler. This means we must serve the ESM chunk to be dynamically imported by CJS, and the thing that serves that ESM chunk is our server.
  - Steps added to copy the `/dist/` into `public/static`
  - Steps added to fetch react-file-viewer from yarn.lock in the server
- Script changes
  - Brew dependencies updated. This can be refreshed via `make prereqs`. It is required per https://github.com/Automattic/node-canvas/wiki/Installation:-Mac-OS-X
  - Client dependencies updated. `make client_deps` now handles canvas binary rebuild and handles servering client dependencies on the server. This is done here for performance reasons as using the CI/CD script of `fetch-react-file-viewer-from-yarn` is slower.

## Technical Details
By dynamically importing ESM modules (served by our backend), we avoid the issue of transpilers removing ESM functionality and the issue of compilers failing to handle ESM code for a CJS repository.

This means we serve pdfjs-dist on the fly in order to preserve functionality.

## Setup and testing

> [!NOTE]
> For the cherished individuals who tested react-file-viewer, you have one extra setup step.
> If you tested the react-file-viewer PR, you must run `brew uninstall pkg-config` before proceeding

For setup, run:
`rm -rf node_modules`
`make prereqs`
`make client_deps`

For testing, do:

1. Plug in your CAC reader and CAC
2. Download a PDF document with a CAC signature option
3. a. One can be found [here](https://caci.sharepoint.us/sites/DPSCollab/WIP/IA/Access%20Requests%20and%20Tracking/Access%20Request%20Documents/TASS%20Form1-Template.pdf)
4. Sign the document with your CAC and save it
5. Hopefully your client is spun up now. Login as a new customer
6. Create a new orders and shipment, uploading your CAC signed form
7. After submitting as the customer, login as SC to review
8. As SC, navigate to your new move -> view/edit orders -> ensure you can see the CAC signature in the document
9. As SC, click manage orders in the top right and upload a duplicate document of the CAC signature
10. You should now have 2 documents you can view (Click the document icon in the top left to see the list)
11. Switch between these two documents and ensure you can zoom in and out
12. You should have been able to switch between documents without crashing
13. Do the same but with rotating the document

Success!

https://github.com/user-attachments/assets/b884b8a1-8879-4a53-9d7e-f2a253d4ab0e

## Illustration
image

### CODE REVIEW

**Comment by cameroncaci** [comment]
The e2e office test will fail until the react-file-viewer PR gets marked as a new release

**Review by traskowskycaci — APPROVED** [review]
Reviewed this functionality with your react-file-viewer PR. Code looks good, so do the tests!

**Review by traskowskycaci — COMMENTED** [review]
Had to force uninstall and now having issues with my environment, specifically running the DB. Might be something I'm doing, doing some investigation.
image

**Comment by cameroncaci** [comment]
Resolving Maria's comments, adjusted PR description to be only `brew uninstall pkg-config`. Brew gets _VERY_ unhappy if you uninstall the other deps. Uninstalling pkg-config successfully prevents canvas from being built, so it suffices for testing

**Review by traskowskycaci — COMMENTED** [review]
Have tried a few times to test this PR and am seeing a fail on `make client_deps`, have talked with Cam and it might just be my environment. @danieljordan-caci @TevinAdams @deandreJones curious if testing this PR would go smoother for you.

**Review by danieljordan-caci — APPROVED** [review]
Very good! Sorry it took me a bit.

Screenshot 2024-11-26 at 9 52 42 AM
Screenshot 2024-11-26 at 9 54 13 AM

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Looks like one test has a non-flaky fail: https://app.circleci.com/pipelines/github/transcom/mymove/81101/workflows/b550c67e-4628-4a73-9a85-4d3e38d26e12/jobs/1440926/tests

**Review by traskowskycaci — APPROVED** [review]
Dismissed my last review after talking via Slack with Cameron. Functionality tested and looks good!

**Comment by cameroncaci** [comment]
Failing client test is FLAKY on build 81308

**Comment by cameroncaci** [comment]
Failing integration test my is FLAKY on build 81308

**Comment by cameroncaci** [comment]
Marking to draft for experimental deploy

**Review by danieljordan-caci — APPROVED** [review]
Previously approved - approving to satisfy frontend check

**Review by deandreJones — APPROVED** [review]

**Comment by cameroncaci** [comment]
Failing step is flaky. Already pushed a separate flaky fix within this PR

**Pull request merged**
