### PR TITLE
MB-1947: PreconditionFailed Error More Descriptive

### PR DESCRIPTION
**Pull request by ralren**
## Description

What the title says.

## Setup
```sh
make server_run
```
Using Postman, make a request to the update mto shipment endpoint with a bad eTag.

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-1947) for this change

### CODE REVIEW

**Comment by LeDeep** [comment]
> Nice - I'll add this to the other endpoints as well.

@ralren would it be a lot more work to add this to the other endpoints in this PR? I think that would be within the scope of the story.

**Comment by ralren** [comment]
Shoot, @LeDeep , I saw your message after merging.

**Comment by LeDeep** [comment]
> Shoot, @LeDeep , I saw your message after merging.

no worries. I'll leave it up to you and @garrettqmartin8 as to who wants to do the remaining endpoints.

**Comment by garrettqmartin8** [comment]
@LeDeep I'll add them in #3732

**Pull request merged**
