### PR TITLE
B-17662 Add "return to move" link to profile page

### PR DESCRIPTION
**Pull request by antgmann**
## Summary
In order to help the customer navigate after editing profile information, a "Return to Move" link has been added to the profile page. This link returns them to the main page "/", so that they can continue their operation or view existing moves. This was used instead of automatically redirecting them to avoid additional routing confusion, and to allow the customer to check their information after it has been saved. 

The link was created by importing links and general routes, and adding them to the profile page. Tests were created on the profiles test page, as well.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access the application as a client user
2. Login as a new user
3. Create your profile
4. When prompted to upload orders, click Edit Profile instead
5. Optionally click return to move here or, continue to edit profile
6. Save profile information
7. Click return to move.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
Screenshot 2023-11-01 at 1 30 32 PM

### CODE REVIEW

**Comment by cameroncaci** [comment]
verified 508 compliance g2g

**Comment by cameroncaci** [comment]
After clicking review and submit there is no option to return back to the move. Just double checking since it's similar functionality was this part of the request or _only_ after profile update? Asking out of pure curiosity. Tested locally and change is g2g.
image
image

**Comment by cameroncaci** [comment]
Profile.jsx has 100% code coverage, interesting..

**Comment by antgmann** [comment]
> After clicking review and submit there is no option to return back to the move. Just double checking since it's similar functionality was this part of the request or _only_ after profile update? Asking out of pure curiosity. Tested locally and change is g2g. image image

Yes, this is intentional. The Review Your Details page is actually an info page based upon the move itself, not the profile page. If you hit edit there next to profile, the button will be present as you'll be back on the profile page. I don't see a need to return to the original page once you're in the move's Review Your Details page, but if that's something requested it could be completed on a separate ticket.

**Comment by antgmann** [comment]
Checks passed once main was merged back into branch making it current. This also explains why the client coverage passed on my local but not here at first.

**Review by cameroncaci — CHANGES_REQUESTED** [review]
Discussed and validated, possibly satisfies AC. Awaiting feedback from RTE Lisa for merge.

Possible deviation:
AC:
```
We need to route them to review page to proceed in the move process.

Then I am routed back to the review page
```

This provides the option of routing rather than auto routing.

**Comment by antgmann** [comment]
> Discussed and validated, possibly satisfies AC. Awaiting feedback from RTE Lisa for merge.
> 
> Possible deviation: AC:
> 
> ```
> We need to route them to review page to proceed in the move process.
> 
> Then I am routed back to the review page
> ```
> 
> This provides the option of routing rather than auto routing.

This has been discussed in the team meeting and it's a change we wanted to make to the item in agility too, regardless, awaiting feedback.

**Comment by deandreJones** [comment]
i think the AC should be updated-to be more broad given the discussion in the team scrum, this approach was acceptable- given that if the govt didnt like it, we coukd change without this approach being detrimental to the user flow

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
