### PR TITLE
INT B-22139

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

There's was a discovered defect in prod where a SC was getting an error when trying to create any customer. Prod has a unique constraint on the `emplid` column and was being saved as an empty string (`""`) instead of `null`.

Approach is to remove all `emplid` rows that have empty strings, fix the code that is saving as an empty string if no value is provided, as well as adding in a backend check.

### How to test

1. You will need to manually add the unique constraint to your local dev db, but first you'll need to sanitize by removing the empty string `emplid` column. In DBeaver, run this:
```
UPDATE service_members 
SET emplid = null 
WHERE emplid = '';

ALTER TABLE service_members
ADD CONSTRAINT service_members_emplid_unique_key UNIQUE (emplid);
```
2. Login as a SC and create any customer of any affiliation
3. Go back and create another one, ensure you don't get an error
4. Confirm you can also create Coast Guard folks without error and the dup check still happens
5. Profit
6. Ensure you drop the unique constraint if ya want to:
```
ALTER TABLE service_members DROP CONSTRAINT service_members_emplid_unique_key;
```

### CODE REVIEW

**Review by paulstonebraker — DISMISSED** [review]

**Review by antgmann — DISMISSED** [review]
Everything looks good. Still checks whether emplid is in use, no more issues creating users.

**Review by brianmanley-caci — DISMISSED** [review]
Everything worked for me.

**Review by pambecker — APPROVED** [review]

**Comment by danieljordan-caci** [comment]
Flakiness fixed, please re-review/approve @antgmann, @paulstonebraker, @brianmanley-caci, @pambecker

**Review by brianmanley-caci — APPROVED** [review]

**Review by antgmann — APPROVED** [review]
Small test changes look good

**Review by pambecker — APPROVED** [review]

**Review by paulstonebraker — APPROVED** [review]

**Pull request merged**
