### PR TITLE
B-21362/B-21363 UB Shipment Updates - MAIN

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

In integration, B-21362 and B-21363 shared an INT PR, then two follow on B-21363 INT PRs were created.

### CODE REVIEW

**Comment by traskowskycaci** [comment]
Only diffs I'm seeing:

pkg/services/mto_shipment/shipment_deleter_test.go
- 8 files changed in [this PR](https://github.com/transcom/mymove/pull/13837/files) but Daniel brought that into main already: https://github.com/transcom/mymove/blob/main/pkg/services/mto_shipment/shipment_deleter_test.go

src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
- Not sure why this was even in [my INT PR](https://github.com/transcom/mymove/pull/13933/files) - probably merging in main to int. Already in main here: https://github.com/transcom/mymove/blob/main/src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx

**Review by cameroncaci — APPROVED** [review]
Diffs are the cause of cherry-pick SHAs. Code changes are present

**Comment by traskowskycaci** [comment]
> Diffs are the cause of cherry-pick SHAs. Code changes are present

Yes, flow of work for this since I relied on int only work was make the change in int, cherry-pick to main, then merge main branch into int branch. Main branch has duplicated commits, one for the cherry pick and then one that matches int where the SHA should match int commit

**Comment by TevinAdams** [comment]
@traskowskycaci The do you need the change for removing the Trailing white space in pkg/handlers/internalapi/moves.go  sha 2ad24d7e89746031c636cda4fd415bddbb913a08

**Comment by traskowskycaci** [comment]
> @traskowskycaci Do you need the change for removing the Trailing white space in pkg/handlers/internalapi/moves.go sha [2ad24d7](https://github.com/transcom/mymove/commit/2ad24d7e89746031c636cda4fd415bddbb913a08)

Already in main, checked here: https://github.com/transcom/mymove/blob/main/pkg/handlers/internalapi/moves.go
image

**Review by TevinAdams — APPROVED** [review]
GTG

**Review by danieljordan-caci — APPROVED** [review]
Looked it over pretty good with your INT PRs side by side - appreciate your comments that helped out resolve the differences that I saw.

Send it!

**Comment by deandreJones** [comment]
```
    "[POP] 2024/10/23 21:12:42 info - 1.4956 seconds",
    "panic: error running migrations: error executing file:///migrate/schema/20241002170242_add_ub_shipment_type.up.sql: error executing statement: \"ALTER TABLE mto_shipments\\nALTER COLUMN shipment_type TYPE mto_shipment_type_2\\nUSING (shipment_type::text::mto_shipment_type_2);\": pq: invalid input value for enum mto_shipment_type_2: \"INTERNATIONAL_HHG\"",
    "goroutine 1 [running]:",
    "main.main()",
```

**Pull request merged**
