### PR TITLE
MB-5227 Remove unused custom icon assets from the repo + update links in files to use FontAwesome in the app

### PR DESCRIPTION
**Pull request by Shkeating**
## Description
This branch takes our new FontAwesome replacements and implements them in the app. This branch also deletes the now defunct icon assets out of the repo.

## Reviewer Notes
I got all the icon assets out and changed the imports in files where they were being used but I am sure there is stuff like tests where I missed references to the old icons. 

Based off my inital review in Happo these are known styling issues that I am working on:

- [x] leftnav and tags alert icon circle
- [x] modals, rejectserviceitemmodal,  and cust modals - turn close icon grey 
- [x] tables stories broken, shipment container too 
- [x] docsuplaoded turn icons grey
- [x] shipmentlist turn icons blue

## Setup

```sh
yarn storybook
```

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5227?atlOrigin=eyJpIjoiZDEyYmZiNzEwNzkzNGQ3NWIyYmExMDllMDJkZThlZDEiLCJwIjoiaiJ9) for this change

## Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by mariaclaratgolfo** [comment]
**Questions**

• Should the icons be maintaining their size? Are we applying more padding around the new thicker icons? Example screenshot of an instance where the icon size shrunk:
smallersize
• In this screenshot it also looks like there's a strange shadow overlap on the header that says 'Documents'. It appears in the before and after though so likely not due to this change.

Maybe this is a comment for a different story but it feels like we can do with a bit more spacing between icons and labels in our tertiary CTAs.

In this example, the icon appears to get bigger with the change:
largersize

This doesn't appear broken, but it does appear the location of the icon has shifted a bit:
locationshift

These seem broken in both before and after 🙈 [likely not part of this story]
oddlinebreaks

Seems like the icons next to accept and reject are slightly different sizes:
inconsistentsize

These are broken in both cases:
floatingCTAs

I'm not sure if this bounding circle + ! are 1 unit [the entire icon], but it seems the new one is not center aligned
iconnotcentered

Maybe intentional but it seems we lose the '!' icon in the global icon set:
noexclamation

These have gotten slightly bigger. Maybe that's okay
slightlybigger

Size change:
smallericon

**Review by mariaclaratgolfo — APPROVED** [review]
@amanda5iu  created a separate story to address the size discrepancies

**Review by suzubara — APPROVED** [review]

**Comment by sojeri** [comment]
hi @Shkeating, I am here, summoned by dangerjs to review new linter override lines. please hold off on merging until I've confirmed the new linter overrides are acceptable. I'm starting right now & it should take 1hr or less. :)

**Review by sojeri — APPROVED** [review]
🚀 

I'm stumped! I don't see any eslint disable lines in your change, so I suspect maybe we had a false positive here. maybe one of the large svg blobs had nosec in it somewhere? either way, I'm fine if you merge. I'll look separately into having us at least list the offending file name so reviewing larger changes like this is easier from a security standpoint. :)

**Pull request merged**
