### PR TITLE
Automated dependency updates | Mon, 25 Jun 2018 12:02:45 +0000

### PR DESCRIPTION
**Pull request by brainsik**
Fairly unhappy tests.

From the [`dep status` test](https://circleci.com/gh/transcom/mymove/14792):
```
Lock inputs-digest mismatch. This happens when Gopkg.toml is modified.
Run `dep ensure` to regenerate the inputs-digest.
input-digest mismatch
```

From [`make server-test`](https://circleci.com/gh/transcom/mymove/14791):
```
error processing ../migrations/20180103215841_create_issues.up.fizz: could not fizz the migration ../migrations/20180103215841_create_issues.up.fizz: parse error: function run error: function wants argument type fizz.Options but received type map[string]interface {}
```

### CODE REVIEW

**Comment by tinyels** [comment]
Looks like the pop update (v4.5.8 -> v4.5.10) broke migrations for a lot of people. See https://github.com/gobuffalo/pop/issues/138

Should we pin to v4.5.8 for now?

**Comment by brainsik** [comment]
Gonna assume that question is @akostibas. :-)

**Comment by tinyels** [comment]
@akostibas pop is recommending locking  `anko at v0.0.4`. I haven't done anything with go dependencies, but would be happy to try that.

If we do that, how do we kick off the automated dependency updates again, @brainsik?

**Comment by brainsik** [comment]
I'd just work off this branch (or pull it into your own) and go from there. There's nothing special about what the automated dependency updater does.

**Comment by akostibas** [comment]
I took a quick shot at setting Anko to `0.0.4` and was getting the same results. It's possible that I didn't do it quite right as I haven't used `dep` a ton. The method I tried was modifying the Gopkg.lock file itself, which showed that anko was at the right version with `dep status`. There may be another approach using `[[override]]`s in the Gopkg.toml, and can play with that later today.

**Comment by jim** [comment]
I think this needs to be specified in `Gopkg.toml`: https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependency-s-version.

**Comment by akostibas** [comment]
I tried the `[[override]]` directive as well in Gopkg.toml, no dice. I'm going to close this for now and hopefully Pop will get it's act together by next week.

**Pull request closed without merging**
