### PR TITLE
B 21077 move shipment button int

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

This PR moves the "add new shipment" button over to the right for the TOO  to match the Service Counselor's "add new shipment" button for better consistency throughout the app.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Login as TOO
2. Click any existing move
3. Confirm "add new shipment" button is aligned to the right of the page*
*similar to the SC "add new shipment" button on their move details page

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
_**(Attachment from agility)  TOO before**_
Screenshot 2024-10-02 at 12 09 19 PM

_**TOO  after**_
Screenshot 2024-10-02 at 1 53 47 PM

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
So I'm not sure if POA will care or not, but the vertical alignment is off, and I see two ways of fixing.

1. Quick dirty fix, add a ~30px margin or padding-top value to the div that holds the button. However this alignment gets messed up on mobile screens.

2. More involved "correct" way, would probably be to take the button out of MoveDetails.jsx and put it inside the ApprovedShipments component. And basically copy the layout that is used in ServicesCounselerMoveDetails.jsx.  The SC page has the button and header in the same div so they are always aligned, but other roles have them in separate divs which is why this problem happens, the above would fix that. You'd also have to code a case to display the add button even if no approved shipments are available. 

But I'm alright with approving and seeing what POA or others think.

**Comment by KonstanceH** [comment]
> So I'm not sure if POA will care or not, but the vertical alignment is off, and I see two ways of fixing.
> 
> 1. Quick dirty fix, add a ~30px margin or padding-top value to the div that holds the button. However this alignment gets messed up on mobile screens.
> 2. More involved "correct" way, would probably be to take the button out of MoveDetails.jsx and put it inside the ApprovedShipments component. And basically copy the layout that is used in ServicesCounselerMoveDetails.jsx.  The SC page has the button and header in the same div so they are always aligned, but other roles have them in separate divs which is why this problem happens, the above would fix that. You'd also have to code a case to display the add button even if no approved shipments are available.
> 
> But I'm alright with approving and seeing what POA or others think.

Oh no that's fair. I'm working on doing your second suggestion now

**Review by JamesHawks224 — CHANGES_REQUESTED** [review]
testing: vertical alignment issue w/button.  noted by Brooklyn and is being worked on by Konstance.
code: lgtm

**Review by JamesHawks224 — APPROVED** [review]
testing: success
code: lgtm

**Pull request merged**
