### PR TITLE
[MB-14399] update move task order status refactor

### PR DESCRIPTION
**Pull request by ruizajtruss**
## Summary

Refactored template and tests. Since there's some ternary logic going on I found it prudent to render the event name for testing as well to ensure everything works as intended.

>**Note**
>I was not able to create a scenario where the `Move status updated:  -`  path would display in move history which makes me think we might be able to just drop the ternary logic all together. Please make an attempt to see if you can trigger that path and get it to display. Be good to remove the code if its no longer necessary.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Login as a TOO officer
2. Approve a move
3. Message should appear in move history

## Verification Steps for Author

These are to be checked by the author.

- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
Continues to display:
image

### CODE REVIEW

**Comment by michaelvaldes-truss** [comment]
@ruizajtruss @mmayo-truss fyi heres the original story https://dp3.atlassian.net/browse/MB-11468
And here's the row from our design doc that specifies the action for the removed ternary logic
image

**Comment by mmayo-truss** [comment]
I am able to reproduce the expected results. 
image

@ruizajtruss I also am unable to create a scenario where the `Move status updated: -`   is displayed.

**Comment by mmayo-truss** [comment]
Follow-up: The only one reference to this event name in our swagger files is in the [ghc.yaml file](https://github.com/transcom/mymove/blob/7a7c9a7a8963a1889e86b89754b44c73b1527fee/swagger/ghc.yaml#L1646) and it is only for approving the move and making available to prime. This is further evidence that the ternary logic can be removed.

**Review by mmayo-truss — APPROVED** [review]
LGTM! 🏅 nice work.

**Pull request merged**
