### PR TITLE
storybook updates

### PR DESCRIPTION
**Pull request by mandaem**
## Summary

This incorporates storybook dependencies into one PR and to the patch level needed for them to work together and have storybook still function.

**You'll also want to run locally to make sure storybook launches and functions properly still.**

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by duncan-truss** [comment]
I checked out the Storybook artifact in CircleCI and it rendered as expected and looks like there were no Happo diffs either.

Two things we might be able to address:
- I'm seeing a console error for a `dump247/storybook-state` plugin that I'm not sure we use anywhere that could likely be removed from package.json and from `.storybook/main.js`
- I noticed the react-uswds embed is showing an error and wondering when that may have stopped working.  It could be worth a quick investigation as to why that composition has stopped working (could be a version mismatch or something between the react-uswds storybook or GitHub Pages setup. https://storybook.js.org/docs/react/sharing/storybook-composition 

Screenshot 2023-07-05 at 1 38 25 PM
Screenshot 2023-07-05 at 1 45 15 PM

**Review by reggieriser — COMMENTED** [review]
It looks like the `storybook` dependency is still at 7.0.22 but there's a 7.0.26 available for it as well.  Should we keep that in sync?

I also see that `@storybook/testing-library` has an upgrade from 0.1.0 to 0.2.0 available, but not sure if that's something to do alongside these or not.

**Comment by mandaem** [comment]
@duncan-truss :

"and wondering when that may have stopped working". I checked in main and it's displaying the exact same message, so it was already doing this before this PR/my .26 updates . 

For @trussworks/react-uswds we’re on 3.2.0, but there’s a 5.0.0 now available. so I’m thinking that storybook for 3.2.0 wasn’t at 7.x yet and this has been an issue since we went to 7.x for storybook, does that sound right?

Just a side note that we’re on uswds 2.13.3, but that’s not as out of date/there’s a 2.14.0 now..

Same thing with showing the same thing/ manager-entries fail in main currently too. But it sounds like you're saying for that one, it's safe to remove storybook-state from /mymove then?

**Comment by duncan-truss** [comment]
> @duncan-truss :
> 
> "and wondering when that may have stopped working". I checked in main and it's displaying the exact same message, so it was already doing this before this PR/my .26 updates .
> 
> For @trussworks/react-uswds we’re on 3.2.0, but there’s a 5.0.0 now available. so I’m thinking that storybook for 3.2.0 wasn’t at 7.x yet and this has been an issue since we went to 7.x for storybook, does that sound right?
> 
> Just a side note that we’re on uswds 2.13.3, but that’s not as out of date/there’s a 2.14.0 now..
> 
> Same thing with showing the same thing/ manager-entries fail in main currently too. But it sounds like you're saying for that one, it's safe to remove storybook-state from /mymove then?

Agreed, these aren't new issues but it makes it harder to review when unrelated errors are displaying to know if anything changed.

I think removing `@dump247/storybook-state` from those two files is worth doing here.

The react-uswds issue likely isn't totally within our control.  I don't see other Truss projects embedding it successfully. I was mainly referring to the Storybook versions differing 7 vs 6.  We are just displaying the latest version of react-uwsds in that group, not necesarily the release that Milmove has implemented.

**Review by duncan-truss — APPROVED** [review]

**Review by reggieriser — APPROVED** [review]

**Pull request merged**
