### PR TITLE
B18988 int 240411 1443 update 5 digit id in move history to be shipment locator

### PR DESCRIPTION
**Pull request by JamesHawks224**
## Agility ticket
[B18988](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18988)

## Summary

In the "Move History" for a move, the shipment id (the value appearing after HHG/PPM Shipment #) was changed to "shipment locator".  Shipment locator = move locator + "-" + sequence number for the the move e.g. "ABC123-01".

#### HHG
* create a HHG move
* login as a SC
* find the move and open it
* go to the "Move History" tab
* all occurrences of "HHG shipment #" should have move locator value + "-" + "01"

#### PPM
* as a user
  - create a PPM move
* as an officer user
  - login as a SC
  - find the move and open it
  - edit allowances
  - submit move
* as the user
  - click upload documents
  - enter vehicle info
  - add pro gear
  - add an expense
  - submit ppm documentation
* as an office user
  - login as an SC
  - go to closeout queue
  - open move
  - go to the "Move History" tab
  - all occurrences of "PPM shipment #" should have move locator value + "-" + "01"

## Screenshots
HHG
image

PPM
image

### CODE REVIEW

**Review by taeJungCaci — COMMENTED** [review]
Changes look good but I think you might be missing few files. 

For example: `src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.jsx`

image

**Comment by JamesHawks224** [comment]
> Changes look good but I think you might be missing a few files.
> 
> For example: `src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.jsx`
> 
> image

I thought I'd merged that fix in.  That was the HHG fix I did recently.  :(. Thx for catching that.

**Review by taeJungCaci — CHANGES_REQUESTED** [review]
Looks like a few more missing ones. If you search for `.shipment_id_abbr.toUpperCase()`, you should be able to find more.

image

**Comment by JamesHawks224** [comment]
> Looks like a few more missing ones. If you search for `.shipment_id_abbr.toUpperCase()`, you should be able to find more.
> 
> image

Sorry about the sloppy work on my part.
Thx for the search string.
Searched the code and updated all relevant spots.
Changes have been committed.  Int branch has been updated and pushed.

**Review by taeJungCaci — APPROVED** [review]
LGTM!

**Comment by brooklyn-welsh** [comment]
Found a couple other ones that need to be updated:

1. `updateServiceItemStatus.jsx` 

Here's the event that you can use to verify, you can just go to the bottom of the MTO page and reject any service item then re-approve it to get it to show up:
Screenshot 2024-04-18 at 12 26 08 PM

2. `editSitEntryDateModal.jsx`

For this one you need to find a service item for Domestic Origin 1st day SIT
Screenshot 2024-04-18 at 12 24 55 PM

Then approve it, you'll then get this:
Screenshot 2024-04-18 at 12 24 43 PM

**Comment by taeJungCaci** [comment]
Thats a good find @brooklyn-welsh

Along with those changes I think `src/pages/Office/MoveHistory/LabeledDetailsWithToolTip.jsx` Line 49 should also be changed to:  
``shipmentDisplay += ` shipment #${changedValuesToUse.shipment_locator}`;``

**Comment by brooklyn-welsh** [comment]
> Thats a good find @brooklyn-welsh
> 
> Along with those changes I think `src/pages/Office/MoveHistory/LabeledDetailsWithToolTip.jsx` Line 49 should also be changed to: `` shipmentDisplay += ` shipment #${changedValuesToUse.shipment_locator}`; ``

Oh, that was actually the file I was meaning to quote for the SIT modal, glad you posted that, I'll edit my previous comment

**Comment by JamesHawks224** [comment]
> Found a couple other ones that need to be updated:
> 
> 1. `updateServiceItemStatus.jsx`
> 
> Here's the event that you can use to verify, you can just go to the bottom of the "Move Task Order" tab for any move and reject any service item then re-approve it to get it to show up: Screenshot 2024-04-18 at 12 26 08 PM
> 
> 2. `LabeledDetailsWithToolTip.jsx`
> 
> For this one you need to find a service item for Domestic Origin 1st day SIT Screenshot 2024-04-18 at 12 24 55 PM
> 
> Then click "edit" and enter a new SIT entry date, you'll then get this: Screenshot 2024-04-18 at 12 24 43 PM

Code updates have been done and pushed to INT.

**Review by brooklyn-welsh — APPROVED** [review]
Requested changes have been addressed, LGTM ✅

**Pull request merged**
