### PR TITLE
[MB-5517] Updates Golang to v1.15.5

### PR DESCRIPTION
**Pull request by chrisrcoles**
# Description

Updates golang from 1.15.2 to 1.15.5 for minor release that include address some security concerns:

1. go1.15.3 (released 2020/10/14) includes fixes to cgo, the compiler, runtime, the go command, and the bytes, plugin, and testing packages. See the Go 1.15.3 milestone on our issue tracker for details.
1. go1.15.4 (released 2020/11/05) includes fixes to cgo, the compiler, linker, runtime, and the compress/flate, net/http, reflect, and time packages. See the Go 1.15.4 milestone on our issue tracker for details.
1. go1.15.5 (released 2020/11/12) includes security fixes to the cmd/go and math/big packages. See the Go 1.15.5 milestone on our issue tracker for details.

## Reviewer Notes

The merged PR for **[step 1](https://github.com/transcom/mymove/wiki/upgrade-go-version#1-updating-our-docker-image)** in the upgrade is [here](https://github.com/transcom/circleci-docker/pull/58).

**Note**: Please [verify](https://hub.docker.com/r/milmove/circleci-docker/tags) sha256 hash matches.

image

## Setup

See [instructions](https://github.com/transcom/mymove/wiki/upgrade-go-version) for reference.

If you've done some PATH sorcery to point to a specific Go version (as detailed here), you'll have to update that as well
(if you do not yet have `asdf` installed, see [How to get up and running](https://github.com/transcom/mymove/wiki/Manage-golang-with-asdf#how-to-get-up-and-running))

1. Run `asdf install` to install the new version

``` 
mylaptop ~ %: asdf install golang 1.15.5
```

2. Run `asdf global golang <version>` to update global version as well `go version` and `asdf which go` to check it worked

``` 
mylaptop ~ %: go version
mylaptop ~ %: go version go1.15.5 darwin/amd64
```

```
mylaptop ~ %: asdf which go
mylaptop ~ %: /Users/me/.asdf/installs/golang/1.15.5/go/bin/go
```

## Changelog or Releases

- [golang](https://golang.org/doc/devel/release.html)

## Code Review Verification Steps

* [x] Request review from a member of a different team.
* [x] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5517) for this change
* [this Wiki](https://github.com/transcom/mymove/wiki/upgrade-go-version) explains more about the approach used.

### CODE REVIEW

**Review by abbyoung — APPROVED** [review]
LGTM!

**Review by gidjin — CHANGES_REQUESTED** [review]
You need to update `.tool-versions` to match the new version please refer to https://github.com/transcom/mymove/wiki/upgrade-go-version

**Review by gidjin — APPROVED** [review]
It wasn't there a moment ago I swear. 🚀  When announcing this remind people to upgrade the global version of `asdf` as well https://github.com/transcom/mymove/wiki/Manage-golang-with-asdf#configure-global-use-of-golang-version

**Review by lynzt — APPROVED** [review]
Downloaded the new go version as stated in the directions and played w/ a the app a bit. Things look ok and act like I expect. 
🚢

**Pull request merged**
