### PR TITLE
Fixes local cypress test failures due to DB user re-use

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Description

When running the Cypress e2e tests locally (through Docker, like CircleCI does), six tests currently consistently fail. These failure are due to sharing user accounts between tests, while expecting that the tests will be run independently. 

CircleCI parallelizes tests and databases in a way that gets around these failures, but when `make e2e_test_docker` is run locally, they're single-threaded and in a predictable order, causing the failures.

This pull request adds several new database users to the e2e dataset, and reworks those failing tests to use the fresh users.

## Reviewer Notes

... I'm a novice at golang, please make sure I didn't break anything. 🙃 

Additionally, ensure that integration tests are still passing on CircleCI.

## Setup

```sh
make e2e_test_docker
```

and then wait for, like, a half hour. Ensure that the modified tests pass. (Note that are a flaky test or two outside of the tests changed in this pull request, which fail on both local and CircleCI runs maybe 10-20% of the time. Those will be looked at and probably addressed in a future PR.)

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

Closes [MB-8377](https://dp3.atlassian.net/browse/MB-8377).

### CODE REVIEW

**Review by YanZ777 — COMMENTED** [review]
Ok reran it again with latest changes and now I'm only seeing this test fail:
✖  mymove/ntsr.js

  1) Customer NTSr Setup flow
       Edits an NTSr shipment from review page:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `button[data-testid="edit-ntsr-shipment-btn"]`, but never found it.
      at customerEditsNTSRShipmentFromReviewPage (http://milmovelocal:4000/__cypress/tests?p=cypress/integration/mymove/ntsr.js:147:6)
      at Context.eval (http://milmovelocal:4000/__cypress/tests?p=cypress/integration/mymove/ntsr.js:115:5)

  2) Customer NTSr Setup flow
       Edits an NTSr shipment from home page:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `textarea[data-testid="remarks"]`, but never found it.
      at customerEditsNTSRShipmentFromHomePage (http://milmovelocal:4000/__cypress/tests?p=cypress/integration/mymove/ntsr.js:125:6)
      at Context.eval (http://milmovelocal:4000/__cypress/tests?p=cypress/integration/mymove/ntsr.js:119:5)

**Review by eamahanna — COMMENTED** [review]
I am fairly certain you are going to want to make the same changes in `devseed.go` that you made in `e2eBasic.go` I believe. When we run `yarn test:e2e` cypress just looks at the the local test db and does not do any data generation. A lot of folks use `make db_dev_e2e_populate` to populate their local db which calls `devseed.go`. So if you don't also make these changes in `devseed.go` the tests will fail locally if people use `db_dev_e2e_populate` and then attempt to debug tests using yarn test:e2e. I'm not sure the reason behind why we have these two different files.

**Review by YanZ777 — APPROVED** [review]
Everything passed! Yay!

**Review by eamahanna — COMMENTED** [review]
I am getting failed tests when I run the following commands: 
`make db_dev_reset`
`make db_dev_e2e_populate`
`make server_run`, `make client_run`
`yarn test:e2e`

**Comment by kylehilltruss** [comment]
Merging this PR, as those failing tests when running `yarn test:e2e` are A) also happening in master right now, and B) outside the scope of this ticket.

**Comment by monfresh** [comment]
@eamahanna The reason we have 2 separate files is because they are meant for different things. `e2ebasic.go` should ONLY be used for e2e tests. Changes that we make to `e2ebasic.go` shouldn't have anything to do with `devseed.go`.

`devseed` is meant for local development and should have nothing to do with e2e tests. `devseed` allows us to populate the DB with data that makes it easy to run the app locally and jump straight into some functionality we want to test while developing, as opposed to having to manually create a move from scratch by signing in as a customer, going through onboarding, etc..

The fact that we have a `yarn test:e2e` command that uses the development database doesn't make any sense to me. If we're running e2e tests, we should be using the test DB.

**Pull request merged**
