### PR TITLE
MAIN B-18642 add origin gbloc to move screen front end

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18642](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18642)

PR to INT:
https://github.com/transcom/mymove/pull/12335
https://github.com/transcom/mymove/pull/12355
https://github.com/transcom/mymove/pull/12462

## Summary

This is the frontend work to implement origin GBLOC in the move headers for office users.

USMC moves are unique and therefore the moves as Marine Corps as BOS will display `/ USMC` in addition to origin GBLOC. e.g. `KKFA / USMC`

#### Non-USMC:
1. Create any move or use any existing moves you have.
2. Access either as SC, TOO, TIO, or QAE (complete counseling for the move if you want to access as TOO/TIO).
3. Go to the move of your choice and look at the move information header and you should see Origin GBLOC matching the origin GLOBC of the move (See image below).

#### USMC:
1. Create a move as a Marine Corps BOS or use `HHGMoveAsUSMCNeedsSC` testharness.
3. Access either as SC, TOO, TIO, or QAE with `USMC` GBLOC (complete counseling for the move if you want to access as TOO/TIO).
4. Go to the move of your choice and look at the move information header and you should see Origin GBLOC matching the origin GLOBC of the move with  `/ USMC` added (See image below).

NOTE: SC vs TOO/TIO/QAE may show different origin GBLOC and this is intentional according to this [confluence page](https://dp3.atlassian.net/wiki/spaces/MT/pages/1631092737/Office+Routing+Explained).

## Screenshots
image

image

### CODE REVIEW

**Comment by JamesHawks224** [comment]
verify rpt ran.
there were diffs.
[B18642-12400.verify_rpt.txt](https://github.com/transcom/mymove/files/14875422/B18642-12400.verify_rpt.txt)

**Comment by JamesHawks224** [comment]
verify rpt:
[B18642-12400.verify_rpt.txt](https://github.com/transcom/mymove/files/14937062/B18642-12400.verify_rpt.txt)

there were diffs.

**Comment by taeJungCaci** [comment]
> verify rpt: [B18642-12400.verify_rpt.txt](https://github.com/transcom/mymove/files/14937062/B18642-12400.verify_rpt.txt)
> 
> there were diffs.

Verified the report and is expected and correct.

**Review by brooklyn-welsh — APPROVED** [review]
LGTM ✔️

**Pull request merged**
