### PR TITLE
B 20753

### PR DESCRIPTION
**Pull request by antgmann**
## [B-20753](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20753)

[INT PR](https://github.com/transcom/mymove/pull/13486)
[INT FIX PR](https://github.com/transcom/mymove/pull/13557/files)

> [!IMPORTANT]  
> Due to an issue on integrationTesting, a follow-on PR was merged [here](https://github.com/transcom/mymove/pull/13557). This bug has already been resolved on this branch, and this issue PR brought integrationTesting up to date.

> [!WARNING]  
> This story may have conflicting tests with [B-19813](https://github.com/transcom/mymove/pull/13542#pullrequestreview-2257345361), hence the last commit on int pr [e7c7693](https://github.com/transcom/mymove/pull/13486/commits/e7c769398b7d969611d4e3d6def01af18f44c6b0) to avoid dependencies. No action should be required if this is merged ahead of 19813, but if 19813 is merged first, that commit will be brought into this branch to ensure no test failures.

## Summary

This is a simple UI change to allow TOO users to enter a requested pickup date for NTS-Release shipments and requested delivery dates for NTS shipments. These will be used as "handle-in/out" dates for the prime to pick up items from or deposit items into long term storage, respectively. They are not customer facing, and will only be seen by office users/prime and only edited by TOOs. No locations are provided as NTS/rs will use facility addresses as the corresponding location with these dates. 20752 will follow shortly to display this information on move details.

## Verification Steps for the Author

These are to be checked by the author.

- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. First, create a customer and move with NTS and NTS-release shipments, one of each should suffice.
2. Fill out the information and submit the move.
3. Due to multi-role office users having permissions for all roles, we will need to test with SC and TOO roles specifically, not multi-role users.
4. Log in as a Service Counselor, navigate to your move. 
5. Edit the NTS shipment. Ensure that there is no delivery date field.
6. Edit the NTS-release shipment. Ensure that there is no pickup date field.
7. Now that we've validated the fields won't show for other office roles, let's edit these fields as a TOO.
8. Sign back into the office app as a TOO. 
9. Edit the NTS shipment. Ensure that the delivery date field is present. 
10. Enter a date and save. The date should persist after saving if you navigate back to the edit shipment page.
11. Edit the NTS-release shipment. Ensure that the pickup date field is present.
12. Enter a date and save. The date should persist after saving if you navigate back to the edit shipment page.

Note: Upon adding a requested pickup date for NTS-releases, an assumption in our calculation function caused NTS-releases to not be approvable when it attempted to price based on the non-existent pickup address (we use facility address instead). Please ensure that the NTS-release can be submitted to the prime successfully. 
### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image
image
Pasted Graphic 2
Pasted Graphic 3

### CODE REVIEW

**Review by r-mettler — COMMENTED** [review]
I see some changes that were in int but not here. Was this part of another PR or somebody else's changes perhaps?

image

**Comment by antgmann** [comment]
> I see some changes that were in int but not here. Was this part of another PR or somebody else's changes perhaps?
> 
> image

These changes are the ones I'm referring to in the warning part of the PR description. This story may have conflicting tests with https://github.com/transcom/mymove/pull/13542#pullrequestreview-2257345361, hence the last commit on int pr [e7c7693](https://github.com/transcom/mymove/pull/13486/commits/e7c769398b7d969611d4e3d6def01af18f44c6b0) to avoid dependencies. No action should be required if this is merged ahead of 19813, but if 19813 is merged first, that commit will be brought into this branch to ensure no test failures.

**Review by ajlusk — APPROVED** [review]
Matches the combination of both INT PRs other than `ShipmentForm.test.jsx` that was mentioned and justified above.

**Review by r-mettler — APPROVED** [review]
looks good with additional comment on non matching code.

**Pull request merged**
