### PR TITLE
B-17958 identify create calculations ppm closeout 1-6

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Summary

[From PR: https://github.com/transcom/mymove/pull/11740] A "GET" end point was added to PPM Shipments to retrieve PPM closeout calculations.  The calculations will be added to the response by other stories...

In this PR the calculations for values 1-6 from the Feature Agility Ticket E-04525 are implemented.
Planned Move Start Date
Actual Move Date
Miles
Estimated Weight
Actual Net Weight
Pro Gear Weight (Customer)
Pro Gear Weight (Spouse)
Gross Incentive

### How to test

1. Obtain a ppm shipment id

* Find a move that has a PPM Shipment.
* Use the following query to get the PPM shipment id
* Change "m.locator" in the where clause to the move code.

```
select m.locator as move_code
       , m.id as move_id
       , ms.id as mto_shipment_id
       , ps.id as ppm_shipment_id
       , ms.shipment_type
  from moves m 
       inner join mto_shipments ms
       on m.id = ms.move_id
       inner join ppm_shipments ps
       on ms.id = ps.shipment_id
 where 1 = 1
   and m.locator = 'CHANGE_ME'
   and ms.shipment_type = 'PPM'
order by m."locator"
         , ms.id 
         , ms.shipment_type 
```
2. Get MilMove login cookie values
* Login to MilMove as a counselor
* Open developer tools
* Go to:  Applications tab > Storage > Cookies > http://officelocal:3000
* Record the values for the following cookies:
_gorilla_csrf
masked_gorilla_csrf
office_session_token

3. Open Postman.  

4. In the MilMove GHC API collection, drill down to the closeout endpoint.  
ppm-shipments > {ppmShipmentId}/closeout/Get the closeout calculations

5. Under the "Send" button, click the "cookies" link to add cookies

6. Add the 3 cookies recorded previously

7. Add an additional cookie, "X-CSRF-Token".  Its value will be the same as the "_gorilla" cookie. Then close the cookies window.

8. In the "Path Variables" section, set the PPM shipment id and click "Send".

9. Verify the values for the field in the JSON response matches the associated fields for values 1-6 from that particular PPM shipment.

## Screenshots

Screenshot 2024-01-12 at 10 13 10 AM

Screenshot 2024-01-12 at 10 14 20 AM

Screenshot 2024-01-12 at 10 15 13 AM

Screenshot 2024-01-12 at 10 15 28 AM

Screenshot 2024-01-12 at 10 15 53 AM

Screenshot 2024-01-12 at 10 16 21 AM

### CODE REVIEW

**Comment by taeJungCaci** [comment]
Looking at the other test files for other services, "_services_test.go" is different from "_test.go". Should we separate those two?

**Comment by WeatherfordAaron** [comment]
> Looking at the other test files for other services, "_services_test.go" is different from "_test.go". Should we separate those two?

I'm gonna say it's your call on this one. I put them in the same file just because there was so little to add. I'll split them up if you think it makes sense.

**Comment by WeatherfordAaron** [comment]
> > > > Looking at the other test files for other services, "_services_test.go" is different from "_test.go". Should we separate those two?
> > > 
> > > 
> > > I'm gonna say it's your call on this one. I put them in the same file just because there was so little to add. I'll split them up if you think it makes sense.
> > 
> > 
> > I don't really have the knowledge to say and was more of just pointing out what I saw from other files. It looked like _service_test.go was more specific to `testingsuite.PopTestSuite` stuff and has only that. Any thoughts @JamesHawks224 @brooklyn-welsh @KonstanceH ?
> 
> It seems like the "_services_test" tests are testing a whole service which calls all of its requests(fetcher, updater etc), and a "_test" is testing each request out individually. Since we aren't doing a separate fetcher/creator file I'm leaning more towards "_test" but I think this should be a majority rules vote

Agreed with the "majority rules".
My vote is that we either leave it the same or we have a separate file that tests the whole service and one that tests only the fetching.

**Comment by KonstanceH** [comment]
> > > > > Looking at the other test files for other services, "_services_test.go" is different from "_test.go". Should we separate those two?
> > > > 
> > > > 
> > > > I'm gonna say it's your call on this one. I put them in the same file just because there was so little to add. I'll split them up if you think it makes sense.
> > > 
> > > 
> > > I don't really have the knowledge to say and was more of just pointing out what I saw from other files. It looked like _service_test.go was more specific to `testingsuite.PopTestSuite` stuff and has only that. Any thoughts @JamesHawks224 @brooklyn-welsh @KonstanceH ?
> > 
> > 
> > It seems like the "_services_test" tests are testing a whole service which calls all of its requests(fetcher, updater etc), and a "_test" is testing each request out individually. Since we aren't doing a separate fetcher/creator file I'm leaning more towards "_test" but I think this should be a majority rules vote
> 
> Agreed with the "majority rules". My vote is that we either leave it the same or we have a separate file that tests the whole service and one that tests only the fetching.

yea I'll go with leaving it the same since we're past the sprint goal. If we want to update it later we can make a separate story for it.

**Review by taeJungCaci — APPROVED** [review]
Works for me!

**Review by KonstanceH — APPROVED** [review]
Intended functionality works for me.

**Pull request merged**
