### PR TITLE
Kim mb 6520 tac format validation

### PR DESCRIPTION
**Pull request by kimallen**
## Description

This limits the TAC field to 4 digits (using `TextMaskedInput`) and shows an error (onChange) if the value is less than 4 digits. 

## Reviewer Notes

I didn't add any tests since it basically utilizes existing components and error functionality.  LMK if there is somewhere I should add tests.

## Setup

Log in as a TxO.
Go to a move and click "Edit orders".

Go to the TAC field and start entering a TAC value.  You should see the error message, "Enter a 4-character TAC", until it is 4 digits.  If there are no values, the error message will say "Required".  The user should not be able to enter more than 4 digits.

## Code Review Verification Steps

* [x] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [x] User facing changes have been reviewed by design.
* [x] Request review from a member of a different team.
* [x] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6520) for this change

## Screenshots

Mar-02-2021 14-45-52

### CODE REVIEW

**Review by YanZ777 — COMMENTED** [review]
Is this meant to block saving until the user has entered in a valid TAC?

**Review by brooksr4 — APPROVED** [review]
Looks good from my end

**Comment by kimallen** [comment]
> Is this meant to block saving until the user has entered in a valid TAC?

It's meant to be a required field, I believe, so yes?  How is it currently behaving?

**Comment by YanZ777** [comment]
> > Is this meant to block saving until the user has entered in a valid TAC?
> 
> It's meant to be a required field, I believe, so yes? How is it currently behaving?

Just confirming! (Currently it doesn't allow saving until I fill out the required fields.)

**Review by YanZ777 — APPROVED** [review]

**Pull request merged**
