### PR TITLE
[MB-10100] Add NTS TAC/SAC rows to orders display Storybook

### PR DESCRIPTION
**Pull request by hannaliebl**
## Description

Add the NTS TAC and NTS SAC rows to the orders display list in Storybook.

## Reviewer Notes

Open questions for design:

The [mocks](https://app.zeplin.io/project/6058ba7eb92cf7391a455943/screen/618c112830dd52a8c1541422) shows the blank lines for missing HHG and NTS SAC/TAC, but the existing styles show the red missing text. I kept the red missing text - is that correct, or should it default to the blank line?

The component also never had styles for missing SACs, so I didn't update that as well, but maybe it should?

Finally, I did update the existing label text for "TAC / MDC" and "SAC / SDN" to "HHG TAC" and "HHG SAC" to match the mocks, but let me know if that isn't correct.

## Setup

```sh
make storybook
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-10100) for this change

## Screenshots
Missing info:

Screen Shot 2021-11-23 at 11 42 25 AM

Info exists:
Screen Shot 2021-11-23 at 11 42 32 AM

### CODE REVIEW

**Review by kylehilltruss — APPROVED** [review]
As Hanna mentioned, there's some open questions for @transcom/truss-design, but from a code perspective this looks good.

**Review by LeDeep — APPROVED** [review]
looks good

**Comment by amanda5iu** [comment]
>The mocks shows the blank lines for missing HHG and NTS SAC/TAC, but the existing styles show the red missing text. I kept the red missing text - is that correct, or should it default to the blank line?

The missing state applies only to items that are required - in this case, the HHG TAC. Optional items with no value show the line. Both SACs as well as the NTS TAC are optional, and should therefore show the line.

> The component also never had styles for missing SACs, so I didn't update that as well, but maybe it should?

See above note.

> Finally, I did update the existing label text for "TAC / MDC" and "SAC / SDN" to "HHG TAC" and "HHG SAC" to match the mocks, but let me know if that isn't correct.

`HHG TAC` and `HHG SAC` are correct.

**Review by amanda5iu — APPROVED** [review]
LGTM!

**Pull request merged**
