### PR TITLE
[ MB-9033 ] Update node v16.15.0

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

Update Node to `16.15.0` from `14.18.1`. This work is being done in anticipation of updating _react-uswds_ to version `3.0.1`. That upgrade is being tracked in #8662 separately.

## Setup to Run Your Code

Load up the application locally and make sure that it builds. I way of doing this is by running `make clean build` which will clean out your local dependencies and then build the client and server. This should exit cleanly without errors. You may also fire up the application with `make client_run` and `make server_run` in separate terminals to ensure that the application is running. Lastly, run `make client_test` and `make e2e_test_fresh` to ensure the testing commands still run after this Node update.
## Verification Steps for Author

These are to be checked by the author.

- [x] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

See https://github.com/transcom/circleci-docker/pull/267 for updates to the underlying Docker image changes.

### CODE REVIEW

**Comment by duncan-truss** [comment]
@rogeruiz Instead of changing the expected heading level in tests to not fail, I think we really want to fix our `<Alert>` component to accept the new `headingLevel` prop and give it a default value of "h3" so the app UI doesn't change.

https://github.com/trussworks/react-uswds/releases/tag/2.9.0

**Comment by rogeruiz** [comment]
Thanks @duncan-truss yeah i have not been taking a look at this as I'm trying to tangle the react-scripts upgrade in another PR. But that makes a ton of sense. I'll switch over to this after pushing up the react-scripts branch. 

Did you see this PR https://github.com/transcom/mymove/pull/8714? It includes some of the changes you mentioned. But it also changes the buttons as well. I think we'll need to split out some of those commits and pull them into this one.

**Comment by rogeruiz** [comment]
The last update on this is that we're going to wait until Monday for a preliminary review from @transcom/truss-design before we can merge this in.

**Comment by rogeruiz** [comment]
I extracted the Components referenced in the Happo diff and put this them in this Gist @juliemoon. This should give us a good idea of what components had style changes that triggered the Happo diff.

https://gist.github.com/rogeruiz/4f67a72d27ab53fc47c1965caaf4094c

**Review by michaelvaldes-truss — APPROVED** [review]
LGTM! Updates here make sense, all tests pass, and client seems to work as expected locally.

**Review by juliemoon — APPROVED** [review]
There are CSS changes that differs from our current MM but that can be addressed later. It LGTM!

**Pull request merged**
