### PR TITLE
[MB-3304] F/E dependencies analysis

### PR DESCRIPTION
**Pull request by suzubara**
## Description

This PR sets up a new Github workflow to use the [webpack-stats-diff-action](https://github.com/chronotruck/webpack-stats-diff-action). On PRs to master that make changes in the F/E source code, the workflow will build production assets for both HEAD and the base ref, and post a comment to the PR comparing the difference in size.

I did some experimenting on this PR to test out the resulting changes but for the most part they were too small to cause a substantial diff. I would like to merge this new workflow to at least give us a baseline to measure against and maybe refine it with more detailed information (like individual chunk sizes) later on.

I also removed the following dependencies, which as far as I can tell are no longer being used in any capacity:
- @18f/us-federal-holidays
- js-yaml
- jwt-decode
- react-form
- react-numeric-input
- selenium-webdriver

Note that removing the above packages would not have an expected diff in the bundle size since they were not being used by the code.

Finally, I removed some of the `resolutions` in the package.json file that are no longer needed (they are resolving to the correct versions now due to dependency updates).

## Reviewer Notes

No code/application changes are in this PR so tests passing should be sufficient. You can run local scripts to test that everything works as expected.

## Setup

```sh
yarn install
yarn test
yarn storybook
yarn audit

make client_run
make client_build
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3304) for this change

### CODE REVIEW

**Comment by suzubara** [comment]
Requesting an @transcom/truss-infrasec review on this since I am adding a Github action: https://github.com/chronotruck/webpack-stats-diff-action

**Review by esacteksab — APPROVED** [review]

**Comment by monfresh** [comment]
Is the idea here to keep an eye on the size of our assets? Is there a specific number we don't want to go over? If so, what happens if we do? How do we enforce the maximum size?

**Comment by monfresh** [comment]
In other words, what problem does this GitHub Action solve?

**Comment by suzubara** [comment]
@monfresh Yes, the idea here is to start measuring asset size. I don't think we have a specific benchmark in mind, or want to start enforcing one at this point (the number here is also misleading because it is size of total assets, which are split up into chunks).

My goal here was to add an easy indicator that can be used when someone is reviewing a PR, if for example some changes result in an unexpectedly large increase in size, that might be a red flag. I'd also like to start measuring a baseline so that we can look for changes as we add code & refactor. AFAIK we are not tracking this anywhere yet, so this was a low lift way to start doing so.

**Review by jenniferlynparsons — APPROVED** [review]
I admit I don't know enough about what analyze-bundle.yml is doing to give a thorough review of that, but things are working as expected locally.

**Review by monfresh — APPROVED** [review]
LGTM. All the commands worked for me locally.

**Comment by monfresh** [comment]
One thing I noticed is that my `yarn.lock` changed locally. Maybe it needs to be updated in this PR?

**Comment by suzubara** [comment]
@monfresh good catch! I updated the lockfile & also resolved conflicts with master

**Pull request merged**
