### PR TITLE
B 20653 mobile home shipment card

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

This PR updates the mobile home shipment status to 'SUBMITTED' when the shipment is submitted by the customer.
This also removes 'Please' from the shipment option description, and updates the shipment opiton description to match the PO AC.
Any labeling for Mobile home that's user facing is now "Mobile Home".

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Login as a customer
2. Add a mobile home shipment
3. Confirm the labeling is "Mobile Home"
4. Confirm description changes described above
5. Complete the move and sign
6. Confirm in DB that the mtoshipment status for that mobile home shipment is set to 'SUBMITTED'

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## ANDI Screenshots
_**Removed location Page title**_
Screenshot 2024-09-05 at 10 13 10 AM

_**Removed Please from shipment list description**_
Screenshot 2024-09-05 at 8 55 38 AM

_**Change of dimension description**_
Screenshot 2024-09-03 at 3 36 21 PM

_**Shipment Option label change**_
Screenshot 2024-09-03 at 3 35 26 PM

_**Shipment Card label change**_
Screenshot 2024-09-03 at 3 34 36 PM

### CODE REVIEW

**Comment by taeJungCaci** [comment]
Some of the things I've noticed while testing the functionality - There is another remarks field on the 2nd page which can be removed. And also when I edit, the pickup address doesn't seem to populate with existing data.

**Comment by KonstanceH** [comment]
> Some of the things I've noticed while testing the functionality - There is a remarks field on the 1st page and another on the 2nd page which can be removed. And also when I edit, the pickup address doesn't seem to populate with existing data.

Why should they be removed?
I left those remark fields because the other shipments have them as well, and in case the customer has other comments on the move before submitting. I feel like I should change the description on them because I left the formatting the same as the boat shipment though lol

I'm working on seeing why the pickupaddress isn't populating on edit now

**Comment by taeJungCaci** [comment]
> > Some of the things I've noticed while testing the functionality - There is a remarks field on the 1st page and another on the 2nd page which can be removed. And also when I edit, the pickup address doesn't seem to populate with existing data.
> 
> Ah actually I see why they gotta go I have the remarks already on the location page, I'll get rid of those. I feel like I should change the description on them because I left the formatting the same as the boat shipment though lol
> 
> I'm working on seeing why the pickupaddress isn't populating on edit now

Yeah, sorry I could have been more clear. For boat I have the remarks on the 1st page and not on the location page. And for the description - yeah... not sure because they boat story had a mockup with those description already on it, but I don't see one for Mobile home.

**Comment by JamesHawks224** [comment]
image
"home" in "Mobile home Information" should be capitalized.

**Review by JamesHawks224 — CHANGES_REQUESTED** [review]
Testing:  Success w/1 issue (see comment)
Code: lgtm

**Review by traskowskycaci — COMMENTED** [review]
Functionality looks good! Code looks good and meets AC. I did notice the AC is 
"Given a Mobile Home shipment has been created, 
When a customer reviews their `boat` shipment," 
and that `When` should probably refer to the mobile home shipment rather than boat

Inserting myself into this PR so forgive me if any of these are supposed to be this way, but noticed a few other small things. If all instances of the words "mobile home" should be "Mobile Home" I see a few spots without that capitalization - "Mobile home Information", "Mobile home details and measurements"
image

Also not sure if they need to be capitalized mid-sentence down in the remarks section here. However, I do see a typo where "signigicantly" should be "significantly"
image

I agree.. it should be Mobile Home Information instead of Mobile home Information.
Anytime "mobile" and "home" are together in reference to the type of shipment, they should both be capitalized. The only caveat is when we are referring to the customer's mobile home.

**Comment by traskowskycaci** [comment]
> Also not sure if they need to be capitalized mid-sentence down in the remarks section here. However, I do see a typo where "signigicantly" should be "significantly" image

If you think that significantly typo is out of scope for this PR, let me know and I can get an issue created. Looks like it would be a typo for both mobile and boat shipment remarks

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
One more comment because I am also looking at Aaron's changes for the office users - can we make the destination address field match? I'm good with either `Destination` or `Destination address`, whatever you both agree on. Just would like it to be the same if it's not too big of a deal :)

`Destination` for customer on the left bottom vs `Destination address` for office user on the right bottom
image

cc @WeatherfordAaron

**Comment by traskowskycaci** [comment]
> B-20653

D

> One more comment because I am also looking at Aaron's changes for the office users - can we make the destination address field match? I'm good with either `Destination` or `Destination address`, whatever you both agree on. Just would like it to be the same if it's not too big of a deal :)
> 
> `Destination` for customer on the left bottom vs `Destination address` for office user on the right bottom image
> 
> cc @WeatherfordAaron

Disregard, you're meeting both meeting AC with what you have

**Comment by KonstanceH** [comment]
> image "home" in "Mobile home Information" should be capitalized.

ah I see I'm on it

**Comment by KonstanceH** [comment]
> Functionality looks good! Code looks good and meets AC. I did notice the AC is "Given a Mobile Home shipment has been created,  When a customer reviews their `boat` shipment," and that `When` should probably refer to the mobile home shipment rather than boat
> 
> Inserting myself into this PR so forgive me if any of these are supposed to be this way, but noticed a few other small things. If all instances of the words "mobile home" should be "Mobile Home" I see a few spots without that capitalization - "Mobile home Information", "Mobile home details and measurements" image
> 
> Also not sure if they need to be capitalized mid-sentence down in the remarks section here. However, I do see a typo where "signigicantly" should be "significantly" image

Yea that's definitely fair. I'm gonna change them all to follow "Mobile Home"

**Comment by WeatherfordAaron** [comment]
> > Functionality looks good! Code looks good and meets AC. I did notice the AC is "Given a Mobile Home shipment has been created,  When a customer reviews their `boat` shipment," and that `When` should probably refer to the mobile home shipment rather than boat
> > Inserting myself into this PR so forgive me if any of these are supposed to be this way, but noticed a few other small things. If all instances of the words "mobile home" should be "Mobile Home" I see a few spots without that capitalization - "Mobile home Information", "Mobile home details and measurements" image
> > Also not sure if they need to be capitalized mid-sentence down in the remarks section here. However, I do see a typo where "signigicantly" should be "significantly" image
> 
> Yea that's definitely fair. I'm gonna change them all to follow "Mobile Home"

If you haven't already, updating this branch might fix some of it.

**Comment by WeatherfordAaron** [comment]
> Functionality looks good! Code looks good and meets AC. I did notice the AC is "Given a Mobile Home shipment has been created,  When a customer reviews their `boat` shipment," and that `When` should probably refer to the mobile home shipment rather than boat
> 
> Inserting myself into this PR so forgive me if any of these are supposed to be this way, but noticed a few other small things. If all instances of the words "mobile home" should be "Mobile Home" I see a few spots without that capitalization - "Mobile home Information", "Mobile home details and measurements" image
> 
> Also not sure if they need to be capitalized mid-sentence down in the remarks section here. However, I do see a typo where "signigicantly" should be "significantly" image

I agree.. it should be Mobile Home Information instead of Mobile home Information.
Anytime "mobile" and "home" are together in reference to the type of shipment, they should both be capitalized. The only caveat is when we are referring to the customer's mobile home.

**Review by WeatherfordAaron — APPROVED** [review]
lgtm once you get any straggling errors cleaned up 👽

**Review by traskowskycaci — APPROVED** [review]
Looking good!

**Comment by JamesHawks224** [comment]
> Testing: Success w/1 issue (see comment) Code: lgtm

Checked update.  issue resolved.

**Review by JamesHawks224 — APPROVED** [review]

**Pull request merged**
