### PR TITLE
Update go 1.16.7

### PR DESCRIPTION
**Pull request by Ryan-Koch**
## Description

Updates go to 1.16.7 using these (steps)[https://github.com/transcom/mymove/wiki/upgrade-go-version#how-to-upgrade-go-version].

## Set up

See instructions in https://github.com/transcom/mymove/wiki/upgrade-go-version

Or:

Update .tool-versions to point to new version of golang
If you've done some PATH sorcery to point to a specific Go version (as detailed here), you'll have to update that as well
(if you do not yet have asdf installed, see How to get up and running)

    Run asdf install to install the new version
    Run asdf global golang to update global version as well
    go version and asdf which go to check it worked
    Add this change to the PR created in the next step
```
go version
go version go1.16.7 darwin/amd64

asdf which go
/Users/ryan/.asdf/installs/golang/1.16.7/go/bin/go
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

### CODE REVIEW

**Review by gidjin — APPROVED** [review]
Change good. I am using nix, probably should get confirmation from someone with asdf setup  too.

**Review by LeDeep — APPROVED** [review]
looks good

**Comment by LeDeep** [comment]
> Change good. I am using nix, probably should get confirmation from someone with asdf setup too.

**Comment by LeDeep** [comment]
oops, accidently closed it. working fine with asdf.

**Review by reggieriser — APPROVED** [review]
LGTM from the `brew`/`asdf` perspective.  Built everything from scratch without any issues.

**Pull request merged**
