### PR TITLE
INT B-18680 Departure Date For Origin Sit Is Not Persisting

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18680](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a905470)

**NOTE:**
This PR includes other changes made by others that are in Main, but not in Integration.
These are the list of files that I have made changes to:

```
- pkg/handlers/primeapi/mto_service_item_test.go
- pkg/handlers/primeapi/payloads/payload_to_model.go
- pkg/handlers/primeapi/payloads/payload_to_model_test.go
- playwright/tests/office/txo/sitUpdates.spec.js
- src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
- src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
- src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
- src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
- src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
```

## Summary

When adding an Origin SIT via Prime and entering both entry and departure at the same time SIT is added, the departure date does not display in the SIT details > SIT Departure Date (TOO)

This PR fixes that and other related quick fixes were added as well.

**Updates:**

- Label changed: `SIT Departure Date` to `SIT departure date`.
- Date format changed to: `dd mm yyyy` to match.
- Value for `SIT departure date` now shows up in the SIT module when Prime requests a SIT and is approved by TOO.
- Added `SIT departure date` in Convert to Customer Expense modal to match with other views.

### How to test

1. Create a HHG move -> SC approves/submits -> TOO approves move
2. Find the move in Prime Simulator -> Click `Add Service Item` -> Fill out the form to add Origin SIT and make sure to include the SIT departure date.
3. Go to TOO's Move Task Order page -> Scroll down and approve SIT requested Items.
4. You should see the date for `SIT departure date` populated.
5. Also label should read `SIT departure date` with date format of `dd mm yyyy`.

## Screenshots
image
image

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
I would say commits need to stay relevant to the BL item for tracking purposes and there's a lot of changed code in this that is not relevant to the Agility description & AC.

**Comment by taeJungCaci** [comment]
> I am seeing a lot of commits that merged `main` into this branch, but you're wanting to merge this into `integrationTesting`. I'll let @deandreJones chime in on this, but I'm not sure what to do about all of the irrelevant code changes to the Agility BL item coming along with this merge.

Yes, there has been items that were merged into Main, but not into Integration after rebase of Integration. Which is why I am having these commits that are not mine going into Integration on this PR. All of their commits are there just have not been merged into Integration.

**Comment by danieljordan-caci** [comment]
> > I am seeing a lot of commits that merged `main` into this branch, but you're wanting to merge this into `integrationTesting`. I'll let @deandreJones chime in on this, but I'm not sure what to do about all of the irrelevant code changes to the Agility BL item coming along with this merge.
> 
> Yes, there has been items that were merged into Main, but not into Integration after rebase of Integration. Which is why I am having these commits that are not mine going into Integration on this PR. All of their commits are there just have not been merged into Integration.

Then wouldn't those devs recreate their PRs and have the team merge them back into `integrationTesting`?

**Comment by deandreJones** [comment]
I will say that if properly pulling in main in the main bl branch and then merging into int branch - there can be cases where there are commits to main but not int(ie dependacies and config changes)
Also a slim chance that some bls were in odd spot after rebase where they passed testing but didn't get into main til after rebase so they would only be seen in main

**Comment by taeJungCaci** [comment]
> > > I am seeing a lot of commits that merged `main` into this branch, but you're wanting to merge this into `integrationTesting`. I'll let @deandreJones chime in on this, but I'm not sure what to do about all of the irrelevant code changes to the Agility BL item coming along with this merge.
> > 
> > 
> > Yes, there has been items that were merged into Main, but not into Integration after rebase of Integration. Which is why I am having these commits that are not mine going into Integration on this PR. All of their commits are there just have not been merged into Integration.
> 
> Then wouldn't those devs recreate their PRs and have the team merge them back into `integrationTesting`?

That would be an option, but then we would have to all wait for each of them to finish doing that before I can get this one moving. I guess I can go with which ever.

**Comment by taeJungCaci** [comment]
> I will say that if properly pulling in main in the main bl branch and then merging into int branch - there can be cases where there are commits to main but not int(ie dependacies and config changes) Also a slim chance that some bls were in odd spot after rebase where they passed testing but didn't get into main til after rebase so they would only be seen in main

This PR was 100% properly pulled in from main and then merged into my int branch. I will wait for your command @deandreJones

**Review by deandreJones — APPROVED** [review]

**Review by brooklyn-welsh — APPROVED** [review]
It looks like Dre approved the changes, and everything worked for me during testing and the code looks good, so I'm approving 👍

**Pull request merged**
