### PR TITLE
B-19551 PPM showing as INCOMPLETE when it's initially saved without a Closeout Office

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Test steps I took
1. Create a move and start the process for creating a PPM shipment on it.
2. For the "PPM Date and Location" form, if you fill out all the info except for the closeout office, you will be unable to continue.

### CODE REVIEW

**Review by KonstanceH — APPROVED** [review]
LGTM

**Review by taeJungCaci — COMMENTED** [review]
Looks like I get error msg up top, but I didn't see any required note on the closeout office field. 
image

**Comment by WeatherfordAaron** [comment]
> Looks like I get error msg up top, but I didn't see any required note on the closeout office field. image

I wonder what it took to get the submit button to not be disabled.

**Comment by taeJungCaci** [comment]
> > Looks like I get error msg up top, but I didn't see any required note on the closeout office field. image
> 
> I wonder what it took to get the submit button to not be disabled.

I think they might want it not disabled so when they click the button and there is no office selected, it auto scrolls up to the closeout office with an error msg that it is required field. At least that's how I took it from the AC I think.

**Comment by taeJungCaci** [comment]
> > > Looks like I get error msg up top, but I didn't see any required note on the closeout office field. image
> > 
> > 
> > I wonder what it took to get the submit button to not be disabled.
> 
> I think they might want it not disabled so when they click the button and there is no office selected, it auto scrolls up to the closeout office with an error msg that it is required field. At least that's how I took it from the AC I think.

Actually, I just read the AC again and seems to be contradicting - because you can't get required field err msg showing if you  don't hit continue lol...AC might be off?

**Review by taeJungCaci — APPROVED** [review]
talked with Aaron - approved

**Pull request merged**
