### PR TITLE
Dependency updates for 20190507

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

Catching up on several weeks of dependency updates.

## Reviewer Notes

Related to #2099

## Code Review Verification Steps

* [x] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/165870745) for this change.

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
@LeDeep @sarboc - there's one failing test here and I'm having trouble figuring it out. Can you give me an assist on this?

**Comment by LeDeep** [comment]
> @LeDeep @sarboc - there's one failing test here and I'm having trouble figuring it out. Can you give me an assist on this?

@chrisgilmerproj have you tried rebuild? Possible that its just an intermittent failure, as 

> @LeDeep @sarboc - there's one failing test here and I'm having trouble figuring it out. Can you give me an assist on this?

@chrisgilmerproj have you tried rebuilding? The failing test passes for me locally when I checkout your branch.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj have you tried rebuilding? The failing test passes for me locally when I checkout your branch.

I did several times. And then I gave up. But it passes locally so I'm at a loss. I could merge master in again and then try and see what happens.

**Comment by LeDeep** [comment]
> > @chrisgilmerproj have you tried rebuilding? The failing test passes for me locally when I checkout your branch.
> 
> I did several times. And then I gave up. But it passes locally so I'm at a loss. I could merge master in again and then try and see what happens.

It didn't appear, on quick glance, that any of the updated dependencies should have an impact on the failing test. Can dig deeper if it continues to fail after merging master.

**Comment by chrisgilmerproj** [comment]
> It didn't appear, on quick glance, that any of the updated dependencies should have an impact on the failing test. Can dig deeper if it continues to fail after merging master.

I merged in master and I'm running the tests once more. I'm 🤞 with this one.

**Comment by chrisgilmerproj** [comment]
@LeDeep - Looks like it worked! Can you review and approve? Per the instructions we're supposed to just merge these in if tests pass.

**Pull request merged**
