### PR TITLE
MB-8983 Create Devseed Data for Reweighs

### PR DESCRIPTION
**Pull request by YanZ777**
## Description

-  extract out related data creation into a new subscenario for reweighs
- create a new function to make reweighs with a given shipment and reweigh weight
- add new devseed data for reweighs with
    - multiple shipments
    - missing reweigh weight
    - max shipment weight exceeded
    - move with billable weights

## Reviewer Notes

Does the setup look ok? 
The UI for the data won't look any different for the TIO because there haven't been any UI elements put in yet. 

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make office_client_run
make server_run
```
When you access the office site and login as the TIO, there should be new moves with the locators of
- BILWEI 
- MULTRW
- MISHRW 
- MAXCED

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8983) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

### CODE REVIEW

**Comment by pearl-truss** [comment]
@YanZ777 looks good and I'm wondering if a shipment that's missing a reweigh should be included?

**Comment by YanZ777** [comment]
> @YanZ777 looks good and I'm wondering if a shipment that's missing a reweigh should be included?

I put in `createReweighWithShipmentMissingReweigh`, where I passed in 0 to `makeReweighForTIO`, but I don't know if that is sufficient for making it a missing reweigh.

**Comment by pearl-truss** [comment]
> > @YanZ777 looks good and I'm wondering if a shipment that's missing a reweigh should be included?
> 
> I put in `createReweighWithShipmentMissingReweigh`, where I passed in 0 to `makeReweighForTIO`, but I don't know if that is sufficient for making it a missing reweigh.

Ah okay, sorry I missed that.. I think it would make since to pass in nil but I'm curious what others think

**Comment by YanZ777** [comment]
> > > @YanZ777 looks good and I'm wondering if a shipment that's missing a reweigh should be included?
> > 
> > 
> > I put in `createReweighWithShipmentMissingReweigh`, where I passed in 0 to `makeReweighForTIO`, but I don't know if that is sufficient for making it a missing reweigh.
> 
> Ah okay, sorry I missed that.. I think it would make since to pass in nil but I'm curious what others think

No worries! Looking at it again, it does make more sense to pass in nil, so I made a new function that takes in the shipment, but doesn't take in a weight so that nothing is passed.

**Review by donaldthai — APPROVED** [review]
Looks really good! I think the only thing I can think of is a shipment that may be missing an estimated weight but that's super minor.

**Comment by YanZ777** [comment]
> Looks really good! I think the only thing I can think of is a shipment that may be missing an estimated weight but that's super minor.

Good catch, I've added another subscenario to handle that case.

**Pull request merged**
