### PR TITLE
B-18413 prime sim sit address change and dest sit form changes

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

We are transitioning to the shipment address being used for the `final_destination_address` on the service item level. This means that we no longer need the components in the Prime Simulator handling a SIT Destination Address Change, as well as removing the address form when requesting destination SIT.

This PR does the following:
- removes address form when requesting destination SIT
- added in some information in the dest SIT form for clarity/understanding of functionality
- removed `Request Destination SIT Address Change` button in `MoveDetails.jsx` component
- removed route & associated components for requesting SIT destination address change
- added tests & test file for destination SIT form
- added in functionality of `createNonSITAddressUpdateRequest` endpoint with new components and form with validation
- added in `createNonSITAddressUpdateRequest` endpoint to `primeApi.js`
- tests for all new components

**NOTE** This PR is dependent on [this BL item](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A882395&RoomContext=TeamRoom%3A808731&concept=TeamRoom) as for functionality. Please ensure that this does not get merged prior to the above mentioned PR.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test Scenario 1

1. Access MM office and open prime simulator
2. Open any move
3. Confirm the `Request Destination SIT Address Change` button is no longer in shipment summaries
4. Click on `Add service item` button
5. In the `Service item type` dropdown, select `Destination SIT`
6. Confirm there are no address fields
7. Confirm that the info appears above `Create service item` button and is clear in understanding

### How to test Scenario 2

1. Access MM office and open prime simulator
2. Open any move
3. Confirm the `Update Shipment Destination Address` is  on the page
4. Click on da button
5. Change whatever values you want - confirm that form is disabled when `Address 1`, `City`, and `Contractor Remarks` are blank
6. Send it
7. Confirm the new address is updated on the page
8. If the ZIP code changed drastically and requires TOO approval, find the move as a TOO and confirm it requires review

## Screenshots
Screenshot 2023-12-29 at 11 36 42 AM

Destination SIT request form
Screenshot 2023-12-29 at 11 37 11 AM

New button added to `Shipment.jsx` to call `createNonSITAddressUpdateRequest` endpoint
Screenshot 2024-01-02 at 10 59 12 AM

Form for `createNonSITAddressUpdateRequest` endpoint
Screenshot 2024-01-02 at 11 00 32 AM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Putting this in draft to add in additional features of using the `createNonSitAddressChangeRequest` endpoint within the prime simulator.

**Comment by danieljordan-caci** [comment]
BACK ONLINE

Added in functionality of `createNonSITAddressRequestUpdate` endpoint to prime simulator. Updated description if y'all wanna check it.

**Review by cameroncaci — APPROVED** [review]
Meets AC, functions as intended when tested locally, and code looks good

**Review by traskowskycaci — COMMENTED** [review]
Looks good. Do we want to disable the edit button next to `Destination Address:` down at the bottom and only allow them to update via the Update Shipment Destination Address button?

**Review by traskowskycaci — COMMENTED** [review]
Also saw that the Save button is not grayed out when the contractor remarks are blank. I do get the "Contractor remarks are required" message when trying to save though. 

Asking for my own learning - do we have a standard or anything for what we do with buttons if the user hasn't filled out all the required fields on a form?

image

**Comment by danieljordan-caci** [comment]
> Looks good. Do we want to disable the edit button next to `Destination Address:` down at the bottom and only allow them to update via the Update Shipment Destination Address button?
> 
> image

Per our convo - that edit button is used to update a shipment address, not create a new one. I'm not sure if it applies to this BL item specifically, but nothing is stopping the prime from updating this to potentially be in a different ZIP code.

Per the docs:
```
This endpoint is used to update the pickup, secondary, and destination addresses on an MTO Shipment. mto-shipments/{mtoShipmentID}/shipment-address-updates is for updating a delivery address. The address details completely replace the original, except for the UUID.
Therefore a complete address should be sent in the request.
When a destination address on a shipment is updated, the destination SIT service items address ID will also be updated so that shipment and service item final destinations match.

This endpoint cannot create an address.
To create an address on an MTO shipment, the caller must use [updateMTOShipment](http://officelocal:3000/swagger-ui/prime.html#operation/updateMTOShipment) as the parent shipment has to be updated with the appropriate link to the address.
```

**Comment by danieljordan-caci** [comment]
> Also saw that the Save button is not grayed out when the contractor remarks are blank. I do get the "Contractor remarks are required" message when trying to save though.
> 
> Asking for my own learning - do we have a standard or anything for what we do with buttons if the user hasn't filled out all the required fields on a form?
> 
> image

I'm not aware of a "standard" or anything. I just make sure that, with validation, the form can't be successfully submitted unless all fields are valid. What you're seeing is the validation schema for the address form is a reusable component that's used everywhere else so I just reused that - since contractor remarks is extra for this endpoint, I just added it to the form and added in some `Yup` validation.

**Review by traskowskycaci — APPROVED** [review]

**Pull request merged**
