### PR TITLE
Fix responsible_user_id and add names to audit log

### PR DESCRIPTION
**Pull request by garrettqmartin8**
## Description

We should be recording the specific admin user's id when logging any activity they perform in the admin app. This PR fixes that and adds their full name to the log line so we can more easily and quickly identify who performed the action.

## Setup

- `make server_run`
- `make client_run`
- Log into the admin app and edit an office user. Then go check the log line and make sure the correct full name is present in the `responsible_user_name` field.

## Code Review Verification Steps

* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/168641855) for this change

### CODE REVIEW

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj who should I check with about the potential PII leak?

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj who should I check with about the potential PII leak?

I've asked Harlan and Jarod in Slack and the answer is we can record names in the logs if the logs are well handled, meaning encrypted and with limited access. That means I have some work to do briefly before we merge so I'll come back to this as soon as I can.

**Comment by chrisgilmerproj** [comment]
@garrettqmartin8 - It appears that our application logs are not encrypted. So before adding names we'll have to address that issue. Can you modify this PR into two separate PRs? The first to update the UUID? And the second with the names that we can apply after I get the logs encrypted? I'll add something to my backlog to address the encryption and the documentation around what we need.

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj sounds good, I'll update this PR and open a new one for the names.

**Comment by garrettqmartin8** [comment]
@chrisgilmerproj updated and opened a draft PR in #2876 for adding names back.

**Pull request merged**
