### PR TITLE
[MB-7547] add EDI_ERROR to support API

### PR DESCRIPTION
**Pull request by jacquelineIO**
## Description

Adding `EDI_ERROR` status to the support API. It was introduced in PR https://github.com/transcom/mymove/pull/6089 but adding to the support API was missed.

## Reviewer Notes

n/a

## Setup

This is the effect support API. Run locally or in staging. There is nothing really see happening right now. The connections to GEX are not working.

filename: sendtosyncada.json
```json
{
  "body": {
    "sendToSyncada": true,
    "readFromSyncada": false,
    "deleteFromSyncada": false
  }
}
```

```sh
prime-api-client --insecure support-reviewed-payment-requests --filename sendtosyncada.json
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7547) for this change

## Screenshots

n/a

### CODE REVIEW

**Review by pearl-truss — COMMENTED** [review]
When I tried running the `support-reviewed-payment-requests` command I get back this error:
`File decode failed: json: unknown field "deleteFromSyncada"`

**Comment by jacquelineIO** [comment]
>  `File decode failed: json: unknown field "deleteFromSyncada"`

Did you rebuild your cli? I have an alias, whenever I pull a branch I rebuild the cmd tools

**Comment by pearl-truss** [comment]
> > `File decode failed: json: unknown field "deleteFromSyncada"`
> 
> Did you rebuild your cli? I have an alias, whenever I pull a branch I rebuild the cmd tools

I used the alias you sent over which resolved the initial issue but then started seeing this error (which also appears on master) so I think there's something up with my local set up

`{"detail":"function ProcessReviewedPaymentRequest failed call to generator.Generate: id: 85c5ae40-b915-41dd-a970-722bd70c7c19 not found for paymentServiceItemParam","instance":"5eca5e47-c4e3-4cc1-b2be-02ff4ffd9b4c","title":"Internal Server Error"}`

**Review by pearl-truss — APPROVED** [review]
Thanks for the info on slack. I finally got my set up to run the processor without errors and the code changes look good

**Pull request merged**
