### PR TITLE
MB-12485 add CUI header to the customer app

### PR DESCRIPTION
**Pull request by YanZ777**
## Summary

This adds the CUI header to the customer app. 
Also adds a test to make sure that the header shows up.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the customer app
2. There should be a new banner saying "CONTROLLED UNCLASSIFIED INFORMATION"
3. The same banner should also be visible on login.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

### Logged Out
image

### Logged In
image

### Phone View - Logged In
image

### CODE REVIEW

**Comment by AnnaGingle** [comment]
It looks like the text size isn’t responsive. I would suggest using Desktop heading/h6 and mobile heading/h6.

**Review by AnnaGingle — COMMENTED** [review]
It looks like the text size isn’t responsive. I would suggest using Desktop heading/h6 and mobile heading/h6.

**Review by AnnaGingle — APPROVED** [review]
Looks good!

**Review by LeDeep — APPROVED** [review]
looks good 🎸

**Pull request merged**
