### PR TITLE
B 18823 ghc create requested office user

### PR DESCRIPTION
**Pull request by cameroncaci**
## [B-18823](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A907135)

[First integration PR](https://github.com/transcom/mymove/pull/12199)
[Second integration PR](https://github.com/transcom/mymove/pull/12534)

### CODE REVIEW

**Review by danieljordan-caci — APPROVED** [review]
Commits seem to match up. LGTM!

**Review by traskowskycaci — APPROVED** [review]
Saw these commits that differed from the integration branches but looks like the code to match both of those is already in integration. Otherwise matches, looks good!

image

**Comment by cameroncaci** [comment]
Let me innnnnnnnn

**Comment by danieljordan-caci** [comment]
Gotta be faster than that Cameron!

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
