### PR TITLE
INT B-18832 admin UI add edit page for requested office users (MERGE AFTER B-18831)

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Expanding upon [this PR](https://github.com/transcom/mymove/pull/12302) where we can see an overview page of the requested office user that was selected, this PR covers what happens when the edit button is clicked. This PR does contain code from B-18831 (link above), so please ensure that merges first.

This PR does the following:
- adds `RequestedOfficeUserEdit.jsx` component
- sprinkled some CSS in there
- removed incorrect `propType` in `AdminTimeout` to get rid of ugly red error in console
- added validation to check if `rejectionReason` is provided when rejecting, if not, throw an error on the screeen
- added validation to check if either `edipi` or `otherUniqueId` is provided, if not, throw an error on the screen

### How to test

1. Access MM as admin
2. Login and you should see the `Requested Office Users` screen
3. If empty, update some values in the `office_users` table to have a status of `REQUESTED`
4. Should see some folks now
5. Select one and click the `Edit` button (either one is fine)
6. Should now be seeing the screen in the screenshot below
7. Update some values, check some validations, and submit the form
8. You should see those values update in the db

## Screenshots
Screenshot 2024-03-25 at 9 31 11 AM

### CODE REVIEW

**Review by cameroncaci — COMMENTED** [review]
Should "Save" be an option without approval or rejection?

**Comment by cameroncaci** [comment]
> Should "Save" be an option without approval or rejection?

I was thinking this because of the "Need to be able to change fields prior to approve / reject", technically that's the case as is, but no change and save prior to actioning

**Comment by danieljordan-caci** [comment]
> Should "Save" be an option without approval or rejection?

I don't believe so. Looking at the AC - seems a bit out of scope:
```
Given I am a MilMove Admin User

When I am viewing the overview screen of a requested office user and click the “edit” button

Then it will navigate me to a screen that lets me update necessary fields




Given I am a MilMove Admin User

When I am viewing the edit screen of a selected requested office user

Then there will be an approve button I can use that will approve that account




Given I am a MilMove Admin User

When I am viewing the edit screen of a selected requested office user

Then there will be a reject button I can use that will reject that account




Given I am a MilMove Admin User

When I am viewing the edit screen of a selected requested office user

Then I can freely change all relevant fields of the user prior to approving/rejecting. 




Given I am a MilMove Admin User

When I am viewing the edit screen of a selected requested office user

Then I can enter a rejection reason prior to rejecting a requested user
```

**Review by cameroncaci — APPROVED** [review]
Meets AC, functions, code looks good

**Review by traskowskycaci — APPROVED** [review]
Worked without issue!

**Pull request merged**
