### PR TITLE
MB-10172 Financial Review Flag handler can both set and unset flag

### PR DESCRIPTION
**Pull request by Ryan-Koch**
## Description

This makes it so the handler and service for Financial Flags is able to take a true/false boolean to say whether it should be set or unset.

I also used this as an opportunity to have the service make use of the validation pattern described in our documentation over [here](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/service-validation#validator-interface).

I also pulled in changes from https://github.com/transcom/mymove/pull/7760.

## Setup

to run the tests and make sure things are going:

```sh
make db_test_reset && make db_test_migrate
```
For the handler:
```sh
go test ./pkg/handlers/ghcapi/ -testify.m TestSetFinancialReviewFlagHandler
```

For the service:
```sh
go test ./pkg/services/payment_service_item -testify.m TestFinancialReviewFlagSetter
```

If you want to test manually you'll need to use postman. Some docs on setting that up [here](https://transcom.github.io/mymove-docs/docs/tools/postman/setting-up-postman). You'll need to hit this endpoint: `/moves/{moveID}/financial-review-flag`.

If you want to interact with it through the app then you need to get the thing running:

```sh
make server_run
make office_client_run
```

Then log in as an office role. From there you can navigate to the Move Details page for a move. Once there you should be able to flag and unflag that move for financial review.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## Screenshots

image
image
image
image

### CODE REVIEW

**Comment by christopherhuii** [comment]
@Ryan-Koch @cosburn When `Yes` is selected and a remark is entered, then `No` is selected, you can't see the remark that was entered. My understanding was that it would display, but just appear as disabled. (It's just a CSS rule that needs to be removed)

Additionally, should the remark be filled when a user clicks on `Edit`. I'm not sure if this is future work or should be included here.

**Comment by Ryan-Koch** [comment]
> @Ryan-Koch @cosburn When `Yes` is selected and a remark is entered, then `No` is selected, you can't see the remark that was entered. My understanding was that it would display, but just appear as disabled. (It's just a CSS rule that needs to be removed)
> 
> Additionally, should the remark be filled when a user clicks on `Edit`. I'm not sure if this is future work or should be included here.

Ah you're right I missed doing the default value thing. I can add that to the PR.

**Comment by Ryan-Koch** [comment]
> > @Ryan-Koch @cosburn When `Yes` is selected and a remark is entered, then `No` is selected, you can't see the remark that was entered. My understanding was that it would display, but just appear as disabled. (It's just a CSS rule that needs to be removed)
> > Additionally, should the remark be filled when a user clicks on `Edit`. I'm not sure if this is future work or should be included here.
> 
> Ah you're right I missed doing the default value thing. I can add that to the PR.

Alright so I got the default values in for this commit: https://github.com/transcom/mymove/pull/7749/commits/cb52c692ae4dfee98d84a84f007a51b5d1bf49b6 though the thing I haven't figured out just yet is disabling the field but also keeping the value.

**Review by christopherhuii — APPROVED** [review]
functionally looks good to me. verified for both the TOO and service counselor.

**Review by Shkeating — APPROVED** [review]
lookin good!

**Pull request merged**
