### PR TITLE
Added weight billed to DDSFSC

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

Added weight billed implementation to DDSFSC serviceItem.
Provided the list I was provided to add serviceItems. If missing any please let me know. I added anything with CWT and/or Weight

ServiceItemsThatAllowBillableWeight

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
What about the sister SIT item code, DOSFSC?

**Comment by danieljordan-caci** [comment]
> What about the sister SIT item code, DOSFSC?

Actually this might be unnecessary since we are only dealing with deliveries OUT of SIT. Right?

**Review by traskowskycaci — COMMENTED** [review]
There aren't differences in how we treat service items with CWT/hundred weight and those with just 'weight', right?

**Review by danieljordan-caci — APPROVED** [review]
Until the next time haha

**Review by traskowskycaci — APPROVED** [review]

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
