### PR TITLE
INT B-20898 sit entry date & FADD validation on update and creation

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

When the Prime requests SIT for destination, we want to make sure that the SIT entry date is not before the provided First Available Delivery Date.
In addition to creation, we also need to consider this logic when SIT service items are updated (resubmitted).

This PR does the following:
- adds `UnprocessableEntity` return with error to the prime `mto_service_item` `CreateMTOServiceItemHandler` handler
- added new section in `mto_service_item_validators.go` and placed existing relevant validators in that section
- added validator for creation of DDFSIT (destination SIT) & SIT dest service item updates that handles logic of ensuring the SIT entry date is on or after any of the FADDs (max of 2)
- updates and adds all relevant tests

### How to test

1. Fire up MilMove as an office user
2. Either create or find a move that contains an HHG shipment
3. Go into the Prime simulator and click "Add service item"
4. Add destination SIT and fill out all the data, but make sure the SIT entry date is BEFORE any of the First/second available delivery dates
5. Try to submit - you should get an error back
6. Now change the SIT entry date to be AFTER the FADDs and submit - it should succeed
7. Now go in as the TOO and reject all of those service items
8. You'll need postman for this next part to test this validation on updating
9. Using the endpoint `http://primelocal:3000/prime/v1/mto-service-items/{mtoServiceItemID}`
10. Find the `id`, `eTag`, `reServiceCode` and `sitEntryDate` values of the service item you want to update
11. In your headers, ensure you have `X-CSRF-Token` with the `masked_gorilla` cookie value
12. Also in your headers, ensure you have `If-Match` with the `eTag` value
13. Now in your body, you want to send something like this for each dest SIT service item:
```
{
    "updateReason": "changing SIT entry date",
    "requestApprovalsRequestedStatus": true,
    "modelType": "UpdateMTOServiceItemSIT",
    "sitEntryDate": "2024-08-11",
    "reServiceCode": "DDASIT"
}
```
14. The goal here is to try and resubmit these by changing the SIT entry date to be before the FADD and make sure you get an error
15. Then try again with a SIT entry date that's after the FADDs and ensure it is successful
16. Rinse and repeat for each destination SIT service item

## Screenshots
Screenshot 2024-08-09 at 2 13 14 PM

### CODE REVIEW

**Review by TevinAdams — APPROVED** [review]
Worked through the test case and was not able to update sitEntry to a date before FADD or SADD. Same results on postman.

**Review by traskowskycaci — COMMENTED** [review]
Could the SIT entry date and the FADD be the same, and should we allow that?

**Comment by danieljordan-caci** [comment]
> Could the SIT entry date and the FADD be the same, and should we allow that?

They can be the same, yes. It should pass if they are.

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
I am getting the validation error for the following test case on an HHG shipment I created:
FADD is 20 Aug
SADD is 22 Aug
SIT entry date is 21 Aug

image

image

Then if I change the SIT entry date to be 2 days after the FADD, I am able to request destination SIT.
image

**Comment by danieljordan-caci** [comment]
> I am getting the validation error for the following test case on an HHG shipment I created: FADD is 20 Aug SADD is 22 Aug SIT entry date is 21 Aug
> 
> image
> 
> image
> 
> Then if I change the SIT entry date to be 2 days after the FADD, I am able to request destination SIT. image

This is expected behavior. When creating service items, the FADD & SADD are stored in an array called `CustomerContacts` and that is what is being looped through to make sure the SIT entry date is before the `FirstAvailableDeliveryDate`  in each object.

**Comment by danieljordan-caci** [comment]
> I am getting the validation error for the following test case on an HHG shipment I created: FADD is 20 Aug SADD is 22 Aug SIT entry date is 21 Aug
> 
> image
> 
> image
> 
> Then if I change the SIT entry date to be 2 days after the FADD, I am able to request destination SIT. image

To add to this, the payload when creating destination SIT looks like this for the Prime:
```
{
  "moveTaskOrderID": "1f2270c7-7166-40ae-981e-b200ebdf3054",
  "mtoShipmentID": "1f2270c7-7166-40ae-981e-b200ebdf3054",
  "modelType": "MTOServiceItemDestSIT",
  "reServiceCode": "DDFSIT",
  "dateOfContact1": "2019-08-24",
  "dateOfContact2": "2019-08-24",
  "timeMilitary1": "1400Z",
  "timeMilitary2": "1400Z",
  "firstAvailableDeliveryDate1": "2019-08-24",
  "firstAvailableDeliveryDate2": "2019-08-24",
  "sitEntryDate": "2019-08-24",
  "sitDepartureDate": "2019-08-24",
  "reason": "string",
  "sitRequestedDelivery": "2019-08-24",
  "sitCustomerContacted": "2019-08-24"
}
```

The `sitEntryDate` has to be before either of the `firstAvailableDeliveryDate1` or `firstAvailableDeliveryDate1`

**Comment by danieljordan-caci** [comment]
@traskowskycaci I have updated the error message to be more specific on dates and also updated the screenshot in the description

Take a look when ya got a minute

**Review by traskowskycaci — APPROVED** [review]
What a beaut of a validation error, if I've ever seen one! Looks wonderful!

image

**Pull request merged**
