### PR TITLE
MB-6045: add permissions to docker-specific postgresql roles

### PR DESCRIPTION
**Pull request by carterjones**
## Description

This makes more changes to the permission scheme within our Docker PostgreSQL environment, so that it has better parity with our RDS environment. Specifically, it makes two changes:

1. It makes the `ecs_user` be a part of the `master` role. This is already the case in RDS.
1. It adds the `CREATEDB` and `CREATEROLE` permissions to the `master` role. This is already the case in RDS.

Here is how things look in RDS. `ecs_user` is a member of `master`, which means that `ecs_user` has permissions to call `SET ROLE master`. Additionally, `master` has the ability to create roles and databases.

```text
sh-4.2$ psql --host="${DBHOST}" --port="${DBPORT}" --username="${DBUSER}" --dbname="${DBNAME}"
psql (9.2.24, server 12.4)
WARNING: psql version 9.2, server version 12.0.
         Some psql features might not work.
SSL connection (cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256)
Type "help" for help.

app=> \dg
                            List of roles
Role name |                   Attributes                   |    Member of
----------+------------------------------------------------+------------------
 ecs_user |                                                | {rds_iam,master}
 master   | Create role, Create DB                        +| {rds_superuser}
<snip>

app=> select current_user;
 current_user
--------------
 ecs_user
(1 row)

app=> set role master;
SET
app=> reset role;
RESET
app=> \q
sh-4.2$
```

Here is how things look in our Docker environments. `ecs_user` is a member of `postgres` (and `rds_iam`, but that isn't relevant here), but not a member of `master`. Therefore, it cannot call `SET ROLE master`. Additionally, `master` does not have the ability to create roles and databases.

```text
$ psql 'postgres://ecs_user:mysecretpassword@localhost:5432/dev_db?sslmode=disable'
psql (13.1, server 12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

dev_db=> \dg
                                        List of roles
 Role name |                         Attributes                         |     Member of
-----------+------------------------------------------------------------+--------------------
 ecs_user  |                                                            | {postgres,rds_iam}
 master    |                                                            | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 rds_iam   | Cannot login                                               | {}

dev_db=> select current_user;
 current_user
--------------
 ecs_user
(1 row)

dev_db=> set role master;
ERROR:  permission denied to set role "master"
dev_db=> \q
```

In <https://github.com/transcom/mymove/pull/5567>, I am working on creating a low privileged user. When I tried to create the role in the experimental account, it [failed](https://app.circleci.com/pipelines/github/transcom/mymove/25298/workflows/fb2619ba-cd33-4e54-959e-e697b92c26aa/jobs/391056) because `ecs_user` does not have permissions to create a role. This is expected, but it means that my local testing gave me a false sense of how our deployed environment (RDS) would function. My local testing of that PR lead me to believe the migration would work. The next step was to call `SET ROLE master` at the top of the migration to assume the role of `master`, which is possible on RDS, in order to create the role. However, if I were to do that locally, then it would fail in multiple ways:

1. If I log into our Docker database locally as the `ecs_user` role and try to call `SET ROLE master` in order to assume the role of master, I will get a permissions error since the `ecs_user` role is not a member of the `master` role in our Docker-based PostgreSQL container.
1. Assuming that the `ecs_user` role is a part of the `master` role, so that I can call `SET ROLE master`, I will still fail to create the role because the `master` role in Docker does not mirror the permissions that exist for the `master` role in RDS, namely the ability to create roles. (Side note: I added `CREATEDB` in the PR too, since `master` in RDS has that permission as well).

After applying the migration in this PR, the Docker PostgreSQL permissions more closely align with those in RDS. This means that when I log in as `ecs_user` and then call `SET ROLE master`, I will be able to create a new role locally, which mirrors the behavior I expect to see in RDS.

```text
$ psql 'postgres://ecs_user:mysecretpassword@localhost:5432/dev_db?sslmode=disable'
psql (13.1, server 12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

dev_db=> \dg
                                           List of roles
 Role name |                         Attributes                         |         Member of
-----------+------------------------------------------------------------+---------------------------
 ecs_user  |                                                            | {postgres,rds_iam,master}
 master    | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 rds_iam   | Cannot login                                               | {}

dev_db=> select current_user;
 current_user
--------------
 ecs_user
(1 row)

dev_db=> set role master;
SET
dev_db=> create role test123;
CREATE ROLE
dev_db=> \dg
                                           List of roles
 Role name |                         Attributes                         |         Member of
-----------+------------------------------------------------------------+---------------------------
 ecs_user  |                                                            | {postgres,rds_iam,master}
 master    | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 rds_iam   | Cannot login                                               | {}
 test123   | Cannot login                                               | {}

dev_db=> reset role;
RESET
dev_db=> \q
```

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
docker kill $(docker ps --quiet --filter ancestor=postgres:12.2)
docker rm $(docker ps --all --quiet --filter ancestor=postgres:12.2)
make db_dev_reset
make db_dev_migrate
psql 'postgres://ecs_user:mysecretpassword@localhost:5432/dev_db?sslmode=disable'
```

## Code Review Verification Steps

* [x] If the change is risky, it has been tested in experimental before merging.
* [x] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [x] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [x] Have been communicated to #g-database
* [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [x] Request review from a member of a different team.

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6045) for this change

### CODE REVIEW

**Comment by carterjones** [comment]
I tested the migration on experimental. [It succeeded](https://app.circleci.com/pipelines/github/transcom/mymove/25323/workflows/27a996db-5e2c-429b-a039-fb0a959188f9/jobs/391401).

**Review by esacteksab — APPROVED** [review]
Great job!

I noticed your example had Postgres 12.2, but we're running 12.4 in all the environments. Worth another ticket to make sure that local matches production. 

Thanks for this!

**Comment by carterjones** [comment]
Good call. Here is a ticket to upgrade 12.2 to 12.4 on containers: https://dp3.atlassian.net/browse/MB-6197

**Review by lynzt — APPROVED** [review]
ran the commands both before and after and see the behavior you are talking about. 
w/ Barry's 👍 , 🚢

**Pull request merged**
