### PR TITLE
MB-1687 rework move task order and mto shipment creation

### PR DESCRIPTION
**Pull request by donaldthai**
## Description

As a TOO when I click on a move from the /too/customer-moves screen

Then I should see 
- Customer Details
- Entitlements
- Orders Information 
- Customer Requested Shipments

And next to each requested shipment I should see an accept or reject button. 

Clicking accept adds the standard service items for the shipment to the MTO 

Clicking reject does nothing for now. 

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make server_run client_run
```
Best way to test this is to find the locally generated service member user and submit their move.

Service Member App
1. Dev login
2. Login with `needs@orde.rs (milmove)`
3. Complete move app, sign and submit

Office App
1. Login
2. Navigate to `officelocal:3000/too/customer-moves`
3. Select the move that was just submitted (last one usually)
4. Check Move Task Order if it has a reference ID
5. Check Shipment if there's at least one
6. Try to Approve shipment
7. There should be base service items added now

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/tree/master/docs/backend.md#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/tree/master/docs/backend.md#querying-the-database-safely)
 have been satisfied.
* [ ] There are no aXe warnings for UI.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-1652) for this change

### CODE REVIEW

**Comment by LeDeep** [comment]
This is doing a lot of work in the model. Wondering, based on the conversation in this [PR](https://github.com/transcom/mymove/pull/3645), if it would be better to have a `move_task_order_creator` service and move the `generateReferenceID` function and the other functions into the service.

**Comment by donaldthai** [comment]
> > This is doing a lot of work in the model. Wondering, based on the conversation in this [PR](https://github.com/transcom/mymove/pull/3645), if it would be better to have a `move_task_order_creator` service and move the `generateReferenceID` function and the other functions into the service.
> 
> We definitely can do that. Since we move towards more service objects, it seems to me that the pop callbacks won't be used anymore. Except for the validation callback on the model.

Following up on this. Since we don't have a formal onboarding process, putting a service object in the `convert.go` file will cause a cycle import. We could move the convert file out of the models package but I think we should save that for later until we actually do have a formal process.

**Comment by LeDeep** [comment]
> > > This is doing a lot of work in the model. Wondering, based on the conversation in this [PR](https://github.com/transcom/mymove/pull/3645), if it would be better to have a `move_task_order_creator` service and move the `generateReferenceID` function and the other functions into the service.
> > 
> > 
> > We definitely can do that. Since we move towards more service objects, it seems to me that the pop callbacks won't be used anymore. Except for the validation callback on the model.
> 
> Following up on this. Since we don't have a formal onboarding process, putting a service object in the `convert.go` file will cause a cycle import. We could move the convert file out of the models package but I think we should save that for later until we actually do have a formal process.

Interesting. Thanks for investigating.

**Comment by donaldthai** [comment]
@LeDeep I ended up moving the convert.go file to the service directory. It didn't take that long to make the changes. :)

**Pull request merged**
