### PR TITLE
Use ntsRecordedWeight for ShipmentWeightInput

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Summary

This pull request changes the `ShipmentWeightInput` component to display and update the `ntsRecordedWeight` value, rather than the `primeActualWeight` value that we had been using previously. It also changes a few tests and stories to use the correct value.

This pull request also fixes two small bugs:

1. Several tests were emitting a prop type validation error for Duty Station addresses in the CustomerHeader component. This was caused by the complex type for origin and destination duty stations being incorrect. This issue has been resolved in this PR.

2. The `ShipmentWeightInput` component was intended to optionally be able to accept commas in user input (e.g. "4,500" or "4500" would both work), but prior to this PR, adding a comma would cause the value that would be sent to the back end to be `NaN`. This issue has been resolved in this PR.

@transcom/truss-design: There should be no visible change in the UI for this component. 

## Setup to Run Your Code

<details>
Start the Storybook locally.

```sh
make storybook
```
</details>

### Additional steps

1. In Storybook, view the "NTS Release Shipment" story (in "Office Components" -> "Forms" -> "ShipmentForm").
2. Input a value containing a comma (e.g. "4,500") for the "Shipment weight (lbs.)" field.
3. Fill out the rest of the required fields for the form, including the Delivery address, and click the "Save" button.
4. In the "Actions" panel of the Storybook console, expand the output object to show the body. Verify the following:
  * The `primeActualWeight` key does not appear in this object
  * The `ntsRecordedWeight` key does appear in this object
  * `ntsRecordedWeight` has a value equal to the numeric value of whatever you entered in the field (stripped of commas, and without surrounding quotation marks.

## Verification Steps for Author

These are to be checked by the author.

- [x] Request review from a member of a different team.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [x] There are no new console errors in the browser devtools
- [x] There are no new console errors in the test output
- [x] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### CODE REVIEW

**Review by donaldthai — APPROVED** [review]

**Review by YanZ777 — COMMENTED** [review]
This may be out of scope for this PR or because it's isolated in Storybook thing, but I'm seeing this error in Storybook for when I fuddle with the `ShipmentWeightInput`.
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

**Comment by kylehilltruss** [comment]
> This may be out of scope for this PR or because it's isolated in Storybook thing, but I'm seeing this error in Storybook for when I fuddle with the `ShipmentWeightInput`...

Oh, yep, I actually know what's causing that. Will fix.

**Review by YanZ777 — APPROVED** [review]
Changes look good to me. 
Does the schema need to be updated for this though?

**Comment by kylehilltruss** [comment]
> Changes look good to me. Does the schema need to be updated for this though?

The ghc.yaml file? That's already been updated.

**Comment by YanZ777** [comment]
> > Changes look good to me. Does the schema need to be updated for this though?
> 
> The ghc.yaml file? That's already been updated.

I was referring to the schemas inside of `getShipmentOptions`.

**Review by amanda5iu — APPROVED** [review]

**Pull request merged**
