### PR TITLE
Readonly filesystem for Containers

### PR DESCRIPTION
**Pull request by pjdufour-truss**
## Description

This PR sets the containers' root filesystem to read only, which is a pretty good security step.  Will require through testing before merging, so this might fall to be after `e2e` tests.

### CODE REVIEW

**Comment by pjdufour-truss** [comment]
Yeah, it's `in-memory`, but  a little worried about some calls to `ioutil.TempFile` deep in the code.  Will thoroughly test before merging.

**Comment by chrisgilmerproj** [comment]
Now that #1608 is merged I think we're in a place where we can test this out in the experimental env with some confidence that it will be fine.

**Comment by chrisgilmerproj** [comment]
I've merge master with this so we can start testing.

**Comment by chrisgilmerproj** [comment]
Now that Master has been merged in the migrations are using a read only root filesystem. So the next step is the app containers.

**Comment by chrisgilmerproj** [comment]
I've deployed this to experimental and tested uploading a document. I think that this is about all we can do for testing.

**Comment by chrisgilmerproj** [comment]
This PR builds on top of #2349

**Pull request merged**
