### PR TITLE
MB-6216 Create EULA Modal in Storybook

### PR DESCRIPTION
**Pull request by YanZ777**
## Description

Create the new EULA modal and add it to storybook.

## Reviewer Notes

Am I storybooking right?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make storybook
```
The new story is under Customer Components, Modals, Eula Modal Story

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6216) for this change
## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

image

### CODE REVIEW

**Review by Shkeating — APPROVED** [review]
I am seeing an accessibility failure (for the close/unstyled button on the modal lacking an aria-label, but it is a logged issue I have on my list for the week.

**Review by suzubara — APPROVED** [review]
My only comment is that I _believe_ this modal is going to be used by both customer & office apps when logging in, so it might make sense to relocate it outside of `components/Customer`. Otherwise, the code looks good!

**Comment by YanZ777** [comment]
> I am seeing an accessibility failure (for the close/unstyled button on the modal lacking an aria-label, but it is a logged issue I have on my list for the week.

Do you want me to add the aria-label? If so, what should they say?

**Comment by YanZ777** [comment]
> My only comment is that I _believe_ this modal is going to be used by both customer & office apps when logging in, so it might make sense to relocate it outside of `components/Customer`. Otherwise, the code looks good!

I think that sounds correct as well. I'll go ask in the channel though.

**Review by Shkeating — APPROVED** [review]

**Pull request merged**
