### PR TITLE
MAIN B-21376

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INT PR](https://github.com/transcom/mymove/pull/14102)
[INT PR 2](https://github.com/transcom/mymove/pull/14263)
[INT PR 3](https://github.com/transcom/mymove/pull/14276)

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21376)

> [!IMPORTANT]
> This PR contains the `main` branches of [B-21374](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21374) & [B-21375](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21375)
> You can review this PR, but do not merge until those have been merged

## Summary

When service members are creating unaccompanied baggage shipments, we need to let them know what their allowance is as they create the shipment. This is as simple as updating the helper text that appears at the top of the page letting them know what their allowance is. 

### How to test

1. In your `.envrc` you'll need to turn `FEATURE_FLAG_UNACCOMPANIED_BAGGAGE` to `true`
2. Think of a duty location and go turn that `address.is_oconus` to `true` 
3. Fire up your `client` and `server`
4. Log in as a customer
5. Create your profile and go to add some orders
6. That duty location that you set up to be OCONUS, make that your origin/destination - you really just need the one
7. Finish setting up your orders
8. Go to your database and find the `entitlements` table
9. Find the row that was just created and update the `ub_allowance` column to be whatever integer you want
10. Go and set up a shipment
11. Select the UB shipment option
12. You should now see the helper text letting you know what your allowance is at the top of the page
13. Delete the value you just put in the `ub_allowance` column in the database
14. Refresh the screen - you should now see the default helper text that's a little more vague but still relevant to the UB shipment

## Screenshots

Screenshot 2024-11-04 at 9 14 01 AM

Screenshot 2024-11-04 at 9 30 17 AM

Screenshot 2024-11-04 at 9 14 22 AM

## Summary

Wanted a ToolTip. Here's yer ToolTip.

### How to test

1. Access MM as customer (need to set up `.envrc` to allow for UB shipments
2. Fill in orders info to qualify you for a UB shipment - submit
3. Go to your home page, you should now see the UB allowance & a tooltip at the top next to the weight allowance

## Screenshots
Screenshot 2024-11-25 at 9 50 09 AM
Screenshot 2024-11-25 at 9 50 47 AM

### CODE REVIEW

**Comment by cameroncaci** [comment]
Happo approved, the error preview was previously existing
image

**Review by cameroncaci — COMMENTED** [review]
Only diff is that src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx isn't getting any love

https://github.com/transcom/mymove/pull/14102/commits/4cf781a464aa71ec87b7204255ad69ec4be4fd86
https://github.com/transcom/mymove/pull/14102/commits/ae8a3f0bc8cd6f9a9629d485137f982c807140f4

**Comment by cameroncaci** [comment]
> Only diff is that src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx isn't getting any love
> 
> [4cf781a](https://github.com/transcom/mymove/commit/4cf781a464aa71ec87b7204255ad69ec4be4fd86) [ae8a3f0](https://github.com/transcom/mymove/commit/ae8a3f0bc8cd6f9a9629d485137f982c807140f4)

Discussed with @danieljordan-caci. These changes are int specific and not functional to the release

**Comment by cameroncaci** [comment]
Flaky is in overdrive this morning

**Review by TevinAdams — APPROVED** [review]

**Pull request merged**
