### PR TITLE
add secure migration for gsa users

### PR DESCRIPTION
**Pull request by mikena-truss**
## Description

Adds GSA users to the `office_user` table for invoice auditing

## Reviewer Notes
- Double check I put in the right info from the ticket please
- These users are only in prod. Pretty sure that's correct in this case.
- I attached them to Scott AFB similar to Truss users. This seems not ideal, but creating a new office for them would would be difficult because of all the associations. Eventually, we should figure out a read only role for this.
- One user didn't have a phone number. I entered an empty string.
- One user had an extension on their phone. I just added it to the phone number string, but the alternative is adding a new column. This would have other implications though. I don't see us denoting phone numbers like this anywhere else though.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
# review
aws s3 cp s3://transcom-ppp-app-prod-us-west-2/secure-migrations/20190320202054_add-gsa-users.sql .

# test
./bin/run-prod-migrations
```

## Code Review Verification Steps

* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](./docs/database.md#zero-downtime-migrations))
  * [ ] Have been communicated to #dp3-engineering
  * [ ] Secure migrations have been tested using `bin/run-prod-migrations`
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/164469685) for this change

### CODE REVIEW

**Comment by mikena-truss** [comment]
@LeDeep good catch! Updated.

**Comment by LeDeep** [comment]
Other than one incorrect phone number, looks good. Agree that handling of office is not ideal. What's the best place to document that we're assigning auditors to same office as Truss users?

**Comment by mikena-truss** [comment]
@LeDeep I'm going to create a follow up ticket for our backlog

**Comment by LeDeep** [comment]
:shipit:

**Pull request merged**
