### PR TITLE
[MB-6302] Removing use of Vault.go

### PR DESCRIPTION
**Pull request by esacteksab**
## Description

Like #5825 and #5734 this removes the use of vault.go

### CODE REVIEW

**Review by kilbergr — APPROVED** [review]
Great! Have you tested still sends payment reminder fine?

**Comment by esacteksab** [comment]
> Great! Have you tested still sends payment reminder fine?

I can't. No AWS on my temp computer. :( But given we've done this exact same thing 3-4 times now, I have no reason to believe that it won't work. Want to pair?

**Comment by kilbergr** [comment]
We've tested!

**Comment by esacteksab** [comment]
Rebecca and I paired on this and confirmed it works.

**Pull request merged**
