### PR TITLE
B 21326 tget data cleanup int

### PR DESCRIPTION
**Pull request by cameroncaci**
> [!WARNING]
> This ticket should not be merged to main until https://github.com/transcom/trdm-lambda/pull/28/ has been released to production

## Summary

Fixes existing trailing spaces and empty values

### How to test

1. Insert bad dummy data

```sql
INSERT INTO transportation_accounting_codes (
    id, tac, tac_sys_id, loa_sys_id, tac_fy_txt, tac_fnct_poc_nm, created_at, updated_at 
)
VALUES
    ('E08FF3DB-F17D-4076-A9E6-AAB6D3F4029C', 'ABCD', 'dummy', '   dummy', 'dummy ', '  ',now(), now());

INSERT INTO lines_of_accounting (
    id, loa_sys_id, loa_dsc_tx, loa_fnct_prs_nm, loa_agnc_acntng_cd, created_at, updated_at
)
VALUES
    ('E08FF3DB-F17D-4076-A9E6-AAB6D3F4029D', 'dummy', '   dummy', 'dummy ', ' ', now(), now());
```

2. Preview trailing spaces in dummy data
3. Run `make db_dev_migrate`
4. Verify spaces are gone and if `' '` then null

### CODE REVIEW

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Couple SIT tests failing

**Comment by danieljordan-caci** [comment]
> Couple SIT tests failing

Those should be fixed once he fixes his CONFLICTS CAMERON

**Review by TevinAdams — APPROVED** [review]

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Not seeing this work for me locally for the transportation_accounting_codes table specifically. It looks good for the lines_of_accounting table

Running make db_dev_migrate doesn't actually do anything since it has already run when I switch to your branch, so:
Steps I'm taking:
1. Inserting the dummy data into the LOA table
2. Running your migration directly in dbeaver as a script
3. Updates the LOA dummy data to not have extra spaces
image
After:
image

Not seeing the same TACs
1. Inserting the dummy data into the TAC table
2. Running your migration directly in dbeaver as a script
3. Not updating the TAC dummy data to not have extra spaces
image
After running migration as script and refreshing dbeaver, no change
image

**Comment by cameroncaci** [comment]
> Not seeing this work for me locally for the transportation_accounting_codes table specifically. It looks good for the lines_of_accounting table
> 
> Running make db_dev_migrate doesn't actually do anything since it has already run when I switch to your branch, so: Steps I'm taking:
> 
> 1. Inserting the dummy data into the LOA table
> 2. Running your migration directly in dbeaver as a script
> 3. Updates the LOA dummy data to not have extra spaces
>    image
>    After:
>    image
> 
> Not seeing the same TACs
> 
> 1. Inserting the dummy data into the TAC table
> 2. Running your migration directly in dbeaver as a script
> 3. Not updating the TAC dummy data to not have extra spaces
>    image
>    After running migration as script and refreshing dbeaver, no change
>    image

@traskowskycaci 
This could be due to an issue of when copy and pasting the single quotation `'` might be a different ASCII(?) format or dbeaver not visually representing right. I tested again and it worked as expected, could you retry and let me know if it persists?

**Comment by traskowskycaci** [comment]
> @traskowskycaci This could be due to an issue of when copy and pasting the single quotation `'` might be a different ASCII(?) format or dbeaver not visually representing right. I tested again and it worked as expected, could you retry and let me know if it persists?

Yep, I'll retest!

**Review by traskowskycaci — APPROVED** [review]
Retested and now seeing TAC table get cleaned up as expected!

**Review by danieljordan-caci — APPROVED** [review]
LGTM! Ran through it locally and all is working as expected.

**Review by begrohmann — APPROVED** [review]

**Pull request merged**
