### PR TITLE
MAIN B-20809

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INT PR](https://github.com/transcom/mymove/pull/14146)
[INT PR 2](https://github.com/transcom/mymove/pull/14194)

### NOTE
This PR also contains some UI compiling fixes that were displaying using USDWS parameters. Adjusting those to not use fixed the compiling errors:
- `@include u-radius('05');`
- `@include u-minw(200px);`

## Summary

With the work [done in B-20808](https://github.com/transcom/mymove/pull/13994) where a GSR user can add appeals to violations, we also want to apply that functionality to serious incidents.

Since serious incidents occur at the evaluation report level and not the report violation level, we had to create a separate endpoint with the goal of being able to differentiate between the two when displaying move history (work not yet complete).

A lot of this work piggybacks off of the previous BL item, but I did do some refactoring in order to use the beauty of reusable components in React by adding in a couple new props into the `AppealModal` and dynamically rendering what the appeal is being added for into the modal (serious incident vs violation).

This PR does the following:
- adds new endpoint where an office user can add an appeal to a serious incident
- adds service object under `evaluationreport` package that handles adding an appeal to a serious incident
- refactors `ViolationAppealModal` to be `AppealModal` with added props for reusability
- refactors variables in the `EvaluationReportView` component for reusability/reduction of similar code
- adds UI tests
- adds server tests
- updates playwright test to cover GSR serious incident actions

### How to test

1. In your `.envrc`, turn the GSR flag to `true`
2. Log in as either a GSR user or a multi office user
3. You can create an evaluation report as a GSR user, so go ahead and create one and ensure you mark that there is a serious incident involved
4. You should now see the `Leave Appeal Decision` button when viewing the report
5. Leave an appeal decision on the serious incident (modal will pop up)
6. Check to make sure it populates in the database and displays on the UI
7. Ensure you can't leave another appeal on the serious incident (similar to violations)
8. Log in as another type of user (QAE for example)
9. View the previously created evaluation report
10. Ensure you can see the appeals
11. Create a new evaluation report as the other role with a serious incident
12. View the report, make sure you can't see the `Leave Appeal Decision` button
13. Log in as the GSR, pull up the report and confirm you CAN see the `Leave Appeal Decision` button

## Screenshots
Screenshot 2024-11-08 at 10 52 33 AM
Screenshot 2024-11-08 at 10 52 59 AM
Screenshot 2024-11-08 at 10 53 11 AM
Screenshot 2024-11-08 at 11 00 51 AM
Screenshot 2024-11-08 at 11 01 22 AM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
This is super weird. I have a failing test in this branch that was not failing in INT. The fix was simple, but wondering why the test was passing in INT?

**Review by traskowskycaci — COMMENTED** [review]
The failing test only here is odd - can you add that change you had to make here, to int as well? `models.GsrAppeal{} `isntead of `nil` for `mockService.On("AddAppealToSeriousIncident"` in `pkg/handlers/ghcapi/evaluation_report_test.go
`
Only thing I can think of as to why they'd be different is maybe something out of sync with the mock generation?

**Comment by danieljordan-caci** [comment]
> The failing test only here is odd - can you add that change you had to make here, to int as well? `models.GsrAppeal{} `isntead of `nil` for `mockService.On("AddAppealToSeriousIncident"` in `pkg/handlers/ghcapi/evaluation_report_test.go ` Only thing I can think of as to why they'd be different is maybe something out of sync with the mock generation?

I tried running `make mocks_generate` again and nothing changed - very weird. Yeah I'll get an INT PR up.

**Comment by danieljordan-caci** [comment]
Need a Happo check plz

**Comment by traskowskycaci** [comment]
> Need a Happo check plz

Happo checked

**Comment by danieljordan-caci** [comment]
Flaky tests failing

**Review by traskowskycaci — APPROVED** [review]

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
