### PR TITLE
Update prereqs script to support nix

### PR DESCRIPTION
**Pull request by gidjin**
## Description

Some of us have been using nix to install MilMove development dependencies. This PR updates the various prerequisite check scripts to support a nix install. This PR also updates the versions for `aws-vault` and `chamber` as the nix config was out of date for what brew installed.

## Reviewer Notes

Will be looking for approval from a fellow `nix` user and someone who is still using `brew`, `asdf`, and `nodenv`.

## Setup

Run the prereqs check. You may have to fix somethings if you haven't run these in a while. Note `nix` users will need to run `nix/update.sh` but the script should warn you about it.

```sh
 ❯ rm -f .prereqs.stamp
 ❯ make prereqs
scripts/prereqs
nix dependencies installed
aws installed.
bash installed.
chamber installed.
docker installed.
jq installed.
go installed.
yarn installed.
pre-commit installed.
shellcheck installed.
psql installed.
node installed.
pkcs11-tool installed.
pkcs15-tool installed.
circleci installed.
direnv installed.
entr installed.
aws-vault installed.
watchman installed.
OK: all prereqs found

aws-cli/2.1.7 Python/3.8.6 Darwin/20.6.0 source/x86_64 prompt/off installed
aws-vault /nix/var/nix/profiles/mymove/bin/aws-vault v6.3.1 installed
Bash 5.1.4(1)-release installed
/nix/var/nix/profiles/mymove/bin/chamber
chamber v2.10.2 installed
Golang go version go1.16.6 darwin/amd64 installed
Node v14.17.1 installed
opensc 0.21.0 installed
touch .prereqs.stamp
```

## Code Review Verification Steps

* [ x ] Request review from a member of a different team.

### CODE REVIEW

**Review by reggieriser — APPROVED** [review]
I use `brew`/`asdf`/`nodeenv` and `prereqs` still works fine for me.  Approving the PR from that perspective but (as you note) we'll need a `nix` reviewer.

One aside -- I've had to pin `awscli` at version 2.1.x because that's what we require in `prereqs`, but version 2.2.x has been out for several months (at least with `brew`).  Not sure if there's anything holding us back from upgrading or not.

**Comment by gidjin** [comment]
> I use `brew`/`asdf`/`nodeenv` and `prereqs` still works fine for me. Approving the PR from that perspective but (as you note) we'll need a `nix` reviewer.
> 
> One aside -- I've had to pin `awscli` at version 2.1.x because that's what we require in `prereqs`, but version 2.2.x has been out for several months (at least with `brew`). Not sure if there's anything holding us back from upgrading or not.

Note for future reference, we decided not to upgrade `chamber` and `awscli` in this PR as they would require changes to the cirlceci-docker images as well. Those will come in a separate PR

**Review by reggieriser — APPROVED** [review]
Updates look good (again from `brew` perspective).  FWIW, I had trouble downgrading chamber to 2.9.x with brew (current brew version was 2.10.x), but the prereqs worked and warned me I was out-of-date.  Apparently `brew switch` is gone and I can't do a direct install of a specific formula commit anymore either.  Going to just stick with the newer `2.10.x` I've been on for a few months until we catch up.

**Review by ahobson — APPROVED** [review]
🚀

**Pull request merged**
