### PR TITLE
Add scripts for DL and TO SQL migrations, and the migrations.

### PR DESCRIPTION
**Pull request by scottmries**
## Summary

This PR adds Python scripts to generate database migrations from the spreadsheets provided, one each for Duty Locations and Transportation Offices (each linked on the Jira ticket), and the resultant migrations themselves, which are added to the migrations_manifest.

Each takes one argument, the name of the input file.

`python ./cmd/load-spreadsheet-data/load-duty-locations.py "path/to/Duty Locations with Names, final"`

`python ./cmd/load-spreadsheet-data/load-transportation-offices.py "path/to/MM Transportation Offices and PPPO Contact Info.xlsx"`

The resultant migrations are included in this PR, so it's not necessary to run the Python scripts before migrating (with `make db_dev_migrate`, e.g.).

### Setup to Run the Code

- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)

#### Front-end

Expect the list of Duty Locations to match those provided in the spreadsheet, e.g. when creating a new move on the Current Duty Location page.

Expect the list of Transportation Offices to be updated from the spreadsheet, e.g. when selecting a TO for an office user in the admin. Note that "Fort Cavazos" is a new name, so its presence should indicate the update.

#### Database

Expect spot-checked Duty Location rows to match the sheet one-to-one, e.g.:
`SELECT dl.id, dl.name, t.gbloc, dl.affiliation, a.street_address_1, a.city, a.state, a.postal_code from duty_locations as dl 
left join transportation_offices as t on dl.transportation_office_id = t.id
left join addresses as a on dl.address_id = a.id
where dl.name = 'Fort Drum, NY 13602'`

Expect the returned count to match the number of rows in the Duty Location spreadsheet (40590):
`SELECT count(*) FROM duty_locations`

Expect spot-checked Transportation Offices to match the sheet. This query includes Fort Cavazos, whose name changed, and San Pedro, which is an addition in the sheet:
`SELECT t.id, t.name, t.gbloc, a.street_address_1, a.street_address_2, a.city, a.state, a.postal_code 
FROM transportation_offices as t
JOIN addresses AS a 
ON t.address_id = a.id
WHERE t.name IN ('PPPO Base San Pedro - USCG', 'CPPSO Fort Cavazos (HBAT) - USA');`

### Front-end
Screenshot 2023-08-11 at 10 27 10 AM
Screenshot 2023-08-11 at 10 27 56 AM

### Database
Screenshot 2023-08-11 at 10 28 21 AM
Screenshot 2023-08-11 at 10 28 55 AM
Screenshot 2023-08-11 at 10 29 22 AM

### CODE REVIEW

**Comment by duncan-truss** [comment]
I saw you decided to remove all of the duty_location_names records which helped with alternative spellings for the fuzzy search.  What conclusion did you all come to there?

**Comment by scottmries** [comment]
@duncan-truss We were told that the data we were given should completely replace the existing list of DLs, so given the lack of reference back to the original records or new `duty_location_name` data, there was no way to preserve or update the `duty_location_name` data (programmatically, given ~40k new records).

That said, we will be doing another round of updates, since phone numbers in the original list need to be manually reformatted, and I will mention this again as something to be included for a future update.

**Comment by ahobson** [comment]
As an FYI: during load testing, the duty location search was the SQL query that hit the database the hardest. In particular, joining to the address table to get the zip code was particularly slow. I believe we are going to need to change/refactor how we do duty location searches to support a large number of users.

My understanding was the in some prior history, we added the zip code to the duty location name so that we wouldn't have to do the join.

I don't know that we need to solve this problem right now, but I just wanted to point out that we will have to revisit these decisions again, so whatever we decide now will be a temporary solution.

**Comment by duncan-truss** [comment]
> @duncan-truss We updated the new duty locations to include entries in the `duty_location_names` table, one of which you can see here. So, `duty_location_names` should be in good shape now.
> 
> Screenshot 2023-08-22 at 4 50 48 PM

@scottmries Awesome, thanks for running that down! Go A-team.

**Comment by kctruss** [comment]
@scottmries Have you been able to test this in EXP or Load Testing? I'm getting errors locally on the migrations, and wondering if that's more a me issue or something that will surface when trying to deploy these changes.

**Comment by kctruss** [comment]
> @scottmries Have you been able to test this in EXP or Load Testing? I'm getting errors locally on the migrations, and wondering if that's more a me issue or something that will surface when trying to deploy these changes.

For the record, it was at least partially me 😅

**Comment by scottmries** [comment]
> > @scottmries Have you been able to test this in EXP or Load Testing? I'm getting errors locally on the migrations, and wondering if that's more a me issue or something that will surface when trying to deploy these changes.
> 
> For the record, it was at least partially me 😅

😂 No worries, I'm deploying to be sure.

**Review by kctruss — APPROVED** [review]
This looks good from my end! My local DB was a bit out of date but once I got that sorted it built no problem, hopefully that's an isolated experience. Pending any findings from the deploy to loadtest I'd say you're good to go :shipit:

**Review by LeDeep — APPROVED** [review]
Only reviewed the DB changes.

**Comment by felipe-lee** [comment]
> This looks good from my end! My local DB was a bit out of date but once I got that sorted it built no problem, hopefully that's an isolated experience. Pending any findings from the deploy to loadtest I'd say you're good to go :shipit:

Hmm I also got a failure on my end:

<details>
<summary>Error output</summary>

```bash
brew services stop postgresql 2> /dev/null || true
Starting the milmove-db-dev docker database container...
# If running do nothing, if not running try to start, if can't start then run
docker start milmove-db-dev || \
		docker run -d --name milmove-db-dev \
			-e POSTGRES_PASSWORD=mysecretpassword \
			-p 5432:5432\
			postgres:12.11
milmove-db-dev
Create the dev_db database...
DB_NAME=postgres scripts/wait-for-db && DB_NAME=postgres psql-wrapper "CREATE DATABASE dev_db;" || true
> psql postgres://postgres:mysecretpassword@localhost:5432/postgres -c 'select 1;' > /dev/null 2>&1
Checking for database connectivity..success!
ERROR:  database "dev_db" already exists
go build -gcflags="all=-N -l -trimpath=/Users/felipe/dev/milmove/mymove/.gopath" -asmflags=-trimpath=/Users/felipe/dev/milmove/mymove/.gopath -ldflags " -X main.gitBranch=sr-MB-16542-duty-station-updates-discovery -X main.gitCommit=e31491b57b0b8cd3834a353e6fd2f435ebfc0e63" -o bin/milmove ./cmd/milmove
Migrating the dev_db database...
DB_DEBUG=0 bin/milmove migrate -p "file://migrations/app/secure;file://migrations/app/schema" -m "migrations/app/migrations_manifest.txt"
2023-08-23T19:59:10.668Z	INFO	milmove/migrate.go:163	migrator starting up	git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.668Z	INFO	milmove/migrate.go:53	checking migration config	git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.668Z	INFO	milmove/migrate.go:177	using migration paths ["file://migrations/app/secure" "file://migrations/app/schema"]	    {"git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.668Z	INFO	cli/dbconn.go:317	Connecting to the database	git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63", "url": "postgres://postgres:*****@localhost:5432/dev_db?sslmode=disable", "db-ssl-root-cert": ""}
2023-08-23T19:59:10.668Z	INFO	cli/dbconn.go:454	Starting database ping....	git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.686Z	INFO	cli/dbconn.go:461	...DB ping successful!	      {"git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.686Z	INFO	milmove/migrate.go:214	tracking migrations using table "schema_migration"	git_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
2023-08-23T19:59:10.686Z	INFO	milmove/migrate.go:217	using migration manifest "file://migrations/app/migrations_manifest.txt"	_branch": "sr-MB-16542-duty-station-updates-discovery", "git_commit": "e31491b57b0b8cd3834a353e6fd2f435ebfc0e63"}
[POP] 2023/08/23 19:59:12 info - > update_transportation_offices
error executing file://migrations/app/schema/20230810180036_update_duty_locations.up.sql: error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
[POP] 2023/08/23 19:59:27 info - 16.9075 seconds
panic: error running migrations: error executing file://migrations/app/schema/20230810180036_update_duty_locations.up.sql: error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"

goroutine 1 [running]:
main.main()
	/Users/felipe/dev/milmove/mymove/cmd/milmove/main.go:132 +0x13d9
make: *** [db_dev_migrate_standalone] Error 2
```

</details>

I'm going to test switching back to `main`, re-creating the dev db, and then trying the branch migrations again to see if I have a similar issue to what you had @kctruss

**Comment by kctruss** [comment]
> 



> > This looks good from my end! My local DB was a bit out of date but once I got that sorted it built no problem, hopefully that's an isolated experience. Pending any findings from the deploy to loadtest I'd say you're good to go :shipit:
> 
> Hmm I also got a failure on my end:
> 
> Error output
> I'm going to test switching back to `main`, re-creating the dev db, and then trying the branch migrations again to see if I have a similar issue to what you had @kctruss
> 
> Edit: it failed again with the same error. I'll try looking into it more after reviewing the python code.
> 
> Edit 2: I forgot to say what commands I ran earlier. I was using `make db_dev_run db_dev_migrate`



> > This looks good from my end! My local DB was a bit out of date but once I got that sorted it built no problem, hopefully that's an isolated experience. Pending any findings from the deploy to loadtest I'd say you're good to go :shipit:
> 
> Hmm I also got a failure on my end:
> 
> Error output
> I'm going to test switching back to `main`, re-creating the dev db, and then trying the branch migrations again to see if I have a similar issue to what you had @kctruss
> 
> Edit: it failed again with the same error. I'll try looking into it more after reviewing the python code.
> 
> Edit 2: I forgot to say what commands I ran earlier. I was using `make db_dev_run db_dev_migrate`

Ah yeah, looks like loadtest deploy is getting the same error as well. I will caveat that I had to do a db reset locally to first get this to run, then I rebuilt main locally to re-test the migrations from this branch, which got this to work.

**Comment by scottmries** [comment]
Yeah @felipe-lee, I second @kctruss. I run `make db_dev_reset db_dev_migrate` locally without error, though: why would this fail on loadtest?

**Comment by kctruss** [comment]
> ```shell
> error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> ```

Resetting the DB cleans out the tables. When running the migrations without a hard db reset, you get an FK violation error:
```
error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
[POP] 2023/08/23 19:59:27 info - 16.9075 seconds

**Comment by scottmries** [comment]
> > ```shell
> > error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> > [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> > ```
> 
> Resetting the DB cleans out the tables. When running the migrations without a hard db reset, you get an FK violation error:
> 
> ```
> error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> ```

Is it safe to drop and replace that constraint then?

**Comment by felipe-lee** [comment]
> > > ```shell
> > > error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> > > [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> > > ```
> > 
> > 
> > Resetting the DB cleans out the tables. When running the migrations without a hard db reset, you get an FK violation error:
> > ```
> > error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> > [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> > ```
> 
> Is it safe to drop and replace that constraint then?

@scottmries @kctruss 

I'm not sure if it's safe to drop the constraint or not. @bellex3, @melissathai, and I were just looking into this more and it looks like there might be duty locations that point to the same address as the transportation office address.

We ran this sql command:

```sql
SELECT
    dl.id,
    dl.name,
    dl.address_id,
    tof.id,
    tof.address_id
FROM duty_locations as dl
INNER JOIN transportation_offices as tof ON tof.id = dl.transportation_office_id
WHERE dl.address_id = tof.address_id;
```
Which brought up these locally:

image

Given their names, these seem to be randomly generated data. The thing I'm not sure about though is if it valid for a duty location and a transportation office to share an address. Do you know? This is part of my concern with dropping the constraint. Like, if they should be sharing and we drop the constraint, then transportation offices could end up without a valid address ID (in that the ID they do have will point to a record that doesn't exist, and also they won't have the ID for the valid address).

**Comment by kctruss** [comment]
> > > ```shell
> > > error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> > > [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> > > ```
> > 
> > 
> > Resetting the DB cleans out the tables. When running the migrations without a hard db reset, you get an FK violation error:
> > ```
> > error executing statement: "DELETE from addresses where id in (select address_id from duty_locations);": pq: update or delete on table "addresses" violates foreign key constraint "transportation_offices_address_id_fkey" on table "transportation_offices"
> > [POP] 2023/08/23 19:59:27 info - 16.9075 seconds
> > ```
> 
> Is it safe to drop and replace that constraint then?

I would think so, I think you're already doing that in another spot so it makes sense to me.

**Comment by kctruss** [comment]
> The thing I'm not sure about though is if it valid for a duty location and a transportation office to share an address. Do you know? This is part of my concern with dropping the constraint. Like, if they should be sharing and we drop the constraint, then transportation offices could end up without a valid address ID (in that the ID they do have will point to a record that doesn't exist, and also they won't have the ID for the valid address).

Not all duty locations are a transportation office, but all transportation offices are duty locations

**Comment by scottmries** [comment]
@felipe-lee It's curious that there are only five TOs that share address IDs with DLs, and if we can confirm that they're only tests, maybe it's safe to override?
In any case, I tried to drop and replace the constraint but somehow I'm still getting that error on loadtest.

**Pull request closed without merging**
