### PR TITLE
Rek view shipments

### PR DESCRIPTION
**Pull request by kilbergr**
This PR is to address [Make a simple front end interface to show Available Shipments & Awarded Shipments](https://www.pivotaltracker.com/story/show/154741512). 
It queries Available Shipments JSON obj and Awarded Shipments JSON objs.
Mostly a skeleton to be filled in once we've done the migrations.
Includes skeleton tests and buttons on the nav bar.

### CODE REVIEW

**Comment by tinyels** [comment]
Is there a reason this isn't using redux?

**Comment by kilbergr** [comment]
I was under the impression it shouldn't be redux yet--like I thought we were doing it how you had originally done the SubmittedFeedback etc. 
I'll change now! My b!

**Comment by tinyels** [comment]
I think now that we have the redux infrastructure in place we should use it on first pass. And point stories accordingly. But this is my opinion. We can discuss.

**Comment by jim** [comment]
Code looks good to me.

One question I have is if we should be treating available and awarded shipments so differently at a data model/endpoint level. It seems they are the same type of object (at least at this point) with the difference being the presence of a single additional field. I can see us having a single API endpoint and just filtering in the client as needed, but I am coming into this after this work was discussed and therefore missed out on the planning for this feature.

**Comment by kilbergr** [comment]
@jim 
@akostibas asked that we treat these as though they were two separate endpoints for now. He thought about filtering, but decided it should come later. I'm therefore merging this and we can change as we move forward.

**Pull request merged**
