### PR TITLE
MB-10519 Office App Only Components having min-widths in Storybook

### PR DESCRIPTION
**Pull request by Shkeating**
## Summary

This branch does several things:
- it creates an `.officeApp` class that has rules in our `storybook.scss` file. and applies a rule that stops office components from getting smaller than `800px` wide, but in some cases I added a custom width of `1000px` or `1240px`.
- it adjusts the `.officeLayout.scss` file to eliminate unneeded css
- it adds a wrapping div to office-only components to get rid of their broken narrow screen state.

This branch should not affect app-level code, with the exception of a minor bug what could be fixed very easily. For example, I ran into several instances of buttons in office app components (Billable Weights Card and Payment Requests Card) setting their width to 100% at reduced screen size when its not a desired behavior in some specific circumstances.

The Milmove Office Application is desktop only, and as a result none of the MMDS components intended only for use in the office were designed or built for narrow screen widths. These components will never display at widths below 1240px based on [MB 9274](https://dp3.atlassian.net/browse/MB-9674). This branch will ensure we don't get broken mobile images in Happo for states that don't exist in the app. This branch WILL make some serious changes to the Happo images, because the broken mobile images should be cleaner looking with this branch's work.

**This PR is in a DRAFT STATE!!!** i have set up the initial CSS and tested it out on one component to make sure it works. I will be going through all the Office components and adding the new `.officeApp` class that I've added styling for in the `storybook.scss` file in the storybook config.

## Setup to Run Your Code
<details>
Start the Storybook locally.

```sh
yarn storybook
```
</details>

### Frontend

- [x] User facing changes have been reviewed by design.
- [x] There are no aXe warnings for UI.
- [x] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [x] There are no new console errors in the browser devtools
- [x] There are no new console errors in the test output

## Example Screenshots

image
image
image

### CODE REVIEW

**Review by YanZ777 — APPROVED** [review]

**Review by amanda5iu — COMMENTED** [review]
Sorry if this isn't in scope for this story, but I noticed some weird behavior:

Shipment details: page title and delete link are wrapping
shipment details

Same thing's happening in modals:
modal reject

Modal content slipping out of view:
modal

Table's getting cut off
table

**Comment by Shkeating** [comment]
@amanda5iu I went through and fixed the things you screenshotted. all good catches!! :) The last one seems to just be an issue with how Happo takes screenshots and is not actually cut off in storybook.

**Review by amanda5iu — COMMENTED** [review]
Ok, per our convo yesterday I'm going to de-prioritize Safari and focus on Chrome in this review, since we have yet to encounter office users with Mac OS. Just a few things left:

Service item table - the buttons aren't right-aligned
Screen Shot 2021-12-16 at 9 29 20 AM

Next and Cancel buttons at the bottom are misaligned
Screen Shot 2021-12-16 at 9 30 39 AM

Extra left padding on the contained checkbox. I can't remember if this was happening in the app as well as Storybook when we looked at it yesterday.
Screen Shot 2021-12-16 at 9 31 26 AM

**Comment by brooksr4** [comment]
I don't see the fixes to these things Amanda called out in Happo

> Ok, per our convo yesterday I'm going to de-prioritize Safari and focus on Chrome in this review, since we have yet to encounter office users with Mac OS. Just a few things left:
> 
> Service item table - the buttons aren't right-aligned Screen Shot 2021-12-16 at 9 29 20 AM
> 
> Next and Cancel buttons at the bottom are misaligned Screen Shot 2021-12-16 at 9 30 39 AM
> 
> Extra left padding on the contained checkbox. I can't remember if this was happening in the app as well as Storybook when we looked at it yesterday. Screen Shot 2021-12-16 at 9 31 26 AM

**Review by juliemoon — APPROVED** [review]
LGTM!

**Review by juliemoon — COMMENTED** [review]
LGTM

**Review by brooksr4 — APPROVED** [review]

**Pull request merged**
