### PR TITLE
[MB-13881] Use swagger 0.30.2 for code generation

### PR DESCRIPTION
**Pull request by reggieriser**
## Summary

This PR updates our Docker references to use an image that has go-swagger 0.30.2 (the latest version).  In turn, I have run `make server_generate` using it; this PR includes any changes to the generated files.  Part of the reason to get on the latest version is to make it easier to install/brew the `swagger` utility locally to avoid long execution times using Docker on Apple Silicon machines.

Note that there are two commits -- the first updates all the hashes and references to go-swagger 0.30.2.  The second contains all the generated files that changed.

Although the majority of generated files changed, almost all of the changes fall into the following categories:
- Whitespace or comment changes
- Passing along the proper context rather than calling `context.Background()`
- Using `os.ReadFile` instead of the deprecated `ioutil.ReadFile`
- Adding some helper methods for responses

I don't believe that any of these will change the way our code currently behaves.  All tests still pass.

See the [go-swagger 0.30.0 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.30.0) and [go-swagger 0.30.2 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.30.2) for more details.

Here is the corresponding PR in the circleci-docker repository: https://github.com/transcom/circleci-docker/pull/304.  ~~I am currently referencing hashes from that branch, but will update this PR with the merged hash after this PR has gone through some initial vetting.~~  This PR has been merged and the main hashes have been incorporated.

## Setup to Run Your Code

Make sure that all tests still pass.  Exercise the app a bit and make sure nothing strange seems to be happening.

Run a `make server_generate` and see that everything still works and that there are no local changes after regenerating.  Get a local version of go-swagger 0.30.2 and see if the local version is used instead of running the one in the Docker image.  If you use homebrew, you can `brew install go-swagger` to get a local version, but note that homebrew makes it hard to go back to a previous version.  So you instead may want to just install a [go-swagger 0.30.2 binary](https://goswagger.io/install.html#static-binary) and change your path temporarily to point to it for testing.  If you don't have a version of 0.30.2 in your path, it should fall back to using the Docker container's go-swagger 0.30.2 for code generation (albeit very slowly on Apple Silicon).

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

### CODE REVIEW

**Review by ahobson — APPROVED** [review]
I checked out the branch locally and confirmed that the nix config installs the right swagger version.

**Comment by reggieriser** [comment]
BTW, @ahobson reminded me that this release [includes fixes](https://github.com/go-swagger/go-swagger/issues/2759) that appear to be required for us to move MilMove to Go 1.19.  So another reason to go ahead and upgrade if we can.

**Review by duncan-truss — APPROVED** [review]

**Comment by reggieriser** [comment]
@Mergifyio refresh

**Comment by rogeruiz** [comment]
FYI @reggieriser Pamplemoose is in dependencies this month and we have it on our board to work on the Go 1.19 upgrade. Please coordinate with @mmayo-truss on this as he has started this work already. Thanks.

**Comment by reggieriser** [comment]
> Please coordinate with @mmayo-truss on this as he has started this work already. Thanks.

I noticed that earlier today and added @mmayo-truss to the PR.  We've already been in communication.

**Pull request merged**
