### PR TITLE
MB-14310: Update go version to 1.19.2

### PR DESCRIPTION
**Pull request by kylehilltruss**
## Summary

This pull request updates the go version from `1.19.1` to `1.19.2`. The updated version [applies security fixes](https://go.dev/doc/devel/release#go1.19.minor), and resolves some minor issues that are presently being experienced by project developers.

### CODE REVIEW

**Review by duncan-truss — APPROVED** [review]
Tested with `asdf` and didn't see any issues, could get a nix user to review too.

**Review by felipe-lee — COMMENTED** [review]
**issue**: `nix` is still on 1.19.1:

image

You'll need to update the `nix/default.nix` file, which will look something like this in this PR https://github.com/transcom/mymove/pull/9205/files#diff-4e3bd328e4c998f53b19da7639df45b2db63601be4b4343534880adfbeaa5840

You can find the new hash here: https://ahobson.github.io/nix-package-search/#/search

I just looked and it looks like it'll be this:

```nix
    (import (builtins.fetchGit {
      # Descriptive name to make the store path easier to identify
      name = "go-1.19.2";
      url = "https://github.com/NixOS/nixpkgs/";
      ref = "refs/heads/nixpkgs-unstable";
      rev = "4f8287f3d597c73b0d706cfad028c2d51821f64d";
    }) {}).go_1_19
```

I tried that hash with `nix` locally and it seems to work (the output below was after I updated the `nix/default.nix` file and then ran the `./nix/update.sh` command):

image

**Review by reggieriser — APPROVED** [review]
Looked good and worked for me as an `asdf` user.

**Review by felipe-lee — APPROVED** [review]
LGTM now, `nix` is on the right version:

image

**Pull request merged**
