### PR TITLE
B-18520: Update Navigation Links

### PR DESCRIPTION
**Pull request by TevinAdams**
## Summary

Went through the milmove workflows and updated the page navigations to route to customerRoutes.MOVE_HOME_PAGE (The Move) where needed. Let me know if I missed any workflows or navigations.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the milmove app as a service member
2. Go through the workflow of creating a user then a move. Go through the workflow of creating shipments.
3. Go through all workflows to catch where anywhere in the workflows navigations it should route back to the move.
4. Go through the edit workflows and backing out of the edit workflows.
5. Go through the workflows saving changes.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by cameroncaci — CHANGES_REQUESTED** [review]
After filling out the profile portion, I get redirected back to the dashboard rather than the next step in the move.

This is where I should be redirected after filling out the profile portion:

image

And this is where I actually get redirected:

image

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
When amending orders, the user should be routed back to the move home page and not the dashboard.

Screenshot 2024-02-06 at 9 37 20 AM
Clicking `Save` or `Cancel` should route them to the move page. Currently they're routed to the move dashboard.

When reviewing the request, they'll need to be routed back to the move home page.
Screenshot 2024-02-06 at 9 39 33 AM
`Return home` should route them back to the move home page, not the dashboard.

When uploading & confirming PPM documents - same thing.
Screenshot 2024-02-06 at 9 40 37 AM
Screenshot 2024-02-06 at 9 41 22 AM
`Return to Homepage` and `Submit PPM Documentation` should route them back to the move home page, not the dashboard.

Need to return the user to the move home page and not the dashboard when uploading orders.
Screenshot 2024-02-06 at 9 44 49 AM
The `Back` button should route them back to the move home page, not the dashboard.

After uploading orders, user should be routed to the move home page, not the dashboard.
Screenshot 2024-02-06 at 9 45 46 AM
When clicking `Next` route the user back to the move home page, not the dashboard.

When setting up shipments, they'll need to be routed back to the move home page when navigating.
Screenshot 2024-02-06 at 9 47 03 AM
`Finish later` should route them to the move home page, not the dashboard.

When reviewing shipment information following entering all info, user needs to be routed back to the move page.
Screenshot 2024-02-06 at 9 49 42 AM
`Finish later` needs to route the user back to the move home page, not the dashboard.

When completing and signing following creating a shipment, they need to be routed back to the move home page.
Screenshot 2024-02-06 at 9 54 56 AM
`Complete` should route the user back to the move home page, not the dashboard.

**Comment by TevinAdams** [comment]
> When amending orders, the user should be routed back to the move home page and not the dashboard.
> 
> Screenshot 2024-02-06 at 9 37 20 AM Clicking `Save` or `Cancel` should route them to the move page. Currently they're routed to the move dashboard.
> 
> When reviewing the request, they'll need to be routed back to the move home page. Screenshot 2024-02-06 at 9 39 33 AM `Return home` should route them back to the move home page, not the dashboard.
> 
> When uploading & confirming PPM documents - same thing. Screenshot 2024-02-06 at 9 40 37 AM Screenshot 2024-02-06 at 9 41 22 AM `Return to Homepage` and `Submit PPM Documentation` should route them back to the move home page, not the dashboard.
> 
> Need to return the user to the move home page and not the dashboard when uploading orders. Screenshot 2024-02-06 at 9 44 49 AM The `Back` button should route them back to the move home page, not the dashboard.
> 
> After uploading orders, user should be routed to the move home page, not the dashboard. Screenshot 2024-02-06 at 9 45 46 AM When clicking `Next` route the user back to the move home page, not the dashboard.
> 
> When setting up shipments, they'll need to be routed back to the move home page when navigating. Screenshot 2024-02-06 at 9 47 03 AM `Finish later` should route them to the move home page, not the dashboard.
> 
> When reviewing shipment information following entering all info, user needs to be routed back to the move page. Screenshot 2024-02-06 at 9 49 42 AM `Finish later` needs to route the user back to the move home page, not the dashboard.
> 
> When completing and signing following creating a shipment, they need to be routed back to the move home page. Screenshot 2024-02-06 at 9 54 56 AM `Complete` should route the user back to the move home page, not the dashboard.

Fixed. I think we might need a Home button. Something to navigate back to the Dashboard.

**Review by traskowskycaci — COMMENTED** [review]
When I go through a new customer flow, the flow looks good. However, after I have entered profile info, orders, shipments and submit the move and am here:
image
If I select "Upload documents" and either save or cancel on this page:
image
I am routed back here:
image
but should go back here:
image

During the customer profile creation flow, that routing works the way I expect it to, it's only after I have added everything that I see that issue.

**Review by traskowskycaci — COMMENTED** [review]
Not sure if this should happen or not - when I review the request:
image
then scroll down to the bottom and click return home:
image
I am routed back here:
image


Is that correct or should that return home button take me to the specific move page?

**Comment by danieljordan-caci** [comment]
> Not sure if this should happen or not - when I review the request: image then scroll down to the bottom and click return home: image I am routed back here: image
> 
> Is that correct or should that return home button take me to the specific move page?

I think you should be routed back to the move home page since that's where you initially started that path at.

**Comment by TevinAdams** [comment]
> Not sure if this should happen or not - when I review the request: image then scroll down to the bottom and click return home: image I am routed back here: image
> 
> Is that correct or should that return home button take me to the specific move page?

fixed

**Review by traskowskycaci — COMMENTED** [review]
Do any of these routing changes need wrapped in a feature flag check before getting to main?

**Review by traskowskycaci — COMMENTED** [review]
First time customer flow after completing the profile, getting ready to upload orders:
image
Hitting back here (whether I fill out order info or not):
image
takes me back to the dashboard rather than the move home page.


On the set up shipments step, 
image
Selecting Finish later here:
image
takes me back to the dashboard rather than the move home page.

Otherwise, looking good!

**Comment by TevinAdams** [comment]
> Do any of these routing changes need wrapped in a feature flag check before getting to main?

If MultiMove isn't enabled then we would definitely not want these changes taking effect. I know @cameroncaci is currently doing some featureFlag implementation changes so not sure where the link navigation changes will need to fall amongst all other MultiMove work work.

**Comment by TevinAdams** [comment]
> First time customer flow after completing the profile, getting ready to upload orders: image Hitting back here (whether I fill out order info or not): image takes me back to the dashboard rather than the move home page.
> 
> On the set up shipments step, image Selecting Finish later here: image takes me back to the dashboard rather than the move home page.
> 
> Otherwise, looking good!

That link has been changed.

**Comment by traskowskycaci** [comment]
> > First time customer flow after completing the profile, getting ready to upload orders: image Hitting back here (whether I fill out order info or not): image takes me back to the dashboard rather than the move home page.
> 
> That link has been changed.

Checked it out, looks good.

**Comment by traskowskycaci** [comment]
> > >On the set up shipments step, image Selecting Finish later here: image takes me back to the dashboard rather than the move home page.


> > Still seeing this step take me back to the dashboard.

**Comment by TevinAdams** [comment]
> > > > On the set up shipments step, image Selecting Finish later here: image takes me back to the dashboard rather than the move home page.
> 
> > > Still seeing this step take me back to the dashboard.

Fixed that one

**Review by traskowskycaci — APPROVED** [review]
Customer flow looks good!

**Review by danieljordan-caci — DISMISSED** [review]
This should take the user back to the move home page, when reviewing their request.
Screenshot 2024-02-12 at 8 22 51 AM

**Comment by danieljordan-caci** [comment]
When the user clicks "Complete" it takes me to the dashboard - should be back to the move home page
Screenshot 2024-02-12 at 8 26 20 AM

**Comment by TevinAdams** [comment]
> This should take the user back to the move home page, when reviewing their request. Screenshot 2024-02-12 at 8 22 51 AM

This navigation link has been updated.

**Comment by cameroncaci** [comment]
> > Do any of these routing changes need wrapped in a feature flag check before getting to main?
> 
> If MultiMove isn't enabled then we would definitely not want these changes taking effect. I know @cameroncaci is currently doing some featureFlag implementation changes so not sure where the link navigation changes will need to fall amongst all other MultiMove work work.

Hey there, you can now find the feature flag changes in effect inside of the `integrationTesting` branch. It uses the async util call under `utils/featureFlags`. See under `mymove/index.jsx` for the conditional handling of routes and feature flags.

**Comment by cameroncaci** [comment]
The `Flipt` feature flag changes are on hold into main until [B-18459](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A886662) makes it way in and fixes the tests

**Comment by cameroncaci** [comment]
@TevinAdams If this is still under work could you move it back to draft?

**Comment by cameroncaci** [comment]
@TevinAdams Here are some tests to make sure pass:

image

image

image

image

image

**Pull request closed without merging**
