### PR TITLE
[MB-13567] SC/TOO can add and edit the secondary addresses for HHG shipments

### PR DESCRIPTION
**Pull request by pearl-truss**
## Summary

This PR 
- Updates the shipment form displayed on the Office App to display the secondary pickup and delivery address fields (these fields are hidden by default if the input for "has secondary pickup/delivery address" is false
- Adds the secondary addresses to the shipment card displayed on the Move Details tab

**NOTE For Design/Product**
- I matched the logic found on the customer's shipment form for whether or not to display these secondary fields for other shipment types. From my understanding, the customer side only displays these for HHGs, so that's what is implemented here. If that's incorrect please let me know 

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

Editing the secondary addresses as a SC/TOO
1. Access the office app
2. Login as a SC or TOO
3. View a move that has an HHG shipment, click the Edit Shipment button and make edits to the secondary address(es). Click save. You should notice the updates in the shipment card. 

## Verification Steps for Reviewers

- The adding a secondary pickup or delivery address as a customer is viewable and editable by a TOO/SC

## Screenshots
Screenshot 2023-04-24 at 3 36 29 PM
Screenshot 2023-04-24 at 3 36 44 PM

### CODE REVIEW

**Review by scottmries — APPROVED** [review]
LGTM Pearl! Thanks for tackling this whole flow in one go.

I was able to update the secondary address, and all tests passed.

I left one suggestion, but since it's just for removing a comment, I'll go ahead and approve.

**Comment by rileyorr** [comment]
Great job on this @pearl-truss! I just had a few things:
- Is the content 'Do you want the movers to deliver any belongings to a second address? (Must be near your delivery address. Subject to approval.)' pulled over from the customer app?
   - I think we should make it more directed towards office users. We can probably just remove the content in parentheses since office users are the folks approving the moves. So we could just have 'Do you want the movers to deliver any belongings to a second address?' 
- Can the H4 'Secondary pickup address' be bolded? It looks like that's the styling in the customer app so I'd like to keep it consistent if possible
- It looks like some Happo diffs included secondary addresses within the NTS 'edit' screen but I didn't see anything indicating that the secondary address displays on the NTS card. It looks like it does in the customer app so I wanted to double-check that this work doesn't cover NTS as well. Here's a screenshot from the customer app for reference:
Screenshot 2023-04-27 at 3 10 37 PM

Let me know if you have any questions!

**Comment by pearl-truss** [comment]
@rileyorr thanks for the review and sorry for delay, I was split working on another ticket

I applied the text changes, bolding the H4 and displaying the secondary pickup address for nts
Screenshot 2023-05-01 at 9 48 16 AM
Screenshot 2023-05-01 at 9 48 45 AM
Screenshot 2023-05-01 at 9 48 52 AM

**Review by rileyorr — APPROVED** [review]
@pearl-truss thank you for incorporating those changes! Everything LGTM

**Pull request merged**
