### PR TITLE
B 21230 resolve canvas dependency v2 main

### PR DESCRIPTION
**Pull request by cameroncaci**
> [!WARNING]
> This ticket requires an advisory release, check with Mountain Movers scrum master and ask about this said advisory before merging this release

> [!IMPORTANT]
> Commits 7b17fcae0583d0c938ffa3f137b120fcc26101b1 and e13ad40feb9deaa39c1b305f5d7cc7f94cccf3d7 will be missing from this PR compared to int. One commit introduces changes and the next immediately reverts it. Both of these commits together amount to NO code changes, please disregard them.

## Ticket
[B-21230](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1013111)

### Integration PR
https://github.com/transcom/mymove/pull/14218 <- B-21230 code
https://github.com/transcom/mymove/pull/14343 <- Happo CI/CD step fix

### CODE REVIEW

**Comment by deandreJones** [comment]
conflicts

**Comment by deandreJones** [comment]
also still in DRAFT status. is it ready?

**Comment by cameroncaci** [comment]
Still awaiting POA and advisory

**Comment by cameroncaci** [comment]
> also still in DRAFT status. is it ready?

^ Well, yes and no. It's ready, but it's been hostage in the pipeline. Still awaiting test/poa/adivsory

**Review by TevinAdams — APPROVED** [review]
Changes match with INT

**Review by traskowskycaci — COMMENTED** [review]
Questions on a few commits from INT that I don't see here. Do we need these?

From INT:
- update react file viewer to dev ref: https://github.com/transcom/mymove/pull/14218/commits/5796a6af4e104e9cfb04e0f96080042b9fa1059a
- yarn install: https://github.com/transcom/mymove/pull/14218/commits/348590f48a708acba8bf2607d4685fe83f43177b
- fix flaky timeout: https://github.com/transcom/mymove/pull/14218/commits/31e6624f5403e45d8092fac9e92bb7e8c72071be

**Comment by cameroncaci** [comment]
> Questions on a few commits from INT that I don't see here. Do we need these?
> 
> From INT:
> 
> * update react file viewer to dev ref: [5796a6a](https://github.com/transcom/mymove/commit/5796a6af4e104e9cfb04e0f96080042b9fa1059a)
> * yarn install: [348590f](https://github.com/transcom/mymove/commit/348590f48a708acba8bf2607d4685fe83f43177b)
> * fix flaky timeout: [31e6624](https://github.com/transcom/mymove/commit/31e6624f5403e45d8092fac9e92bb7e8c72071be)

update react ifle viewer to dev ref is unneeded, it's an int specific commit
yarn install is another int specific commit since it used that dev ref

flaky timeout is _not_ and int specific commit. It's one that I pushed to int but not main, thanks for finding this one. Cherry-picked under https://github.com/transcom/mymove/pull/14240/commits/4d5b74df83c757d711dc145776478bcf00d6e683

Heads up I'll be pushing a new yarn install to resolve conflicts with main, this will be a main specific commit and will not match int.

**Review by traskowskycaci — APPROVED** [review]
Looks good! Changed files match, other than `yarn.lock`, which is expected.

**Comment by cameroncaci** [comment]
Codeowner please do not approve until POA'd and advisory sent out (Please contact the Mountain Movers scrum master for if it has been released yet or not)

**Review by danieljordan-caci — APPROVED** [review]
solid

**Comment by cameroncaci** [comment]
Merged fix to happo ci/cd step failing

**Comment by cameroncaci** [comment]
File changes `.github/workflows/happo-tests.yml` and `.github/workflows/happo-tests-main.yml` are present in integration

**Comment by cameroncaci** [comment]
> Codeowner who reviews this please do not approve until POA'd and advisory sent out (Please contact the Mountain Movers scrum master for if it has been released yet or not)

bumping to keep this the most recent comment

**Comment by cameroncaci** [comment]
Product owner has marked this ready for staging release. Requesting approval and will merge once coordinated

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
