### PR TITLE
INT B-21528 AER SSW

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## Summary

This branch adds fields on the Shipment Summary Worksheet that is downloaded by the customer after a PPM Closeout when they click the "Download Payment Packet" button.

The following changes were made:
1. New "Reimbursement Type" section under the "Entitlements & move summary" header, with a checkbox for "Actual Expense Reimbursement"
2. Text field beside the "100% GCC" header under the "Actual obligations" section (lower right of page 1) that will show "Actual Expense Reimbursement" in red text when the move is of that type.
3. Text field underneath the "Remaining PPM Incentive (pre-tax) header on the left-side of page 2 that will show "Actual Expense Reimbursement" in red text when the move is of that type.
4. Field inside the "Current Payment Request" header on page 2 that will read "This PPM is being processed at actual expense reimbursement for valid expenses not to exceed the government constructed cost (GCC)." when the move is an AER type.

### How to test

1. Run `make db_dev_fresh` if you haven't already, this will reset the database and populate it with test data.
2. Login as SC and access the move with move code "CLOSE0", in network tools get the eTag and ID for the MTO Shipment, as well as the move task order ID (found in the "mto-shipment" request).
3. Access the swagger API page and hit the PATCH endpoint here ([/move_task_orders/{moveTaskOrderID}/mto_shipments/{shipmentID}](http://officelocal:3000/swagger-ui/ghc.html#/mtoShipment/updateMTOShipment) and use the following body (this just changes the "isActualExenseReimbursement" field to true):

```
{
    "shipmentType": "PPM",
    "counselorRemarks": "test",
    "ppmShipment": {
        "expectedDepartureDate": "2024-10-01",
        "pickupAddress": {
            "city": "Beverly Hills",
            "country": "US",
            "county": "LOS ANGELES",
            "eTag": "MjAyNC0xMC0xOFQxNTozOToyMi40NDExOTJa",
            "postalCode": "90210",
            "state": "CA",
            "streetAddress1": "123 Any Street",
            "streetAddress2": "P.O. Box 12345",
            "streetAddress3": "c/o Some Person"
        },
        "destinationAddress": {
            "city": "Beverly Hills",
            "county": "LOS ANGELES",
            "eTag": "MjAyNC0xMC0xOFQxNTozOToyMi40NDM4Wg==",
            "postalCode": "90210",
            "state": "CA",
            "streetAddress1": "Test"
        },
        "sitExpected": false,
        "estimatedWeight": 100,
        "hasProGear": false,
        "hasRequestedAdvance": false,
        "hasSecondaryPickupAddress": false,
        "hasSecondaryDestinationAddress": false,
        "hasTertiaryPickupAddress": false,
        "hasTertiaryDestinationAddress": false,
        "isActualExpenseReimbursement": true
    }
}
```
Verify that the operation returned a 200 and that the returned object contains "isActualExpenseReimbursement:true" by scrolling down.

4. Review documents and submit to closeout the PPM.
5. Go to the customer site and access the pre-made user account under this email using ctrl+f to find: **weightTicketPPM+closeout@ppm.approved**
6. Click "Download Payment packet" and verify that the results match the screenshots below.

## Screenshots
Screenshot 2024-10-30 at 4 17 34 PM
Screenshot 2024-10-30 at 4 17 55 PM

### CODE REVIEW

**Review by KonstanceH — APPROVED** [review]
LGTM

**Comment by taeJungCaci** [comment]
Red texts are still showing for non-actual expense reimbursement ppms. Is this normal?
make db_dev_reset db_dev_migrate

**Comment by brooklyn-welsh** [comment]
> Red texts are still showing for non-actual expense reimbursement ppms. Is this normal? image

Definitely not, something must've changed during either a merge or when I was editing the PDF one last time for alignment, was working earlier, will pull and push up a fix.

**Review by taeJungCaci — APPROVED** [review]
LGTM!

**Pull request merged**
