### PR TITLE
INT B-18411-UI-shipment-address-update-review-screen-updates-v2

### PR DESCRIPTION
**Pull request by danieljordan-caci**
INTEGRATION BRANCH

## Summary

In order to get the full functionality, please run `git merge origin/B-18475-INT` to merge the backend portion of this feature into the branch.
[B-18475 PR](https://github.com/transcom/mymove/pull/11790)

When you're finished run `git reset --hard HEAD~1` to undo the commit of the above branch.

When the TOO reviews a shipment destination address update request - there's a reason for it. It means that there was a check done in the backend that changed the status of the request in the `shipment_address_updates` table to `REQUESTED` instead of automatically changing it to `APPROVED`.

When a shipment contains destination SIT service items, the above mentioned backend branch does logic checks that populates the table with SIT data. 

This PR does the following:
- takes that SIT data sent to the UI and returns an info banner if the new mileage change for a shipment containing SIT is changed to **greater than** 50 miles

### How to test

1. Access MM as prime
2. Request a shipment destination address update to a ZIP that is > 50 miles of what the current destination address is
3. Log in as the TOO & navigate to that shipment
4. Follow the red prompts until you get to the address update modal that shows the changes
5. You should see an info banner that shows the updated mileage and a general statement to the TOO letting them know what's up

## Screenshots

Screenshot 2024-01-23 at 10 58 24 AM

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Auto merge failed for me:
image

**Comment by danieljordan-caci** [comment]
> Auto merge failed for me: image

Try `git merge origin/B-18475-shipment-dest-address-update-with-sit-updates`

I created a new branch but forgot to update the comment. Also make sure you run the server & client before merging just in case you need to build.

**Review by traskowskycaci — APPROVED** [review]
Frontend showed the mileage for a SIT distance < 50 miles, looks good. Commented on 18475 with an issue I saw

**Comment by cameroncaci** [comment]
> > Auto merge failed for me: image
> 
> Try `git merge origin/B-18475-INT`
> 
> I created a new branch but forgot to update the comment. Also make sure you run the server & client before merging just in case you need to build.

This branch doesn't appear to exist anymore. Is the merge still required for successful testing?

**Comment by danieljordan-caci** [comment]
> > > Auto merge failed for me: image
> > 
> > 
> > Try `git merge origin/B-18475-INT`
> > I created a new branch but forgot to update the comment. Also make sure you run the server & client before merging just in case you need to build.
> 
> This branch doesn't appear to exist anymore. Is the merge still required for successful testing?

Since `B-18475-INT` has been merged into `integrationTesting` and `integrationTesting` has been synced with this branch... it *should* no longer be necessary. Do a `git pull` and that code should be in there.

**Review by cameroncaci — CHANGES_REQUESTED** [review]
Approving the requested changes (When >50 SIT miles) goes in as "Updated Move" rather than "Updated Address". It also does not state the details of the change within the move history.

It will utilize "Updated Address" if the provided zip code is <50 miles.

image

Additionally, I found an issue with using zip code of 73169 and 73064 (Both Oklahoma City) showing as >50 miles

image

**Comment by danieljordan-caci** [comment]
> Approving the requested changes (When >50 SIT miles) goes in as "Updated Move" rather than "Updated Address". It also does not state the details of the change within the move history.
> 
> It will utilize "Updated Address" if the provided zip code is <50 miles.
> 
> image
> Additionally, I found an issue with using zip code of 73169 and 73064 (Both Oklahoma City) showing as >50 miles
> 
> image

I'm aware of these issues, but these are out of scope of this PR.

The move history should have a component to show events for this (currently they don't).
The mileage issue is likely something to do with the zip distance calculator (I've also found the results to be wildly inaccurate).

I don't believe this hinder the approval of this PR.

**Comment by cameroncaci** [comment]
> > Approving the requested changes (When >50 SIT miles) goes in as "Updated Move" rather than "Updated Address". It also does not state the details of the change within the move history.
> > It will utilize "Updated Address" if the provided zip code is <50 miles.
> > image
> > Additionally, I found an issue with using zip code of 73169 and 73064 (Both Oklahoma City) showing as >50 miles
> > image
> 
> I'm aware of these issues, but these are out of scope of this PR.
> 
> The move history should have a component to show events for this (currently they don't). The mileage issue is likely something to do with the zip distance calculator (I've also found the results to be wildly inaccurate).
> 
> I don't believe this hinder the approval of this PR.

@danieljordan-caci Understood, is there an existing issue ticket or backlog item where I can paste these findings?

**Comment by danieljordan-caci** [comment]
> > > Approving the requested changes (When >50 SIT miles) goes in as "Updated Move" rather than "Updated Address". It also does not state the details of the change within the move history.
> > > It will utilize "Updated Address" if the provided zip code is <50 miles.
> > > image
> > > Additionally, I found an issue with using zip code of 73169 and 73064 (Both Oklahoma City) showing as >50 miles
> > > image
> > 
> > 
> > I'm aware of these issues, but these are out of scope of this PR.
> > The move history should have a component to show events for this (currently they don't). The mileage issue is likely something to do with the zip distance calculator (I've also found the results to be wildly inaccurate).
> > I don't believe this hinder the approval of this PR.
> 
> @danieljordan-caci Understood, is there an existing issue ticket or backlog item where I can paste these findings?

Nah, I realized how crazy inaccurate the `ZipTransitDistance` function is when working on the backend of this PR. Meant to bring it up, but forgot about it.

**Comment by cameroncaci** [comment]
> Nah, I realized how crazy inaccurate the ZipTransitDistance function is when working on the backend of this PR. Meant to bring it up, but forgot about it.

Create that issue ticket with the knowledge in that brain of yours and I'll give you the green stamp :)

**Comment by danieljordan-caci** [comment]
> > Nah, I realized how crazy inaccurate the ZipTransitDistance function is when working on the backend of this PR. Meant to bring it up, but forgot about it.
> 
> Create that issue ticket with the knowledge in that brain of yours and I'll give you the green stamp :)

UGH you dirty dawg

**Comment by danieljordan-caci** [comment]
> > Nah, I realized how crazy inaccurate the ZipTransitDistance function is when working on the backend of this PR. Meant to bring it up, but forgot about it.
> 
> Create that issue ticket with the knowledge in that brain of yours and I'll give you the green stamp :)

Interesting... I just calculated the distance between 73064 -> 73169 and got 34 miles. Why'd you get such wildly different results? In your testing, I'd go through the process of adding service items as the prime, approve them as the TOO, and then request to update the addy.

Screenshot 2024-01-26 at 11 02 26 AM

**Comment by danieljordan-caci** [comment]
> > Nah, I realized how crazy inaccurate the ZipTransitDistance function is when working on the backend of this PR. Meant to bring it up, but forgot about it.
> 
> Create that issue ticket with the knowledge in that brain of yours and I'll give you the green stamp :)

But I did create an issue because I did get a crazy result from Tulsa -> OKC

https://www13.v1host.com/USTRANSCOM38/Issue.mvc/Summary?oidToken=Issue%3A892453

**Comment by cameroncaci** [comment]
> > > Nah, I realized how crazy inaccurate the ZipTransitDistance function is when working on the backend of this PR. Meant to bring it up, but forgot about it.
> > 
> > 
> > Create that issue ticket with the knowledge in that brain of yours and I'll give you the green stamp :)
> 
> Interesting... I just calculated the distance between 73064 -> 73169 and got 34 miles. Why'd you get such wildly different results? In your testing, I'd go through the process of adding service items as the prime, approve them as the TOO, and then request to update the addy.
> 
> Screenshot 2024-01-26 at 11 02 26 AM

Interesting, I bet it's because of something like the state being different. Since in my testing the state was California but it was an Oklahoma zip code? Definitely notes for the issue ticket

**Review by cameroncaci — APPROVED** [review]

**Pull request merged**
