### PR TITLE
INT B-19939 Diversion Reason in API

### PR DESCRIPTION
**Pull request by ajlusk**
## Summary

This ticket adds a field for a diversion request's reason to the API. The field can be edited by the request diversion endpoint and viewed in any endpoint returning a full MTO Shipment. Generally followed how rejection reason was added to the reject shipment endpoint.

Upstream Dependency: [B-19938](https://github.com/transcom/mymove/pull/12589)

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test
I'd recommend testing in both the app, to ensure the existing request diversion button still works, and postman or swagger, to ensure the endpoint works fully as intended.

#### In the App
1. Create or Identify an approved HHG to request diversions on (PENDNG & BILWEI should work if they are fresh).
2. Access the office app.
3. Login as a TOO.
4. Select one of the moves identified above from your queue.
5. Navigate to the move task order page and locate the request diversion button.
6. Open the developer tools' network tab to capture the request we're about to send.
7. Click the request diversion button, the UI should show the request was made successfully.
8. Find the request named "request-diversion"
9. The request's payload should have a body containing a blank "diversionReason"
10. The response should be a 200 and include`status: "DIVERSION_REQUESTED"` and `diversionReason: ""`. The diversion reason is blank so that the front-end can still send the request since a body is now required. The field will be made to require a non-blank string in a later ticket when the user is able to submit a reason.

#### In Postman
1. Create or Identify an approved HHG to request diversions on (PENDNG & BILWEI should work if they are fresh). 
2. For authentication to use in Postman, access the office app and login as a TOO.
3. Obtain the ID and eTag of the shipment you intend to request as well as your the x-Csrf-Token
4. Submit a POST request to the following URL with the following body
URL:`http://officelocal:3000/ghc/v1/shipments/{shipmentID}/request-diversion`
Body `{"diversionReason": "Your diversion reason"}`
5. The response should include `status: "DIVERSION_REQUESTED"` and `diversionReason: "Your diversion reason"`
6. Optionally verify the reason you submitted is in the database in the mto_shipments.diversion_reason column.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by MInthavongsay — APPROVED** [review]
I believe we have to update API spreadsheet with these changes. UI and postman/swagger tests all passed per instructions.

**Comment by ajlusk** [comment]
> I believe we have to update API spreadsheet with these changes. UI and postman/swagger tests all passed per instructions.

Spoke with Matthew about that. Sounds like that only applies to changes to the Prime API.

**Review by r-mettler — APPROVED** [review]
See blank diversion request in payload. 
Screenshot 2024-05-17 at 3 43 50 PM

Reason updated using api call.

**Comment by r-mettler** [comment]
> > I believe we have to update API spreadsheet with these changes. UI and postman/swagger tests all passed per instructions.
> 
> Spoke with Matthew about that. Sounds like it only applies to changes to the Prime API. He'll confirm on Monday.

I believe that is correct, its just for Prime API. Its a way for them to track changes we have made to the Prime API.

**Pull request merged**
