### PR TITLE
INT B-22122

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Adding AK zips to `zip3_distances` so we can use them to get... distances?

### How to test

1. Fire up your server
2. Should see the migration successfully run
3. In DBeaver query the `zip3_distances` table `WHERE to_zip3 = 999` 
4. Also check ZIPs `998`, `997`, `996`, `995` and any other AK ZIPs you find

### CODE REVIEW

**Comment by brianmanley-caci** [comment]
I noticed in the new data that not all combinations are represented. For example I see the '360' -> ('998', '999), but I don't see '360' to ('997', '996',or '995'). Is that the expectation or do you think we are missing some needed combos?

**Comment by danieljordan-caci** [comment]
> > I noticed in the new data that not all combinations are represented. For example I see the '360' -> ('998', '999), but I don't see '360' to ('997', '996',or '995'). Is that the expectation or do you think we are missing some needed combos?
> 
> That is a @begrohmann question.
> 
> There's also not a `361 -> 995/996/997`. There seems to be some little things like that missing in there.

**Comment by pambecker** [comment]
> > I noticed in the new data that not all combinations are represented. For example I see the '360' -> ('998', '999), but I don't see '360' to ('997', '996',or '995'). Is that the expectation or do you think we are missing some needed combos?
> 
> That is a @begrohmann question.
> 
> There's also not a `361 -> 995/996/997`. There seems to be some little things like that missing in there.

There is a

**Comment by pambecker** [comment]
> > I noticed in the new data that not all combinations are represented. For example I see the '360' -> ('998', '999), but I don't see '360' to ('997', '996',or '995'). Is that the expectation or do you think we are missing some needed combos?
> 
> That is a @begrohmann question.
> 
> There's also not a `361 -> 995/996/997`. There seems to be some little things like that missing in there.

We do have that huge data file that Dre found, we can weed through that to find the missing ones if Beth can't get them easily.

**Review by deandreJones — APPROVED** [review]

**Comment by deandreJones** [comment]
have to remember that conus zip wouldn't go from say offalon il- to Alaska zip.. only conus zip to the port

**Pull request merged**
