### PR TITLE
MB-4198 Document viewer long filenames overflow with ellipsis

### PR DESCRIPTION
**Pull request by donaldthai**
## Description

This pr changes the text overflow style on the document viewer menu. Ellipsis will now show if the text overflows.

## Reviewer Notes

- This PR addresses the issue on IE11 where the document viewer height was shrinking to 0. Check out the resource article below.
- The document title will also have ellipsis.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make storybook
```

To see changes:

- http://localhost:6006/?path=/story/components-document-viewer-menu--menu
- http://localhost:6006/?path=/story/components-document-viewer-document-viewer--pdf-viewer

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4198) for this change
* [this article](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) explains more about the approach used.
* [this article](https://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/) explains the fix for IE11 flexbox height issue shrinking to 0.

## Screenshots

Sep-21-2020 15-51-24

image

### CODE REVIEW

**Comment by duncan-truss** [comment]
The collapsed menu is looking good to me.  The menu icon seems to be disappearing in Chrome at least when the filename in the titlebar is too long as well.  Do we want to deal with it in the titlebar in a similar fashion?  Should we just call the `filenameFromPath` once and pass it to the DocumentViewer component since it's needed both places?

officelocal_3000_moves_77f05c7d-ead6-4bd5-8c5d-1e8c6794991b_orders(Laptop with HiDPI screen)

**Comment by duncan-truss** [comment]
IE11 is showing me an empty screen for this page 😬 
Screen Shot 2020-09-22 at 10 39 03 AM

**Review by amanda5iu — APPROVED** [review]
LGTM!

**Comment by donaldthai** [comment]
> IE11 is showing me an empty screen for this page 😬
> Screen Shot 2020-09-22 at 10 39 03 AM

Doesn't seem like it's because of the changes in the PR?

**Comment by donaldthai** [comment]
> The collapsed menu is looking good to me. The menu icon seems to be disappearing in Chrome at least when the filename in the titlebar is too long as well. I think we need to make specify the icon should not flex shrink.
> 
> Do we want to deal with the text-transform it in the titlebar in a similar fashion? Should we just call the `filenameFromPath` once and pass it to the DocumentViewer component since it's needed both places?
> 
> officelocal_3000_moves_77f05c7d-ead6-4bd5-8c5d-1e8c6794991b_orders(Laptop with HiDPI screen)

Yea, I can just pass in the transformed title and pass it down to the menu

**Comment by duncan-truss** [comment]
@donaldthai The text transform looks good for the titlebar.  The menu icon is still shrinking for me because we haven't set `flex-shrink: 0` on that button.

**Comment by duncan-truss** [comment]
On IE11 the title doesn't display on hover but if we move the title attribute to the button instead of the paragraph I think it will work.

**Review by duncan-truss — COMMENTED** [review]
@donaldthai Did you want to revert `.loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png` to what's on master?

**Comment by donaldthai** [comment]
> @donaldthai Did you want to revert `.loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png` to what's on master?

Let me revert that file

**Comment by donaldthai** [comment]
@duncan-truss yayyyy it's passing now!

**Review by duncan-truss — APPROVED** [review]
Thanks for the extra effort here I think it was worth it!

**Pull request merged**
