### PR TITLE
[MB-3592] RequestedShipments card wrapping

### PR DESCRIPTION
**Pull request by suzubara**
## Description

Fixes issue where multiple Shipment cards on the Move details page don't wrap correctly. Also made some other style changes, to make this section better match the designs.

## Reviewer Notes

@transcom/truss-design - This should wrap up design tweaks to this component (Move Details > Requested Shipments / Approved Shipments). Please note if there is any additional feedback!

## Setup

The changes can be viewed in Storybook (under **TOO/TIO Components > RequestedShipments**):

```
yarn storybook
```

Or via the app:

```
make db_dev_e2e_populate
make server_run
make client_run
```

- Move `6fca843a-a87e-4752-b454-0fac67aa4988` should display one requested shipment
- Move `ca59791f-7b1a-4769-84a2-5cf0ec258677` should display two approved shipments

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3592) for this change

## Screenshots

image

image

image

image

image

### CODE REVIEW

**Review by Ryan-Koch — APPROVED** [review]

**Review by brooksr4 — APPROVED** [review]
Looks good, although I would like to see an example with 3 shipments to see if it stacks correctly.

**Review by duncan-truss — APPROVED** [review]
Wraps as expected in Firefox and Chrome from what I saw.  IE11 doesn't seem to want to stack in a single column and the text overflows but did wrap initially.

Screen Shot 2020-09-16 at 12 13 44 PM

**Comment by suzubara** [comment]
> Looks good, although I would like to see an example with 3 shipments to see if it stacks correctly.

@brooksr4 I added an example with 3 shipments to Storybook!

**Review by donaldthai — APPROVED** [review]
Looks good. Issue with IE11 that Duncan mentioned.

**Comment by suzubara** [comment]
@duncan-truss thanks for taking a look in IE! I added some tweaks that should fix the wrapping issue, and improve responsiveness in other browsers as well. I will note that there are still some issues at smaller screen sizes, since the Office app was not built to be fully responsive, that I think we'll have to resolve in the future.

image

**Pull request merged**
