### PR TITLE
B-18329 Remove N/A customer's address

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary
Integration PR: https://github.com/transcom/mymove/pull/12196

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Create PPM move.
2. Edit and submit move as SC. Take note of pickup and destination address.
3. As TOO find move and click "Move task order" tab to confirm addresses

## Screenshots
Screenshot 2024-03-13 at 8 33 00 AM
Screenshot 2024-03-13 at 8 29 16 AM

### CODE REVIEW

**Review by taeJungCaci — COMMENTED** [review]
Missing value `line 31` in `src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx`

Integration PR has `Street Address`

**Comment by JamesHawks224** [comment]
verify rpt.
[B18329-12237.verify_rpt.txt](https://github.com/transcom/mymove/files/14607088/B18329-12237.verify_rpt.txt)

        Same?         file
         -      n     pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
         y      -     pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
         -      n     src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
         y      -     src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
         y      -     src/utils/shipmentDisplay.jsx

**Comment by KonstanceH** [comment]
> Missing value `line 31` in `src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx`
> 
> Integration PR has `Street Address`

okay got it changed and pushed up

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Comment by KonstanceH** [comment]
> verify rpt. [B18329-12237.verify_rpt.txt](https://github.com/transcom/mymove/files/14607088/B18329-12237.verify_rpt.txt)
> 
> ```
>     Same?         file
>      -      n     pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
>      y      -     pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
>      -      n     src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
>      y      -     src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
>      y      -     src/utils/shipmentDisplay.jsx
> ```

I fixed the diff in the ShipmentAddresses.test file so now everything looks correct and complete.

**Comment by JamesHawks224** [comment]
updated verify rpt:

        Same?         file
         -      n     pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
         y      -     pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
         y      -     src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
         y      -     src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
         y      -     src/utils/shipmentDisplay.jsx

**Comment by KonstanceH** [comment]
> everything looks correct and complete

Cool everything looks correct and complete

**Comment by KonstanceH** [comment]
> updated verify rpt:
> 
> ```
>     Same?         file
>      -      n     pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
>      y      -     pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
>      y      -     src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
>      y      -     src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
>      y      -     src/utils/shipmentDisplay.jsx
> ```

Cool everything looks correct and complete

**Comment by JamesHawks224** [comment]
dev has certified changes are correct and complete.

**Pull request merged**
