### PR TITLE
Setup new relic browser monitoring [delivers #158307863]

### PR DESCRIPTION
**Pull request by jim**
~~**DO NOT MERGE** as staging and production haven't been configured with the correct environment variables yet.~~ The environment variables have been configured on staging and production.

## Description

This PR sets up the app to include [New Relic Browser Pro](https://newrelic.com/products/browser-monitoring) so we can collect errors from the front end and also gain some insight into our client-side performance on users' devices.

## Reviewer Notes

* When running `make client_run`, an empty `script` tag will be present in `index.html`. Its `type` attribute will result in it being ignored by browsers.
* When running `make server_run` and loading the site via `localhost:8081`, the empty `script` tag will be replaced with the New Relic client code. Since there will be no configuration for it, the client code will not attempt to activate.
* On staging and production (or when ever the file is served by the go app *and* there are values for the two environment variables), the empty `script` tag will be replaced with the New Relic client code and configured to collect errors and other client data.

## Code Review Verification Steps

* [ ] All tests pass.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/blob/master/docs/backend.md#logging)
* [ ] This works in IE.
* Any new client dependencies (Google Analytics, hosted libraries, CDNs, etc) have been:
  * [ ] Communicated to @willowbl00
  * [ ] Added to the list of [network dependencies](https://github.com/transcom/mymove#client-network-dependencies)
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/158307863) for this change

### CODE REVIEW

**Comment by akostibas** [comment]
Unless you've run `make client_build` in your checkout, you'll run into this problem:

```
panic: open build/new_relic.html: no such file or directory
```

This story could help: https://www.pivotaltracker.com/story/show/158678117

**Comment by jim** [comment]
@akostibas I ran into that and didn't want to add that dependency since `make client_build` is so slow. I will add a better error message to the code to handle this.

**Comment by jim** [comment]
The error now explains how it can be resolved:

```
2018-06-29T14:07:20.852-0500	FATAL	webserver/main.go:329	could not read index.html template: run make client_build	{"error": "open build/index.html: no such file or directory"}
main.indexHandler
	/Users/jimb/go/src/github.com/transcom/mymove/cmd/webserver/main.go:329
main.main
	/Users/jimb/go/src/github.com/transcom/mymove/cmd/webserver/main.go:280
runtime.main
	/Users/jimb/.goenv/versions/1.10.1/src/runtime/proc.go:198
```

**Comment by tinyels** [comment]
LGTM

**Comment by akostibas** [comment]
I think you need to add a client network dependency for New Relic, and notify @willowbl00 (per the PR template)
https://github.com/transcom/mymove#client-network-dependencies

**Comment by jim** [comment]
@akostibas I added a note to the README [here](https://github.com/transcom/mymove/pull/734/files#diff-04c6e90faac2675aa89e2176d2eec7d8R59). Do you think that is sufficient?

**Pull request merged**
