### PR TITLE
MB-10437 Link edit accounting codes modal to edit link on shipment sidebar of move task order page

### PR DESCRIPTION
**Pull request by michaelvaldes-truss**
## Summary

This pr will add a modal for editing accounting codes from the Shipment Details Sidebar.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

##### Terminal 3

Run the populate the development database with E2E Data 

```sh
make db_dev_e2e_populate
```

</details>

### Additional steps

Perform a local login as a TXO and search for the move code `HGNTSR`. This Move should contain at least one NTS shipments, _if it doesn't then look for another_. Then click on the **Move Task Order** tab and go down to **Accounting codes** on the right hand-side of the **Non-temporary storage** section towards the bottom of the page. Then click the **Edit** button to open the modal. Edit the TAC/SAC codes and then save the to close the modal. Once closed, the modal should disappear and the **Accounting codes** section will be updated with the codes that were modified in the previous step.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [x] User facing changes have been reviewed by design.
- [x] There are no aXe warnings for UI.
- [x] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [x] There are no new console errors in the browser devtools
- [x] There are no new console errors in the test output
- [x] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Looks like Happo is complaining about things that we don't need to worry too much about.

**Comment by rogeruiz** [comment]
@Mergifyio refresh

**Comment by rogeruiz** [comment]
@amanda5iu could we get your review on this. It's similar to #8043 but with @michaelvaldes-truss added the changes to **Edit** link that you pointed out.

**Review by amanda5iu — APPROVED** [review]
Works beautifully :)

**Comment by rogeruiz** [comment]
@Mergifyio refresh

**Pull request merged**
