### PR TITLE
MAIN B-18386-Multi-Moves-Landing-Page-Component-Creation

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION BRANCH PR #1](https://github.com/transcom/mymove/pull/11811)
[INTEGRATION BRANCH PR #2 - enhancements](https://github.com/transcom/mymove/pull/11838)

## Summary

As we transition to allow for multiple moves, a new home page and component must be created to display to the customer. 

Right now in order to see this component, we are using a feature flag in `featureFlags.js` called `multiMove` that is being implemented in [this Agility Ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A873911&RoomContext=TeamRoom%3A808731&concept=TeamRoom) and [this PR](https://github.com/transcom/mymove/pull/11753). I have merged that PR into this PR in order to use that functionality.

This PR does the following:
- New component `MultiMovesLandingPage` that is the parent component holding containers of moves/shipments for current & previous moves
- tests for `MultiMovesLandingPage`
- New component `MultiMovesMoveHeader` that takes in a title and displays a moving truck icon to the left of the title
- tests for `MultiMovesMoveHeader`
- New component `MultiMovesMoveContainer` that holds data pertaining to current & previous moves. This is a reusable component that maps over an array of objects containing move data
- tests for `MultiMovesMoveContainer`
- New component `MultiMovesInfoList` that shows a grid/table of pertinent move data that can be seen at a glance. There is conditional logic that does determine different displays based on `orderType`
- tests for `MultiMovesInfoList`
- New component `ButtonDropdownMenu` that takes in an array of objects and displays a dropdown menu that is web/mobile friendly and uses a function passed in as a parameter. Also takes in parameter to determine if it is outlined or not and various classes/styles as needed
- tests for `ButtonDropdownMenu`
- test data to be used in the above mentioned components to mimic upcoming API call to be created and used on user load

Added enhancements to allow for testing & conditional rendering for previous PR of [B-18309](https://github.com/transcom/mymove/pull/11811)

This PR does the following:
- added conditional rendering if the data came back as an empty array
- added in param use to allow for testing - a user can navigate to `/moves` and add the following params and have different test data populated:
`?moveData=PCS`
`?moveData=retirement`
`?moveData=separation`
`?moveData=noPreviousMoves`
`?moveData=noCurrentMove`
`?moveData=noMoves`

### How to test

1. Access MM as a customer and sign in
2. Navigate to `http://milmovelocal:3000/moves` to see the new dashboard
3. This is currently using test data so it should display the same for everyone

## Screenshots
Expanded
Screenshot 2024-01-22 at 11 58 08 AM

Condensed
Screenshot 2024-01-22 at 11 57 55 AM

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
Seeing a blank dashboard, both for previously created service members and a new one I created. No errors in server logs

image

**Comment by danieljordan-caci** [comment]
> Seeing a blank dashboard, both for previously created service members and a new one I created. No errors in server logs
> 
> image

because the flag is not turned on - that's why. You can manipulate the code to show it if you want or add `multiMove: true` to `featureFlags.js`

**Comment by traskowskycaci** [comment]
> because the flag is not turned on - that's why. You can manipulate the code to show it if you want or add `multiMove: true` to `featureFlags.js`

Cameron's feature flag work isn't in main yet. Do we want to hold off on this PR until then?

**Comment by danieljordan-caci** [comment]
> > because the flag is not turned on - that's why. You can manipulate the code to show it if you want or add `multiMove: true` to `featureFlags.js`
> 
> Cameron's feature flag work isn't in main yet. Do we want to hold off on this PR until then?

I don't think it's necessary to hold off this PR, no. Once he gets it in then this will be viewable. You can still test it.

**Review by traskowskycaci — APPROVED** [review]
Manually added multimove: true to featureFlags.js and see the dashboard working as expected

**Review by TevinAdams — APPROVED** [review]

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
