### PR TITLE
B 21490 INT - Storybook/Happo Fixes

### PR DESCRIPTION
**Pull request by ajlusk**
## Summary

Fixes unintended happo changes/failures found in [the main PR for this backlog](https://github.com/transcom/mymove/pull/14265).

The failures related to the Document Reviewer appear to be unrelated to the changes for the BL but I fixed them before considering that.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Verify you can still switch to your secondary GBLOC
2. Run `make storybook`
3. Verify GblocSwitcher.stories.jsx, TableQueue.stories.jsx, and DocumentViewer.stories.jsx build correctly.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
Looks like you're failing pre-test and storybook checks - re-request when ya got those figured out. Looks like simple fixes.

**Comment by ajlusk** [comment]
Draft again as I think I found a better way to use redux with storybook

**Comment by ajlusk** [comment]
> Looks like you're failing pre-test and storybook checks - re-request when ya got those figured out. Looks like simple fixes.

That's what I get for resolving a conflict in github without a linter and marking it ready before letting the tests finish. Should all be fixed.

**Review by r-mettler — APPROVED** [review]
Applicable Happo issues resolved, still can change gbloc, looks good to me.

**Review by antgmann — APPROVED** [review]
Happo, changes, gblock switching, and storybook look good!

**Pull request merged**
