### PR TITLE
MAIN B-18987 update diversion msg shipment locator

### PR DESCRIPTION
**Pull request by taeJungCaci**
PR into INT: https://github.com/transcom/mymove/pull/12497

## Summary

This is to update FE diversion alert message to display the new Shipment Locator instead of Shipment ID.

### How to test

1. Create any move with a shipment that is counseled by SC (can use HHGMoveInSIT testharness).
2. As a TOO, go to the move created.
3. Under 'Move task order' tab, scroll down and find "Request diversion" link/button.
4. Click once and you should see a success alert message at the top with the new Shipment Locator. Note: Going out of focus(clicking anywhere) will review the alert message.

## Screenshots
image

### CODE REVIEW

**Comment by JamesHawks224** [comment]
verify rpt:
[B18987-12529.verify_rpt.txt](https://github.com/transcom/mymove/files/15017280/B18987-12529.verify_rpt.txt)

there were diffs

**Comment by taeJungCaci** [comment]
> verify rpt: [B18987-12529.verify_rpt.txt](https://github.com/transcom/mymove/files/15017280/B18987-12529.verify_rpt.txt)
> 
> there were diffs

Checked and verified the diffs are same correct

**Review by KonstanceH — APPROVED** [review]
LGTM

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Comment by taeJungCaci** [comment]
finally test stopped failing @JamesHawks224

**Pull request merged**
