### PR TITLE
MAIN B-18313 fixes and storybook updates

### PR DESCRIPTION
**Pull request by danieljordan-caci**
[INTEGRATION PR](https://github.com/transcom/mymove/pull/12215)

## Summary

This PR includes fixes for two issues (listed above) as well as updating the storybook for the `Summary` component. 

PR does the following:
- fixes typo in customer helper header when they have more than one move
- requires customer to validate their profile when they have anything in `currentMove` instead of `previousMoves`
- updates logic of helper box based on `currentMove` length
- updates tests
- updates storybook for `Summary` component

### How to test

1. Access MM as a customer
2. Create a move, no need to set up shipments
3. Head back to the dashboard
4. When going back to the dashboard, make sure the correct helper box is showing (tells you to validate your profile)
5. Click `Create a Move` button
6. This should navigate you to the profile validation flow

### CODE REVIEW

**Review by cameroncaci — APPROVED** [review]
Git hashes good, ping me when ready to merge please

**Review by traskowskycaci — APPROVED** [review]

**Comment by traskowskycaci** [comment]
> Git hashes good, ping me when ready to merge please

Ready to merge @cameroncaci

**Comment by cameroncaci** [comment]
Appears main is locked at the moment. Thank you for the ping @traskowskycaci

**Review by TevinAdams — APPROVED** [review]

**Comment by cameroncaci** [comment]
Still locked as of this morning

**Pull request merged**
