### PR TITLE
B-18269 show estimated on payment request

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

Allow TIO to view PPM Weights

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Find PPM with payment request
2. log in as TIO
3. view Payment request page 
4. verify estimated and Actual(if available) Weight displays

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
image
updated to:

image

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
May I suggest something? What you have is absolutely fine, but I think doing something similar to what is to the left of the PPM component would be awesome and a little more UI friendly. 

Something like:
Screenshot 2024-01-03 at 1 29 33 PM

If you want to do that, this is what the code looks like:
```
{showShipmentWeight && (
        <div className={styles.shipmentWeight}>
          {isPPM && (
            <div className={styles.spaceBetween}>
              <div className={styles.textAlignRight}>
                <h6>Estimated</h6>
                <h6>Actual</h6>
              </div>
              <div className={styles.textAlignLeft}>
                <h6>
                  <strong>{formatWeight(shipment.ppmShipment.estimatedWeight)}</strong>
                </h6>
                <h6>
                  <strong>{formatWeight(shipment.calculatedBillableWeight)}</strong>
                </h6>
              </div>
            </div>
          )}
          {!isPPM && formatWeight(shipment.calculatedBillableWeight)}
        </div>
```

And a little css:
```
.spaceBetween {
  display: flex;
  justify-content: center;
  align-items: center;
}

.textAlignRight {
  text-align: right;
}

.textAlignLeft {
  text-align: left;
}
```

You can absolutely ignore this suggestion - just giving my two cents!

**Comment by danieljordan-caci** [comment]
Also... Could youuuuuu update `ShipmentList.test.jsx` to reflect these changes? Thank youuuuuuuuu

**Comment by danieljordan-caci** [comment]
> > May I suggest something? What you have is absolutely fine, but I think doing something similar to what is to the left of the PPM component would be awesome and a little more UI friendly.
> > Something like: Screenshot 2024-01-03 at 1 29 33 PM
> > If you want to do that, this is what the code looks like:
> > ```
> > {showShipmentWeight && (
> >         <div className={styles.shipmentWeight}>
> >           {isPPM && (
> >             <div className={styles.spaceBetween}>
> >               <div className={styles.textAlignRight}>
> >                 <h6>{estimated}</h6>
> >                 <h6>{actual}</h6>
> >               </div>
> >               <div className={styles.textAlignLeft}>
> >                 <h6>
> >                   <strong>{formatWeight(shipment.ppmShipment.estimatedWeight)}</strong>
> >                 </h6>
> >                 <h6>
> >                   <strong>{formatWeight(shipment.calculatedBillableWeight)}</strong>
> >                 </h6>
> >               </div>
> >             </div>
> >           )}
> >           {!isPPM && formatWeight(shipment.calculatedBillableWeight)}
> >         </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And a little css:
> > ```
> > .spaceBetween {
> >   display: flex;
> >   justify-content: center;
> >   align-items: center;
> > }
> > 
> > .textAlignRight {
> >   text-align: right;
> > }
> > 
> > .textAlignLeft {
> >   text-align: left;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can absolutely ignore this suggestion - just giving my two cents!
> 
> ok, i dont hate this and a bit prettier

D'awwwww glad you didn't hate it haha. Don't forget your tests ;)

**Comment by deandreJones** [comment]
> > > May I suggest something? What you have is absolutely fine, but I think doing something similar to what is to the left of the PPM component would be awesome and a little more UI friendly.
> > > Something like: Screenshot 2024-01-03 at 1 29 33 PM
> > > If you want to do that, this is what the code looks like:
> > > ```
> > > {showShipmentWeight && (
> > >         <div className={styles.shipmentWeight}>
> > >           {isPPM && (
> > >             <div className={styles.spaceBetween}>
> > >               <div className={styles.textAlignRight}>
> > >                 <h6>{estimated}</h6>
> > >                 <h6>{actual}</h6>
> > >               </div>
> > >               <div className={styles.textAlignLeft}>
> > >                 <h6>
> > >                   <strong>{formatWeight(shipment.ppmShipment.estimatedWeight)}</strong>
> > >                 </h6>
> > >                 <h6>
> > >                   <strong>{formatWeight(shipment.calculatedBillableWeight)}</strong>
> > >                 </h6>
> > >               </div>
> > >             </div>
> > >           )}
> > >           {!isPPM && formatWeight(shipment.calculatedBillableWeight)}
> > >         </div>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And a little css:
> > > ```
> > > .spaceBetween {
> > >   display: flex;
> > >   justify-content: center;
> > >   align-items: center;
> > > }
> > > 
> > > .textAlignRight {
> > >   text-align: right;
> > > }
> > > 
> > > .textAlignLeft {
> > >   text-align: left;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can absolutely ignore this suggestion - just giving my two cents!
> > 
> > 
> > ok, i dont hate this and a bit prettier
> 
> D'awwwww glad you didn't hate it haha. Don't forget your tests ;)

yea.... im working that now-

**Comment by deandreJones** [comment]
> > > May I suggest something? What you have is absolutely fine, but I think doing something similar to what is to the left of the PPM component would be awesome and a little more UI friendly.
> > > Something like: Screenshot 2024-01-03 at 1 29 33 PM
> > > If you want to do that, this is what the code looks like:
> > > ```
> > > {showShipmentWeight && (
> > >         <div className={styles.shipmentWeight}>
> > >           {isPPM && (
> > >             <div className={styles.spaceBetween}>
> > >               <div className={styles.textAlignRight}>
> > >                 <h6>{estimated}</h6>
> > >                 <h6>{actual}</h6>
> > >               </div>
> > >               <div className={styles.textAlignLeft}>
> > >                 <h6>
> > >                   <strong>{formatWeight(shipment.ppmShipment.estimatedWeight)}</strong>
> > >                 </h6>
> > >                 <h6>
> > >                   <strong>{formatWeight(shipment.calculatedBillableWeight)}</strong>
> > >                 </h6>
> > >               </div>
> > >             </div>
> > >           )}
> > >           {!isPPM && formatWeight(shipment.calculatedBillableWeight)}
> > >         </div>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And a little css:
> > > ```
> > > .spaceBetween {
> > >   display: flex;
> > >   justify-content: center;
> > >   align-items: center;
> > > }
> > > 
> > > .textAlignRight {
> > >   text-align: right;
> > > }
> > > 
> > > .textAlignLeft {
> > >   text-align: left;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can absolutely ignore this suggestion - just giving my two cents!
> > 
> > 
> > ok, i dont hate this and a bit prettier
> 
> D'awwwww glad you didn't hate it haha. Don't forget your tests ;)

Tests added, just for you

**Review by danieljordan-caci — APPROVED** [review]
LGTM (especially that beautiful test)

**Review by traskowskycaci — APPROVED** [review]

**Pull request merged**
