### PR TITLE
[MB-14914] Update nodejs to 18.x

### PR DESCRIPTION
**Pull request by reggieriser**
## Summary

This PR updates our node version from node 16.x to 18.x (see [node 17.x changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md) and [node 18.x changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md)).  Support for node 16.x [will be ending in September 2023](https://nodejs.org/ar/blog/announcements/nodejs16-eol/).

~~Note that I had to turn on node's `--openssl-legacy-provider` option via the `NODE_OPTIONS` environment variable to get things to compile successfully.  [Since node 17.x+ uses openssl 3.0](https://nodejs.org/es/blog/release/v17.0.0/#openssl-3-0), I believe this means we still have some dependencies using features from older openssl versions.~~  Update: We were able to isolate the problem to the `babel-loader` dependency and get that updated instead of enabling the legacy provider.

The corresponding PR from the `circleci-docker` repo is https://github.com/transcom/circleci-docker/pull/364.  ~~I'm using the hash from the branch's commit for now; once we sign off that everything is working, I'll merge the `circleci-docker` PR and update the hashes here to the `main` one.~~  This is done.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

You'll either need to do a `nodenv install` or update your nix config, depending on which setup you've got.  I would like to have at least one person with each test the PR.

Make sure all tests pass.  Also, just start up the app locally, click around, and verify that nothing odd seems to be happening.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

### CODE REVIEW

**Comment by duncan-truss** [comment]
I tried to run Cypress locally and ran into an issue that I think needs fixed.

I ran `make e2e_test_fresh` and then attempted to run all of the tests through the Cypress UI.

It looks like there's something in our plugins/index.js that is causing the error.  I'm guessing something with the filesystem writeFile methods that I remember reading about in the v17 and v18 changelogs.

Screenshot 2023-02-01 at 11 28 36 AM

```
**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/duncan/workspace/mymove/cypress/plugins/index.js`)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/duncan/workspace/mymove/cypress/plugins/index.js`)
    at Object.get (/Users/duncan/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1021:15)
    at EventEmitter.handleError (/Users/duncan/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:189:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/duncan/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
```

**Review by ahobson — APPROVED** [review]
🚀

**Comment by reggieriser** [comment]
> I tried to run Cypress locally and ran into an issue that I think needs fixed.
> 
> I ran `make e2e_test_fresh` and then attempted to run all of the tests through the Cypress UI.
> 
> It looks like there's something in our plugins/index.js that is causing the error. I know I saw a lot about filesystem changes in the v17 and v18 changelogs but I guess it could be something with our plugins too?

Good catch!  So I dug around a bit and I think the error being blamed on the plugins is incorrect.  See this PR (and linked issue): https://github.com/cypress-io/cypress/pull/19094

If I add the `NODE_OPTIONS=--openssl-legacy-provider` to the run-e2e-test script, then I don't get the error anymore.  We'd be using openssl just as we are today but could hopefully drop all this when we get completely on playwright.  I think that's the path of least resistance if we want to land this now.  Otherwise, we should probably just wait for all the playwright stuff to get merged.

**Comment by duncan-truss** [comment]
> Good catch! So I dug around a bit and I think the error being blamed on the plugins is incorrect. See this PR (and linked issue): [cypress-io/cypress#19094](https://github.com/cypress-io/cypress/pull/19094)
> 
> If I add the `NODE_OPTIONS=--openssl-legacy-provider` to the run-e2e-test script, then I don't get the error anymore. We'd be using openssl just as we are today but could hopefully drop all this when we get completely on playwright. I think that's the path of least resistance if we want to land this now. Otherwise, we should probably just wait for all the playwright stuff to get merged.

Nice find, I was looking some myself and didn't come across that yet.  Makes sense that it's the same problem you were troubleshooting before with Storybook build issues.

**Review by duncan-truss — APPROVED** [review]

**Review by mandaem — APPROVED** [review]
no more plugin error for cypress. LGTM

**Pull request merged**
