### PR TITLE
INT-B-19298

### PR DESCRIPTION
**Pull request by loganwc**
## Summary

Updated helpdesk url from mail.mil to army.mil

### How to test

1. Access the app and get a helpdesk error to appear

### CODE REVIEW

**Review by paulstonebraker — APPROVED** [review]

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
- update spectral count to pass `pre_test`

- you need to fix the failing client test on `MoveHome.test.jsx`
- line 1284 should be:
```
expect(wrapper.text()).toContain('Something went wrong downloading PPM AOA paperwork');
```

**Review by danieljordan-caci — APPROVED** [review]

**Comment by danieljordan-caci** [comment]
Oh and looks like another one in `index.test.jsx` for `Home` component:
line 655 needs to be:
```
screen.getByText(/Something went wrong downloading PPM AOA paperwork./, { exact: false }),
```

**Comment by danieljordan-caci** [comment]
DO YOU EVEN TEST BRO

**Review by danieljordan-caci — DISMISSED** [review]
FIX YA TESTS BRUH

**Comment by loganwc** [comment]
> FIX YA TESTS BRUH

Smh this test doesnt have anything to do with my changes

**Comment by danieljordan-caci** [comment]
Screenshot 2024-03-29 at 1 24 05 PM
Ohhhh but it does cause you updated the modal

**Comment by danieljordan-caci** [comment]
This might sound crazy, but... Would it be better to store that email as a variable instead of manually change it for each one?

**Comment by danieljordan-caci** [comment]
Maybe in `src/shared/constants.js`?

**Review by landan-parker-0 — APPROVED** [review]
I concur with @danieljordan-caci 
But, hotfix is a hotfix and it's showtime

**Comment by deandreJones** [comment]
> I concur with @danieljordan-caci But, hotfix is a hotfix and it's showtime

only a warmfix... we aint live yet

**Comment by deandreJones** [comment]
> Maybe in `src/shared/constants.js`?

id rather see it in DB or some param that doenst take code change to update

**Comment by danieljordan-caci** [comment]
> > Maybe in `src/shared/constants.js`?
> 
> id rather see it in DB or some param that doenst take code change to update

Yeah could be something to throw into `chamber`! Good idea.

**Pull request merged**
