### PR TITLE
[ MB-14300 ] - Performance Improvements to Move History Fetcher

### PR DESCRIPTION
**Pull request by kctruss**
## Summary

Made changes informed by the Execution Plan for move_history_fetcher.sql

- Update all _log CTEs to change JOIN on table_name to WHERE clauses
- Add index to audit_history on table_name
- Use subqueries to obtain duty location name instead of JOINs
- Change UNION ALLs to UNION and ~~remove DISTINCT from final query~~ Kept `DISTINCT` to resolve edge case duplicates.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office application
2. Login as any office user
3. Navigate to Move History
4. Verify that audit history displays as expected

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots
Screen Shot 2022-11-17 at 10 48 03 AM
Screen Shot 2022-11-17 at 10 48 58 AM

### CODE REVIEW

**Comment by duncan-truss** [comment]
@kctruss My understanding is you need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax

**Comment by kctruss** [comment]
> @kctruss My understanding is you may need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax

@duncan-truss the documentation warning makes it look like the `!` won't work. I noticed elsewhere in the CODEOWNERS file that we're setting directories to have "empty owners" which is what I was trying to do initially... I'll do some more digging.

**Comment by duncan-truss** [comment]
> > @kctruss My understanding is you may need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> 
> @duncan-truss the documentation warning makes it look like the `!` won't work. I noticed elsewhere in the CODEOWNERS file that we're setting directories to have "empty owners" which is what I was trying to do initially... I'll do some more digging.

Eeek I see what you mean now, whoops.  That part of the gitignore syntax is NOT supported in CODEOWNERS 🫤 Are you dismissing the Truss-DB group as a way to test if it gets reapplied with a commit? I can't remember for certain if it will auto-remove once it's been triggered initially.

**Comment by kctruss** [comment]
> > > @kctruss My understanding is you may need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> > 
> > 
> > @duncan-truss the documentation warning makes it look like the `!` won't work. I noticed elsewhere in the CODEOWNERS file that we're setting directories to have "empty owners" which is what I was trying to do initially... I'll do some more digging.
> 
> Eeek I see what you mean now, whoops 🤦‍♂️. That part of the gitignore syntax is NOT supported in CODEOWNERS 🫤 Are you dismissing the Truss-DB group as a way to test if it gets reapplied with a commit? I can't remember for certain if it will auto-remove once it's been triggered initially.

I was trying to change the order to see if listing the excluded file first was the issue, but after re-reading the documentation I am pretty sure that's not the problem so I reverted it:

```
# Order is important; the last matching pattern takes the most
# precedence.
```

I'm going to create a separate issue to troubleshoot this, since I figured changes wouldn't auto-remove the db-reviewers.

**Comment by duncan-truss** [comment]
> > > > @kctruss My understanding is you may need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> > > 
> > > 
> > > @duncan-truss the documentation warning makes it look like the `!` won't work. I noticed elsewhere in the CODEOWNERS file that we're setting directories to have "empty owners" which is what I was trying to do initially... I'll do some more digging.
> > 
> > 
> > Eeek I see what you mean now, whoops 🤦‍♂️. That part of the gitignore syntax is NOT supported in CODEOWNERS 🫤 Are you dismissing the Truss-DB group as a way to test if it gets reapplied with a commit? I can't remember for certain if it will auto-remove once it's been triggered initially.
> 
> I was trying to change the order to see if listing the excluded file first was the issue, but after re-reading the documentation I am pretty sure that's not the problem so I reverted it:
> 
> ```
> # Order is important; the last matching pattern takes the most
> # precedence.
> ```
> 
> I'm going to create a separate issue to troubleshoot this, since I figured changes wouldn't auto-remove the db-reviewers.

Cool, yea with the index migration added in this PR too that is going to require the Truss-DB group to be added.

**Comment by kctruss** [comment]
> > > > > > @kctruss My understanding is you may need to prefix the negation `!` before that sql file to exclude it https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> > > > > 
> > > > > 
> > > > > @duncan-truss the documentation warning makes it look like the `!` won't work. I noticed elsewhere in the CODEOWNERS file that we're setting directories to have "empty owners" which is what I was trying to do initially... I'll do some more digging.
> > > > 
> > > > 
> > > > Eeek I see what you mean now, whoops 🤦‍♂️. That part of the gitignore syntax is NOT supported in CODEOWNERS 🫤 Are you dismissing the Truss-DB group as a way to test if it gets reapplied with a commit? I can't remember for certain if it will auto-remove once it's been triggered initially.
> > > 
> > > 
> > > I was trying to change the order to see if listing the excluded file first was the issue, but after re-reading the documentation I am pretty sure that's not the problem so I reverted it:
> > > ```
> > > # Order is important; the last matching pattern takes the most
> > > # precedence.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm going to create a separate issue to troubleshoot this, since I figured changes wouldn't auto-remove the db-reviewers.
> > 
> > 
> > Cool, yea with the index migration added in this PR too that is going to require the Truss-DB group to be added.
> 
> Oh my gosh, you're right. So the exclusion could be working just fine. 🤦

For anyone following along, I created (and then closed) a [test PR](https://github.com/transcom/mymove/pull/9613) with just a change to the .sql file, and confirmed that the codeowners exclusion is working as expected. I just panicked early on this current PR because I'd already forgotten about the migration I added. 😬

**Review by donaldthai — APPROVED** [review]
praise: awesome improvements! 🚀

**Pull request merged**
