### PR TITLE
B 20639 b 20606 nts loa main

### PR DESCRIPTION
**Pull request by cameroncaci**
## Tickets
[B-20606](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A982379) https://github.com/transcom/mymove/pull/13399
[B-20639](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20639) https://github.com/transcom/mymove/pull/13372

## Summary

These tickets require real TGET data for testing, this merge to main is to allow said testing to main. After which it will be POA'd, then marked with a build number in order to release to production.

[Approval](https://caci-bits.slack.com/archives/C060PJCD1BQ/p1723492966376549)

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Looks like you are missing these commits from `B-20639` - looking [here](https://github.com/transcom/mymove/pull/13372/commits)
`enhanced handler comments and api docs`
`payload doc enhancement`
`add if not exists to script`

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Missing a few commits from int #13372 
image

**Comment by cameroncaci** [comment]
Tracking, thank you both. This appears to have popped up from me syncing both branches on the remote, I had changes that were not pushed from my local branches. Resolving

**Comment by traskowskycaci** [comment]
> Tracking, thank you both. This appears to have popped up from me syncing both branches on the remote, I had changes that were not pushed from my local branches. Resolving

Apologies, hadn't refreshed the page to see Daniel already called those out as missing

**Comment by cameroncaci** [comment]
Ready for review again

**Review by danieljordan-caci — APPROVED** [review]
much betta

**Review by deandreJones — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]

**Pull request merged**
