### PR TITLE
MAIN B-18629 Add Origin GBLOC To Move Screen (Backend)

### PR DESCRIPTION
**Pull request by taeJungCaci**
## [B-18629](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18629)

INT PR: https://github.com/transcom/mymove/pull/12229

## Summary

This is to add Origin Duty Location GBLOC alongside the rest of the move header information (origin and destination information. This information should be visible to all Government users regardless of the page that they are on (SC, TOO, TIO and QAE/CSR).

This is only the Backend portion of the code and I have added OriginDutyLocationGBLOC to show on the returned payload data when retrieving `Order` using `GET`. GET request for `Order` is being called in all of the areas mentioned above - so this will be used in the Frontend implementation of the code.

### How to test

1. Create a move.
2. As a SC, TOO, TIO or QAE/CSR -> Open up your browser Developer's Tool(Inspect tool) and open a move.
3. Use a network tab to search for `GET` request for `Order`(shown in image below).
4. Make sure you see `originDutyLocationGBLOC` in the preview tab and it matches the one you saw in the move queue table(where you search for moves).
5. See the images below for reference.

## Screenshots
image

image
image

### CODE REVIEW

**Comment by JamesHawks224** [comment]
verify rpt:
see attached.  had many issues.
[B18629-12235.verify_rpt.txt](https://github.com/transcom/mymove/files/14604991/B18629-12235.verify_rpt.txt)

**Comment by taeJungCaci** [comment]
> verify rpt: rpt fixed. looks "sane" now. [B18629-12235.verify_rpt.txt](https://github.com/transcom/mymove/files/14606919/B18629-12235.verify_rpt.txt)
> 
> ```
>     Same?         file
>      -      n     pkg/gen/ghcapi/embedded_spec.go
>      y      -     pkg/gen/ghcmessages/order.go
>      -      n     pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
>      -      n     pkg/handlers/ghcapi/orders_test.go
>      -      n     swagger-def/ghc.yaml
>      -      n     swagger/ghc.yaml
> ```

All changes are correct. It is showing `n` because all the content in the file do not match.

**Review by brooklyn-welsh — APPROVED** [review]
LGTM ✅

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Pull request merged**
