### PR TITLE
Main b 17960 UI fixes

### PR DESCRIPTION
**Pull request by brooklyn-welsh**
## INT PR
#12324 

## Summary

Another quick fix that adds the missing "Authorized Receipt Total" field at the end of the receipt/weight ticket summary screen. The total does not include any excluded or rejected receipts, and per government request, does not include SIT/Storage receipts.

To test, make a PPM closeout shipment with one of each type expense receipt. When at the end of the screen, you should notice that the storage receipt is not added onto the total.

You can also go back and test that exclusions/rejections are not included in the total amount by rejecting/excluding certain receipts.

### CODE REVIEW

**Comment by taeJungCaci** [comment]
Will this be following the new process where the POA demo will be done in Integration? and this should get merged after POA?

**Comment by brooklyn-welsh** [comment]
> Will this be following the new process where the POA demo will be done in Integration? and this should get merged after POA?

Good point, I assume so but can confirm during standup this morning.

**Comment by deandreJones** [comment]
since we have main- accepted as is
PO acceptance will be from IntegrationTesting(loadtest)

**Review by JamesHawks224 — APPROVED** [review]
LGTM

**Comment by brooklyn-welsh** [comment]
Closing until integration has passed POA. Will re-open then.

**Comment by JamesHawks224** [comment]
Verify rpt:
Looks good.  no issues.
[B17960-12326.verify_rpt.txt](https://github.com/transcom/mymove/files/14873208/B17960-12326.verify_rpt.txt)

**Review by taeJungCaci — APPROVED** [review]
lgtm!

**Pull request merged**
