### PR TITLE
Update email: ppm has been processed

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Testing Steps I took
1. Start the local server with the following command:
```
EMAIL_BACKEND=ses AWS_REGION=us-gov-west-1  aws-vault exec transcom-gov-dev -- make server_run
```
2. Start the local client.
3. As a Service Member, create a new PPM move and send to Service Counsellor. Make sure you try this at least once with one of each of the following categories:
- Marines, Navy, or Coast Guard
- Army
- Air Force or Space Force

_Note: Make sure you use an email address that you have access to and have a checkmark in the "Email" checkbox for preferred contact method._

4. As Service Counsellor, update the orders and approve the move and be sure to try at least one time with Actual Expense Reimbursement checked and at least one time with it unchecked.
5. As the Service Member, make sure to finish the process to that it shows up in the PPM Closeout Queue for the Service Counsellor role.
6. As a Closeout Counsellor, make sure you can see the move under the PPM Closeout tab and open it. You may have to click on the "Review Documents" button and approve any of the items that need approval.
7. Open your email and you should see several emails.. one of which will have the subject:
```
Your Personally Procured Move (PPM) closeout has been processed and is now available for your review.
```

You should see email body that follows the appropriate conditions in the Agility Ticket [B-21525](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21525)

___
# Screenshots of the email bodies
## Navy, Marine Corps, Coast Guard (AER)
Screenshot 2024-11-01 at 11 02 09 AM

## Nave, Marine Corps, Coast Guard (not AER)
Screenshot 2024-11-01 at 10 59 49 AM

## Army (AER)
Screenshot 2024-11-01 at 11 09 29 AM

## Army (not AER)
Screenshot 2024-11-01 at 11 07 31 AM

## Air Force, Space Force (AER)
Screenshot 2024-11-01 at 11 15 27 AM

## Air Force, Space Force (not AER)
Screenshot 2024-11-01 at 11 16 43 AM

### CODE REVIEW

**Review by brooklyn-welsh — APPROVED** [review]
Looks like everything was changed according to our Slack conversation.

Tested with each branch and with "IsActualExpenseReimbursement" turned on and off, got expected email results.

LGTM ✅

**Comment by WeatherfordAaron** [comment]
Test coverage was holding me hostage even though everything I added is covered in tests (from what I could tell) so I'm adding test coverage for one of the red items (Feedback.jsx)

**Comment by WeatherfordAaron** [comment]
I was finally able to confirm that the layout looks like the attachments on the Agility ticket
Screenshot 2024-10-31 at 7 44 11 PM

**Comment by KonstanceH** [comment]
> I was finally able to confirm that the layout looks like the attachments on the Agility ticket Screenshot 2024-10-31 at 7 44 11 PM

The "This will allow you to edit your voucher, and complete and sign DD Form 1351-2" should be on another line.
I know we talked about the "Note: Not all claimed expenses may have been accepted..." not being added but because its in the Agility PDF I think this is worth asking Gary or Brittney about.
Other than those things this Army email without an Actual Expense Reimbursement looks good.

**Review by taeJungCaci — APPROVED** [review]
LGTM

**Review by brooklyn-welsh — APPROVED** [review]
LGTM

**Pull request merged**
