### PR TITLE
B 18823 ghc create requested office user int

### PR DESCRIPTION
**Pull request by cameroncaci**
## Summary

Db level unique constraints were not getting passed back from the API as detailed errors, and instead was sending back a blank `500` error code, as detailed in the issue ticket.

[First Integration PR](https://github.com/transcom/mymove/pull/12199)

The validation errors were not all pooled together as this is a DB level constraint error, not a service level.

The quotation mark changes in swagger-def come from merging the main base.

### How to test

1. Import latest ghc.yaml into postman
2. Grab a transportation office id from the transportation-offices GHC endpoint. Grab the “Id”, not the “Address -> Id”. There are 2 Ids per response back, grab the root one.
3. Login to office as any office user
4. Open network tab in browser dev tools and refresh page
5. Select latest network request, select headers
6. Grab ‘X-Csrf-Token’ value from the headers
7. Open postman
8. Navigate to MilMove GHC API requested-office-users “POST Create an Office User”
9. Navigate to Headers and add a new header, ‘X-Csrf-Token’, past your value in the value box
10. Update the URL to be respective of your environment, such as `officelocal:3000/ghc/v1/requested-office-users`
11. Update the body to be something like this (Update the transportationOfficeId:
```
{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe12@example.com",
  "telephone": "555-555-5555",
  "transportationOfficeId": "5a3388e1-6d46-4639-ac8f-a8937dc26938",
  "roles": [
    {
      "name": "Transportation Ordering Officer",
      "roleType": "transportation_ordering_officer"
    }
  ],
  "edipi": “1234456789",
  "otherUniqueId": "2234567892"
}
```
12. Now, submit it again. You should receive a response back from the server that the email is already taken
13. Change the email and send again, now the server should say it's your EDIPI
14. Change the EDIPI and send again, now it should say it's your otherUniqueID

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
So are `edipi` & `otherUniqueId` unique in the database? I'm not seeing that they are.

**Comment by TevinAdams** [comment]
> So are `edipi` & `otherUniqueId` unique in the database? I'm not seeing that they are.

They are in the office_users table.

**Comment by TevinAdams** [comment]
Are you not returning the invalid_fields we discussed in slack? When I send a post without email:
image

I get no invalid_fields:
image

**Comment by cameroncaci** [comment]
> Are you not returning the invalid_fields we discussed in slack? When I send a post without email: image
> 
> I get no invalid_fields: image

You have to provide an email to hit the invalid fields from the service object

**Comment by danieljordan-caci** [comment]
> > So are `edipi` & `otherUniqueId` unique in the database? I'm not seeing that they are.
> 
> @danieljordan-caci I think they are in the office_users table.

Oh you're right. I was thinking of the `service_members` table. Thanks.

**Review by TevinAdams — APPROVED** [review]

**Review by danieljordan-caci — APPROVED** [review]
LGTM!

**Pull request merged**
