### PR TITLE
B-21667 & B-21487 MAIN

### PR DESCRIPTION
**Pull request by traskowskycaci**
> [!IMPORTANT]  
> Please ensure the upstreams are merged into main first:
> [B-21374](https://github.com/transcom/mymove/pull/14121)
> [B-21375](https://github.com/transcom/mymove/pull/14124)
> [B-21376](https://github.com/transcom/mymove/pull/14100)

This main branch contains commits from all the below integration PRs. I combined B-21667 and B-21487, because the rename of a variable in B-21487 was the cause of some of the issues needing fixed. 

## [B-21667 I-13574 INT PR](https://github.com/transcom/mymove/pull/14277)

### CODE REVIEW

**Comment by cameroncaci** [comment]
Heads up I resolved a lot of these conflicts in the upstream @traskowskycaci , don't worry about resolving them here. Once the upstream is merged the fix will be in the git history

**Comment by cameroncaci** [comment]
Alternatively you can merge the upstream into your PR now and it'll resolve them like that, I did that just now with https://github.com/transcom/mymove/pull/14342

**Comment by traskowskycaci** [comment]
> Alternatively you can merge the upstream B-21374 into your PR now and it'll resolve them like that, I did that just now with #14342

I'll merge in 21374 - just brought it in yesterday to resolve some test fails so shouldn't be too bad! Thanks for the heads up @cameroncaci

**Comment by cameroncaci** [comment]
upstream to this pr is next, advise merging it in to help resolve the current conflicts

**Review by cameroncaci — APPROVED** [review]
Both tickets POA'd. All three issue tickets present. Commit shas are GOOD. WHEEEW 🚀

**Review by TevinAdams — APPROVED** [review]

**Pull request merged**
