### PR TITLE
B 21522 int

### PR DESCRIPTION
**Pull request by deandreJones**
## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Create a new move- take note of the pickup location zip and find the gbloc associated to it in DB (postal_code_to_gbloc) choose a duty location that is associated to a different gbloc (look up duty location address, grab the zip and reference postal_code_to_gbloc to be sure
2. log in as SC - TOO, approve it- then access it as prime- create a payment request for MMF (or any but that is easiest)
3. login as TIO -- approve the payment_request
4. grab the payment request number 
5. run  `go run ./cmd/generate-payment-request-edi/ --payment-request-number 9641-6802-1`
6. review the 858 string output - look for the `N1 *BY `segment validate the last part of it is the GBLOC of the pickup location and not the gbloc of the origin duty location
```
ISA*00*0084182369*00*0000000000*ZZ*MILMOVE        *12*8004171844     *241015*1351*U*00401*152229978*0*T*|
GS*SI*MILMOVE*8004171844*00010101*0000*152229978*X*004010
ST*858*0001
BX*00*J*PP*2803-4667*HSFR**4
N9*CN*2803-4667-1**
N9*CT*TRUSS_TEST**
N9*1W*qwsdbjjz, zrwcvcustomer**
N9*ML*E_1**
N9*3L*ARMY**
N9*4A*7833288121**
N9*CMN*HWWKXQ**
C3*USD***
G62*10*20200315**
G62*76*20200316**
G62*86*20200316**
N1*BY*RLjHwFM4jc, IA 50309*92*KKFA
N1*SE*Prime*2*HSFR
N1*ST*Fort Eisenhower, GA 30813*10*CNNQ
N4*Fort Eisenhower*GA*30813*US**
PER*CN**TE*7067914184
N1*SF*RLjHwFM4jc, IA 50309*10*KKFA
N3*987 Other Avenue*P.O. Box 1234
N4*Des Moines*IA*50309*US**
PER*CN**TE*5105555555
HL*1**9
N9*PO*2803-4667-212bfa63**
L5*1*DLH*TBD*D**
L0*1*354.000*DM*1400.000*B******L
L1*1*1400.00*LB*80000
FA1*DZ
FA2*TA*E01A
HL*2**9
N9*PO*2803-4667-ae1f5a65**
L5*2*FSC*TBD*D**
L0*2*354.000*DM*1400.000*B******L
L1*2*1400.00*LB*10700
FA1*DZ
FA2*TA*E01A
HL*3**9

```
### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Review by traskowskycaci — APPROVED** [review]
Seeing the glboc of the pickup for the N1 BY segment!

**Review by danieljordan-caci — APPROVED** [review]
A test and everything. Looks good on my end.

**Review by cameroncaci — APPROVED** [review]
Meets AC and code looks good

**Comment by deandreJones** [comment]
> A test and everything. Looks good on my end.

Just for you my homie

**Pull request merged**
