### PR TITLE
B 18318 add seed data for multiple moves INT

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

This work is to populate the dev db with multiple move seed data. Open to suggestions on what to add/modify to make the scenarios realistic.

### How to test

1. Run `make db_dev_fresh` to populate the dev db with data.

2. Poke around in the database, making sure you can see the moves codes below. You can use this query to see all of the moves: `"locator" LIKE 'MMOVE%'`

3. Make sure that the below move groupings are associated with one service member, each having three moves.

4. Login as a customer and verify you can see the following accounts to log in as:
- multiplemoves@HHG_PPM.com
     - Moves: MMOVEA, MMOVEB, MMOVEC
     - Service member affiliation: Army
     - Should have one service member ID for all three moves
- multiplemoves@HHG_PPM_NTS.com
     - Moves: MMOVED, MMOVEE, MMOVEF
     - Service member affiliation: Air force
     - Should have one service member ID for all three moves
- multiplemoves@NTS_HHG.com
     - Moves: MMOVEG, MMOVEH, MMOVEI
     - Service member affiliation: Navy
     - Should have one service member ID for all three moves
- multiplemoves@PPM.com
     - Moves: MMOVEJ, MMOVEK, MMOVEL
     - Service member affiliation: Coast Guard
     - Should have one service member ID for all three moves
image

5. Login as a TOO and click on any of the moves you see with multiple move codes. Ensure you can see the expected shipments for that move code.

6. Login as a service counselor and click on any of the moves you see with multiple move codes. Ensure you can see the expected information for that move code.

Note: I spent quite a bit of time trying to pass in a custom origin duty location and was unable to get it working. These moves are all in KKFA for now. If we want to expand that to other GBLOCs, I will likely need some assistance on figuring that out.

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
> Fails
> 🚫	
> One of these files have been edited:
> 
> * `pkg/testdatagen/scenario/devseed.go`
> * `pkg/testdatagen/scenario/subscenarios.go`
> * `cmd/generate-test-data/main.go`
> 
> Please undo changes to these files as we have deprecated `devseed` data functions from MilMove entirely and will be deleting this code on the 8th of November 2023.
> 
> View the [ADR 0083](https://transcom.github.io/mymove-docs/docs/adrs/deprecating-devseed-scenarios) for more information
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [5c4a809](https://github.com/transcom/mymove/commit/5c4a8097b3422c1dca517c65a82851b7ef77f6d2)

HA this error is hilarious

**Comment by deandreJones** [comment]
> > Fails
> > 🚫
> > One of these files have been edited:
> > 
> > * `pkg/testdatagen/scenario/devseed.go`
> > * `pkg/testdatagen/scenario/subscenarios.go`
> > * `cmd/generate-test-data/main.go`
> > 
> > Please undo changes to these files as we have deprecated `devseed` data functions from MilMove entirely and will be deleting this code on the 8th of November 2023.
> > View the [ADR 0083](https://transcom.github.io/mymove-docs/docs/adrs/deprecating-devseed-scenarios) for more information
> > Generated by 🚫 [dangerJS](https://danger.systems/js) against [5c4a809](https://github.com/transcom/mymove/commit/5c4a8097b3422c1dca517c65a82851b7ef77f6d2)
> 
> HA this error is hilarious

lol- yea- 
i remember asking truss about this, they said it was some arbitrary date to start using another method for populating data- its really irrelevant and i will remved this depriecation warning

**Comment by traskowskycaci** [comment]
> > HA this error is hilarious
> 
> lol- yea- i remember asking truss about this, they said it was some arbitrary date to start using another method for populating data- its really irrelevant and i will remved this depriecation warning

Sounds good!

**Review by danieljordan-caci — APPROVED** [review]
Can see the moves in the multiple move dashboard as well! Great work! LGTM!
Screenshot 2024-02-08 at 12 57 43 PM

**Review by loganwc — APPROVED** [review]

**Comment by traskowskycaci** [comment]
This branch just wants to fight today. Passing server tests locally, haven't figured out why pre_test is failing

**Comment by danieljordan-caci** [comment]
> > Fails
> > 🚫
> > One of these files have been edited:
> > 
> > * `pkg/testdatagen/scenario/devseed.go`
> > * `pkg/testdatagen/scenario/subscenarios.go`
> > * `cmd/generate-test-data/main.go`
> > 
> > Please undo changes to these files as we have deprecated `devseed` data functions from MilMove entirely and will be deleting this code on the 8th of November 2023.
> > View the [ADR 0083](https://transcom.github.io/mymove-docs/docs/adrs/deprecating-devseed-scenarios) for more information
> > Generated by 🚫 [dangerJS](https://danger.systems/js) against [bcc876c](https://github.com/transcom/mymove/commit/bcc876c06596e5ccc16924e381b7ff66411d9f59)
> 
> @deandreJones why is this still showing despite you removing it with this PR?: #11968

Ohhh it is cause you merged it into `main` and not `integrationTesting`

**Comment by danieljordan-caci** [comment]
@deandreJones should @traskowskycaci remove these lines of code in `dangerfile.ts` in this PR?

```
  const deprecatedDevSeedFiles = danger.git.fileMatch(
    'pkg/testdatagen/scenario/devseed.go',
    'pkg/testdatagen/scenario/subscenarios.go',
    'cmd/generate-test-data/main.go',
  );

  if (deprecatedDevSeedFiles.modified) {
    fail(`One of these files have been edited:
* ${'`'}pkg/testdatagen/scenario/devseed.go${'`'}
* ${'`'}pkg/testdatagen/scenario/subscenarios.go${'`'}
* ${'`'}cmd/generate-test-data/main.go${'`'}
Please undo changes to these files as we have deprecated
${'`'}devseed${'`'} data functions from MilMove entirely and will be
deleting this code on the 8th of November 2023.
View the [ADR 0083](https://transcom.github.io/mymove-docs/docs/adrs/deprecating-devseed-scenarios) for more information`);
  }
```

**Comment by deandreJones** [comment]
need to merge main back into this

**Comment by danieljordan-caci** [comment]
> need to merge main back into this

but it's a PR into `integrationTesting`?

**Comment by deandreJones** [comment]
> > need to merge main back into this
> 
> but it's a PR into `integrationTesting`?

main is the source of truth- branches should always stay up with main

**Comment by deandreJones** [comment]
..shoudlnt

**Comment by deandreJones** [comment]
unless there are other changes in that file that conflict

**Comment by traskowskycaci** [comment]
> unless there are other changes in that file that conflict

I'll merge main into my B-18318-Add-seed-data-for-multiple-moves main branch, then merge that main branch into this one. 

> unless there are other changes in that file that conflict

Merging main in now

**Pull request merged**
