### PR TITLE
B 21682 store total dependents int

### PR DESCRIPTION
**Pull request by cameroncaci**
## Summary

Adds service logic validation on ghc entitlements to calculate sum of total dependents. This field is currently not used _anywhere_ besides in API payloads. Now it will reflect the sum when dependent amounts are present.

Calculated column was attempted but pop fought me on it when attempting to insert `nil` as `null` into a calculated, read-only column

### How to test

1. Set UB FF to true
2. Set a duty location address as OCONUS
3. Login as a customer
4. Create a new OCONUS order with dependents under 12 / 12 and older. Any amount greater than 0 for either of them works, or 2 under 12 and 0 12 and over sort of thing
5. Create a new shipment of HHG or UB (Doesn’t matter which)
6. Submit your order
7. Grab your order UUID
8. Log into office local
9. Open postman and do a GET request for officelocal:3000/orders/:orderID

## Screenshots
Screenshot 2024-11-20 at 3 36 02 PM

Screenshot 2024-11-20 at 4 10 10 PM

### CODE REVIEW

**Review by danieljordan-caci — CHANGES_REQUESTED** [review]
Created my orders and submitted my move as a customer & fetched from office API

Screenshot 2024-11-21 at 2 10 17 PM

Updated my orders as a customer and went to call the endpoint again to see if it updated and it has disappeared. Any idea why?

Screenshot 2024-11-21 at 2 12 20 PM

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Seeing the orders.entitlements.total_depedents field as null at the point of the TOO submitting the move. Then when calling the getMoveTaskOrder endpoint, since it's null, that field isn't included. If I edit the number of dependents as an office user, then the field gets populated.

Steps to reproduce
1. Create a new move as a customer, I did 1 for the first dependents age group and 0 for the second
2. I made a UB shipment only going from AK to KS
3. Get the move through the SC and the TOO steps to make it available to the prime
4. Call http://primelocal:3000/prime/v3/move-task-orders/moveId and see that totalDependents is not in the response
5. Check the DB and see that total_dependents is null
6. Edit the number of dependents as an office user
7. Check the DB and see that total_dependents is no longer null
8. Check the getMoveTaskOrder endpoint again and see it now returned in the response

**Comment by cameroncaci** [comment]
@traskowskycaci @danieljordan-caci 
Try and break it this time, switched it to be a generated column with our handy dandy ORM setting it to read only 💪🏻

**Review by traskowskycaci — APPROVED** [review]
Working great for me now! I tested prime v1, v2, and v3 responses for getMoveTaskOrder and was able to see it on intial creation and get updated when the office user edited.

**Review by danieljordan-caci — APPROVED** [review]
You got a conflict, but all testing normal over here. Seeing it in all prime endpoints. Noice.

**Review by TevinAdams — APPROVED** [review]
Worked
image

**Review by begrohmann — APPROVED** [review]

**Comment by cameroncaci** [comment]
I am confirming here the 2 failing steps are flaky for CircleCI build 81081

**Pull request merged**
