### PR TITLE
Install react-table v7.0

### PR DESCRIPTION
**Pull request by Ronolibert**
## Description
Add react-table 7.0 to the project now that we have react-table-6 installed to keep the office queue looking the same

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References
* [Jira story](https://dp3.atlassian.net/browse/MB-1661) for this change

### CODE REVIEW

**Comment by tinyels** [comment]
I was expecting us to have some example code where we are using this component. Do we have any places where we think it is going to be used in the new system?

**Comment by gidjin** [comment]
There were 2 stories in the current sprint that mentioned tables, MB-1805 and MB-1811 that we thought might benefit from this, which is where I was thinking we'd get examples. Though I'm open to other options.

**Comment by Ronolibert** [comment]
@tinyels This should be coming in upcoming PRs. We're just waiting on design to tell us which tables they want us to get started on

**Comment by chrisgilmerproj** [comment]
Honestly I'd prefer to wait to add new dependencies unless we're actively using them. Adding them early without the code it supports puts us in a position of maybe dragging around this extra dep for a while and possibly never using it. 

Also, adding dependencies has a cost. It increases build time and also the size of the docker containers, which in the end costs actual money. So holding on this for now until the other PRs are ready is likely the best way forward.

**Comment by gidjin** [comment]
Let's close this PR and revisit once we have a table to implement this with.

**Comment by gidjin** [comment]
I'm closing this in favor of adding this package once we have a table to add as an example. Thanks for the work you put in @Ronolibert !

**Pull request closed without merging**
