### PR TITLE
B-21375 UB Allowance Calculation - MAIN

### PR DESCRIPTION
**Pull request by traskowskycaci**
> [!IMPORTANT]  
> Please ensure the upstream, [B-21374](https://github.com/transcom/mymove/pull/14121), is merged into main first

## [B-21375 I-13559 INT PR](https://github.com/transcom/mymove/pull/14253)

This PR contains the commits from the two integration PRs above.

### CODE REVIEW

**Comment by cameroncaci** [comment]
awaiting upstream

**Comment by cameroncaci** [comment]
Upstream merge will solve conflicts, re https://github.com/transcom/mymove/pull/14288#issuecomment-2524082037

**Comment by cameroncaci** [comment]
main is locked this morning

**Review by cameroncaci — APPROVED** [review]
Commits are good

**Comment by cameroncaci** [comment]
main unlocked

**Comment by TevinAdams** [comment]
Whats the reason for the change differences in pkg/models/entitlements_test.go?
image

**Review by danieljordan-caci — APPROVED** [review]
Commits & code looks good!

**Comment by traskowskycaci** [comment]
> Whats the reason for the change differences in pkg/models/entitlements_test.go? image

@TevinAdams not sure why they'd pop up as new, but just double checked that integration is the same as main here: https://github.com/transcom/mymove/blob/integrationTesting/pkg/models/entitlements_test.go

**Pull request merged**
