### PR TITLE
[ MB-14723 ] Turn on linter for Admin API

### PR DESCRIPTION
**Pull request by rogeruiz**
## Summary

This patch just turns on the linter. This **must be** merged after Admin UI
description refactors #10137 gets merged into the default branch.

### CODE REVIEW

**Review by felipe-lee — APPROVED** [review]
🎉 LGTM and the other PR has merged, just need is3 approval now.

**Comment by rogeruiz** [comment]
@felipe-lee are you okay with closing and re-opening this yourself so I can review this? That way we can get this turned on 🙃 thanks!

**Comment by felipe-lee** [comment]
> @felipe-lee are you okay with closing and re-opening this yourself so I can review this? That way we can get this turned on 🙃 thanks!

Yeah that works for me 😅

**Comment by felipe-lee** [comment]
@rogeruiz, here you go: #10177

**Comment by rogeruiz** [comment]
closed by #10177

**Pull request closed without merging**
