### PR TITLE
MB-6299 TOO status queue filter shows SUBMITTED not New Move when selected

### PR DESCRIPTION
**Pull request by jenniferlynparsons**
## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_run
make office_client_run
```
1. Log in as TOO and view Move queue
2. Filter the queue by "New Move" status
3. Note Filter placeholder is "New Move", not SUBMITTED.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6299) for this change

## Screenshots

Screen Shot 2021-01-28 at 9 33 29 AM

### CODE REVIEW

**Review by monfresh — APPROVED** [review]
LGTM. I tested it locally and I can see the fix. Thanks for adding the tests! One visual bug I noticed is if you check multiple checkboxes in the Status filter, and then start unchecking them, the placeholder text starts looking strange.

**Review by brooksr4 — APPROVED** [review]
Looks good here

**Comment by jenniferlynparsons** [comment]
@monfresh I do see the issue as well. It seems to be a quirk in CSS where the span wrapping each filter name is being repositioned in an unexpected way. I fiddled with the css and finding the correct combination of declarations to fix this may not be worth the effort at this time.

**Comment by jenniferlynparsons** [comment]
FWIW, the CSS issue also seems to be inconsistent. Occurs less often when dev console is closed (on Chrome) and only seems to happen after a number of checking/unchecking cycles.

**Pull request merged**
