### PR TITLE
B-21537-INT PPM Closeout Queue Management

### PR DESCRIPTION
**Pull request by paulstonebraker**
## Summary

PPM Closeout Queue, queue management work. In addition to adding functionality for work assignment to the PPM Closeout queue, I refactored the code in `model_to_payload` because it was bugging me. Changes include using helper functions to make the QueueMoves function (hopefully) more readable, and moving logic up so when we create a ghcmessages.QueueMove, all the data is set.  Please feel free to give feedback on if I made the code worse - can change it back.

Lots of complicated rules for queue management, I'll list them all for testing, but new logic is all the stuff related to PPM closeout.

### Across all queues
-if a user is NOT a supervisor, they can self assign to any move that is UNASSIGNED. If a move is already ASSIGNED, the aforementioned NON SUPERVISOR user cannot assign/reassign/unassign that move

### Supervisor rules
-SC Counseling queue
--Move is counseled by SC's transportation office: assign/unassign/reassign freely to any SC at their office
--Move is NOT counseled by SC's transportation office: cannot assign/unassign/reassign freely; can only self assign if move is unassigned
-SC Closeout queue
--Supervisor is NAVY, MARINE, USCG: assign/unassign/reassign freely to any SC at their office, for any move in their queue
--Supervisor is NOT NAVY, MARINE, USCG, and move's closeout office is the SC's transportation office: assign/unassign/reassign freely to any SC at their office
--Supervisor is NOT NAVY, MARINE, USCG, and move's closeout office is the NOT SC's transportation office: cannot assign/unassign/reassign freely; can only self assign if move is unassigned
-TOO queue
--assign/unassign/reassign freely to any TOO at their office, for any move in their queue
-TIO queue
--assign/unassign/reassign freely to any TIO at their office, for any payment request in their queue

Okay, now that you read the rules once, and they all make sense, here is how I would test it:

Non Navy/Marine/USCG:
1. first, if you have not already, create a bunch of SC users at a transportation office of your choice that provides services counseling, and a second transportation office of your choice that provides closeout. At least one SC non supervisor, and one SC supervisor at each.
2. Create a non Navy, Marine, or Coast Guard move with a PPM, and select the counseling office and closeout office you have users for.
3. In the counseling queue, ensure that the rules are followed: non supervisor SC should only see themself in dropdowns, and supervisor SC should see all the SCs at their office for moves counseled by their office
4. Do the necessary steps to get a PPM to the closeout queue, and when viewing it, make sure the rules are followed: non supervisor SC should only see themself in dropdowns, and supervisor SC should see all the SCs at their office for moves closed out by their office

Navy/Marine/USCG:
1. First, if you have not already, create a bunch of SC users at the following transportation offices, similar to step 1 above: PPM Processing (TVCB) - USMC, USN PPM Processing (NAVY) - USN, PPM Processing (FINCEN) - USCG
2. Create Navy, Marine, or Coast Guard moves with PPMs.
3. Do the necessary steps to get a PPM to the closeout queue, and when viewing it, make sure the rules are followed: non supervisor SC should only see themself in dropdowns, and supervisor SC should see all the SCs at their office for moves closed out by their office

Try and break it! Also access the HQ role and make sure the queues all work

### CODE REVIEW

**Comment by pambecker** [comment]
The Assigned column sort and filter are blowing up if logged in as a Navy/Marine/USCG Service Counselor.  Works fine for a regular affiliation SC user.

**Review by pambecker — APPROVED** [review]

**Review by loganwc — CHANGES_REQUESTED** [review]
Assigned myself to a move as a non supervisor, logged in as a supervisor and that individual was not showing as assigned to the move.
Screenshot 2024-11-13 at 7 46 05 PM
Screenshot 2024-11-13 at 7 46 16 PM

**Comment by paulstonebraker** [comment]
> Assigned myself to a move as a non supervisor, logged in as a supervisor and that individual was not showing as assigned to the move. Screenshot 2024-11-13 at 7 46 05 PM Screenshot 2024-11-13 at 7 46 16 PM

Brother are you using seeded data?? SMH

**Comment by loganwc** [comment]
> Assigned myself to a move as a non supervisor, logged in as a supervisor and that individual was not showing as assigned to the move. Screenshot 2024-11-13 at 7 46 05 PM Screenshot 2024-11-13 at 7 46 16 PM

Dummy data is dumb

**Review by loganwc — APPROVED** [review]

**Pull request merged**
