### PR TITLE
B 19137 payment requests billable weight param changes int

### PR DESCRIPTION
**Pull request by cameroncaci**
[B-19137](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A922171)

[First Pull Request](https://github.com/transcom/mymove/pull/12340)

# Summary
The AC was adjusted after this ticket reached testing to now allow for shuttle payment requests for shipment actual weights under 500 lbs, see in the first pull request where shuttle is explicitly denied (Prior AC, now removed from ticket). Additionally, adjusted the frontend for shuttle payment calculations to display the weight of either the shipment, or shuttle service item, rather than just the weight it was billed at.

Shuttle service items can now be created on mto shipments with actual weights under 500 pounds and will round up to be billed as if they were 500 lbs.

# Steps to reproduce

1. Login as prime sim
2. Select any move
3. Create a new HHG shipment with an estimated weight of 300
4. As the prime, update the shipment and give it an actual weight of 250
5. Create service items for DOSHUT and DDSHUT (Do not provide any optional weights, we want it to inherit the shipment weight)
6. Login as TOO -> Approve shipment, DOSHUT, and DDSHUT
7. Login as Prime -> Navigate to move
8. Create payment request on your newly approved HHG shipment for DOSHUT and DDSHUT (Don't provide a weight billed)
9. It should create successfully with no error
10. Login as TIO -> Navigate to move
11. Your payment request should have a billable weight calculation of “5 cwt” while showing an “original” of 250 lbs, estimated will be empty because the shuttle service item technically did not receive any estimated weight cause none were provided.
12. Now, we're going to want to create new DOSHUT and DDSHUT service items. If you want, reject the previous 2 you just made just so no confusion occurs later on.
13. Login as prime -> navigate to move -> create new DOSHUT and DDSHUT service items, but this time WITH the optional weights. Please provide optional weights under 500 but not 250.
14. Login as TOO -> Approve the 2 new shuttles
15. Login as prime -> Create payment requests on the 2 shuttles, but don't provide a "Weight Billed" because we don't want a partial payment
16. Login as TIO -> Verify that the payment request for these 2 shuttles have the same price as the last two, but if you open up the calculations you'll see weights different from the shipment (But still under 500), and also still being billed as if it were 5 cwt.

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
At what step here do we need to add the DOSHUT and DDSHUT service items? I could be doing things out of order and creating problems for myself lol.

I am doing it this way:
1. creating the HHG shipment with 300 lbs est
2. requesting DOSHUT
3. requesting DDSHUT
4. updating HHG shipment to 250 lbs actual as prime
5. Logging in as TOO and approving shipment
6. Still as TOO, approving the DOSHUT and DDSHUT service items on the MTO page
7. Trying to create a payment request on the DOSHUT and DDSHUT service items (at the same time) and am getting a 500 error of:
```
2024-04-08T21:46:26.205Z        ERROR   primeapi/payment_request.go:86  Error creating payment request  {"git_branch": "B-18800-county-with-address-response-INT", "git_commit": "f7c25f4ed79b009a51bbe7103baf6460ab19ef03", "host": "officelocal:3000", "milmove_trace_id": "15a10b91-9b13-4582-9d2b-c7478e6843e9", "session_id": "3NPnI3m3YUh4V3EkegXOmaU-7crhcInbKzZOOm6ImZg", "error": "Failed to create service item param for param key <WeightOriginal>  MTO ID <9c7b255c-2981-4bf8-839f-61c7458e2b4d> paymentRequestID <00000000-0000-0000-0000-000000000000> MTO Service item ID <97a19579-d7ff-4d83-baa7-02b2f61961bd> RE Service Item Code: <DOSHUT> Name: <Domestic origin shuttle service> err: Failed to lookup ServiceParamValue for param key <WeightOriginal>  err:  failed ServiceParamValue WeightOriginalLookup with error could not find actual weight for MTOServiceItemID [97a19579-d7ff-4d83-baa7-02b2f61961bd]"}
github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:86
github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
2024-04-08T21:46:26.205Z        ERROR   primeapi/payment_request.go:130 Payment Request {"git_branch": "B-18800-county-with-address-response-INT", "git_commit": "f7c25f4ed79b009a51bbe7103baf6460ab19ef03", "host": "officelocal:3000", "milmove_trace_id": "15a10b91-9b13-4582-9d2b-c7478e6843e9", "session_id": "3NPnI3m3YUh4V3EkegXOmaU-7crhcInbKzZOOm6ImZg", "payload": {"moveTaskOrderID":"9c7b255c-2981-4bf8-839f-61c7458e2b4d","serviceItems":[{"id":"97a19579-d7ff-4d83-baa7-02b2f61961bd","params":null},{"id":"29234540-c62c-4a8b-905f-7192cb0158e3","params":null}]}}
github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:130
github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
[POP] 2024/04/08 21:46:26 sql - ROLLBACK Transaction --- (conn=tx-2177613468711250980, tx=2177613468711250980)
```

**Comment by traskowskycaci** [comment]
> ```
> 2024-04-08T21:46:26.205Z        ERROR   primeapi/payment_request.go:86  Error creating payment request  {"git_branch": "B-18800-county-with-address-response-INT", "git_commit": "f7c25f4ed79b009a51bbe7103baf6460ab19ef03", "host": "officelocal:3000", "milmove_trace_id": "15a10b91-9b13-4582-9d2b-c7478e6843e9", "session_id": "3NPnI3m3YUh4V3EkegXOmaU-7crhcInbKzZOOm6ImZg", "error": "Failed to create service item param for param key <WeightOriginal>  MTO ID <9c7b255c-2981-4bf8-839f-61c7458e2b4d> paymentRequestID <00000000-0000-0000-0000-000000000000> MTO Service item ID <97a19579-d7ff-4d83-baa7-02b2f61961bd> RE Service Item Code: <DOSHUT> Name: <Domestic origin shuttle service> err: Failed to lookup ServiceParamValue for param key <WeightOriginal>  err:  failed ServiceParamValue WeightOriginalLookup with error could not find actual weight for MTOServiceItemID [97a19579-d7ff-4d83-baa7-02b2f61961bd]"}
> github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:86
> github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> 2024-04-08T21:46:26.205Z        ERROR   primeapi/payment_request.go:130 Payment Request {"git_branch": "B-18800-county-with-address-response-INT", "git_commit": "f7c25f4ed79b009a51bbe7103baf6460ab19ef03", "host": "officelocal:3000", "milmove_trace_id": "15a10b91-9b13-4582-9d2b-c7478e6843e9", "session_id": "3NPnI3m3YUh4V3EkegXOmaU-7crhcInbKzZOOm6ImZg", "payload": {"moveTaskOrderID":"9c7b255c-2981-4bf8-839f-61c7458e2b4d","serviceItems":[{"id":"97a19579-d7ff-4d83-baa7-02b2f61961bd","params":null},{"id":"29234540-c62c-4a8b-905f-7192cb0158e3","params":null}]}}
> github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:130
> github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> [POP] 2024/04/08 21:46:26 sql - ROLLBACK Transaction --- (conn=tx-2177613468711250980, tx=2177613468711250980)
> ```

Ohhh as I type that out I see an issue, still says my branch name of 18800 even though I've checked out yours. Restarting the server and trying again

**Review by traskowskycaci — COMMENTED** [review]
Alright on the right branch now at least! Step 10 looks good:

image

Seeing an issue when trying step 11. This is the output I get, following that same order I posted above. Could be me at fault for doing things out of order on the service item additions but getting the `"Weight must be a minimum of 500"` message:
```
2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:86  Error creating payment request  {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "error": "failure pricing service DDSHUT for MTO service item ID 72487aef-791a-4237-931c-d61c8525040e: Weight must be a minimum of 500"}
github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:86
github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:130 Payment Request {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "payload": {"moveTaskOrderID":"ec8ef640-2a79-45d8-bfe3-ad682c74f339","serviceItems":[{"id":"72487aef-791a-4237-931c-d61c8525040e","params":[{"key":"WeightBilled","value":"302"}]},{"id":"a7af482c-77b4-4997-874c-44cc1a2c274a","params":[{"key":"WeightBilled","value":"302"}]}]}}
github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:130
github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
        /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
[POP] 2024/04/08 22:26:03 sql - ROLLBACK Transaction --- (conn=tx-1519225185721045583, tx=1519225185721045583
```

The exact step I see this at is on creating the second payment request and trying to provide an actual weight by filling out the Weight Billed field here:
image

**Comment by cameroncaci** [comment]
> Alright on the right branch now at least! Step 10 looks good:
> 
> image
> 
> Seeing an issue when trying step 11. This is the output I get, following that same order I posted above. Could be me at fault for doing things out of order on the service item additions but getting the `"Weight must be a minimum of 500"` message:
> 
> ```
> 2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:86  Error creating payment request  {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "error": "failure pricing service DDSHUT for MTO service item ID 72487aef-791a-4237-931c-d61c8525040e: Weight must be a minimum of 500"}
> github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:86
> github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> 2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:130 Payment Request {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "payload": {"moveTaskOrderID":"ec8ef640-2a79-45d8-bfe3-ad682c74f339","serviceItems":[{"id":"72487aef-791a-4237-931c-d61c8525040e","params":[{"key":"WeightBilled","value":"302"}]},{"id":"a7af482c-77b4-4997-874c-44cc1a2c274a","params":[{"key":"WeightBilled","value":"302"}]}]}}
> github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:130
> github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
>         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> [POP] 2024/04/08 22:26:03 sql - ROLLBACK Transaction --- (conn=tx-1519225185721045583, tx=1519225185721045583
> ```
> 
> The exact step I see this at is on creating the second payment request and trying to provide an actual weight by filling out the Weight Billed field here: image

Got time to huddle this morning regarding this?

**Comment by traskowskycaci** [comment]
> > Alright on the right branch now at least! Step 10 looks good:
> > image
> > Seeing an issue when trying step 11. This is the output I get, following that same order I posted above. Could be me at fault for doing things out of order on the service item additions but getting the `"Weight must be a minimum of 500"` message:
> > ```
> > 2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:86  Error creating payment request  {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "error": "failure pricing service DDSHUT for MTO service item ID 72487aef-791a-4237-931c-d61c8525040e: Weight must be a minimum of 500"}
> > github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:86
> > github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> > github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> > 2024-04-08T22:26:03.561Z        ERROR   primeapi/payment_request.go:130 Payment Request {"git_branch": "B-19137-Payment-Requests-Billable-Weight-Param-Changes-Int", "git_commit": "313cab15e0b3abf455fe6a2b83500644f4c6876e", "host": "officelocal:3000", "milmove_trace_id": "0c9396bd-b8cc-46f1-934f-ad780eaa17d7", "session_id": "jQ_QFJ4r8vCrRit6AyCEyyre389jk51JDTzZn1FAKPI", "payload": {"moveTaskOrderID":"ec8ef640-2a79-45d8-bfe3-ad682c74f339","serviceItems":[{"id":"72487aef-791a-4237-931c-d61c8525040e","params":[{"key":"WeightBilled","value":"302"}]},{"id":"a7af482c-77b4-4997-874c-44cc1a2c274a","params":[{"key":"WeightBilled","value":"302"}]}]}}
> > github.com/transcom/mymove/pkg/handlers/primeapi.CreatePaymentRequestHandler.Handle.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/primeapi/payment_request.go:130
> > github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/handlers/config.go:145
> > github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
> >         /Users/mariatraskowsky/Documents/GitHub_Projects/mymove/pkg/appcontext/context.go:67
> > [POP] 2024/04/08 22:26:03 sql - ROLLBACK Transaction --- (conn=tx-1519225185721045583, tx=1519225185721045583
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The exact step I see this at is on creating the second payment request and trying to provide an actual weight by filling out the Weight Billed field here: image
> 
> Got time to huddle this morning regarding this?

Yes, going to meet with Danny at 9 so prepping for that but right after will be free.

**Comment by cameroncaci** [comment]
Updated steps to reproduce per our discussion

**Review by traskowskycaci — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
