### PR TITLE
19782 shipment cancellation date validation Backend INT

### PR DESCRIPTION
**Pull request by KonstanceH**
## Summary

This PR prevents the TOO from cancelling any shipment that's 'actualPickupdate' is on or after the request date.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Make a HHG 
2. Login as SC to edit and submit move 
3. Login as Prime to update shipment with an 'actualPickupDate' on or after today
4. Login as TOO and try to cancel the move
5. Confirm the Update error message

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots
Screenshot 2024-06-05 at 1 23 44 PM

### CODE REVIEW

**Review by taeJungCaci — COMMENTED** [review]
I think you may have the AC backwards on this one. I read it as the request date cannot be on or after actual pickup date.

**Comment by KonstanceH** [comment]
> I think you may have the AC backwards on this one. I read it as the request date cannot be on or after actual pickup date.

Yikes! I'm gonna reach out to Brittney to get the logic straight and push a fix

**Comment by KonstanceH** [comment]
> > I think you may have the AC backwards on this one. I read it as the request date cannot be on or after actual pickup date.
> 
> Yikes! I'm gonna reach out to Brittney to get the logic straight and push a fix

Okay just made the changes and pushed it up

**Review by taeJungCaci — APPROVED** [review]
LGTM!

**Review by brooklyn-welsh — APPROVED** [review]
Tested and working. LGTM 👍

**Pull request merged**
