### PR TITLE
Run integration tests in parallel

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

Integration tests can take up to 27 minutes when we run them across 4 separate instances. Unfortunately our spitting of the tests is uneven. This PR lets CircleCI split the tests into 10 separate containers so that we get more even coverage and then it runs them in parallel.  Now the average time is closer to 16min.  Here's a breakdown of [a single run](https://circleci.com/gh/transcom/mymove/141165):

Screen Shot 2019-07-18 at 3 01 23 PM

You can read more about [Running Tests in Parallel](https://circleci.com/docs/2.0/parallelism-faster-jobs/) on the CircleCI website.  This also leverages the Cypress [spec](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-spec-lt-spec-gt) utility like we were using before.

Could we do this faster? Yes! But we'd have to do one e2e test per file and then use CircleCI's built in test timer to figure out how to split them. This is something we could address in the future if we wanted to.

**Note:** If accepted we have to update github's merge criteria first and then folks need to rebase on master to get this change.

### CODE REVIEW

**Comment by tinyels** [comment]
We should test using https://www.cypress.io/dashboard before doing even more customization of our integration test runners.

**Comment by chrisgilmerproj** [comment]
> We should test using https://www.cypress.io/dashboard before doing even more customization of our integration test runners.

Agreed, seems like a great tool. This PR doesn't change anything except how we divide up the tests. Previously I divided them up based on directory. Now its divided up based on filename in a predictable order. Same infra, same CI/CD, and no code changes. The advantage here is getting back 10+ min per run. It's probably the best optimization we have right now.

I also want to point out that integration tests aren't just testing out the cypress js stuff. It's also doing a lot of end to end testing on our infrastructure and containerization. So before we move them to move to the Cypress Dashboard we ought to confirm we aren't losing anything.

**Comment by rdhariwal** [comment]
The only risk I foresee is if some tests depends on other tests to be run before them and when circle ci spilts them it might be ignorant of the fact.

**Comment by rdhariwal** [comment]
> The only risk I foresee is if some tests depends on other tests to be run before them and when circle ci spilts them it might be ignorant of the fact.

We should not be doing this anyways so not a ding but something to keep in mind.

**Pull request merged**
