### PR TITLE
[ MB-16759 ] Removing the departure date validation check in the number days SIT for additional days SIT service items

### PR DESCRIPTION
**Pull request by mmayo-truss**
## Summary

This PR removes the validation check for departure date on payment requests relating to Origin and Destination SIT service items in the number of days SIT lookup. This validation check is only related to first day and additional days service items. 

### What was happening
The error was occurring when a payment request for a first day origin or destination SIT service item that has a departure date was made before a payment request for additional days SIT. We would hit this validation check and the payment request for the additional days SIT could not get created. 

### How to replicate the error
1. As the prime go to an approved move and create either origin or destination SIT service items, make sure to include the departure date.
2. As a TOO go to that move and approve those service items.
3. As the prime create a payment request for the first day SIT service item. This should get approved
4. As the prime create a payment request for the additional days SIT service item. This should throw the error

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. As the prime go to an approved move and create either origin or destination SIT service items, make sure to include the departure date.
2. As a TOO go to that move and approve those service items.
3. As the prime create a payment request for the first day SIT service item. This should get approved
4. As the prime create a payment request for the additional days SIT service item. You should not see the error.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by ronaktruss** [comment]
This seems to work as expected and does resolve the issue!

One general question, do you have a sense of what the function `fetchAndVerifyMTOShipmentSITDates` (this is the function that we removed the check from) is actually verifying and if/how each of those scenarios is possible?

**Comment by mmayo-truss** [comment]
> This seems to work as expected and does resolve the issue!
> 
> One general question, do you have a sense of what the function `fetchAndVerifyMTOShipmentSITDates` (this is the function that we removed the check from) is actually verifying and if/how each of those scenarios is possible?

@ronaktruss It is being called in the [lookup method of the number_days_sit_lookup](https://github.com/transcom/mymove/blob/ff10da92531b32c843f82191df21eac703d53f2b/pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go#L30). You can see that we are only using the error there so it is really only used as a validation check.

**Comment by ronaktruss** [comment]
> > This seems to work as expected and does resolve the issue!
> > One general question, do you have a sense of what the function `fetchAndVerifyMTOShipmentSITDates` (this is the function that we removed the check from) is actually verifying and if/how each of those scenarios is possible?
> 
> @ronaktruss It is being called in the [lookup method of the number_days_sit_lookup](https://github.com/transcom/mymove/blob/ff10da92531b32c843f82191df21eac703d53f2b/pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go#L30). You can see that we are only using the error there so it is really only used as a validation check.

It's not clear to me what we have to do in order for the `fetchAndVerifyMTOShipmentSITDates` to return an error. My initial read is that since we don't allow for duplicate First Day of SIT there aren't any situations in which this function will actually result in an error. Does that match your understanding or am I missing something?

**Review by ronaktruss — APPROVED** [review]
Thanks for making this change and adding https://dp3.atlassian.net/browse/MB-17047 to capture some additional investigation that we may want to do.

**Pull request merged**
