### PR TITLE
INT B-19474 approvals requested or approved move status check issue

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

When the TOO has actions they need to take (approve a shipment, review destination address request, etc), the move status should be `APPROVALS_REQUESTED` instead of `APPROVED`. Now once the TOO has completed those actions, we want to move the status back to `APPROVED` as well to reflect that those actions have been taken.

There was an issue created that addressed this and this BL item and PR was a lot of analysis and essentially expanding and adding in the function `ApproveOrRequestApproval` into service objects that are used when the TOO performs an action.

The following actions that a TOO can perform were assessed/updated to ensure that the move status was being checked on completion of the action:

**MOVE**
- update billed weight amount (excess weight alert)
- approve/reject sit extension
- SIT extension approve/reject

**ORDERS**
- updating orders
- updating allowances

**SHIPMENT**
- approve shipment
- delete shipment
- approving diversions
- address update request/review

**SERVICE ITEM**
- SI creation
- SI approve/reject

**NOTE**
Right now there is a BL item in process to fix an issue with a flag persisting on the MTO page (this seems to be related to excess weight & SIT data): https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19178
So there might be a situation where you aren't able to successfully test if it falls within that specific issue.

### How to test

1. Access MM as a TOO
2. Find a move that has a status of `Approvals Requested`
3. Complete any items that need review
4. Ensure that the move status changes back to `Approved` in the queue following completion of the actions

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
There seems to be a test failing for playwright, not sure why and this PR didn't touch any of that code. Locally I can reproduce and here's the error I get:
```
2024-04-11T14:42:17.071Z        ERROR   ppmshipment/ppm_estimator.go:293        could not calculate param value lookup  {"git_branch": "INT-B-19474-approvals-requested-or-approved-move-status-check-issue", "git_commit": "e3052448cd3e3caf15c26fe79e5977f3c72bceea", "host": "officelocal:3000", "milmove_trace_id": "eb78ee43-248a-4ad7-ad93-a4a86722dbfa", "session_id": "GzsnsLiM7Y-NrXAjbxrfvmlNtAJLVmoELwMuE2f2SRY", "error": " failed ServiceParamValue DistanceZipLookup with error invalid distance using pickup 84022 and destination 38649"}
github.com/transcom/mymove/pkg/services/ppmshipment.estimatePPM.calculatePrice
```

```
2024-04-11T14:42:17.071Z        ERROR   ghcapi/mto_shipment.go:141      ghcapi.CreateMTOShipmentHandler error   {"git_branch": "INT-B-19474-approvals-requested-or-approved-move-status-check-issue", "git_commit": "e3052448cd3e3caf15c26fe79e5977f3c72bceea", "host": "officelocal:3000", "milmove_trace_id": "eb78ee43-248a-4ad7-ad93-a4a86722dbfa", "session_id": "GzsnsLiM7Y-NrXAjbxrfvmlNtAJLVmoELwMuE2f2SRY", "error": " failed ServiceParamValue DistanceZipLookup with error invalid distance using pickup 84022 and destination 38649"}
```

**Comment by danieljordan-caci** [comment]
Passing now suckas

**Review by traskowskycaci — COMMENTED** [review]
Looking good so far as far as actions the TOO takes moving it back the Approved state!

Reading through the story description, it says "Expected Behavior: A move with a status of "Approvals Requested" should have an item to review in the MTO page and should not erroneously display a status of "Approvals Requested" if there is nothing to review."

I do still see that behavior - for REWAYD for example, appears as Approvals requested but there is no action to take as the TOO. Maybe since that's a pre-existing move after a db refresh, it's not an issue and your changes will apply to all new moves. Thoughts?

**Comment by danieljordan-caci** [comment]
> Looking good so far as far as actions the TOO takes moving it back the Approved state!
> 
> Reading through the story description, it says "Expected Behavior: A move with a status of "Approvals Requested" should have an item to review in the MTO page and should not erroneously display a status of "Approvals Requested" if there is nothing to review."
> 
> I do still see that behavior - for REWAYD for example, appears as Approvals requested but there is no action to take as the TOO. Maybe since that's a pre-existing move after a db refresh, it's not an issue and your changes will apply to all new moves. Thoughts?

Changes will apply to all new moves. There's no way to go back and retroactively change all of those statuses without doing a loop when listing all of the moves, but that just seems like unnecessary and might impact performance.

For now you can just update the orders without changing anything and that should do it.

**Comment by traskowskycaci** [comment]
> For now you can just update the orders without changing anything and that should do it.

Yep updating orders works. Not sure if it's mentioning to users that it will only be for new moves, as they might get confused on why they still see moves without action to take after your fix goes in.

**Comment by danieljordan-caci** [comment]
> > For now you can just update the orders without changing anything and that should do it.
> 
> Yep updating orders works. Not sure if it's mentioning to users that it will only be for new moves, as they might get confused on why they still see moves without action to take after your fix goes in.

I mentioned to Danny about calling the function when the TOO fetches the move, [but he didn't want it](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19474). So... It's a check that is reactionary and not a proactive call at this time.

**Review by traskowskycaci — COMMENTED** [review]
Possible issue here:

WTSTAT has two shipments to approve so it's in Approvals Requested status.

image

I approve and send both shipments.

image

I now see an action to take on the MTO page, reviewing billable weight:

image

However, the move is already in the Move approved state while still having an action to take on the MTO page so the TOO doesn't really know they have something to approve if looking at their move queue:

image


This WTSTAT test can be duplicated with `db_dev_fresh`.

You could make the argument that the TOO should see the things to review on the MTO page and take care of them, but the issue is that the status of the move does not reflect that there are still items needing review. The TOO could close the browser or somehow not see that MTO page and those things requiring review might get lost

**Comment by traskowskycaci** [comment]
> > > For now you can just update the orders without changing anything and that should do it.
> > 
> > 
> > Yep updating orders works. Not sure if it's mentioning to users that it will only be for new moves, as they might get confused on why they still see moves without action to take after your fix goes in.
> 
> I mentioned to Danny about calling the function when the TOO fetches the move, [but he didn't want it](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19474). So... It's a check that is reactionary and not a proactive call at this time.

Alright, bases covered then! Good by me

**Comment by traskowskycaci** [comment]
> Possible issue here:
> 
> WTSTAT has two shipments to approve so it's in Approvals Requested status.
> 
> image
> 
> I approve and send both shipments.
> 
> image
> 
> I now see an action to take on the MTO page, reviewing billable weight:
> 
> image
> 
> However, the move is already in the Move approved state while still having an action to take on the MTO page so the TOO doesn't really know they have something to approve if looking at their move queue:
> 
> image
> 
> This WTSTAT test can be duplicated with `db_dev_fresh`.
> 
> You could make the argument that the TOO should see the things to review on the MTO page and take care of them, but the issue is that the status of the move does not reflect that there are still items needing review. The TOO could close the browser or somehow not see that MTO page and those things requiring review might get lost

Just checked and also see this in main so... going to ignore this!

**Review by traskowskycaci — APPROVED** [review]

**Review by TevinAdams — APPROVED** [review]
Test case passed and changes reviewed.

**Pull request merged**
