### PR TITLE
Fix modal scrolling in admin app

### PR DESCRIPTION
**Pull request by LeDeep**
## Summary

The consent modal that appears after clicking `Sign in` would not allow for scrolling in the admin app, on smaller screens. This prevented users from accepting the consent terms. In the office and milmove applications, the modal worked as expected and users could scroll down to accept.

This PR makes a minor change to the HTML in the admin app to separate the modal into its own `div`, similar to the office and milmove applications. Now admin users using smaller screens can scroll down to accept the terms.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

### How to test

1. Use a small screen; either a) resize your browser window so full modal is not visible, b) use mobile emulator, if you have access to one. Note: I didn't find the device selector in the browser (checked in Brave and Firefox) was able to recreate the initial issue.
2. Go to the admin application sign in screen
3. Click `Sign In`
4. When the modal pops up, you should not see the buttons at the bottom
5. Scroll down within the modal and you will be able to `Accept terms` or 'Cancel'

### CODE REVIEW

**Review by YanZ777 — CHANGES_REQUESTED** [review]
These changes aren't allowing the screen to scroll for me.

**Comment by LeDeep** [comment]
>

**Comment by LeDeep** [comment]
> These changes aren't allowing the screen to scroll for me.

Looks to be working on exp, if you want to give it a try.

**Review by YanZ777 — APPROVED** [review]
Tried it out again on exp and locally. Looks like it works! (I'm not sure why it didn't work the first time.)

**Pull request merged**
