### PR TITLE
B-18109 I-12397 diverted shipments int

### PR DESCRIPTION
**Pull request by cameroncaci**
## Summary

This resolves diverted shipments attempting to calculate the weight too early.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Is this good code practice?
- [ ] Does it resolve the issue ticket?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Login as the TOO
2. Identify any HHG move that has an approved shipment
3. Request diversion on that shipment
4. Login as the prime
5. Update shipment, check the "Diversion" boolean box, apply update
6. Copy down the destination address and shipment UUID
7. Create a new HHG shipment on this move
8. Set the diversion boolean box to true on this new move
9. Set the origin address and divertedFromShipmentID to the destination address and UUID you copied, fill the rest out however you see fit
10. Create shipment
11. Login as TOO
12. Approve both shipments
13. You should not encounter this screen:
14. 
image

15. Instead it should just load normally

16. 
image

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
@deandreJones will likely say that this needs to be linked to a BL item and not an issue ticket

**Comment by cameroncaci** [comment]
> @deandreJones will likely say that this needs to be linked to a BL item and not an issue ticket

Understandable, added in the associated backlog item to the description

**Comment by deandreJones** [comment]
> > @deandreJones will likely say that this needs to be linked to a BL item and not an issue ticket
> 
> Understandable, added in the associated backlog item to the description

Yes- code being merged in should come from a B-XXXX then merged to Int branch- and then merged to main, our workflow doesnt include creating branches off issues and merging those into integration or main (keeps it more manageable) and within agility- issues are resolved with BLs
image

**Comment by cameroncaci** [comment]
> Yes- code being merged in should come from a B-XXXX then merged to Int branch- and then merged to main, our workflow doesnt include creating branches off issues and merging those into integration or main (keeps it more manageable) and within agility- issues are resolved with BLs image

@deandreJones 
What about for tickets [B-18472](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A887939) and [B-18109](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A871306). These tickets are directly dependent on each other, if one is merged without the other then things will break (It's a UI and Backend split-up story). Should these be merged into a singular "feature" branch with those 2 combined story branches, then a PR made for that one? Would this be an exception to the rule?

**Comment by deandreJones** [comment]
> > Yes- code being merged in should come from a B-XXXX then merged to Int branch- and then merged to main, our workflow doesnt include creating branches off issues and merging those into integration or main (keeps it more manageable) and within agility- issues are resolved with BLs image
> 
> @deandreJones What about for tickets [B-18472](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A887939) and [B-18109](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A871306). These tickets are directly dependent on each other, if one is merged without the other then things will break (It's a UI and Backend split-up story). Should these be merged into a singular "feature" branch with those 2 combined story branches, then a PR made for that one? Would this be an exception to the rule?

if neither of those BLs could be merged into a branch without braking - then that work should have probably been under 1BL- and jsut be worked by 2 devs coordinating - but i get we are where we are.. and since we dont have agiity tracking commits to BLs(yet).. this can move forward this time

**Review by deandreJones — APPROVED** [review]

**Review by danieljordan-caci — APPROVED** [review]

**Pull request merged**
