### PR TITLE
Adds annotation for G101 linter suppression

### PR DESCRIPTION
**Pull request by reggieriser**
## Description

This PR adds an annotation for a G101 linter suppression that was [just merged](https://github.com/transcom/mymove/pull/6163).  This is similar to other cases where we are referencing the name of a flag for a password, not the password itself.

## Reviewer Notes

We need the validator to update the "RA Validator Status" in the annotation (as well as make any other updates to the annotation as needed).

### CODE REVIEW

**Comment by jneuner-mitre** [comment]
IIRC, syncada_sftp is:
1) the CLI util used to test the Syncada connection, and
2) not production code.
Correct?

**Comment by gidjin** [comment]
@reggieriser is this pr something we can close?

**Comment by jneuner-mitre** [comment]
@Leofscott I'm looking for a story that says we'll be implementing mutual public-key authentication for these SSH interfaces before signing off this PR.  @tmishorich are our interface partners onboard with pubkey auth?

**Comment by gidjin** [comment]
@jneuner-mitre and @Leofscott I created two tickets based on the last ATO meeting. I also added a commit to reference the jira id's in the code as well.

* [MB-7727](https://dp3.atlassian.net/browse/MB-7727) To remove the code related to connecting to Syncada directly which will remove the need for the code being flagged in this PR.
* [MB-7728](https://dp3.atlassian.net/browse/MB-7728) To track switching from username/password combo for connecting to GEX Sftp to connecting with a username/key pair instead.

**Pull request merged**
