### PR TITLE
INT B-20946 SSW max obligation calculation correction

### PR DESCRIPTION
**Pull request by danieljordan-caci**
## Summary

Seems like the SSW packet was showing the wrong value for the 100% GCC under the weight & entitlements section. This was changed from `TotalWeight` to `Entitlement` since they don't want Pro Gear included in there.

Also removed old commented out code.

### How to test

1. You can use pre-existing test data or create your own (I created my own because some older test data does not include weight tickets which will trigger an error)
2. There have been some DTOD issues, so go ahead and make `DTOD_USE_MOCK=true` in your `envrc`
3. Hit up `direnv allow` and fire up your `server` and `client`
4. Set up a new customer with a PPM move, set up your shipment - request an advance - and sign
5. Go in as a SC, approve the advance and submit the move
6. Log back in as the customer and download your AOA packet - you should now see the `100% GCC` value show the ENTITLEMENT poundage instead of the estimated weight
Screenshot 2024-08-27 at 10 16 54 AM
7. Go ahead and complete your PPM by uploading your weight tickets
8. Log back in as a SC and close it out by reviewing the weight tickets and approving everything
9. You can review the AOA packet and the Payment Packet as the office user to confirm both contain the same change
Screenshot 2024-08-27 at 10 21 32 AM
Screenshot 2024-08-27 at 10 21 52 AM

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Closing this as it looks like there's more to it per @antgmann

**Comment by danieljordan-caci** [comment]
Reopening - instead of using the customer provided estimated weight value in the calculation to populate the `estimated_incentive` column in the `ppm_shipments` column - using the customer's max entitlement value instead per the feature criteria.

**Review by traskowskycaci — APPROVED** [review]
Don't believe we need a 508 screenshot for the pdf - looks good!

**Review by CoryKleinjanCACI — APPROVED** [review]
Changes look good and test steps worked as described. Approved.

**Pull request merged**
