### PR TITLE
B-18902 and I-12678 I-12681 fixes MAIN

### PR DESCRIPTION
**Pull request by traskowskycaci**
## Summary

This main PR contains the commits from the 18902 integration PR, as well as the follow on commits from the fix made for I-12678 and the commits for the fix made for I-12681.

### CODE REVIEW

**Comment by danieljordan-caci** [comment]
Looks like you need to fix `pre_test` checks

**Comment by traskowskycaci** [comment]
> Looks like you need to fix `pre_test` checks

dangit thank you

**Comment by traskowskycaci** [comment]
Also successful on circle and not seeing that reflected here - good to review though.

**Review by danieljordan-caci — APPROVED** [review]
Majority of the commits match up. The code change counts are a little wonky between the three PRs, but I trust you on this one.

**Review by deandreJones — APPROVED** [review]

**Pull request merged**
