### PR TITLE
[MB-6664] Replace the GCN with the ICN

### PR DESCRIPTION
**Pull request by pearl-truss**
## Description

This PR updates the GroupControlNumber field to match the value of the InterchangeControlNumber

## Setup

Best way to test this is with a code review to make sure I didn't miss any GCNs and you can run the prime-api-demo to generate an EDI and ensure the generated GCNs in the EDI are now ICNs
```sh
prime-api-demo RDY4PY local
```

In this example EDI the ICN is 000000002 and appears in the ISA and IEA segmenst as the original ICN as well new to this PR: in the GS and GE segments

```sh
ISA*00*0084182369*00*0000000000*ZZ*MILMOVE        *12*8004171844     *210318*1353*U*00401*000000002*0*T*|
GS*SI*MILMOVE*8004171844*20210318*1353*000000002*X*004010
ST*858*0001
BX*00*J*PP*9270-9758-1*TRUS**4
N9*CN*9270-9758-1**
N9*CT*TRUSS_TEST**
N9*1W*Leo, Spacemen**
N9*ML*E_1**
N9*3L*ARMY**
G62*10*20210318**
G62*76*20210101**
G62*86*20210101**
N1*BY*JPPSO Testy McTest*92*LKNQ
N1*SE*Prime*2*PRME
N1*ST*Fort Gordon*10*CNNQ
N3*Fort Gordon*
N4*Augusta*GA*30813*USA**
PER*CN**TE*706-791-4184
N1*SF*GvgAFNXyPI*10*LKNQ
N3*987 Other Avenue*P.O. Box 1234
N4*Des Moines*IA*50309*USA**
PER*CN**TE*(510) 555-5555
HL*1**I
N9*PO*9270-9758-90a2f6c5**
L5*1*DLH*TBD*D**
L0*1*2361.000*DM*1349.000*B******L
L1*1*1349*LB*13405473
FA1*DY
FA2*TA*F8E1
HL*2**I
N9*PO*9270-9758-b9ca22b0**
L5*2*FSC*TBD*D**
L0*2*2361.000*DM*1349.000*B******L
L1*2*1349*LB*-660
FA1*DY
FA2*TA*F8E1
HL*3**I
N9*PO*9270-9758-b49950c2**
L5*3*DDFSIT*TBD*D**
L0*3***1349.000*B******L
L1*3*1349*LB*22194
FA1*DY
FA2*TA*F8E1
HL*4**I
N9*PO*9270-9758-e1238aed**
L5*4*CS*TBD*D**
L0*4**********
L1*4***22353
FA1*DY
FA2*TA*F8E1
HL*5**I
N9*PO*9270-9758-d083ee28**
L5*5*MS*TBD*D**
L0*5**********
L1*5***45423
FA1*DY
FA2*TA*F8E1
L3*****13494783
SE*57*0001
GE*1*000000002
IEA*1*000000002
```

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6664) for this change

### CODE REVIEW

**Comment by jacquelineIO** [comment]
@pearl-truss Can you update the generator file with a comment to say that 
the GCN from GS06 and GE02 will match the ICN in ISA13 and IEA02, which restricts the 858 to only ever have 1 functional group. If multiple functional groups are needed, this will have to change.

And maybe also add a test in the generator to make sure this is happening happening.

**Review by gidjin — COMMENTED** [review]
Changes look good and work. One minor request to not pad the GCN unlike the ICN.

**Comment by pearl-truss** [comment]
All PR feedback has been addressed so this is ready for re-review

**Review by jacquelineIO — APPROVED** [review]
Thank you for the updates. Looks good. Ran locally and saw expected EDI.

**Comment by pearl-truss** [comment]
> Thank you for the updates. Looks good. Ran locally and saw expected EDI.

Thanks for reviewing!

**Pull request merged**
