### PR TITLE
Add 5 minute timeout to health checker

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

Adds a timeout so we don't wait forever on this health check.

I want to point out that this will only set the timeout for the http client but does not do any math around the max tries.

## Setup

I'd like some help figuring out how to do a proper test on this.  Here's what I did:

```
./bin/health_checker --hosts my.move.mil --skip-verify --timeout 1 --log-level debug
2018-12-07T00:30:56.674Z        INFO    health_checker/main.go:282      HTTP GET request completed      {"try": 0, "url": "http://my.move.mil/health", "code": 200}
2018-12-07T00:30:56.847Z        INFO    health_checker/main.go:282      HTTP GET request completed      {"try": 0, "url": "https://my.move.mil/health", "code": 200}
```

Here is the help text:

```sh
./bin/health_checker --help
Usage of ./bin/health_checker:
      --backoff int           backoff in seconds (default 1)
      --ca string             base64-encoded certificate authority for mutual TLS
      --ca-file string        path to file of base64-encoded certificate authority for mutual TLS
      --cert string           base64-encoded public key for client TLS
      --cert-file string      path to file of base64-encoded public key for client TLS
      --exit-on-error         exit on first health check error
      --hosts string          comma-separated list of host names to check
      --key string            path to file of base64-encoded private key for client TLS
      --key-file string       path to file of base64-encoded private key for client TLS
      --log-env string        logging config: development or production (default "development")
      --log-level string      log level: debug, info, warn, error, dpanic, panic, or fatal (default "error")
  -p, --paths string          slice of paths to check on each host (default "/health")
  -s, --schemes string        slice of schemes to check (default "http,https")
      --skip-verify           skip certifiate validation
      --status-codes string   valid response status codes (default "200")
      --timeout int           timeout in seconds (default 300)
      --tries int             number of tries (default 5)
pflag: help requested
```

## Code Review Verification Steps

* [x] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/161934552) for this change
* [this article](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/) explains more about the approach used.

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
This has been updated.  Here is the new help output:

```
go run cmd/health_checker/main.go --help
Usage of /var/folders/by/wb9l8d6x7ld8gz2gdx5cdcth0000gn/T/go-build706679771/b001/exe/main:
      --backoff int           backoff in seconds (default 1)
      --ca string             base64-encoded certificate authority for mutual TLS
      --ca-file string        path to file of base64-encoded certificate authority for mutual TLS
      --cert string           base64-encoded public key for client TLS
      --cert-file string      path to file of base64-encoded public key for client TLS
      --exit-on-error         exit on first health check error
      --hosts string          comma-separated list of host names to check
      --key string            path to file of base64-encoded private key for client TLS
      --key-file string       path to file of base64-encoded private key for client TLS
      --log-env string        logging config: development or production (default "development")
      --log-level string      log level: debug, info, warn, error, dpanic, panic, or fatal (default "error")
  -p, --paths string          slice of paths to check on each host (default "/health")
  -s, --schemes string        slice of schemes to check (default "http,https")
      --skip-verify           skip certifiate validation
      --status-codes string   valid response status codes (default "200")
      --timeout duration      timeout duration (default 5m0s)
      --tries int             number of tries (default 5)
pflag: help requested
```

And an example of usage:

```
go run cmd/health_checker/main.go --timeout 4m --hosts my.move.mil --skip-verify --log-level debug
2018-12-11T17:30:55.104Z        INFO    health_checker/main.go:282      HTTP GET request completed      {"try": 0, "url": "http://my.move.mil/health", "code": 200}
2018-12-11T17:30:55.344Z        INFO    health_checker/main.go:282      HTTP GET request completed      {"try": 0, "url": "https://my.move.mil/health", "code": 200}
```

**Comment by chrisgilmerproj** [comment]
@pjdufour-truss - Take another look at this when you have a chance.  I think this is what you were after and honestly it's really nice with this change.

**Comment by pjdufour-truss** [comment]
I uploaded a commit for timing out each try.  https://github.com/transcom/mymove/commit/bc7225050536af615f2f3b367010827152eb417a.  You can cherry-pick in, if it's the desired use case.

**Comment by pjdufour-truss** [comment]
Could you also add a 15 minute timeout to the deploy services?

**Comment by chrisgilmerproj** [comment]
Using the CircleCI command: 

```
$ go run cmd/health_checker/main.go --schemes http,https --hosts my.move.mil,office.move.mil,tsp.move.mil  --tries 10 --backoff 3 --log-level info --timeout 15m
2018-12-12T18:01:16.439Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "http://my.move.mil/health", "code": 200}
2018-12-12T18:01:16.838Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "http://office.move.mil/health", "code": 200}
2018-12-12T18:01:17.240Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "http://tsp.move.mil/health", "code": 200}
2018-12-12T18:01:17.565Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "https://my.move.mil/health", "code": 200}
2018-12-12T18:01:17.737Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "https://office.move.mil/health", "code": 200}
2018-12-12T18:01:17.966Z        INFO    health_checker/main.go:292      HTTP GET request completed      {"try": 0, "url": "https://tsp.move.mil/health", "code": 200}
```

This appears to be all working now.

**Comment by chrisgilmerproj** [comment]
The integration tests are passing again :)

**Pull request merged**
