### PR TITLE
[MB-14417] update service item status refactor

### PR DESCRIPTION
**Pull request by ruizajtruss**
## Summary

Refactored template and testing - now capturing rejection reason 🎉 

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access an approved move as a too user
2. Approve and reject some service items
3. Should display in the history tab 🎉 

## Verification Steps for Author

These are to be checked by the author.

- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
Before:
image

After:
image

### CODE REVIEW

**Review by juliemoon — COMMENTED** [review]
@ruizajtruss Thanks for doing this! The rejected remarks look great. I noticed a small difference between this PR & what we're showing in prod. Can we hide the **status:rejected** field in the Details column? Since the event name says **rejected service item** it is redundant info for the user, and I'm thinking during peak season users will get information overload. 
Screen Shot 2022-11-02 at 1 50 02 PM
Screen Shot 2022-11-02 at 1 49 17 PM

**Comment by ruizajtruss** [comment]
> @ruizajtruss Thanks for doing this! The rejected remarks look great. I noticed a small difference between this PR & what we're showing in prod. Can we hide the **status:rejected** field in the Details column? Since the event name says **rejected service item** it is redundant info for the user, and I'm thinking during peak season users will get information overload. Screen Shot 2022-11-02 at 1 50 02 PM Screen Shot 2022-11-02 at 1 49 17 PM

Done!

**Review by mmayo-truss — APPROVED** [review]
Looks good! I verified that this functions as expected.

**Review by juliemoon — COMMENTED** [review]
This looks great, thanks @ruizajtruss 
Screen Shot 2022-11-03 at 3 50 09 PM

**Pull request merged**
