### PR TITLE
PrimeAPI / UpdateMTOShipmentHandler - update payload

### PR DESCRIPTION
**Pull request by chrisrcoles**
## Description

This PR ensures that `approvedDate` and `reService.Code` are valid and present in the response payload for `primeapi/updateMTOShipmentHandler`. 

## Reviewer Notes

In-line comments.

## Setup

```
mylaptop ~ %: cd /mymove
mylaptop ~ %: make server_run
mylaptop ~ %: go test ./pkg/handlers/primeapi -testify.m TestCreateMTOShipmentHandler -v 
```

## Code Review Verification Steps

* [x] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [x] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* [x] Request review from a member of a different team.
* [x] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3824)

### CODE REVIEW

**Review by sandy-wright — COMMENTED** [review]
The changes look good! I was wondering - was the `approvedDate` supposed to be returned for the service items? I'm still not seeing that value in the response.

**Comment by chrisrcoles** [comment]
Hey @sandy-wright - I'm actually not sure. The [story as defined ](https://dp3.atlassian.net/browse/MB-3824)wasn't very explicit regarding this. I've asked @shimonacarvalho in [Slack](https://ustcdp3.slack.com/archives/GQT904HE2/p1601669249003300) and am awaiting a response.

**Review by sandy-wright — APPROVED** [review]
Confirmed it was the shipment's `approvedDate`, not the service items. Tested again and all looks good!

**Review by donaldthai — APPROVED** [review]
:shipit:

**Pull request merged**
