### PR TITLE
B-18799 Address County Update Logic

### PR DESCRIPTION
**Pull request by cameroncaci**
# [B-18799](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A906813)

# Warning

This is a considerable refactor. Address service logic has been modified, and there are many instances in the codebase of address db record modification that bypasses service-level logic. It was bypassed via instances of `appCtx.DB().Save(interface)`. Meaning tests do not fully encapsulate this new logic. Please manually test thoroughly.

# Summary
When an address is now updated, it should check for if the zip code has been modified. If it has, then it looks up the corresponding county and applies it to the newly updated address. This was updated on the service level.

Additionally, shipment update logic was adjusted to switch away from manually injected POP queries using `appCtx.DB().Save(interface)`. This involved removing those instances, replacing with the service, and adding additional conditions.

County was also marked to no longer be a pointer on the Address model, which is why @deandreJones PSQL migration to backfill counties is present again.

## Steps to repoduce (Simply)

1. Login as service counselor
2. Grab a move that needs counseling
3. Click “Edit shipment”
4. Open up browser dev tools -> navigate to network -> refresh your page while still under “edit shipment”
5. Copy the UUID from your URL (counesling/moves/${locator}/shipments/abcdf-ghijkl-mnop)
6. Under your browser dev tools under the network tab, select the “mto_shipments” network request
7. After clicking the network request, click “Response” for said network request. Now, search the UUID you copied from the URL (CTRL/CMD+F)
8. Grab the “pickupAddress” id.
9. Using Postman, hit the office router `/internal/addresses/${paste_pickup_address_id_here}` endpoint.
10. You should see your pickup address and its respective county.
11. Now, back to the service counselor view. Go ahead and update the pickup address zip code to a new, real zip code.
12. Save
13. Hit the `/internal/addresses/${paste_pickup_address_id_here}` endpoint again. The county should now be different (If the zip code you provided is in a different county)
14. Test that other areas where you can update shipments are functional

### CODE REVIEW

**Comment by cameroncaci** [comment]
Failing tests are flaky

**Review by traskowskycaci — CHANGES_REQUESTED** [review]
Following your tests, looks good!

Running through creating a brand new move with a PPM and HHG shipment as the service member and routing it through the counselor and TOO steps also looked good. However, I did run into a few issues as the prime. I was unable to edit the pickup address directly, got a 500. Then when I tried to request origin SIT for the HHG, I got a "A service item with reServiceCode DOFSIT must have the sitHHGActualOrigin field set.:
reServiceCode - DOFSIT cannot be created" message. I was able to request destination SIT.

**Comment by cameroncaci** [comment]
@traskowskycaci Good for re-review

**Review by traskowskycaci — APPROVED** [review]
Tested again and all looks good - requested origin and destination SIT, did some destination address change requests. Very nice!

**Review by TevinAdams — APPROVED** [review]
Test Case passed for me.

**Pull request merged**
