### PR TITLE
INT B-18859 Prime Simulator Display HHG Pro Gear

### PR DESCRIPTION
**Pull request by ajlusk**
## Summary

A user should now be able to update an HHG's Pro Gear weights from the Update Shipment form in the Prime Simulator. Depends on the recent changes that added pro gear weights to mtoShipment and makes them updateable via the prime API.

Downstream dependency of B-18840 and B-18669

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Ensure at least one move, containing at least one HHG shipment, exists and is accessible to the Prime User. You can probably use an existing move created by dev_db_e2e_populate.
2. Access the prime simulator and open that move.
3. Verify there are rows to display both pro gear weights near the other weights listed for that shipment.
4. Select the "Update Shipment"
5. Fill out any required fields as necessary, the date fields can't be blank to submit the form.
6. Enter values for the Pro Gear Weight and Spouse Pro Gear Weight fields.
7. Save the form.
8. Verify your new values are displayed in the location you verified existed in step 3.
9. Re-open the form to verify the values persist.
10. Open a new move that contains a PPM shipment (ex: MMOVEL)
11. Verify the rows you checked for in step 3 are not displayed since PPMs display their pro gear weights elsewhere.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

### CODE REVIEW

**Comment by r-mettler** [comment]
I see and can update the Actual weight fields
image

**Comment by r-mettler** [comment]
The Prime Sim currently displays all the data that can be updated when you are on the Update Shipment page. Can you also add the Actual weights on this main page?
image

**Comment by ajlusk** [comment]
> The Prime Sim currently displays all the data that can be updated when you are on the Update Shipment page. Can you also add the Actual weights on this main page? image

This has been added.

**Comment by ajlusk** [comment]
Updated testing instructions to cover displaying pro gear weights on the main Prime Sim page.

**Review by CoryKleinjanCACI — APPROVED** [review]
Code looks good and tested functionality. Everything looks good to include the update Ricky asked for.

**Review by antgmann — COMMENTED** [review]
Looks good on functionality and code. However, there was an issue with merge conflicts that are causing a server test or two to fail. Alex said he knows what it's from, once that's resolved this should be g2g

**Review by antgmann — APPROVED** [review]
Issues resolved, approved.

**Pull request merged**
