### PR TITLE
Removes permission for TIO to be able to update MTOServiceItem status.

### PR DESCRIPTION
**Pull request by Ryan-Koch**
## Summary

During a user exercise we had a TIO make a change to an MTOServiceItem status. The feedback we got was that they shouldn't be able to do that, so this removes the `update.MTOServiceItem` permission from the TIO role.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

### CODE REVIEW

**Review by ronaktruss — COMMENTED** [review]
@Ryan-Koch LGTM. Functionally this works as expected. I am not seeing the accept or reject options after this change.

As someone who hasn't really looked or touched the permissions code, I am a bit confused as to why we don't need to have a permission on [the endpoint](https://github.com/transcom/mymove/blob/main/swagger-def/ghc.yaml#L1499) that is actually being called to update the service item status. Is there a quick explanation that would explain this?

I spent a few minutes looking at the above, would this fix just not show the options on the UI but still theoretically allow them to hit the API to update the status?

**Comment by Ryan-Koch** [comment]
> @Ryan-Koch LGTM. Functionally this works as expected. I am not seeing the accept or reject options after this change.
> 
> As someone who hasn't really looked or touched the permissions code, I am a bit confused as to why we don't need to have a permission on [the endpoint](https://github.com/transcom/mymove/blob/main/swagger-def/ghc.yaml#L1499) that is actually being called to update the service item status. Is there a quick explanation that would explain this?
> 
> I spent a few minutes looking at the above, would this fix just not show the options on the UI but still theoretically allow them to hit the API to update the status?

We make use of these tags at the end point level in swagger. In this case we have this x-permissions tag under the end point for updating MTO service item status:

```
      x-permissions:
        - update.MTOServiceItem
```

So it should make it non-visible in the UI and ensure they can't hit the end point as well.

**Comment by ronaktruss** [comment]
> We make use of these tags at the end point level in swagger. In this case we have this x-permissions tag under the end point for updating MTO service item status:
> 
> ```
>       x-permissions:
>         - update.MTOServiceItem
> ```

Aren't there two different end-points here? `/move-task-orders/{moveTaskOrderID}/service-items/{mtoServiceItemID}/` and  `/move-task-orders/{moveTaskOrderID}/service-items/{mtoServiceItemID}/status`. Afaict the status endpoint is being used for the update of the MTO service item status. And this permission exists on the generic `/move-task-orders/{moveTaskOrderID}/service-items/{mtoServiceItemID}/` end point.

Or am I off the mark/misunderstanding things?

**Comment by Ryan-Koch** [comment]
> 

Oh you're right there. It looks like we missed adding this to the end status end point but attached it to the generic one (as you noted). I'll try fixing that and seeing if there's any issue afterward.

**Comment by ronaktruss** [comment]
Fwiw, there might need to be some accompanying FE changes as well. Right now [the FE](https://github.com/transcom/mymove/blob/main/src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx#L50), the approve/reject buttons rely on update.MTOServiceItem permissions.

**Comment by Ryan-Koch** [comment]
> Fwiw, there might need to be some accompanying FE changes as well. Right now [on the FE](https://github.com/transcom/mymove/blob/main/src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx#L50) the approve/reject buttons rely on update.MTOServiceItem permissions.

I wound up using the same permission (both things are about modifying MTOServiceItems), so I think we're good on the frontend.

**Review by ronaktruss — APPROVED** [review]
LGTM! Is there a ticket associated with this? I assume there isn't since this was supposed to be a quick change.

**Comment by Ryan-Koch** [comment]
> LGTM! Is there a ticket associated with this? I assume there isn't since this was supposed to be a quick change.

There isn't, but I'm going to make one to document the change ASAP so we don't lose context for why the change happened.

**Pull request merged**
