### PR TITLE
B-18459: Multi-Move Automated Regression Testing

### PR DESCRIPTION
**Pull request by TevinAdams**
[Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18459)

## Summary
This story was to complete MultiMove automated playwright tests. Adjustments made in this MR includes getting rid of the skips on multi move tests. A MultiMove test is now only skipped if the Multi-Move feature flag is off. Some tests adjustments were made to match the Multi-Move workflow and attribute changes.

## Just a few highlights that I have found:
1. Estimated incentive number expected in the test is different than what is actually in the header. 

My thoughts: Did anything change with calculating the estimated incentive?

Solution: Check for incenative header to show up in th eplaywright test.

2. Pickup and desitination primary and secondary zipcodes error message handling seems to have changed.
Changes in this file were made about 2 months ago. Changes consisted of attribute name change but the error

My thoughts: I suspect the error messages are not working how the playwright tests expected because the <DateAndLocationForm /> component is not using the postalCodeValidator={validatePostalCode} prop that is being passed to it. The validatePostalCode() method which generates those error messages is being referenced but not being used.

Solution: Remove error message assertions because that does not happen.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Ensure Multimove feature flags are on. Check Circle CI to ensure playwright tests succeed.

### CODE REVIEW

**Review by traskowskycaci — COMMENTED** [review]
I understand your reasoning for taking out the postal code validation messages but I would hate to lose that validation. I think we should actually use the validator where it should be used and test for it. I asked Cory for an issue number since he mentioned making one. 

For now, could we instead of removing them, have them skip or comment them out until that is validation is fixed? Then as part of the issue for fixing that, uncomment or remove the skip for the postal code validation tests?

@CoryKleinjanCACI

**Comment by TevinAdams** [comment]
> I understand your reasoning for taking out the postal code validation messages but I would hate to lose that validation. I think we should actually use the validator where it should be used and test for it. I asked Cory for an issue number since he mentioned making one.
> 
> For now, could we instead of removing them, have them skip or comment them out until that is validation is fixed? Then as part of the issue for fixing that, uncomment or remove the skip for the postal code validation tests?
> 
> @CoryKleinjanCACI

@traskowskycaci  Yeah If we want to use that functionality we will just have to skip that test until that functionality is fixed. Wasnt sure if a story came down to not use that or what.

**Review by danieljordan-caci — APPROVED** [review]
most excellent. looks good on my end!

**Comment by traskowskycaci** [comment]
> > I understand your reasoning for taking out the postal code validation messages but I would hate to lose that validation. I think we should actually use the validator where it should be used and test for it. I asked Cory for an issue number since he mentioned making one.
> > For now, could we instead of removing them, have them skip or comment them out until that is validation is fixed? Then as part of the issue for fixing that, uncomment or remove the skip for the postal code validation tests?
> > @CoryKleinjanCACI
> 
> @traskowskycaci Yeah If we want to use that functionality we will just have to skip that test until that functionality is fixed. Wasn't sure if a story came down to not use that or what. Once whoever works fixing that validator they will just have to unskip the test and adjust accordingly. But for now if we want we can just keep that one skipped and note it.

Alright looks like you added that skip back in, thanks for doing that. The issue Cory created to capture that postal code validation is I-12791. Do you mind updating that issue with the test that needs to have the skip taken out when that validation is fixed?

**Comment by TevinAdams** [comment]
> > > I understand your reasoning for taking out the postal code validation messages but I would hate to lose that validation. I think we should actually use the validator where it should be used and test for it. I asked Cory for an issue number since he mentioned making one.
> > > For now, could we instead of removing them, have them skip or comment them out until that is validation is fixed? Then as part of the issue for fixing that, uncomment or remove the skip for the postal code validation tests?
> > > @CoryKleinjanCACI
> > 
> > 
> > @traskowskycaci Yeah If we want to use that functionality we will just have to skip that test until that functionality is fixed. Wasn't sure if a story came down to not use that or what. Once whoever works fixing that validator they will just have to unskip the test and adjust accordingly. But for now if we want we can just keep that one skipped and note it.
> 
> Alright looks like you added that skip back in, thanks for doing that. The issue Cory created to capture that postal code validation is I-12791. Do you mind updating that issue with the test that needs to have the skip taken out when that validation is fixed?

@traskowskycaci Added to the story description.

**Pull request merged**
