### PR TITLE
B21575-INT-add order types

### PR DESCRIPTION
**Pull request by JamesHawks224**
## Agility ticket
[B21575](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21575)

## Summary
For the customer, 2 new order types were added:  Student Travel, Early Return of Dependents.  If either of these were selected, then "Has Dependents" would default to "yes" and be disabled so it can't be changed.  If another order type besides these 2 were selected, "Has Dependents" would be re-enabled and would be reset to nothing selected.

### How to test
Scenario 1: Creating a move
* login as a customer
* create a move
* at the move orders page ("tell us about your move orders")
  - set initial values all fields:
    - order type: Permanent Change of Station
    - remaining fields: any value is fine
* verification
  - verify: order type,  changing existing type to another existing type
    - change order type to local move
    - verify no fields are changed
  - verify: order type, changing existing type to new type (student travel)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (student travel) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing existing type to new type (early return of dependents)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (early return of dependents) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing new type (early return of dependents) to to new type (student travel)
    - change order type to early return of dependents
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
* finish creating the move w/a ppm shipment.

Scenario 2: edit existing orders
* login as a customer
* use the move just created in scenario 1
* click on "review your request"
* edit orders
* on the "edit orders" page, set the initial values the same as in scenario 1
* perform verification the same verification as in scenario 1.
* save the page

## ANDI Screenshots
Creating a move:
image

Editing existing orders:
image

## Testing Screenshots
N/A

### CODE REVIEW

**Review by WeatherfordAaron — APPROVED** [review]
I'm going to approve because this suggestion doesn't have to do with how the code works. I would recommend using double-quotes instead of backticks for the assertion strings (i.e. expectedHTMLContent var in the tests inside the move_counseled_test.go) for the tests for emails and use \n for line breaks. The only reason for this is that if formatting is changed at all inside the string literals that use backticks it will mess up the test results and I believe that using \n instead of an actual line-break.

That being said, they use the same formatting that you have in these tests throughout the app so I have no real objection with it.

all in all LGTM 👽

**Comment by brooklyn-welsh** [comment]
Currently getting an error when trying to edit orders, ""error": "pq: invalid input value for enum orders_type: \"EARLY_RETURN_OF_DEPENDENTS\""", will message you with more details

**Comment by WeatherfordAaron** [comment]
> Currently getting an error when trying to edit orders, ""error": "pq: invalid input value for enum orders_type: "EARLY_RETURN_OF_DEPENDENTS""", will message you with more details, but my first assumption is that there needs to be an SQL migration file added that adds enums for these new move types to the orders table.
> 
> But let me know if it's working for you without that. Could always be local environment stuff.

I believe it worked for me.. I will go back and test again though. Did you do a fresh db before trying it?

**Comment by brooklyn-welsh** [comment]
> > Currently getting an error when trying to edit orders, ""error": "pq: invalid input value for enum orders_type: "EARLY_RETURN_OF_DEPENDENTS""", will message you with more details, but my first assumption is that there needs to be an SQL migration file added that adds enums for these new move types to the orders table.
> > But let me know if it's working for you without that. Could always be local environment stuff.
> 
> I believe it worked for me.. I will go back and test again though. Did you do a fresh db before trying it?

Yep I ran the fresh script after running into the error to ensure that it wasn't an old DB change hanging around. Asked Jim to retry as well to see if it happens on his local. I'll also retry tomorrow just to see, it's possible maybe the fresh script failed or something.

However, the fact that it's complaining about enums for the new types missing in the DB makes me think that it's accurate, since I don't see an SQL file in the diff that would add those enums, and as far as I know we're the only team who's worked on these. But we'll see after some more debugging tomorrow

**Review by taeJungCaci — COMMENTED** [review]
I think we might need to add FF or use existing Alaska FF for this story so these new types don't get shown in Production until they are ready. Please check and confirm.

**Pull request closed without merging**
