### PR TITLE
[MB-6304] GetAWSConfig

### PR DESCRIPTION
**Pull request by esacteksab**
Following the pattern from [here](https://github.com/transcom/mymove/pull/5734/files).

### CODE REVIEW

**Review by travelar — APPROVED** [review]

**Review by mdawn — CHANGES_REQUESTED** [review]
would you mind deleting this puppy while you're at it?
https://github.com/transcom/mymove/blob/master/config/env/experimental.save-ghc-fuel-price-data.env

**Comment by esacteksab** [comment]
> would you mind deleting this puppy while you're at it?
> https://github.com/transcom/mymove/blob/master/config/env/experimental.save-ghc-fuel-price-data.env
> 
> 🧹🧹🧹

Done!

**Review by mdawn — APPROVED** [review]

**Comment by kilbergr** [comment]
Is there reason to remove https://github.com/transcom/mymove/blob/master/config/env/experimental.save-ghc-fuel-price-data.env but not https://github.com/transcom/mymove/blob/master/config/env/prod.save-ghc-fuel-price-data.env and https://github.com/transcom/mymove/blob/master/config/env/staging.save-ghc-fuel-price-data.env?

**Comment by kilbergr** [comment]
Also!! Tell us how you ultimately tested!!!! That would be so great to have in a doc 🥺

**Comment by esacteksab** [comment]
> Is there reason to remove https://github.com/transcom/mymove/blob/master/config/env/experimental.save-ghc-fuel-price-data.env but not https://github.com/transcom/mymove/blob/master/config/env/prod.save-ghc-fuel-price-data.env and https://github.com/transcom/mymove/blob/master/config/env/staging.save-ghc-fuel-price-data.env?

Probably not. Misty asked me to remove the one. Not the others. Given my laptop is dead, I'll fix this when I'm back up and running.

**Pull request merged**
