### PR TITLE
update moves and delete duty stations w/ no zip3: 167301662

### PR DESCRIPTION
**Pull request by lynzt**
## Description

Cleanup of this pr: https://github.com/transcom/mymove/pull/2397
During this pr, we discovered some of the moves on `staging` and `prod` had a foreign key constraint. 

This migration updates the (origin/destination) duty station to another duty station. Then we delete duty stations that have no zip3 rows.

## Reviewer Notes

Hard to verify locally since in our prior pr, we removed the duty stations w/o zip3 data. This is to clean up `staging` and `prod`.

## Setup
`make db_dev_reset`
`make db_dev_migrate`

## Code Review Verification Steps

* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/tree/master/docs/database.md#zero-downtime-migrations))
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Request review from a member of a different team.
* [ ] Have the Pivotal acceptance criteria been met for this change?

## References

* [Pivotal story](https://www.pivotaltracker.com/story/show/167301662) for this change

### CODE REVIEW

**Comment by sarboc** [comment]
@chrisgilmerproj My understanding was that secure migrations were meant to obscure private data, not an indication of where a migration should be run. Since there's no private data here, a regular migration should be fine.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj My understanding was that secure migrations were meant to obscure private data, not an indication of where a migration should be run. Since there's no private data here, a regular migration should be fine.

It serves two purposes: 1) Obscure sensitive data, 2) Protect each environment from the other. 

So if this migration should be applied to each environment and local development then its fine as is. But if its not supposed to run in Experimental or if the UUIDs are different on Experimental than on Staging/Prod then we should use secure-migrations. I'm mostly looking for clarification here and making sure we're not inadvertently modifying data we don't intend to in each environment.

**Comment by lynzt** [comment]
@chrisgilmerproj - This update is for all db environments, not just `staging` and `prod`. 

We are running this because there were 1 or more moves in those databases that used duty stations we were trying to delete. This pr updates the moves to use another duty station so we can delete duty stations without running into constraint errors (on staging and prod). 

ping me if you have questions... might be quicker to talk it out... 😄

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj - This update is for all db environments, not just `staging` and `prod`.

That answers my question!

**Pull request merged**
