### PR TITLE
INT B-19789 fe office user ability to manage docs

### PR DESCRIPTION
**Pull request by taeJungCaci**
## Summary

This is the frontend work for giving the office users the ability to manage documents(orders, amended orders, and supporting documents). QAE/CSR can only view and will not be able to add or delete documents.
The UI design and the functionality to partially add orders was already implemented by another team and I've followed that design.

### How to test

1. As a customer -> create a move and finish submitting with any shipment.
2. As a SC -> find the move -> click `View and edit orders` button in move details page.
3. Use the Manage Orders and Manage Amended Orders button on the right sidebar to add/delete documents and see the changes reflected.
4. Go back to move details page and click the "Supporting Documents" tab.
5. Use the document component on the right sidebar to add/delete supporting documents.
6. Repeat for TOO/TIO.
7. QAE/CSR should not be able to add/delete documents.

## Screenshots
image
image

### CODE REVIEW

**Comment by paulstonebraker** [comment]
Just here to say I love the picture you uploaded :)

**Review by KonstanceH — APPROVED** [review]
LGTM!

**Comment by taeJungCaci** [comment]
> Just here to say I love the picture you uploaded :)

Haha thanks Paul! I totally stole that from an existing move cause I liked it too 😸 .

**Review by JamesHawks224 — APPROVED** [review]
testing: success
code: lgtm

**Pull request merged**
