### PR TITLE
make the prereqs actually required for our most common commands

### PR DESCRIPTION
**Pull request by macrael**
## Description

This adds prereqs to the build_client and build_server tasks in the make file so that if a new prerequisite is added it will present a nice error on next run. 

## Reviewer Notes

Are there other make tasks that need this?

## Code Review Verification Steps

* [ ] Request review from a member of a different team.

### CODE REVIEW

**Comment by amitch23** [comment]
It looks like psql may not be needed on CircleCI (?), so could probably be moved into the conditional block for local development only.

**Comment by dynamike** [comment]
Just looking at the build errors and the prereq script I see two things.
1) The functionality to split out dependencies between CircleCI and MacOS already exists
https://github.com/transcom/mymove/blob/master/bin/prereqs#L27
https://github.com/transcom/mymove/blob/master/bin/prereqs#L32
2) The build_app job fails because it's trying to run the make commands with a different base container (https://github.com/transcom/mymove/blob/master/Dockerfile#L3) 

To me this highlights a larger problem of having multiple sources of truth for dependencies
* prereq script
* https://github.com/trussworks/circleci-docker-primary
* https://github.com/transcom/mymove/blob/master/Dockerfile#L7

**Comment by macrael** [comment]
For one, I think that we should decommission the build-container. It was created so that we could do container builds locally on MacOS but we don't actually do that and could easily just build directly in circle.

**Comment by macrael** [comment]
But I'm going to close this PR for now, I don't think it's worth trying to fix this right now.

**Pull request closed without merging**
