### PR TITLE
set up key press handling so that backspace would clear out the field

### PR DESCRIPTION
**Pull request by WeatherfordAaron**
## Summary

I found the common component that is used for all location-related drop-down selection fields and added functionality that will allow the user to hit the BACKSPACE key on their keyboard to retype the search query as the previous functionality was not clear to the user how to retype the search query.

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Automated Testing:
Added test criteria to existing Onboarding and Orders tests.

Manual Testing:
1. Access the MilMove app
2. Create a new user.
3. As you are following the "new user setup" process, you should notice the modified selection box for selecting the location/address.
4. In addition, you may want to check some other areas where the location/address selection drop-down is.
a. Closeout Office Input
b. Duty Location
c. Orders Panel
d. Edit Profile

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots

Screenshot 2023-10-27 at 8 00 09 AM

### CODE REVIEW

**Comment by taeJungCaci** [comment]
Code looks fine to me. Tested the branch and works as expected. May need to write tests for it thought.

**Review by JamesHawks224 — COMMENTED** [review]
Code looks good.
Tested the following paths:
milmove url > create new move> ... > current duty location
office url > counselor > counseling > select move> shipments > edit shipments > closeout office
office url > counselor > counseling > select move > orders > view and edit orders > duty location
office url > too > select move > orders > view and edit orders > duty location
Tests were successful.

**Review by WeatherfordAaron — COMMENTED** [review]
fixed the arg name so it is more descriptive

**Comment by deandreJones** [comment]
were there any tests added for this?

**Comment by WeatherfordAaron** [comment]
> were there any tests added for this?

Yes. We added these tests:

milmove url > create new move> ... > current duty location
office url > counselor > counseling > select move> shipments > edit shipments > closeout office
office url > counselor > counseling > select move > orders > view and edit orders > duty location
office url > too > select move > orders > view and edit orders > duty location

**Comment by deandreJones** [comment]
was that added in a different Branch?

**Comment by WeatherfordAaron** [comment]
> was that added in a different Branch?

I think I'm confused as to what you're asking. We just tested it by clicking through. We did write any automated tests for it (if that's what you're asking).

**Comment by taeJungCaci** [comment]
> > was that added in a different Branch?
> 
> I think I'm confused as to what you're asking. We just tested it by clicking through. We didn't write any automated tests for it (if that's what you're asking).
> 
> I should add that when Tae commented that we needed to add a test for it, I had not yet updated the "How to test" section of the boiler plate description on the PR. I took his comment to mean that he was suggesting that I update that section, which I since did.

Sorry for the confusion. When I meant test, I meant automated tests such as Jest or Playwrite. Not sure if those are absolute requirements thought.

**Comment by WeatherfordAaron** [comment]
> > > was that added in a different Branch?
> > 
> > 
> > I think I'm confused as to what you're asking. We just tested it by clicking through. We didn't write any automated tests for it (if that's what you're asking).
> > I should add that when Tae commented that we needed to add a test for it, I had not yet updated the "How to test" section of the boiler plate description on the PR. I took his comment to mean that he was suggesting that I update that section, which I since did.
> 
> Sorry for the confusion. When I meant test, I meant automated tests such as Jest or Playwrite. Not sure if those are absolute requirements thought.

Just created new tests for it and pushed.

**Review by JamesHawks224 — COMMENTED** [review]
looks good. no changes.

**Comment by taeJungCaci** [comment]
I think similar test can be written in this file at line 80 since the issue is more specific to PPM closeout location.
`playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js`

**Comment by WeatherfordAaron** [comment]
> I think similar test can be written in this file at line 80 since the issue is more specific to PPM closeout location. `playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js`

Ok. I believe I have gotten the tests to work like I want them to (finally). @deandreJones Would you mind checking again?

**Review by taeJungCaci — APPROVED** [review]
Tested and looks good!

**Review by deandreJones — APPROVED** [review]

**Review by JamesHawks224 — COMMENTED** [review]
looks good. no changes.

**Pull request merged**
